# @(#)34        1.1  src/bos/usr/lib/unixtomh/Makefile, cmdmailx, bos411, 9428A410j 8/5/92 17:20:16
# COMPONENT_NAME:
#
# FUNCTIONS:
#
# ORIGINS: 27
#
# IBM CONFIDENTIAL -- (IBM Confidential Restricted when
# combined with the aggregated modules for this product)
#                  SOURCE MATERIALS
# (C) COPYRIGHT International Business Machines Corp. 1988, 1989
# All Rights Reserved
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#

VPATH		= ../bugfiler

PROGRAMS	= unixtomh
MSGHDRS		= bf_msg.h
CATFILES	= 
HFILES		= ${MSGHDRS}

ILIST		= unixtomh
IDIR		= /usr/lib/


.include <${RULES_MK}>
