#!/etc/drivers/scdisk
* @(#)02	1.2  src/bos/kernext/disk/scdisk.exp, sysxdisk, bos411, 9428A410j 6/15/90 18:20:07
*
* COMPONENT_NAME: (SYSXDISK) SCSI Disk Device Driver Top Half Export List
*
* FUNCTIONS:
*
* ORIGINS: 27
*
* (C) COPYRIGHT International Business Machines Corp. 1988, 1990
* All Rights Reserved
* Licensed Materials - Property of IBM
*
* US Government Users Restricted Rights - Use, duplication or
* disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
*
