# @(#)50	1.1  src/bos/usr/lib/piosCN/Makefile, ils-zh_CN, bos41J, 9507B 1/26/95 09:55:05
#
#   COMPONENT_NAME: ils-zh_CN
#
#   FUNCTIONS: none
#
#   ORIGINS: 27
#
#   IBM CONFIDENTIAL -- (IBM Confidential Restricted when
#   combined with the aggregated modules for this product)
#                    SOURCE MATERIALS
#
#   (C) COPYRIGHT International Business Machines Corp. 1995
#   All Rights Reserved
#   US Government Users Restricted Rights - Use, duplication or
#   disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#

EXPINC_SUBDIRS		= msg

EXPLIB_SUBDIRS		= lib

SUBDIRS		= \
	fmtrs predef

.include <${RULES_MK}>
