# @(#)42        1.1  src/bos/usr/lib/assist/fr_CA/Makefile, cmdassist, bos411, 9440A411d 10/5/94 08:17:49
#
# COMPONENT_NAME:  cmdassist
#
# FUNCTIONS:
#
# ORIGINS: 27
#
# IBM CONFIDENTIAL -- (IBM Confidential Restricted when
# combined with the aggregated modules for this product)
#                  SOURCE MATERIALS
# (C) COPYRIGHT International Business Machines Corp. 1994
# All Rights Reserved
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#

MSGLANG		= fr_CA

CATFILES	= softlic.cat

.include <${RULES_MK}>
