$ @(#)35        1.4  src/bos/usr/lib/assist/fr_CA/softlic.msg, cmdassist, bos41J, 9521B_all 5/26/95 14:41:02
$
$ COMPONENT_NAME:
$
$ FUNCTIONS:  Message catalog for Software License Agreement
$
$ ORIGINS:  27
$
$  (C) COPYRIGHT International Business Machines Corp. 1994
$   All Rights Reserved
$   Licensed Materials - Property of IBM
$   US Government Users Restricted Rights - Use, duplication or
$   disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
$ --------------------------------------------------------------------
 
$quote "
$
$set 1
 
$
$ NOTE to translators:
$   The following messages should be able to be displayed on
$   a 80 column screen.
$
 
1 "\
       LICENCE RELATIVE AU MICROCODE DU SYSTÈME RISC/6000\n\
\n\
AIX version 4 intègre des fichiers de microcode destinés à être\n\
utilisés avec le Système RISC/6000 IBM. IBM détient tous les droits\n\
d'auteur relatifs à ce microcode. Par les présentes, IBM vous accorde\n\
une licence vous permettant d'exécuter ce microcode uniquement sur des\n\
machines RISC/6000 ou sur d'autres machines approuvées par IBM. IBM ne\n\
vous accorde toutefois aucune licence concernant la modification,\n\
l'affichage, l'adaptation, la distribution électronique, l'assemblage ou\n\
la compilation à rebours, le décodage, la traduction, la cession ou la\n\
location du microcode ou, encore, l'octroi de sous-licences relativement à\n\
celui-ci.\n\
\n\
REMARQUE. - Ce microcode ne se chargera pas automatiquement sur votre machine\n\
IBM, à moins qu'il ne s'agisse d'une machine RISC/6000. Tous les fichiers\n\
et supports contenant du microcode portent une légende à cet effet.\n\
\n"

2 "\
	       Contrat IBM de licence de programmes\n\
\n\
AVIS : SI VOUS ACQUÉREZ CE PROGRAMME D'IBM ET AVEZ SIGNÉ UN CONTRAT DE\n\
LICENCE AVEC IBM, LEDIT CONTRAT RÉGIRA L'UTILISATION DE CE PROGRAMME.\n\
SINON, VEUILLEZ LIRE ATTENTIVEMENT LE PRÉSENT CONTRAT AVANT D'UTILISER LE\n\
PROGRAMME, CAR IBM NE VOUS ACCORDERA DE LICENCE POUR LE PROGRAMME QUE SI VOUS\n\
ACCEPTEZ D'ABORD LES PRÉSENTES MODALITÉS. EN UTILISANT LE PROGRAMME,\n\
VOUS CONVENEZ DE RESPECTER LES MODALITÉS DU PRÉSENT CONTRAT AINSI QUE\n\
LES LOIS APPLICABLES EN MATIÈRE DE DROITS D'AUTEUR.  SI VOUS N'ACCEPTEZ\n\
PAS LES PRÉSENTES MODALITÉS, VEUILLEZ EN AVISER SANS DÉLAI LE\n\
FOURNISSEUR DU PROGRAMME ET LUI DEMANDER LE REMBOURSEMENT DE LA SOMME QUE\n\
VOUS LUI AVEZ PAYÉE.\n\
\n\
Ce programme est la propriété d'International Business Machines\n\
Corporation ou de ses filiales (IBM) ou, encore, de fournisseurs d'IBM, et il\n\
est protégé par des droits d'auteur. Il vous est fourni sous licence,\n\
et non vendu. IBM ne vous en transfère pas le titre de propriété.\n\
Les modalités du présent contrat s'appliquent à toute copie\n\
supplémentaire du programme qu'IBM vous autorise à faire.\n\
\n\
Par «programme», on entend l'original et toutes les copies\n\
intégrales ou partielles qui en sont faites, y compris les portions\n\
fusionnées avec d'autres programmes. Un programme consiste en des\n\
instructions assimilables par machine et des articles autorisés connexes,\n\
y compris de la documentation.\n\
\n\
IBM vous accorde une licence (ou permis d'utilisation) non exclusive vous\n\
permettant d'utiliser le programme dans le pays où vous l'avez acquis.\n\
Les spécifications, qui comprennent les «Caractéristiques du\n\
programme» (Licensed Program Specifications) et un document appelé\n\
«Avis de disponibilité», et qui sont intégrées à la\n\
documentation qu'IBM fournit avec le programme, peuvent contenir des\n\
modalités supplémentaires qui font partie de ce contrat.\n\
\n\
À moins que vous ayez signé un contrat de licence avec IBM, auquel cas\n\
ledit contrat s'applique, le présent contrat et ses documents\n\
transactionnels applicables (tels qu'une facture ou un supplément)\n\
constituent l'entente intégrale et unique relative au programme et\n\
remplacent toutes les autres communications, verbales ou écrites,\n\
échangées entre vous et IBM. Pour qu'une modification soit valide, elle\n\
doit faire l'objet d'un document signé par vous et IBM.\n\
\n\
Vous signifiez votre acceptation des modalités supplémentaires\n\
contenues dans un document transactionnel en utilisant le programme ou en\n\
acquittant toute somme s'y rapportant. En cas de divergence entre les\n\
modalités de différents documents, celles d'un document transactionnel\n\
prévaudront.\n\
\n"
 
3 "\
LICENCE\n\
\n\
En vertu de cette licence, vous pouvez : 1. utiliser le programme sur une\n\
seule machine à la fois; 2. le copier à des fins de sauvegarde; et\n\
3. le modifier ou le fusionner avec un autre programme.\n\
\n\
Vous convenez de reproduire, sur chaque copie intégrale ou partielle, la\n\
mention de droits d'auteur et toute autre légende concernant la\n\
propriété.\n\
\n\
Vous ne pouvez utiliser toute partie du programme portant une quelconque\n\
mention de restriction de la part d'IBM («Article IBM à usage\n\
restreint», par exemple), que pour : 1.  résoudre des incidents liés\n\
à l'utilisation du programme; et 2.  modifier le programme pour le rendre\n\
compatible avec d'autres produits.\n\
\n\
Vous convenez de ne pas : 1. utiliser, copier ou fusionner le programme\n\
autrement qu'il est stipulé dans ce contrat; 2. effectuer à rebours\n\
l'assemblage ou la compilation du programme ou autrement le traduire;\n\
3. transférer la licence relative au programme, sauf tel qu'IBM le permet\n\
expressément dans les spécifications; 4. céder ou louer, à bail\n\
ou non, la licence relative au programme, ou accorder de sous-licence; ni\n\
5. distribuer le programme à un tiers quel qu'il soit.\n\
\n\
FONCTIONS INDÉPENDANTES\n\
\n\
Certains programmes comportent des fonctions qui sont conçues pour être\n\
exécutées sur des machines autres que celle sur laquelle le programme\n\
est utilisé. Vous pouvez faire une (1) copie d'une fonction et de la\n\
documentation qui l'accompagne. Vous convenez de n'utiliser cette copie que\n\
sur une seule machine à la fois. Les personnes qui utilisent une machine\n\
située hors de votre entreprise peuvent utiliser ladite copie uniquement\n\
pour accéder au programme. L'utilisation de certaines de ces fonctions\n\
donne lieu à des redevances. Ces fonctions sont alors appelées\n\
«fonctions indépendantes», et vous devez payer des redevances à\n\
IBM pour chacune des copies que vous en faites.\n\
  \n\
PROTECTION DU PROGRAMME \n\
                \n\
Vous convenez : 1. de conserver un registre de toutes les copies du\n\
programme; et 2. de vous assurer que quiconque l'utilise le fait dans le\n\
cadre de votre utilisation autorisée et respecte les présentes\n\
modalités.\n\
                   \n\
REDEVANCES, PAIEMENT ET TAXES\n\
       \n\
Les redevances relatives aux programmes peuvent être sous forme de\n\
paiement unique, périodiques ou une combinaison des deux.\n\
\n\
Les redevances peuvent être fonction d'un groupe de machines qu'IBM\n\
précise. Dans ce cas, vous convenez d'aviser IBM ou son intermédiaire\n\
du type et du modèle de la machine sur laquelle le programme sera\n\
utilisé et de payer les redevances applicables. Les redevances peuvent\n\
également être fonction d'une unité de mesure (tel le nombre\n\
d'utilisateurs) qui sera précisée dans les spécifications. Dans ce\n\
cas, vous convenez d'aviser IBM ou son intermédiaire des unités de\n\
mesure et de payer les redevances applicables.\n\
              \n\
Si vous utilisez le programme sur une autre machine ou si vous changez\n\
d'unité de mesure, vous convenez d'en informer IBM ou son intermédiaire\n\
et de payer les redevances applicables. IBM n'accordera aucun remboursement\n\
en ce qui concerne les redevances déjà exigibles ou payées.\n\
              \n\
Vous devez payer les redevances à la personne (soit IBM, soit son\n\
intermédiaire) auprès de laquelle vous avez acquis le programme. Si\n\
vous l'avez acquis d'IBM, vous convenez de vous acquitter du paiement tel\n\
qu'elle le précise. Si une autorité impose un droit, une taxe ou une\n\
cotisation (à l'exclusion des impôts sur le revenu net d'IBM) à\n\
l'égard de ce contrat ou du programme lui-même, vous convenez de payer\n\
la somme exigée tel que le précisera IBM.\n\
                       \n\
IBM peut modifier les redevances périodiques applicables à des\n\
programmes acquis auprès d'elle (et non auprès de son\n\
intermédiaire), en vous donnant un avis écrit de trois (3) mois à\n\
cet effet.\n\
      \n\
PROGRAMMES À REDEVANCES PÉRIODIQUES      \n\
    \n\
La licence relative à un programme à redevances périodiques que vous\n\
avez acquis auprès d'un intermédiaire prend fin si la relation qui unit\n\
IBM et cet intermédiaire prend fin, à moins que vous ne conserviez le\n\
programme. Dans ce cas, vous devrez payer à IBM les redevances\n\
applicables.\n\
\n"
 
4 "\
GARANTIE LIMITÉE      \n\
              \n\
Pour chacun des programmes IBM garantis, IBM garantit : 1. qu'elle a le\n\
droit de le fournir sous licence; et 2. qu'il fonctionne conformément\n\
aux spécifications qui y sont associées. La période de garantie d'un\n\
programme expire lorsque les services de logiciel s'y rapportant ne sont plus\n\
offerts.\n\
\n\
Durant la période de garantie, IBM offre gratuitement des services\n\
prévus par la garantie sous forme de services de logiciel. Les services de\n\
logiciel sont offerts pour un programme garanti pendant une période\n\
minimale de un (1) an à compter de sa date de disponibilité\n\
générale. Par conséquent, la durée des services prévus par la\n\
garantie est fonction du moment où vous obtenez votre licence. Si, au\n\
cours de la première année à compter du moment où vous obtenez\n\
votre licence, le programme ne fonctionne pas tel que le prévoit la\n\
garantie et qu'IBM ne puisse faire en sorte qu'il fonctionne ainsi, vous\n\
pouvez le retourner à IBM (ou à son intermédiaire) et obtenir le\n\
remboursement des sommes que vous aurez versées. Pour pouvoir vous\n\
prévaloir de cette disposition, vous devez avoir acquis le programme alors\n\
que les services de logiciel s'y rapportant étaient disponibles (peu\n\
importe pour combien de temps encore ils l'étaient).\n\
\n\
L'exploitation du programme dans un cadre d'utilisation autre que celui\n\
prescrit peut entraîner l'annulation des garanties.\n\
\n\
CES GARANTIES REMPLACENT TOUTES LES AUTRES GARANTIES ET CONDITIONS, EXPRESSES\n\
OU IMPLICITES, NOTAMMENT LES GARANTIES OU CONDITIONS IMPLICITES DE VALEUR\n\
MARCHANDE ET D'ADAPTATION À UNE FIN PARTICULIÈRE.\n\
\n\
IBM ne garantit pas qu'un programme fonctionnera sans interruption ni sans\n\
erreur. IBM identifiera les programmes pour lesquels elle n'offre aucune\n\
garantie.\n\
\n\
Ces garanties vous confèrent des droits légaux spécifiques, qui\n\
s'ajoutent aux autres droits dont vous pouvez bénéficier en vertu de\n\
lois qui varient d'un pays à l'autre. De plus, certaines lois ne\n\
permettant pas l'exclusion de garanties implicites, ladite exclusion peut ne\n\
pas s'appliquer dans votre cas. Ces garanties implicites ne seront alors\n\
valables que pendant la période de garantie. Aucune garantie ne\n\
s'appliquera après ladite période.\n\
\n\
SERVICES DE LOGICIEL \n\
\n\
IBM fournit des services de logiciel pour les programmes garantis et pour\n\
certains autres programmes. Si IBM peut reproduire l'incident que vous lui\n\
avez signalé dans le cadre d'utilisation prescrit, elle vous fournira des\n\
informations de correction ou de contournement du défaut ou, encore, vous\n\
avisera d'une restriction de fonction. IBM n'assure de services de logiciel\n\
que pour la portion non modifiée de la version courante d'un programme.\n\
\n\
Si vous avez acquis le programme auprès d'elle, IBM vous fournira\n\
directement les services de logiciel. Si vous l'avez acquis auprès d'un\n\
intermédiaire IBM, IBM fournira les services de logiciel à ce dernier\n\
(qui, à son tour, vous les fournira).\n\
\n\
IBM assure les services de logiciel : 1. pour une période\n\
indéterminée (dans ce cas, elle doit donner un préavis d'au moins six\n\
(6) mois avant de mettre fin aux services offerts pour un programme); \n\
2. jusqu'à la date qu'elle précise; ou 3. pour la période qu'elle\n\
précise.\n\
\n\
BREVETS ET DROITS D'AUTEUR \n\
            \n\
Si un tiers allègue qu'un programme qu'IBM vous fournit contrevient à\n\
un brevet ou viole des droits d'auteur qu'il détient, IBM vous défendra\n\
à ses frais contre cette réclamation et paiera tous les dépens,\n\
dommages-intérêts et frais judiciaires accordés en dernier ressort\n\
par un tribunal, à condition que : 1. vous l'avisiez par écrit, sans\n\
délai, de la réclamation; et 2. vous lui permettiez de diriger la\n\
défense et les négociations entamées en vue de régler le litige\n\
et coopériez pleinement avec elle dans ces procédures.\n\
          \n\
Si une telle réclamation est faite ou paraît probable, vous convenez\n\
d'autoriser IBM à faire en sorte que vous puissiez continuer à utiliser\n\
le programme ou à le modifier ou, encore, à le remplacer par un\n\
programme présentant au moins des fonctions équivalentes. Si IBM\n\
détermine qu'aucune de ces solutions n'est raisonnablement possible, vous\n\
convenez de lui retourner le programme, sur demande écrite de sa part. IBM\n\
vous accordera alors un crédit dans le cas des programmes donnant lieu\n\
à des redevances sous forme de paiement unique, à condition toutefois\n\
que lesdites redevances aient été intégralement payées.\n\
     \n\
Les dispositions de cette clause définissent l'entière\n\
responsabilité d'IBM à votre égard relativement à toute\n\
réclamation fondée sur la contrefaçon de brevets ou la violation de\n\
droits d'auteur.\n\
                     \n\
IBM n'assume aucune obligation relativement à toute réclamation\n\
fondée : 1. sur votre modification d'un programme; 2. sur la combinaison,\n\
l'exploitation ou l'utilisation d'un programme avec un produit, des\n\
données ou des appareils non fournis par IBM; ni 3. sur la contrefaçon\n\
de brevets ou la violation de droits d'auteur par un programme non IBM.\n\
\n\
LIMITATION DE RESPONSABILITÉ \n\
           \n\
Des circonstances peuvent survenir vous donnant le droit, en raison d'un\n\
manquement de la part d'IBM (notamment la violation d'une condition\n\
fondamentale) ou d'une autre forme de responsabilité (y compris la\n\
négligence ou une fausse déclaration), de réclamer des\n\
dommages-intérêts d'IBM. Dans chaque cas, quel que soit le fondement de\n\
votre réclamation, IBM n'est responsable que : 1. des paiements\n\
mentionnés à la clause intitulée «Brevets et droits d'auteur»\n\
ci-dessus; 2. des lésions corporelles (y compris le décès) et des\n\
dommages causés aux biens immobiliers et aux biens mobiliers tangibles; et\n\
3. du montant de toute autre perte ou de tout autre dommage réellement\n\
subi, jusqu'à concurrence du plus élevé des montants suivants : 100\n\
000 $ US ou les redevances associées au programme. Dans le cas des\n\
redevances périodiques, ce montant correspond aux redevances de douze (12)\n\
mois.\n\
\n\
Cette limitation de responsabilité s'étend également à tout\n\
concepteur d'un programme fourni à IBM. Les montants susmentionnés\n\
constituent le maximum dont IBM et ledit concepteur sont collectivement\n\
responsables.\n\
\n\
IBM ne peut en aucun cas être tenue responsable : 1. des réclamations\n\
dirigées contre vous par un tiers relativement à des pertes ou à des\n\
dommages (autres que ceux qui sont mentionnés aux points 1 et 2\n\
ci-dessus); ni 2. de la perte ou de l'endommagement de vos enregistrements ou\n\
de vos données.\n\
\n\
IBM NE PEUT ÊTRE TENUE RESPONSABLE DE LA PERTE DE BÉNÉFICES OU\n\
PROFITS, DE L'IMPOSSIBILITÉ DE RÉALISER DES ÉCONOMIES, DES DOMMAGES\n\
ACCESSOIRES, SPÉCIAUX OU INDIRECTS NI DES AUTRES DOMMAGES ÉCONOMIQUES\n\
INDIRECTS, ET CE, MÊME SI IBM OU SON INTERMÉDIAIRE A ÉTÉ AVISÉ\n\
DE LA POSSIBILITÉ DE LEUR SURVENANCE. CERTAINES LOIS NE PERMETTENT PAS\n\
L'EXCLUSION OU LA LIMITATION DES DOMMAGES ACCESSOIRES OU INDIRECTS. LES\n\
LIMITATIONS OU EXCLUSIONS QUI PRÉCÈDENT PEUVENT DONC NE PAS\n\
S'APPLIQUER DANS VOTRE CAS.\n\
\n"
 
5 "\
DISPOSITIONS GÉNÉRALES \n\
\n\
Veuillez conserver une copie de votre reçu ou de votre facture afin\n\
d'établir la preuve de votre licence.\n\
\n\
Vous pouvez mettre fin à votre licence sur avis écrit de un (1) mois.\n\
IBM peut révoquer votre licence si vous ne respectez pas les présentes\n\
modalités. Dans les deux cas, vous devez détruire toutes vos copies du\n\
programme. Vous pouvez toutefois en conserver une (1) copie pour vos\n\
archives.\n\
\n\
Aucune des parties ne peut intenter d'action en vertu de ce contrat plus\n\
de deux (2) ans après la date de l'événement qui lui a donné\n\
naissance.\n\
\n\
Ce contrat est régi par les lois du pays dans lequel vous avez acquis le\n\
programme, sauf que : 1. si vous avez acquis le programme aux États-Unis\n\
ou à Porto Rico, il sera régi par les lois de l'État de New York; et\n\
2. si vous avez acquis le programme au Canada, il sera régi par les lois\n\
de la province d'Ontario."

6 "\n\n\nFaites Entrée pour signer le Contrat IBM de licence de programmes.\n"
 
7 "Contrat de licence de logiciel"
 
8 "Pour les programmes acquis en Europe, au Moyen-Orient ou en Afrique"
 
9 "Pour les programmes acquis dans tous les autres pays"
 
10 "Tel qu'il est indiqué sur l'emballage, IBM ne vous accordera de licence pour ce programme que si vous acceptez d'abord toutes les MODALITÉS ET CONDITIONS du CONTRAT IBM DE LICENCE DE PROGRAMMES que vous venez de visualiser.\n\n\
Acceptez-vous toutes ces MODALITÉS ET CONDITIONS?\n\n\
Si c'est le cas, signez ce document en entrant votre nom dans la zone ci-dessous. Si vous N'ACCEPTEZ PAS ces MODALITÉS ET CONDITIONS, vous pouvez SORTIR de ce programme sans entrer votre nom et retourner le programme pour obtenir un remboursement intégral."
 
11 "Aucune autre action nécessaire. Faites Entrée pour poursuivre."
 
12 "Entrez votre nom"
 
13 "Signature de la licence"
 
14 "Annulation"
 
15 "Sauvegarde"
 
16 "Entrez votre nom :"
 
17 "Vous devez taper des données dans la zone d'entrée."
 
18 "OK"

19 "Pour les programmes acquis en Australie."

$set 2
 
$
$ NOTE to translators:
$   The following messages should be able to be displayed on
$   a 80 column screen.
$
 
1 "\
       LICENCE RELATIVE AU MICROCODE DU SYSTÈME RISC/6000\n\
\n\
AIX version 4 intègre des fichiers de microcode destinés à être\n\
utilisés avec le Système RISC/6000 IBM. IBM détient tous les droits\n\
d'auteur relatifs à ce microcode. Par les présentes, IBM vous accorde\n\
une licence vous permettant d'exécuter ce microcode uniquement sur des\n\
machines RISC/6000 ou sur d'autres machines approuvées par IBM. IBM ne\n\
vous accorde toutefois aucune licence concernant la modification,\n\
l'affichage, l'adaptation, la distribution électronique, l'assemblage ou\n\
la compilation à rebours, le décodage, la traduction, la cession ou la\n\
location du microcode ou, encore, l'octroi de sous-licences relativement à\n\
celui-ci.\n\
\n\
REMARQUE. - Ce microcode ne se chargera pas automatiquement sur votre machine\n\
IBM, à moins qu'il ne s'agisse d'une machine RISC/6000. Tous les fichiers\n\
et supports contenant du microcode portent une légende à cet effet.\n\
\n"

2 "\
	       Contrat IBM de licence de programmes\n\
\n\
AVIS : SI VOUS ACQUÉREZ CE PROGRAMME D'IBM ET AVEZ SIGNÉ UN CONTRAT DE\n\
LICENCE AVEC IBM, LEDIT CONTRAT RÉGIRA L'UTILISATION DE CE PROGRAMME.\n\
SINON, VEUILLEZ LIRE ATTENTIVEMENT LE PRÉSENT CONTRAT AVANT D'UTILISER LE\n\
PROGRAMME, CAR IBM NE VOUS ACCORDERA DE LICENCE POUR LE PROGRAMME QUE SI VOUS\n\
ACCEPTEZ D'ABORD LES PRÉSENTES MODALITÉS. EN UTILISANT LE PROGRAMME,\n\
VOUS CONVENEZ DE RESPECTER LES MODALITÉS DU PRÉSENT CONTRAT AINSI QUE\n\
LES LOIS APPLICABLES EN MATIÈRE DE DROITS D'AUTEUR.  SI VOUS N'ACCEPTEZ\n\
PAS LES PRÉSENTES MODALITÉS, VEUILLEZ EN AVISER SANS DÉLAI LE\n\
FOURNISSEUR DU PROGRAMME ET LUI DEMANDER LE REMBOURSEMENT DE LA SOMME QUE\n\
VOUS LUI AVEZ PAYÉE.\n\
\n\
Ce programme est la propriété d'International Business Machines\n\
Corporation ou de ses filiales (IBM) ou, encore, de fournisseurs d'IBM, et il\n\
est protégé par des droits d'auteur. Il vous est fourni sous licence,\n\
et non vendu. IBM ne vous en transfère pas le titre de propriété.\n\
Les modalités du présent contrat s'appliquent à toute copie\n\
supplémentaire du programme qu'IBM vous autorise à faire.\n\
\n\
Par «programme», on entend l'original et toutes les copies\n\
intégrales ou partielles qui en sont faites, y compris les portions\n\
fusionnées avec d'autres programmes. Un programme consiste en des\n\
instructions assimilables par machine et des articles autorisés connexes,\n\
y compris de la documentation.\n\
\n\
IBM vous accorde une licence (ou permis d'utilisation) non exclusive vous\n\
permettant d'utiliser le programme dans le pays où vous l'avez acquis.\n\
Les spécifications, qui comprennent les «Caractéristiques du\n\
programme» (Licensed Program Specifications) et un document appelé\n\
«Avis de disponibilité», et qui sont intégrées à la\n\
documentation qu'IBM fournit avec le programme, peuvent contenir des\n\
modalités supplémentaires qui font partie de ce contrat.\n\
\n\
À moins que vous ayez signé un contrat de licence avec IBM, auquel cas\n\
ledit contrat s'applique, le présent contrat et ses documents\n\
transactionnels applicables (tels qu'une facture ou un supplément)\n\
constituent l'entente intégrale et unique relative au programme et\n\
remplacent toutes les autres communications, verbales ou écrites,\n\
échangées entre vous et IBM. Pour qu'une modification soit valide, elle\n\
doit faire l'objet d'un document signé par vous et IBM.\n\
\n\
Vous signifiez votre acceptation des modalités supplémentaires\n\
contenues dans un document transactionnel en utilisant le programme ou en\n\
acquittant toute somme s'y rapportant. En cas de divergence entre les\n\
modalités de différents documents, celles d'un document transactionnel\n\
prévaudront.\n\
\n"
 
3 "\
LICENCE\n\
\n\
En vertu de cette licence, vous pouvez : 1. utiliser le programme sur une\n\
seule machine à la fois; 2. le copier à des fins de sauvegarde; et\n\
3. le modifier ou le fusionner avec un autre programme.\n\
\n\
Vous convenez de reproduire, sur chaque copie intégrale ou partielle, la\n\
mention de droits d'auteur et toute autre légende concernant la\n\
propriété.\n\
\n\
Vous ne pouvez utiliser toute partie du programme portant une quelconque\n\
mention de restriction de la part d'IBM («Article IBM à usage\n\
restreint», par exemple), que pour : 1.  résoudre des incidents liés\n\
à l'utilisation du programme; et 2.  modifier le programme pour le rendre\n\
compatible avec d'autres produits.\n\
\n\
Vous convenez de ne pas : 1. utiliser, copier ou fusionner le programme\n\
autrement qu'il est stipulé dans ce contrat; 2. effectuer à rebours\n\
l'assemblage ou la compilation du programme ou autrement le traduire;\n\
3. transférer la licence relative au programme, sauf tel qu'IBM le permet\n\
expressément dans les spécifications; 4. céder ou louer, à bail\n\
ou non, la licence relative au programme, ou accorder de sous-licence; ni\n\
5. distribuer le programme à un tiers quel qu'il soit.\n\
\n\
FONCTIONS INDÉPENDANTES\n\
\n\
Certains programmes comportent des fonctions qui sont conçues pour être\n\
exécutées sur des machines autres que celle sur laquelle le programme\n\
est utilisé. Vous pouvez faire une (1) copie d'une fonction et de la\n\
documentation qui l'accompagne. Vous convenez de n'utiliser cette copie que\n\
sur une seule machine à la fois. Les personnes qui utilisent une machine\n\
située hors de votre entreprise peuvent utiliser ladite copie uniquement\n\
pour accéder au programme. L'utilisation de certaines de ces fonctions\n\
donne lieu à des redevances. Ces fonctions sont alors appelées\n\
«fonctions indépendantes», et vous devez payer des redevances à\n\
IBM pour chacune des copies que vous en faites.\n\
  \n\
PROTECTION DU PROGRAMME \n\
                \n\
Vous convenez : 1. de conserver un registre de toutes les copies du\n\
programme; et 2. de vous assurer que quiconque l'utilise le fait dans le\n\
cadre de votre utilisation autorisée et respecte les présentes\n\
modalités.\n\
                   \n\
REDEVANCES, PAIEMENT ET TAXES\n\
       \n\
Les redevances relatives aux programmes peuvent être sous forme de\n\
paiement unique, périodiques ou une combinaison des deux.\n\
\n\
Les redevances peuvent être fonction d'un groupe de machines qu'IBM\n\
précise. Dans ce cas, vous convenez d'aviser IBM ou son intermédiaire\n\
du type et du modèle de la machine sur laquelle le programme sera\n\
utilisé et de payer les redevances applicables. Les redevances peuvent\n\
également être fonction d'une unité de mesure (tel le nombre\n\
d'utilisateurs) qui sera précisée dans les spécifications. Dans ce\n\
cas, vous convenez d'aviser IBM ou son intermédiaire des unités de\n\
mesure et de payer les redevances applicables.\n\
              \n\
Si vous utilisez le programme sur une autre machine ou si vous changez\n\
d'unité de mesure, vous convenez d'en informer IBM ou son intermédiaire\n\
et de payer les redevances applicables. IBM n'accordera aucun remboursement\n\
en ce qui concerne les redevances déjà exigibles ou payées.\n\
              \n\
Vous devez payer les redevances à la personne (soit IBM, soit son\n\
intermédiaire) auprès de laquelle vous avez acquis le programme. Si\n\
vous l'avez acquis d'IBM, vous convenez de vous acquitter du paiement tel\n\
qu'elle le précise. Si une autorité impose un droit, une taxe ou une\n\
cotisation (à l'exclusion des impôts sur le revenu net d'IBM) à\n\
l'égard de ce contrat ou du programme lui-même, vous convenez de payer\n\
la somme exigée tel que le précisera IBM.\n\
                       \n\
IBM peut modifier les redevances périodiques applicables à des\n\
programmes acquis auprès d'elle (et non auprès de son\n\
intermédiaire), en vous donnant un avis écrit de trois (3) mois à\n\
cet effet.\n\
      \n\
PROGRAMMES À REDEVANCES PÉRIODIQUES      \n\
    \n\
La licence relative à un programme à redevances périodiques que vous\n\
avez acquis auprès d'un intermédiaire prend fin si la relation qui unit\n\
IBM et cet intermédiaire prend fin, à moins que vous ne conserviez le\n\
programme. Dans ce cas, vous devrez payer à IBM les redevances\n\
applicables.\n\
\n"
 
4 "\
GARANTIE LIMITÉE      \n\
              \n\
Pour chacun des programmes IBM garantis, IBM garantit : 1. qu'elle a le\n\
droit de le fournir sous licence; et 2. qu'il fonctionne conformément\n\
aux spécifications qui y sont associées. La période de garantie d'un\n\
programme expire lorsque les services de logiciel s'y rapportant ne sont plus\n\
offerts.\n\
\n\
Durant la période de garantie, IBM offre gratuitement des services\n\
prévus par la garantie sous forme de services de logiciel. Les services de\n\
logiciel sont offerts pour un programme garanti pendant une période\n\
minimale de un (1) an à compter de sa date de disponibilité\n\
générale. Par conséquent, la durée des services prévus par la\n\
garantie est fonction du moment où vous obtenez votre licence. Si, au\n\
cours de la première année à compter du moment où vous obtenez\n\
votre licence, le programme ne fonctionne pas tel que le prévoit la\n\
garantie et qu'IBM ne puisse faire en sorte qu'il fonctionne ainsi, vous\n\
pouvez le retourner à IBM (ou à son intermédiaire) et obtenir le\n\
remboursement des sommes que vous aurez versées. Pour pouvoir vous\n\
prévaloir de cette disposition, vous devez avoir acquis le programme alors\n\
que les services de logiciel s'y rapportant étaient disponibles (peu\n\
importe pour combien de temps encore ils l'étaient).\n\
\n\
L'exploitation du programme dans un cadre d'utilisation autre que celui\n\
prescrit peut entraîner l'annulation des garanties.\n\
\n\
CES GARANTIES REMPLACENT TOUTES LES AUTRES GARANTIES ET CONDITIONS, EXPRESSES\n\
OU IMPLICITES, NOTAMMENT LES GARANTIES OU CONDITIONS IMPLICITES DE VALEUR\n\
MARCHANDE ET D'ADAPTATION À UNE FIN PARTICULIÈRE.\n\
\n\
IBM ne garantit pas qu'un programme fonctionnera sans interruption ni sans\n\
erreur. IBM identifiera les programmes pour lesquels elle n'offre aucune\n\
garantie.\n\
\n\
Ces garanties vous confèrent des droits légaux spécifiques, qui\n\
s'ajoutent aux autres droits dont vous pouvez bénéficier en vertu de\n\
lois qui varient d'un pays à l'autre. De plus, certaines lois ne\n\
permettant pas l'exclusion de garanties implicites, ladite exclusion peut ne\n\
pas s'appliquer dans votre cas. Ces garanties implicites ne seront alors\n\
valables que pendant la période de garantie. Aucune garantie ne\n\
s'appliquera après ladite période.\n\
\n\
SERVICES DE LOGICIEL \n\
\n\
IBM fournit des services de logiciel pour les programmes garantis et pour\n\
certains autres programmes. Si IBM peut reproduire l'incident que vous lui\n\
avez signalé dans le cadre d'utilisation prescrit, elle vous fournira des\n\
informations de correction ou de contournement du défaut ou, encore, vous\n\
avisera d'une restriction de fonction. IBM n'assure de services de logiciel\n\
que pour la portion non modifiée de la version courante d'un programme.\n\
\n\
Si vous avez acquis le programme auprès d'elle, IBM vous fournira\n\
directement les services de logiciel. Si vous l'avez acquis auprès d'un\n\
intermédiaire IBM, IBM fournira les services de logiciel à ce dernier\n\
(qui, à son tour, vous les fournira).\n\
\n\
IBM assure les services de logiciel : 1. pour une période\n\
indéterminée (dans ce cas, elle doit donner un préavis d'au moins six\n\
(6) mois avant de mettre fin aux services offerts pour un programme); \n\
2. jusqu'à la date qu'elle précise; ou 3. pour la période qu'elle\n\
précise.\n\
\n\
BREVETS ET DROITS D'AUTEUR \n\
            \n\
Si un tiers allègue qu'un programme qu'IBM vous fournit contrevient à\n\
un brevet ou viole des droits d'auteur qu'il détient, IBM vous défendra\n\
à ses frais contre cette réclamation et paiera tous les dépens,\n\
dommages-intérêts et frais judiciaires accordés en dernier ressort\n\
par un tribunal, à condition que : 1. vous l'avisiez par écrit, sans\n\
délai, de la réclamation; et 2. vous lui permettiez de diriger la\n\
défense et les négociations entamées en vue de régler le litige\n\
et coopériez pleinement avec elle dans ces procédures.\n\
          \n\
Si une telle réclamation est faite ou paraît probable, vous convenez\n\
d'autoriser IBM à faire en sorte que vous puissiez continuer à utiliser\n\
le programme ou à le modifier ou, encore, à le remplacer par un\n\
programme présentant au moins des fonctions équivalentes. Si IBM\n\
détermine qu'aucune de ces solutions n'est raisonnablement possible, vous\n\
convenez de lui retourner le programme, sur demande écrite de sa part. IBM\n\
vous accordera alors un crédit dans le cas des programmes donnant lieu\n\
à des redevances sous forme de paiement unique, à condition toutefois\n\
que lesdites redevances aient été intégralement payées.\n\
     \n\
Les dispositions de cette clause définissent l'entière\n\
responsabilité d'IBM à votre égard relativement à toute\n\
réclamation fondée sur la contrefaçon de brevets ou la violation de\n\
droits d'auteur.\n\
                     \n\
IBM n'assume aucune obligation relativement à toute réclamation\n\
fondée : 1. sur votre modification d'un programme; 2. sur la combinaison,\n\
l'exploitation ou l'utilisation d'un programme avec un produit, des\n\
données ou des appareils non fournis par IBM; ni 3. sur la contrefaçon\n\
de brevets ou la violation de droits d'auteur par un programme non IBM.\n\
\n\
LIMITATION DE RESPONSABILITÉ \n\
           \n\
Des circonstances peuvent survenir vous donnant le droit, en raison d'un\n\
manquement de la part d'IBM (notamment la violation d'une condition\n\
fondamentale) ou d'une autre forme de responsabilité (y compris la\n\
négligence ou une fausse déclaration), de réclamer des\n\
dommages-intérêts d'IBM. Dans chaque cas, quel que soit le fondement de\n\
votre réclamation, IBM n'est responsable que : 1. des paiements\n\
mentionnés à la clause intitulée «Brevets et droits d'auteur»\n\
ci-dessus; 2. des lésions corporelles (y compris le décès) et des\n\
dommages causés aux biens immobiliers et aux biens mobiliers tangibles; et\n\
3. du montant de toute autre perte ou de tout autre dommage réellement\n\
subi, jusqu'à concurrence du plus élevé des montants suivants : 100\n\
000 $ US ou les redevances associées au programme. Dans le cas des\n\
redevances périodiques, ce montant correspond aux redevances de douze (12)\n\
mois.\n\
\n\
Cette limitation de responsabilité s'étend également à tout\n\
concepteur d'un programme fourni à IBM. Les montants susmentionnés\n\
constituent le maximum dont IBM et ledit concepteur sont collectivement\n\
responsables.\n\
\n\
IBM ne peut en aucun cas être tenue responsable : 1. des réclamations\n\
dirigées contre vous par un tiers relativement à des pertes ou à des\n\
dommages (autres que ceux qui sont mentionnés aux points 1 et 2\n\
ci-dessus); ni 2. de la perte ou de l'endommagement de vos enregistrements ou\n\
de vos données.\n\
\n\
IBM NE PEUT ÊTRE TENUE RESPONSABLE DE LA PERTE DE BÉNÉFICES OU\n\
PROFITS, DE L'IMPOSSIBILITÉ DE RÉALISER DES ÉCONOMIES, DES DOMMAGES\n\
ACCESSOIRES, SPÉCIAUX OU INDIRECTS NI DES AUTRES DOMMAGES ÉCONOMIQUES\n\
INDIRECTS, ET CE, MÊME SI IBM OU SON INTERMÉDIAIRE A ÉTÉ AVISÉ\n\
DE LA POSSIBILITÉ DE LEUR SURVENANCE. CERTAINES LOIS NE PERMETTENT PAS\n\
L'EXCLUSION OU LA LIMITATION DES DOMMAGES ACCESSOIRES OU INDIRECTS. LES\n\
LIMITATIONS OU EXCLUSIONS QUI PRÉCÈDENT PEUVENT DONC NE PAS\n\
S'APPLIQUER DANS VOTRE CAS.\n\
\n"
 
5 "\
DISPOSITIONS GÉNÉRALES \n\
\n\
Veuillez conserver une copie de votre reçu ou de votre facture afin\n\
d'établir la preuve de votre licence.\n\
\n\
Vous pouvez mettre fin à votre licence sur avis écrit de un (1) mois.\n\
IBM peut révoquer votre licence si vous ne respectez pas les présentes\n\
modalités. Dans les deux cas, vous devez détruire toutes vos copies du\n\
programme. Vous pouvez toutefois en conserver une (1) copie pour vos\n\
archives.\n\
\n\
Aucune des parties ne peut intenter d'action en vertu de ce contrat plus\n\
de deux (2) ans après la date de l'événement qui lui a donné\n\
naissance.\n\
\n\
Ce contrat est régi par les lois du pays dans lequel vous avez acquis le\n\
programme, sauf que : 1. si vous avez acquis le programme aux États-Unis\n\
ou à Porto Rico, il sera régi par les lois de l'État de New York; et\n\
2. si vous avez acquis le programme au Canada, il sera régi par les lois\n\
de la province d'Ontario."

