# @(#)70        1.1  src/bldenv/ls/Makefile, ade_build, bos412, GOLDA411a 9/27/94 09:52:39
#
#   COMPONENT_NAME: BOSBUILD
#
#   FUNCTIONS:
#
#   ORIGINS: 27
#
#   IBM CONFIDENTIAL -- (IBM Confidential Restricted when
#   combined with the aggregated modules for this product)
#                    SOURCE MATERIALS
#
#   (C) COPYRIGHT International Business Machines Corp. 1993
#   All Rights Reserved
#   US Government Users Restricted Rights - Use, duplication or
#   disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#

VPATH		= ${MAKETOP}/bos/usr/bin/ls

PROGRAMS	= ls 
MSGHDRS		= ls_msg.h
CATFILES	= ls.cat
HFILES		= ${MSGHDRS}

ILIST		= ls 
IDIR		= /bin/


.include <${RULES_MK}>
