# @(#)35	1.1  src/bos/usr/lpp/kls/defaults/Makefile, libkr, bos411, 9428A410j 1/13/93 12:35:36
#
# COMPONENT_NAME:  LIBKR
#
# FUNCTIONS: Korean Input Method Defaults File
#
# ORIGINS: 27
#
# IBM CONFIDENTIAL -- (IBM Confidential Restricted when
# combined with the aggregated modules for this product)
#                  SOURCE MATERIALS
# (C) COPYRIGHT International Business Machines Corp. 1988, 1993
# All Rights Reserved
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#

ILIST 	= kimrc
IDIR	= /usr/lpp/kls/defaults/

.include <${RULES_MK}>
