# static char sccsid[] = "@(#)45    1.3  src/bos/usr/lbin/trmps/Makefile, sysxmps, bos411, 9438A411a 9/18/94 19:24:04";
#
#   COMPONENT_NAME: sysxmps
#
#   FUNCTIONS: none
#
#   ORIGINS: 27
#
#   IBM CONFIDENTIAL -- (IBM Confidential Restricted when
#   combined with the aggregated modules for this product)
#                    SOURCE MATERIALS
#
#   (C) COPYRIGHT International Business Machines Corp. 1994
#   All Rights Reserved
#   US Government Users Restricted Rights - Use, duplication or
#   disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#

PROGRAMS        = trmps 

OFILES		= main.o trmps_dmp.o 

INCFLAGS        = -I${MAKETOP}/bos/kernext/mps_tok

ILIST           = trmps 

IDIR		= /usr/lib/ras/dmprtns/

.include <${RULES_MK}>
