# @(#)13        1.1  src/bos/usr/lib/methods/ucfggraphics/Makefile, dispcfg, bos411, 9428A410j 12/3/93 13:44:22
#
# COMPONENT_NAME: (DISPCFG)  Generic Functions for Display Configuration
#
# FUNCTIONS:
#
# ORIGINS: 27
#
# IBM CONFIDENTIAL -- (IBM Confidential Restricted when
# combined with the aggregated modules for this product)
#                  SOURCE MATERIALS
# (C) COPYRIGHT International Business Machines Corp. 1993
# All Rights Reserved
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#

PROGRAMS	= ucfggraphics

INCFLAGS	= -I../common
##CFLAGS		= -DDEBUG -DCFGDEBUG
ILIST		= ucfggraphics
IDIR		= /usr/lib/methods/

LIBS		= -ls -lodm -lcfg -lrts

.include <${RULES_MK}>
