#  @(#)05	1.1  src/bos/diag/tu/ped4/mcode_binary/Makefile, tu_ped4, bos411, 9428A410j 11/12/93 15:40:37 
#
#   COMPONENT_NAME: tu_ped4
#
#   FUNCTIONS: 
#
#   ORIGINS: 27
#
#   IBM CONFIDENTIAL -- (IBM Confidential Restricted when
#   combined with the aggregated modules for this product)
#                    SOURCE MATERIALS
#
#   (C) COPYRIGHT International Business Machines Corp. 1992, 1993
#   All Rights Reserved
#   US Government Users Restricted Rights - Use, duplication or
#   disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#


ILIST	= \
		8ee3p4d1.00.01 \
		8ee3p4d2.00.01 \
		8ee3p4d3.00.01 \
		8ee3p4d4.00.01 \
		8ee3p4d5.00.01

IDIR		= /usr/lib/microcode/


OTHERS=

OTHERS+=8ee3p4d1.00.01
8ee3p4d1.00.01:8ee3p4d1.00.01.ibmstub
	-${RM} -f ${.TARGET}
	${CP} -f ${.ALLSRC} ${.TARGET}

OTHERS+=8ee3p4d2.00.01
8ee3p4d2.00.01:8ee3p4d2.00.01.ibmstub
	-${RM} -f ${.TARGET}
	${CP} -f ${.ALLSRC} ${.TARGET}

OTHERS+=8ee3p4d3.00.01
8ee3p4d3.00.01:8ee3p4d3.00.01.ibmstub
	-${RM} -f ${.TARGET}
	${CP} -f ${.ALLSRC} ${.TARGET}

OTHERS+=8ee3p4d4.00.01
8ee3p4d4.00.01:8ee3p4d4.00.01.ibmstub
	-${RM} -f ${.TARGET}
	${CP} -f ${.ALLSRC} ${.TARGET}

OTHERS+=8ee3p4d5.00.01
8ee3p4d5.00.01:8ee3p4d5.00.01.ibmstub
	-${RM} -f ${.TARGET}
	${CP} -f ${.ALLSRC} ${.TARGET}

.include <${RULES_MK}>
