# @(#)12       1.1  src/bldenv/loc/Makefile, cmdiconv, bos412, GOLDA411a 3/21/94 15:14:47
#
#   COMPONENT_NAME: CMDICONV
#
#   FUNCTIONS:
#
#   ORIGINS: 27
#
#   IBM CONFIDENTIAL -- (IBM Confidential Restricted when
#   combined with the aggregated modules for this product)
#                    SOURCE MATERIALS
#
#   (C) COPYRIGHT International Business Machines Corp. 1994
#   All Rights Reserved
#   US Government Users Restricted Rights - Use, duplication or
#   disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#

SUBDIRS		= iconv iconvTable

.include <${RULES_MK}>
