# @(#)17        1.4  src/bos/usr/lib/nim/awk/Makefile, cmdnim, bos411, 9428A410j 6/13/94 15:30:25
#
#   COMPONENT_NAME: CMDNIM
#
#   FUNCTIONS: ./lib/nim/awk/Makefile
#
#   ORIGINS: 27
#
#
#   (C) COPYRIGHT International Business Machines Corp. 1993
#   All Rights Reserved
#   Licensed Materials - Property of IBM
#   US Government Users Restricted Rights - Use, duplication or
#   disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#

SCRIPTS =	lsnim_l.awk \
				lsnim_L.awk \
				lsnim_P.awk \
				lsnim_pa.awk \
				popxop.awk \
				cutfs.awk \
				niminfo.awk \
				image_data.awk

ILIST		= ${SCRIPTS}

IDIR		= /usr/lpp/bos.sysmgt/nim/awk/

.include <${RULES_MK}>

