# @(#)18       1.1  src/bldenv/libg/Makefile, ade_build, bos412, GOLDA411a 9/7/94 15:27:03
#
# COMPONENT_NAME: ade_build
#
# FUNCTIONS:
#
# ORIGINS: 27
#
# IBM CONFIDENTIAL -- (IBM Confidential Restricted when
# combined with the aggregated modules for this product)
#                  SOURCE MATERIALS
# (C) COPYRIGHT International Business Machines Corp. 1988, 1989
# All Rights Reserved
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#

VPATH		= ${MAKETOP}bos/usr/ccs/lib/libg

ILIST           = libg.exp
IDIR            = /usr/lib/

.include <${RULES_MK}>
