# @(#)48        1.1  src/bldenv/tail/Makefile, ade_build, bos412, GOLDA411a 4/21/93 20:28:55
# COMPONENT_NAME:
#
# FUNCTIONS:
#
# ORIGINS: 27
#
# IBM CONFIDENTIAL -- (IBM Confidential Restricted when
# combined with the aggregated modules for this product)
#                  SOURCE MATERIALS
# (C) COPYRIGHT International Business Machines Corp. 1988, 1989
# All Rights Reserved
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#

VPATH           = ${MAKETOP}/bos/usr/bin/tail
PROGRAMS	= tail
MSGHDRS		= tail_msg.h
CATFILES	= tail.cat
HFILES		= ${MSGHDRS}

ILIST		= tail
IDIR		= /usr/bin/


.include <${RULES_MK}>
