# @(#)43	1.3  src/bos/diag/tu/dca/Makefile, tu_tca, bos411, 9428A410j 1/7/94 10:19:55
#
#   COMPONENT_NAME: TU_TCA
#
#   FUNCTIONS: 
#
#   ORIGINS: 27
#
#   IBM CONFIDENTIAL -- (IBM Confidential Restricted when
#   combined with the aggregated modules for this product)
#                    SOURCE MATERIALS
#
#   (C) COPYRIGHT International Business Machines Corp. 1992, 1994
#   All Rights Reserved
#   US Government Users Restricted Rights - Use, duplication or
#   disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#

#------------------------------------------------------------------------#
#                                                                        #
#     This Makefile builds the library libdcatu.a for the DA application #
#                                                                        #
#------------------------------------------------------------------------#

LIBRARIES       =   libdcatu.a

EXPLIB_TARGETS  =   export_libdcatu.a
EXPDIR          =   /usr/lib/

OFILES		= detrace.o \
			exectu.o \
			mktu_rc.o \
			rwtreg.o \
			sdelay.o \
			simrw.o \
			trcvcmd.o \
			tu001.o \
			tu002.o \
			tu003.o \
			tu004.o \
			tu005.o

.include <${RULES_MK}>
