static char sccsid[] = "@(#)02  1.2  src/bldenv/pkgtools/cdboot/Makefile, pkgtools, bos412, GOLDA411a 9/2/94 16:52:17";
# COMPONENT_NAME: pkgtools
#
# FUNCTIONS:
#
# ORIGINS: 27
#
# IBM CONFIDENTIAL -- (IBM Confidential Restricted when
# combined with the aggregated modules for this product)
#                  SOURCE MATERIALS
# (C) COPYRIGHT International Business Machines Corp. 1994
# All Rights Reserved
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#

INCFLAGS	= -I${MAKETOP}/rspc/usr/lib/boot/mkmboot
LINTFLAGS	+= ${_CCDEFS_} -wP -Nn3000 -Nd4000
PROGRAMS	= cdboot
ILIST		= cdboot
IDIR		= /usr/bin/

.include <${RULES_MK}>

