# @(#)96        1.1  src/bos/usr/lib/nls/loc/jim/jkkc/Makefile, libKJI, bos411, 9428A410j 1/20/93 10:59:19
#
# COMPONENT_NAME: libKJI
#
# FUNCTIONS: Japanese Input Method
#
# ORIGINS: 27
#
# IBM CONFIDENTIAL -- (IBM Confidential Restricted when
# combined with the aggregated modules for this product)
#                  SOURCE MATERIALS
# (C) COPYRIGHT International Business Machines Corp. 1989, 1991, 1993
# All Rights Reserved
# Licensed Materials - Property of IBM
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#

LIBRARIES	= libjkkc.a

CFLAGS		= -D_AIX -D_OLD
DEBUG		=

OFILES		= _Kc0dici.o \
			_Kcbpath.o \
			_Kcdctiq.o \
			_Kcjldct.o \
			_Kckcan3.o \
			_Kcncutb.o \
			_Kcrinit.o \
			_Kc0dicr.o \
			_Kcbproc.o \
			_Kcdctln.o \
			_Kcjmdct.o \
			_Kckcanr.o \
			_Kcnmtch.o \
			_Kcrproc.o \
			_Kc0flrn.o \
			_Kcbrbst.o \
			_Kcdctlw.o \
			_Kcjproc.o \
			_Kckicnv.o \
			_Kcnxtcv.o \
			_Kcrrstb.o \
			_Kcbsbst.o \
			_Kcdctrg.o \
			_Kcjsdct.o \
			_Kckkjtb.o \
			_Kcnxtop.o \
			_Kcrsfzk.o \
			_Kc0jlrn.o \
			_Kcc72hr.o \
			_Kcfchek.o \
			_Kcjsget.o \
			_Kckmktb.o \
			_Kcobro1.o \
			_Kcrsjrt.o \
			_Kc0lern.o \
			_Kcc72kn.o \
			_Kcfendm.o \
			_Kcjsgt1.o \
			_Kckncnv.o \
			_Kcobro2.o \
			_Kcrsout.o \
			_Kc0lrnw.o \
			_Kccbknj.o \
			_Kcffcon.o \
			_Kcjshsh.o \
			_Kckncv1.o \
			_Kcobrob.o \
			_Kcrtfcn.o \
			_Kcabcnv.o \
			_Kccfknj.o \
			_Kcffdct.o \
			_Kcjsjrt.o \
			_Kckpcnv.o \
			_Kcobrof.o \
			_Kcrtlcn.o \
			_Kcabrop.o \
			_Kccfpth.o \
			_Kcfhyki.o \
			_Kcjsknj.o \
			_Kckunit.o \
			_Kcobrop.o \
			_Kcsbro1.o \
			_Kcabrst.o \
			_Kccfree.o \
			_Kcfinit.o \
			_Kcjslng.o \
			_Kcladpr.o \
			_Kcofcnv.o \
			_Kcsbrop.o \
			_Kcaicnv.o \
			_Kccget.o  \
			_Kcfjclc.o \
			_Kclcadp.o \
			_Kcofkkc.o \
			_Kcsglbw.o \
			_Kcallbw.o \
			_Kccinit.o \
			_Kcfjcon.o \
			_Kcjstag.o \
			_Kcldcta.o \
			_Kcoicnv.o \
			_Kcsglfw.o \
			_Kcallfw.o \
			_Kccinsb.o \
			_Kcfproc.o \
			_Kcjsunq.o \
			_Kcldtsc.o \
			_Kcoicv1.o \
			_Kcsglop.o \
			_Kcallop.o \
			_Kccjknj.o \
			_Kcfsfzk.o \
			_Kcjudct.o \
			_Kcliccs.o \
			_Kcolcnv.o \
			_Kctmpry.o \
			_Kcamktb.o \
			_Kccldc0.o \
			_Kcfstmp.o \
			_Kcjuget.o \
			_Kclixsc.o \
			_Kconcnv.o \
			_Kcxcmpk.o \
			_Kcancnv.o \
			_Kccldcf.o \
			_Kcicmpt.o \
			_Kcjugt1.o \
			_Kclmrua.o \
			_Kconcv2.o \
			_Kcxcmpm.o \
			_Kcancv1.o \
			_Kccldcs.o \
			_Kcicode.o \
			_Kcjuhsh.o \
			_Kclmvch.o \
			_Kcopcnv.o \
			_Kcxcmpy.o \
			_Kcapcnv.o \
			_Kccldcu.o \
			_Kcilbst.o \
			_Kcjuknj.o \
			_Kclrepl.o \
			_Kcopdcf.o \
			_Kcxinia.o \
			_Kcbaddp.o \
			_Kcclose.o \
			_Kcimora.o \
			_Kcjulng.o \
			_Kcmbrop.o \
			_Kcopdcs.o \
			_Kcxstat.o \
			_Kcbbpen.o \
			_Kcconv.o  \
			_Kcinchk.o \
			_Kcjuunq.o \
			_Kcmicnv.o \
			_Kcopdcu.o \
			_Kcxusrd.o \
			_Kcbchkp.o \
			_Kccpurg.o \
			_Kcinprc.o \
			_Kck7ycd.o \
			_Kcmmktb.o \
			_Kcopen.o  \
			_Kczread.o \
			_Kcbcutp.o \
			_Kccswpb.o \
			_Kcjchek.o \
			_Kckbrop.o \
			_Kcmncnv.o \
			_Kcprvcv.o \
			_Kczwrit.o \
			_Kcbhyki.o \
			_Kccswpj.o \
			_Kcjdict.o \
			_Kckcan1.o \
			_Kcmncv1.o \
			_Kcrchek.o \
			_Kcbnewp.o \
			_Kccswpp.o \
			_Kcjjpen.o \
			_Kckcan2.o \
			_Kcmpcnv.o \
			_Kcrgeta.o \
			_Kc0init.o \
			CloseDict.o  \
			WatchUdict.o \
			OpenFile.o \
			_Kcfmtom.o   \
			_Kchkex.o    \
			_Kcjscnt.o   \
			_Kcosset.o   \
			_Knumchk.o   \
			_Knumset.o   \
			_Kcopdcf2.o  \
			_Kcopdcu2.o

.include <${RULES_MK}>
