#
# dependents of cfg_mag.o:
cfg_mag.o: ${MAKETOP}../export/power/usr/include/sys/types.h
cfg_mag.o: ${MAKETOP}../export/power/usr/include/standards.h
cfg_mag.o: ${MAKETOP}../export/power/usr/include/sys/m_types.h
cfg_mag.o: ${MAKETOP}../export/power/usr/include/stdio.h
cfg_mag.o: ${MAKETOP}../export/power/usr/include/va_list.h
cfg_mag.o: ${MAKETOP}../export/power/usr/include/sys/limits.h
cfg_mag.o: ${MAKETOP}../export/power/usr/include/float.h
cfg_mag.o: ${MAKETOP}../export/power/usr/include/fcntl.h
cfg_mag.o: ${MAKETOP}../export/power/usr/include/sys/flock.h
cfg_mag.o: ${MAKETOP}../export/power/usr/include/unistd.h
cfg_mag.o: ${MAKETOP}../export/power/usr/include/sys/access.h
cfg_mag.o: ${MAKETOP}../export/power/usr/include/sys/lockf.h
cfg_mag.o: ${MAKETOP}../export/power/usr/include/sys/stat.h
cfg_mag.o: ${MAKETOP}../export/power/usr/include/sys/mode.h
cfg_mag.o: ${MAKETOP}../export/power/usr/include/sys/sysconfig.h
cfg_mag.o: ${MAKETOP}../export/power/usr/include/sys/lockl.h
cfg_mag.o: ${MAKETOP}../export/power/usr/include/sys/lock_def.h
cfg_mag.o: ${MAKETOP}../export/power/usr/include/sys/device.h
cfg_mag.o: ${MAKETOP}../export/power/usr/include/sys/file.h
cfg_mag.o: ${MAKETOP}../export/power/usr/include/sys/param.h
cfg_mag.o: ${MAKETOP}../export/power/usr/include/sys/m_param.h
cfg_mag.o: ${MAKETOP}../export/power/usr/include/jfs/fsparam.h
cfg_mag.o: ${MAKETOP}../export/power/usr/include/sys/sysmacros.h
cfg_mag.o: ${MAKETOP}../export/power/usr/include/sys/cred.h
cfg_mag.o: ${MAKETOP}../export/power/usr/include/sys/priv.h
cfg_mag.o: ${MAKETOP}../export/power/usr/include/sys/tcb.h
cfg_mag.o: ${MAKETOP}../export/power/usr/include/sys/pcl.h
cfg_mag.o: ${MAKETOP}../export/power/usr/include/sys/intr.h
cfg_mag.o: ${MAKETOP}../export/power/usr/include/sys/m_intr.h
cfg_mag.o: ${MAKETOP}../export/power/usr/include/sys/low.h
cfg_mag.o: ${MAKETOP}../export/power/usr/include/sys/syspest.h
cfg_mag.o: ${MAKETOP}../export/power/usr/include/sys/errno.h
cfg_mag.o: ${MAKETOP}../export/power/usr/include/sys/cfgodm.h
cfg_mag.o: ${MAKETOP}../export/power/usr/include/odmi.h
cfg_mag.o: ${MAKETOP}../export/power/usr/include/sys/dir.h
cfg_mag.o: ${MAKETOP}../export/power/usr/include/sys/lkup.h
cfg_mag.o: ${MAKETOP}../export/power/usr/include/limits.h
cfg_mag.o: ${MAKETOP}../export/power/usr/include/cf.h
cfg_mag.o: ${MAKETOP}bos/usr/lib/methods/common/cfgdebug.h
cfg_mag.o: ${MAKETOP}../export/power/usr/include/sys/ioctl.h
cfg_mag.o: ${MAKETOP}../export/power/usr/include/sys/ttychars.h
cfg_mag.o: ${MAKETOP}../export/power/usr/include/sys/ttydev.h
cfg_mag.o: ${MAKETOP}../export/power/usr/include/sys/devinfo.h
cfg_mag.o: ${MAKETOP}../export/power/usr/include/sys/mdio.h
cfg_mag.o: ${MAKETOP}../export/power/usr/include/sys/iplcb.h
cfg_mag.o: ${MAKETOP}../export/power/usr/include/sys/rosinfo.h
cfg_mag.o: ${MAKETOP}bos/kernext/disp/mag/inc/mag_dds.h
cfg_mag.o: ${MAKETOP}bos/kernext/disp/mag/inc/mag_diag.h
#
# dependents of cfgtools.o:
cfgtools.o: ${MAKETOP}../export/power/usr/include/stdio.h
cfgtools.o: ${MAKETOP}../export/power/usr/include/standards.h
cfgtools.o: ${MAKETOP}../export/power/usr/include/va_list.h
cfgtools.o: ${MAKETOP}../export/power/usr/include/sys/types.h
cfgtools.o: ${MAKETOP}../export/power/usr/include/sys/m_types.h
cfgtools.o: ${MAKETOP}../export/power/usr/include/sys/limits.h
cfgtools.o: ${MAKETOP}../export/power/usr/include/float.h
cfgtools.o: ${MAKETOP}../export/power/usr/include/sys/errno.h
cfgtools.o: ${MAKETOP}../export/power/usr/include/sys/stat.h
cfgtools.o: ${MAKETOP}../export/power/usr/include/sys/mode.h
cfgtools.o: ${MAKETOP}../export/power/usr/include/sys/sysmacros.h
cfgtools.o: ${MAKETOP}../export/power/usr/include/sys/param.h
cfgtools.o: ${MAKETOP}../export/power/usr/include/sys/m_param.h
cfgtools.o: ${MAKETOP}../export/power/usr/include/jfs/fsparam.h
cfgtools.o: ${MAKETOP}bos/usr/lib/methods/common/cfgdebug.h
cfgtools.o: ${MAKETOP}bos/usr/lib/methods/common/pparms.h
cfgtools.o: ${MAKETOP}../export/power/usr/include/sys/cfgodm.h
cfgtools.o: ${MAKETOP}../export/power/usr/include/odmi.h
cfgtools.o: ${MAKETOP}../export/power/usr/include/sys/dir.h
cfgtools.o: ${MAKETOP}../export/power/usr/include/sys/lkup.h
cfgtools.o: ${MAKETOP}../export/power/usr/include/limits.h
cfgtools.o: ${MAKETOP}../export/power/usr/include/sys/cfgdb.h
cfgtools.o: ${MAKETOP}../export/power/usr/include/ctype.h
cfgtools.o: ${MAKETOP}../export/power/usr/include/sys/localedef.h
cfgtools.o: ${MAKETOP}../export/power/usr/include/sys/lc_core.h
cfgtools.o: ${MAKETOP}../export/power/usr/include/locale.h
cfgtools.o: ${MAKETOP}../export/power/usr/include/sys/localedef31.h
cfgtools.o: ${MAKETOP}../export/power/usr/include/cf.h
#
# dependents of chkslot.o:
chkslot.o: ${MAKETOP}../export/power/usr/include/stdio.h
chkslot.o: ${MAKETOP}../export/power/usr/include/standards.h
chkslot.o: ${MAKETOP}../export/power/usr/include/va_list.h
chkslot.o: ${MAKETOP}../export/power/usr/include/sys/types.h
chkslot.o: ${MAKETOP}../export/power/usr/include/sys/m_types.h
chkslot.o: ${MAKETOP}../export/power/usr/include/sys/limits.h
chkslot.o: ${MAKETOP}../export/power/usr/include/float.h
chkslot.o: ${MAKETOP}../export/power/usr/include/fcntl.h
chkslot.o: ${MAKETOP}../export/power/usr/include/sys/flock.h
chkslot.o: ${MAKETOP}../export/power/usr/include/unistd.h
chkslot.o: ${MAKETOP}../export/power/usr/include/sys/access.h
chkslot.o: ${MAKETOP}../export/power/usr/include/sys/lockf.h
chkslot.o: ${MAKETOP}../export/power/usr/include/sys/stat.h
chkslot.o: ${MAKETOP}../export/power/usr/include/sys/mode.h
chkslot.o: ${MAKETOP}../export/power/usr/include/cf.h
chkslot.o: ${MAKETOP}../export/power/usr/include/sys/mdio.h
chkslot.o: ${MAKETOP}../export/power/usr/include/sys/eu.h
chkslot.o: ${MAKETOP}bos/usr/lib/methods/common/cfgdebug.h
#
# dependents of ddstools.o:
ddstools.o: ${MAKETOP}../export/power/usr/include/sys/sysmacros.h
ddstools.o: ${MAKETOP}../export/power/usr/include/sys/param.h
ddstools.o: ${MAKETOP}../export/power/usr/include/sys/m_param.h
ddstools.o: ${MAKETOP}../export/power/usr/include/sys/limits.h
ddstools.o: ${MAKETOP}../export/power/usr/include/standards.h
ddstools.o: ${MAKETOP}../export/power/usr/include/float.h
ddstools.o: ${MAKETOP}../export/power/usr/include/jfs/fsparam.h
ddstools.o: ${MAKETOP}../export/power/usr/include/sys/types.h
ddstools.o: ${MAKETOP}../export/power/usr/include/sys/m_types.h
ddstools.o: ${MAKETOP}../export/power/usr/include/sys/cfgodm.h
ddstools.o: ${MAKETOP}../export/power/usr/include/odmi.h
ddstools.o: ${MAKETOP}../export/power/usr/include/sys/dir.h
ddstools.o: ${MAKETOP}../export/power/usr/include/sys/lkup.h
ddstools.o: ${MAKETOP}../export/power/usr/include/limits.h
ddstools.o: ${MAKETOP}../export/power/usr/include/sys/cfgdb.h
ddstools.o: ${MAKETOP}../export/power/usr/include/cf.h
ddstools.o: ${MAKETOP}bos/usr/lib/methods/common/cfgdebug.h
ddstools.o: ${MAKETOP}../export/power/usr/include/stdio.h
ddstools.o: ${MAKETOP}../export/power/usr/include/va_list.h
ddstools.o: ${MAKETOP}../export/power/usr/include/strings.h
ddstools.o: ${MAKETOP}../export/power/usr/include/string.h
#
# dependents of iplcb_tools.o:
iplcb_tools.o: ${MAKETOP}../export/power/usr/include/sys/types.h
iplcb_tools.o: ${MAKETOP}../export/power/usr/include/standards.h
iplcb_tools.o: ${MAKETOP}../export/power/usr/include/sys/m_types.h
iplcb_tools.o: ${MAKETOP}../export/power/usr/include/stdio.h
iplcb_tools.o: ${MAKETOP}../export/power/usr/include/va_list.h
iplcb_tools.o: ${MAKETOP}../export/power/usr/include/sys/limits.h
iplcb_tools.o: ${MAKETOP}../export/power/usr/include/float.h
iplcb_tools.o: ${MAKETOP}bos/usr/lib/methods/common/cfgdebug.h
iplcb_tools.o: ${MAKETOP}../export/power/usr/include/sys/mdio.h
iplcb_tools.o: ${MAKETOP}../export/power/usr/include/sys/iplcb.h
iplcb_tools.o: ${MAKETOP}../export/power/usr/include/sys/rosinfo.h
#
# dependents of mag_cfg_load.o:
mag_cfg_load.o: ${MAKETOP}../export/power/usr/include/cf.h
mag_cfg_load.o: ${MAKETOP}../export/power/usr/include/sys/types.h
mag_cfg_load.o: ${MAKETOP}../export/power/usr/include/standards.h
mag_cfg_load.o: ${MAKETOP}../export/power/usr/include/sys/m_types.h
mag_cfg_load.o: ${MAKETOP}bos/usr/lib/methods/common/cfgdebug.h
mag_cfg_load.o: ${MAKETOP}../export/power/usr/include/sys/aixfont.h
mag_cfg_load.o: ${MAKETOP}../export/power/usr/include/sys/dir.h
mag_cfg_load.o: ${MAKETOP}../export/power/usr/include/sys/lkup.h
mag_cfg_load.o: ${MAKETOP}../export/power/usr/include/limits.h
mag_cfg_load.o: ${MAKETOP}../export/power/usr/include/sys/limits.h
mag_cfg_load.o: ${MAKETOP}../export/power/usr/include/float.h
mag_cfg_load.o: ${MAKETOP}../export/power/usr/include/sys/mdio.h
mag_cfg_load.o: ${MAKETOP}../export/power/usr/include/sys/file.h
mag_cfg_load.o: ${MAKETOP}../export/power/usr/include/sys/param.h
mag_cfg_load.o: ${MAKETOP}../export/power/usr/include/sys/m_param.h
mag_cfg_load.o: ${MAKETOP}../export/power/usr/include/jfs/fsparam.h
mag_cfg_load.o: ${MAKETOP}../export/power/usr/include/sys/sysmacros.h
mag_cfg_load.o: ${MAKETOP}../export/power/usr/include/sys/access.h
mag_cfg_load.o: ${MAKETOP}../export/power/usr/include/sys/lock_def.h
mag_cfg_load.o: ${MAKETOP}../export/power/usr/include/sys/cred.h
mag_cfg_load.o: ${MAKETOP}../export/power/usr/include/sys/priv.h
mag_cfg_load.o: ${MAKETOP}../export/power/usr/include/sys/mode.h
mag_cfg_load.o: ${MAKETOP}../export/power/usr/include/sys/tcb.h
mag_cfg_load.o: ${MAKETOP}../export/power/usr/include/sys/pcl.h
mag_cfg_load.o: ${MAKETOP}../export/power/usr/include/sys/lockl.h
mag_cfg_load.o: ${MAKETOP}../export/power/usr/include/fcntl.h
mag_cfg_load.o: ${MAKETOP}../export/power/usr/include/sys/flock.h
mag_cfg_load.o: ${MAKETOP}../export/power/usr/include/unistd.h
mag_cfg_load.o: ${MAKETOP}../export/power/usr/include/sys/lockf.h
mag_cfg_load.o: ${MAKETOP}../export/power/usr/include/sys/stat.h
mag_cfg_load.o: ${MAKETOP}../export/power/usr/include/sys/intr.h
mag_cfg_load.o: ${MAKETOP}../export/power/usr/include/sys/m_intr.h
mag_cfg_load.o: ${MAKETOP}../export/power/usr/include/sys/ioacc.h
mag_cfg_load.o: ${MAKETOP}../export/power/usr/include/sys/adspace.h
mag_cfg_load.o: ${MAKETOP}../export/power/usr/include/sys/seg.h
mag_cfg_load.o: ${MAKETOP}../export/power/usr/include/sys/inode.h
mag_cfg_load.o: ${MAKETOP}../export/power/usr/include/jfs/inode.h
mag_cfg_load.o: ${MAKETOP}../export/power/usr/include/jfs/ino.h
mag_cfg_load.o: ${MAKETOP}../export/power/usr/include/sys/time.h
mag_cfg_load.o: ${MAKETOP}../export/power/usr/include/jfs/fsdefs.h
mag_cfg_load.o: ${MAKETOP}../export/power/usr/include/jfs/filsys.h
mag_cfg_load.o: ${MAKETOP}../export/power/usr/include/jfs/jfsmount.h
mag_cfg_load.o: ${MAKETOP}../export/power/usr/include/sys/vnode.h
mag_cfg_load.o: ${MAKETOP}../export/power/usr/include/sys/uio.h
mag_cfg_load.o: ${MAKETOP}../export/power/usr/include/sys/xmem.h
mag_cfg_load.o: ${MAKETOP}../export/power/usr/include/jfs/quota.h
mag_cfg_load.o: ${MAKETOP}../export/power/usr/include/sys/vmuser.h
mag_cfg_load.o: ${MAKETOP}../export/power/usr/include/sys/acl.h
mag_cfg_load.o: ${MAKETOP}../export/power/usr/include/sys/systemcfg.h
mag_cfg_load.o: ${MAKETOP}../export/power/usr/include/vt.h
mag_cfg_load.o: ${MAKETOP}../export/power/usr/include/sys/font.h
mag_cfg_load.o: ${MAKETOP}../export/power/usr/include/cdd.h
mag_cfg_load.o: ${MAKETOP}../export/power/usr/include/cdd_macros.h
mag_cfg_load.o: ${MAKETOP}../export/power/usr/include/cdd_intr.h
mag_cfg_load.o: ${MAKETOP}../export/power/usr/include/cdd_intr_macros.h
mag_cfg_load.o: ${MAKETOP}../export/power/usr/include/ccm.h
mag_cfg_load.o: ${MAKETOP}../export/power/usr/include/ccm_macros.h
mag_cfg_load.o: ${MAKETOP}bos/usr/lib/methods/graphics/cfg_graphics.h
mag_cfg_load.o: ${MAKETOP}bos/usr/lib/methods/graphics/cfg_graphics_macros.h
