$ @(#)47	1.6  src/bos/usr/ccs/lib/libqb/libqb.msg, libqb, bos411, 9428A410j 5/8/91 17:01:58
$
$ COMPONENT_NAME: (CMDQUE) spooling commands
$
$ FUNCTIONS: 
$
$ ORIGINS: 27
$
$ IBM CONFIDENTIAL -- (IBM Confidential Restricted when
$ combined with the aggregated modules for this product)
$                  SOURCE MATERIALS
$ (C) COPYRIGHT International Business Machines Corp. 1989
$ All Rights Reserved
$
$ US Government Users Restricted Rights - Use, duplication or
$ disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
$

$quote "
$set MS_LIBQB
MSGTITL		"Title:"
MSGTIME		"Time printed:"
MSGQUEU		"Time queued:"
MSGMODI		"Last modified:"
MSGPRNT		"Printed by:"
MSGDELI		"Deliver to:"
MSGTWOC		"End of output for:"
MSGFORK 	"0781-264  Unable to fork a new process."
MSGEXEC 	"0781-265  Unable to send message to remote user."
MSGMHDR		"Message from queueing system:\n"
MSGTELL		"0781-266  Cannot use telluser() unless you are a backend."
MSGMBER		"0781-314  Error in multibyte character conversion."
