# @(#)57	1.1  src/bos/usr/lib/asw/artic/Makefile, artic, bos411, 9428A410j 8/23/93 10:02:22
#
# COMPONENT_NAME: ARTIC
#
# FUNCTIONS: Makefile - ARTIC adapter software 
#
# ORIGINS: 27
#
# IBM CONFIDENTIAL -- (IBM Confidential Restricted when
# combined with the aggregated modules for this product)
#                  SOURCE MATERIALS
# (C) COPYRIGHT International Business Machines Corp. 1992
# All Rights Reserved
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#-----------------------------------------------------------------------#
#       Makefile for artic adapter software (geteibid.com)              #
#-----------------------------------------------------------------------#

ILIST           = geteibid.com

IDIR            = /usr/lib/asw/

.include <${RULES_MK}>
