# @(#)57	1.1  src/bos/usr/lib/microcode/cat/Makefile, ucod370p, bos411, 9428A410j 2/25/94 19:19:52
# COMPONENT_NAME:
#
# FUNCTIONS:
#
# ORIGINS: 27
#
# IBM CONFIDENTIAL -- (IBM Confidential Restricted when
# combined with the aggregated modules for this product)
#                  SOURCE MATERIALS
# (C) COPYRIGHT International Business Machines Corp. 1994
# All Rights Reserved
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#


ILIST		= cu3088b.00.00 cu3088e.00.00 cu3172b.00.00 fe92.00.03

IDIR		= /usr/lib/microcode/

.include <${RULES_MK}>
