# @(#)27        1.13  src/bos/usr/lib/nls/Makefile, cfgnls, bos411, 9428A410j 4/16/94 11:46:18
#
# COMPONENT_NAME: CFGNLS
#
# FUNCTIONS:
#
# ORIGINS: 27
#
# IBM CONFIDENTIAL -- (IBM Confidential Restricted when
# combined with the aggregated modules for this product)
#                  SOURCE MATERIALS
# (C) COPYRIGHT International Business Machines Corp. 1988, 1994
# All Rights Reserved
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#

EXPINC_SUBDIRS	= loc

SUBDIRS		= charmap loc bidi lsmle

ILIST		= README
IDIR		= /usr/lib/nls/

.include <${RULES_MK}>
