# @(#)96        1.2  src/bos/usr/games/Makefile, cmdgames, bos411, 9428A410j 1/14/93 16:18:10
#
# COMPONENT_NAME: CMDGAMES
#
# FUNCTIONS:
#
# ORIGINS: 27
#
# IBM CONFIDENTIAL -- (IBM Confidential Restricted when
# combined with the aggregated modules for this product)
#                  SOURCE MATERIALS
# (C) COPYRIGHT International Business Machines Corp. 1988, 1993
# All Rights Reserved
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#

SUBDIRS		= lib

PROGRAMS	= arithmetic back bj craps fish hangman moo \
		  number quiz ttt wump
SCRIPTS		= turnoff turnon

ILIST		= ${PROGRAMS} ${SCRIPTS} backrules w2006
IDIR		= /usr/games/
w2006_IDIR	= /usr/lib/

.include <${RULES_MK}>
