# @(#)90        1.3  src/bldenv/bdftosnf/Makefile, sysxdisp, bos412, GOLDA411a 2/21/94 15:21:07
# COMPONENT_NAME: sysxdisp
#
# FUNCTIONS:
#
# ORIGINS: 27
#
# IBM CONFIDENTIAL -- (IBM Confidential Restricted when
# combined with the aggregated modules for this product)
#                  SOURCE MATERIALS
# (C) COPYRIGHT International Business Machines Corp. 1988, 1989
# All Rights Reserved
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#

PROGRAMS	= bdftosnf

OFILES		= bdftosnf.o fontutil.o itrunc.o

ILIST		= bdftosnf
IDIR		= /usr/bin/

.include <${RULES_MK}>
