# @(#)50  1.1  src/bos/usr/lib/methods/ucfgfddi/Makefile, sysxfddi, bos411, 9428A410j 3/16/94 16:47:13
#
# COMPONENT_NAME: SYSXFDDI
#
# FUNCTIONS:
#
# ORIGINS: 27
#
# IBM CONFIDENTIAL -- (IBM Confidential Restricted when
# combined with the aggregated modules for this product)
#                  SOURCE MATERIALS
# (C) COPYRIGHT International Business Machines Corp. 1994
# All Rights Reserved
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#

VPATH           = ../ucfgcommo

PROGRAMS        = ucfgfddi

OFILES          = ucfgcommo.o ucfglanwe.o

INCFLAGS        = -I../common -I../cfgcie

ILIST           = ucfgfddi
IDIR		= /usr/lib/methods/

LIBS		= -ls -lodm -lcfg -lrts

.include <${RULES_MK}>
