# @(#)10        1.3  src/bos/usr/ccs/lib/libswvpd/Makefile, libswvpd, bos411, 9428A410j 12/13/93 16:06:57
# COMPONENT_NAME:
#
# FUNCTIONS:
#
# ORIGINS: 27
#
# IBM CONFIDENTIAL -- (IBM Confidential Restricted when
# combined with the aggregated modules for this product)
#                  SOURCE MATERIALS
# (C) COPYRIGHT International Business Machines Corp. 1988, 1989
# All Rights Reserved
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#



LIBRARIES	= libswvpd.a
MSGHDRS         =
CATFILES        =
HFILES          = ${MSGHDRS}

EXPLIB_TARGETS  = export_libswvpd.a

ILIST           = libswvpd.a
IDIR            = /usr/ccs/lib/

OFILES		= \
	vpdclass.o vpdadd.o vpdchg.o vpddel.o vpdget.o \
	vpd_free.o vpdinit.o vpdremote.o vpdreslpp.o vpdsql.o init_vchars.o


.include <${RULES_MK}>
