# @(#)36        1.2  src/bos/kernel/include/vmm/Makefile, sysvmm, bos411, 9428A410j 7/11/94 13:28:28
# COMPONENT_NAME:
#
# FUNCTIONS:
#
# ORIGINS: 10,27
#
# IBM CONFIDENTIAL -- (IBM Confidential Restricted when
# combined with the aggregated modules for this product)
#                  SOURCE MATERIALS
# (C) COPYRIGHT International Business Machines Corp. 1988, 1994
# All Rights Reserved
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#

VPATH		=${MAKETOP}bos/kernel/vmm/${TARGET_MACHINE}

IDIR		= /kernel/include/vmm/

DATAFILES	= \
	vmdefs.h vmsys.h vmpfhdata.h vmpft.h vmscb.h vmlock.h \
	vmxpt.h vmmacs.h vm_mmap.h vm_map.h mplock.h

INCLUDES	= ${DATAFILES}

.include <${RULES_MK}>
