# @(#)15        1.2  src/bos/usr/ccs/lib/libprint/Makefile, libprint, bos411, 9428A410j 9/1/92 19:36:58
# COMPONENT_NAME:
#
# FUNCTIONS:
#
# ORIGINS: 27
#
# IBM CONFIDENTIAL -- (IBM Confidential Restricted when
# combined with the aggregated modules for this product)
#                  SOURCE MATERIALS
# (C) COPYRIGHT International Business Machines Corp. 1988, 1989
# All Rights Reserved
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#



LIBRARIES	= libprint.a
MSGHDRS         =
CATFILES        =
HFILES          = ${MSGHDRS}

EXPLIB_TARGETS  = export_libprint.a

ILIST           =libprint.a
IDIR            = /usr/lib/

OFILES		= \
	arc.o box.o circle.o close.o cont.o doscreen.o \
	dot.o erase.o label.o line.o linemod.o move.o \
	open.o point.o printdata.o scale.o setdot.o \
	space.o

.include <${RULES_MK}>
