# @(#)36	1.1  src/bos/usr/lpp/Unicode/charmap/Makefile, cfgnls, bos411, 9428A410j 1/21/94 10:08:37
#
#   COMPONENT_NAME: CFGNLS
#
#   FUNCTIONS: none
#
#   ORIGINS: 27
#
#   IBM CONFIDENTIAL -- (IBM Confidential Restricted when
#   combined with the aggregated modules for this product)
#                    SOURCE MATERIALS
#
#   (C) COPYRIGHT International Business Machines Corp. 1994
#   All Rights Reserved
#   US Government Users Restricted Rights - Use, duplication or
#   disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#

ILIST		= UNIVERSAL.cm

IDIR		= /usr/lpp/Unicode/charmap/

.include <${RULES_MK}>
