# @(#)56       1.1  src/bos/usr/lib/methods/udefdlc/Makefile, dlccfg, bos411, 9428A410j 1/24/94 11:06:27 
# COMPONENT_NAME: DLCCFG
#
# FUNCTIONS:
#
# ORIGINS: 27
#
# IBM CONFIDENTIAL -- (IBM Confidential Restricted when
# combined with the aggregated modules for this product)
#                  SOURCE MATERIALS
# (C) COPYRIGHT International Business Machines Corp. 1994
# All Rights Reserved
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#

VPATH		= ../common

PROGRAMS	= udefdlc

OFILES          = udefdlc.o

INCFLAGS        = -I../common

ILIST		= udefdlc
IDIR		= /usr/lib/methods/


LIBS		= -ls -lodm -lcfg -lrts

.include <${RULES_MK}>
