# @(#)63        1.2  src/bos/kernext/inputdd/Makefile, inputdd, bos41J 3/13/95 08:40:57
# COMPONENT_NAME: INPUTDD
#
# FUNCTIONS: N/A
#
# ORIGINS: 27
#
# IBM CONFIDENTIAL -- (IBM Confidential Restricted when
# combined with the aggregated modules for this product)
#                  SOURCE MATERIALS
# (C) COPYRIGHT International Business Machines Corp. 1993
# All Rights Reserved
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#

EXPINC_SUBDIRS = inc

SUBDIRS = \
	ktsdd kbddd mousedd tabletdd giodd sgiodd

.include <${RULES_MK}>
