# @(#)02        1.4  src/bldenv/makepath/Makefile, bldprocess, bos412, GOLDA411a 1/10/94 15:44:08
#
# COMPONENT_NAME:
#
# FUNCTIONS:
#
# ORIGINS: 27, 71
#
# IBM CONFIDENTIAL -- (IBM Confidential Restricted when
# combined with the aggregated modules for this product)
#                  SOURCE MATERIALS
# (C) COPYRIGHT International Business Machines Corp. 1988, 1989
# All Rights Reserved
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#

PROGRAMS	= makepath

CFLAGS          = -DMACH -DCMU -UMSG -D_BLD -D_${TARGET_MACHINE}

ILIST           = ${PROGRAMS}
IDIR            = /usr/bin/

.include <${RULES_MK}>
