# @(#)32        1.2  src/bos/usr/lib/sa/Makefile, cmdstat, bos411, 9428A410j 1/26/93 20:57:46
# COMPONENT_NAME:  (CMDSTAT)
#
# FUNCTIONS:
#
# ORIGINS: 27
#
# IBM CONFIDENTIAL -- (IBM Confidential Restricted when
# combined with the aggregated modules for this product)
#                  SOURCE MATERIALS
# (C) COPYRIGHT International Business Machines Corp. 1988, 1993
# All Rights Reserved
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#

PROGRAMS	= sadc
MSGHDRS		= sadc_msg.h
CATFILES	= sadc.cat
HFILES		= ${MSGHDRS}

ILIST		= sadc
IDIR		= /usr/lib/sa/


.include <${RULES_MK}>
