$ @(#)75   1.1  src/bos/usr/lib/methods/cfgcie/ciedd.msg, sysxcie, bos411, 9428A410j 4/1/94 15:32:54
$
$  COMPONENT_NAME: SYSXCIE
$
$  FUNCTIONS: Device configuration message catalog
$
$  ORIGINS: 27
$
$  IBM CONFIDENTIAL -- (IBM Confidential Restricted when
$  combined with the aggregated modules for this product)
$                   SOURCE MATERIALS
$  (C) COPYRIGHT International Business Machines Corp. 1992
$  All Rights Reserved
$
$  US Government Users Restricted Rights - Use, duplication or
$  disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
$
$quote "
$
$  COMIO Emulator
$set 1
1  "Receive Queue Size (Frames)"
2  "Status Queue Size (Events)"
3  "Pass Beacon Frames"
4  "Pass NSA Frames"
5  "Pass SMT Frames"
6  "802.3 ETHERTYPE Field Offset"
7  "Standard ETHERTYPE Field Offset"
