# @(#)59        1.2  src/bldenv/sed/Makefile, ade_build, bos412, GOLDA411a 1/10/94 14:08:38
#
#   COMPONENT_NAME: BOSBUILD
#
#   FUNCTIONS:
#
#   ORIGINS: 27
#
#   IBM CONFIDENTIAL -- (IBM Confidential Restricted when
#   combined with the aggregated modules for this product)
#                    SOURCE MATERIALS
#
#   (C) COPYRIGHT International Business Machines Corp. 1993
#   All Rights Reserved
#   US Government Users Restricted Rights - Use, duplication or
#   disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#

VPATH		= ${MAKETOP}bos/usr/bin/sed

PROGRAMS	= sed
MSGHDRS		= sed_msg.h
CATFILES	= sed.cat
HFILES		= ${MSGHDRS}

INCFLAGS	= -I${MAKETOP}bos/usr/bin/sed

ILIST		= ${PROGRAMS}
IDIR		= /usr/bin/

OFILES		= sed0.o sed1.o

.include <${RULES_MK}>
