#
# dependents of mslaclose.o:
mslaclose.o: ${MAKETOP}../export/power/kernel/include/sys/devinfo.h
mslaclose.o: ${MAKETOP}../export/power/kernel/include/sys/types.h
mslaclose.o: ${MAKETOP}../export/power/kernel/include/standards.h
mslaclose.o: ${MAKETOP}../export/power/kernel/include/sys/m_types.h
mslaclose.o: ${MAKETOP}../export/power/kernel/include/sys/errno.h
mslaclose.o: ${MAKETOP}../export/power/kernel/include/fcntl.h
mslaclose.o: ${MAKETOP}../export/power/kernel/include/sys/flock.h
mslaclose.o: ${MAKETOP}../export/power/kernel/include/unistd.h
mslaclose.o: ${MAKETOP}../export/power/kernel/include/sys/access.h
mslaclose.o: ${MAKETOP}../export/power/kernel/include/sys/lockf.h
mslaclose.o: ${MAKETOP}../export/power/kernel/include/sys/stat.h
mslaclose.o: ${MAKETOP}../export/power/kernel/include/sys/mode.h
mslaclose.o: ${MAKETOP}../export/power/kernel/include/stdio.h
mslaclose.o: ${MAKETOP}../export/power/kernel/include/va_list.h
mslaclose.o: ${MAKETOP}../export/power/kernel/include/sys/limits.h
mslaclose.o: ${MAKETOP}../export/power/kernel/include/float.h
mslaclose.o: ${MAKETOP}../export/power/kernel/include/sys/ioctl.h
mslaclose.o: ${MAKETOP}../export/power/kernel/include/sys/ttychars.h
mslaclose.o: ${MAKETOP}../export/power/kernel/include/sys/ttydev.h
mslaclose.o: ${MAKETOP}../export/power/kernel/include/sys/file.h
mslaclose.o: ${MAKETOP}../export/power/kernel/include/sys/param.h
mslaclose.o: ${MAKETOP}../export/power/kernel/include/sys/m_param.h
mslaclose.o: ${MAKETOP}../export/power/kernel/include/jfs/fsparam.h
mslaclose.o: ${MAKETOP}../export/power/kernel/include/sys/sysmacros.h
mslaclose.o: ${MAKETOP}../export/power/kernel/include/sys/lock_def.h
mslaclose.o: ${MAKETOP}../export/power/kernel/include/sys/cred.h
mslaclose.o: ${MAKETOP}../export/power/kernel/include/sys/priv.h
mslaclose.o: ${MAKETOP}../export/power/kernel/include/sys/tcb.h
mslaclose.o: ${MAKETOP}../export/power/kernel/include/sys/pcl.h
mslaclose.o: ${MAKETOP}../export/power/kernel/include/sys/lockl.h
mslaclose.o: ${MAKETOP}../export/power/kernel/include/sys/signal.h
mslaclose.o: ${MAKETOP}../export/power/kernel/include/sys/context.h
mslaclose.o: ${MAKETOP}../export/power/kernel/include/sys/mstsave.h
mslaclose.o: ${MAKETOP}../export/power/kernel/include/sys/pin.h
mslaclose.o: ${MAKETOP}../export/power/kernel/include/sys/malloc.h
mslaclose.o: ${MAKETOP}../export/power/kernel/include/sys/sleep.h
mslaclose.o: ${MAKETOP}../export/power/kernel/include/sys/intr.h
mslaclose.o: ${MAKETOP}../export/power/kernel/include/sys/m_intr.h
mslaclose.o: ${MAKETOP}../export/power/kernel/include/sys/iocc.h
mslaclose.o: ${MAKETOP}../export/power/kernel/include/sys/io3270.h
mslaclose.o: ${MAKETOP}../export/power/kernel/include/sys/errids.h
mslaclose.o: ${MAKETOP}../export/power/kernel/include/sys/err_rec.h
mslaclose.o: ${MAKETOP}bos/kernext/msla/msladefs.h
mslaclose.o: ${MAKETOP}bos/kernext/msla/msladecls.h
mslaclose.o: ${MAKETOP}../export/power/kernel/include/sys/xmem.h
mslaclose.o: ${MAKETOP}bos/kernext/msla/mslamac.h
mslaclose.o: ${MAKETOP}bos/kernext/msla/msladd.h
mslaclose.o: ${MAKETOP}../export/power/kernel/include/sys/trchkid.h
mslaclose.o: ${MAKETOP}../export/power/kernel/include/sys/trcmacros.h
mslaclose.o: ${MAKETOP}../export/power/kernel/include/sys/ioacc.h
mslaclose.o: ${MAKETOP}../export/power/kernel/include/sys/lock_alloc.h
mslaclose.o: ${MAKETOP}bos/kernext/msla/mslaextern.h
#
# dependents of msladd.o:
msladd.o: ${MAKETOP}../export/power/kernel/include/sys/file.h
msladd.o: ${MAKETOP}../export/power/kernel/include/sys/types.h
msladd.o: ${MAKETOP}../export/power/kernel/include/standards.h
msladd.o: ${MAKETOP}../export/power/kernel/include/sys/m_types.h
msladd.o: ${MAKETOP}../export/power/kernel/include/sys/param.h
msladd.o: ${MAKETOP}../export/power/kernel/include/sys/m_param.h
msladd.o: ${MAKETOP}../export/power/kernel/include/sys/limits.h
msladd.o: ${MAKETOP}../export/power/kernel/include/float.h
msladd.o: ${MAKETOP}../export/power/kernel/include/jfs/fsparam.h
msladd.o: ${MAKETOP}../export/power/kernel/include/sys/sysmacros.h
msladd.o: ${MAKETOP}../export/power/kernel/include/sys/access.h
msladd.o: ${MAKETOP}../export/power/kernel/include/sys/lock_def.h
msladd.o: ${MAKETOP}../export/power/kernel/include/sys/cred.h
msladd.o: ${MAKETOP}../export/power/kernel/include/sys/priv.h
msladd.o: ${MAKETOP}../export/power/kernel/include/sys/mode.h
msladd.o: ${MAKETOP}../export/power/kernel/include/sys/tcb.h
msladd.o: ${MAKETOP}../export/power/kernel/include/sys/pcl.h
msladd.o: ${MAKETOP}../export/power/kernel/include/sys/lockl.h
msladd.o: ${MAKETOP}../export/power/kernel/include/fcntl.h
msladd.o: ${MAKETOP}../export/power/kernel/include/sys/flock.h
msladd.o: ${MAKETOP}../export/power/kernel/include/unistd.h
msladd.o: ${MAKETOP}../export/power/kernel/include/sys/lockf.h
msladd.o: ${MAKETOP}../export/power/kernel/include/sys/stat.h
msladd.o: ${MAKETOP}../export/power/kernel/include/sys/errno.h
msladd.o: ${MAKETOP}../export/power/kernel/include/sys/devinfo.h
msladd.o: ${MAKETOP}../export/power/kernel/include/sys/device.h
msladd.o: ${MAKETOP}../export/power/kernel/include/sys/intr.h
msladd.o: ${MAKETOP}../export/power/kernel/include/sys/m_intr.h
msladd.o: ${MAKETOP}../export/power/kernel/include/sys/low.h
msladd.o: ${MAKETOP}../export/power/kernel/include/sys/syspest.h
msladd.o: ${MAKETOP}../export/power/kernel/include/sys/ioctl.h
msladd.o: ${MAKETOP}../export/power/kernel/include/sys/ttychars.h
msladd.o: ${MAKETOP}../export/power/kernel/include/sys/ttydev.h
msladd.o: ${MAKETOP}../export/power/kernel/include/sys/iocc.h
msladd.o: ${MAKETOP}../export/power/kernel/include/sys/conf.h
msladd.o: ${MAKETOP}../export/power/kernel/include/sys/systm.h
msladd.o: ${MAKETOP}../export/power/kernel/include/sys/mstsave.h
msladd.o: ${MAKETOP}../export/power/kernel/include/sys/vnode.h
msladd.o: ${MAKETOP}../export/power/kernel/include/sys/uio.h
msladd.o: ${MAKETOP}../export/power/kernel/include/sys/xmem.h
msladd.o: ${MAKETOP}../export/power/kernel/include/sys/proc.h
msladd.o: ${MAKETOP}../export/power/kernel/include/sys/ptrace.h
msladd.o: ${MAKETOP}../export/power/kernel/include/sys/thread.h
msladd.o: ${MAKETOP}../export/power/kernel/include/sys/processor.h
msladd.o: ${MAKETOP}../export/power/kernel/include/sys/var.h
msladd.o: ${MAKETOP}../export/power/kernel/include/sys/atomic_op.h
msladd.o: ${MAKETOP}../export/power/kernel/include/sys/timer.h
msladd.o: ${MAKETOP}../export/power/kernel/include/sys/time.h
msladd.o: ${MAKETOP}../export/power/kernel/include/sys/resource.h
msladd.o: ${MAKETOP}../export/power/kernel/include/sys/pri.h
msladd.o: ${MAKETOP}../export/power/kernel/include/sys/inode.h
msladd.o: ${MAKETOP}../export/power/kernel/include/jfs/inode.h
msladd.o: ${MAKETOP}../export/power/kernel/include/jfs/ino.h
msladd.o: ${MAKETOP}../export/power/kernel/include/jfs/fsdefs.h
msladd.o: ${MAKETOP}../export/power/kernel/include/jfs/filsys.h
msladd.o: ${MAKETOP}../export/power/kernel/include/jfs/jfsmount.h
msladd.o: ${MAKETOP}../export/power/kernel/include/jfs/quota.h
msladd.o: ${MAKETOP}../export/power/kernel/include/sys/vmuser.h
msladd.o: ${MAKETOP}../export/power/kernel/include/sys/acl.h
msladd.o: ${MAKETOP}../export/power/kernel/include/sys/buf.h
msladd.o: ${MAKETOP}../export/power/kernel/include/sys/filsys.h
msladd.o: ${MAKETOP}../export/power/kernel/include/sys/malloc.h
msladd.o: ${MAKETOP}../export/power/kernel/include/malloc.h
msladd.o: ${MAKETOP}../export/power/kernel/include/sys/pin.h
msladd.o: ${MAKETOP}../export/power/kernel/include/sys/sysdma.h
msladd.o: ${MAKETOP}../export/power/kernel/include/sys/io3270.h
msladd.o: ${MAKETOP}../export/power/kernel/include/sys/ioacc.h
msladd.o: ${MAKETOP}../export/power/kernel/include/sys/errids.h
msladd.o: ${MAKETOP}../export/power/kernel/include/sys/err_rec.h
msladd.o: ${MAKETOP}bos/kernext/msla/msladefs.h
msladd.o: ${MAKETOP}bos/kernext/msla/msladecls.h
msladd.o: ${MAKETOP}bos/kernext/msla/mslamac.h
msladd.o: ${MAKETOP}bos/kernext/msla/msladd.h
msladd.o: ${MAKETOP}../export/power/kernel/include/sys/trchkid.h
msladd.o: ${MAKETOP}../export/power/kernel/include/sys/trcmacros.h
msladd.o: ${MAKETOP}../export/power/kernel/include/sys/lock_alloc.h
#
# dependents of mslaintr.o:
mslaintr.o: ${MAKETOP}../export/power/kernel/include/sys/poll.h
mslaintr.o: ${MAKETOP}../export/power/kernel/include/standards.h
mslaintr.o: ${MAKETOP}../export/power/kernel/include/sys/types.h
mslaintr.o: ${MAKETOP}../export/power/kernel/include/sys/m_types.h
mslaintr.o: ${MAKETOP}../export/power/kernel/include/sys/file.h
mslaintr.o: ${MAKETOP}../export/power/kernel/include/sys/param.h
mslaintr.o: ${MAKETOP}../export/power/kernel/include/sys/m_param.h
mslaintr.o: ${MAKETOP}../export/power/kernel/include/sys/limits.h
mslaintr.o: ${MAKETOP}../export/power/kernel/include/float.h
mslaintr.o: ${MAKETOP}../export/power/kernel/include/jfs/fsparam.h
mslaintr.o: ${MAKETOP}../export/power/kernel/include/sys/sysmacros.h
mslaintr.o: ${MAKETOP}../export/power/kernel/include/sys/access.h
mslaintr.o: ${MAKETOP}../export/power/kernel/include/sys/lock_def.h
mslaintr.o: ${MAKETOP}../export/power/kernel/include/sys/cred.h
mslaintr.o: ${MAKETOP}../export/power/kernel/include/sys/priv.h
mslaintr.o: ${MAKETOP}../export/power/kernel/include/sys/mode.h
mslaintr.o: ${MAKETOP}../export/power/kernel/include/sys/tcb.h
mslaintr.o: ${MAKETOP}../export/power/kernel/include/sys/pcl.h
mslaintr.o: ${MAKETOP}../export/power/kernel/include/sys/lockl.h
mslaintr.o: ${MAKETOP}../export/power/kernel/include/fcntl.h
mslaintr.o: ${MAKETOP}../export/power/kernel/include/sys/flock.h
mslaintr.o: ${MAKETOP}../export/power/kernel/include/unistd.h
mslaintr.o: ${MAKETOP}../export/power/kernel/include/sys/lockf.h
mslaintr.o: ${MAKETOP}../export/power/kernel/include/sys/stat.h
mslaintr.o: ${MAKETOP}../export/power/kernel/include/sys/errno.h
mslaintr.o: ${MAKETOP}../export/power/kernel/include/sys/io3270.h
mslaintr.o: ${MAKETOP}../export/power/kernel/include/sys/pin.h
mslaintr.o: ${MAKETOP}../export/power/kernel/include/sys/malloc.h
mslaintr.o: ${MAKETOP}../export/power/kernel/include/sys/errids.h
mslaintr.o: ${MAKETOP}../export/power/kernel/include/sys/err_rec.h
mslaintr.o: ${MAKETOP}bos/kernext/msla/msladefs.h
mslaintr.o: ${MAKETOP}bos/kernext/msla/msladecls.h
mslaintr.o: ${MAKETOP}../export/power/kernel/include/sys/xmem.h
mslaintr.o: ${MAKETOP}../export/power/kernel/include/sys/intr.h
mslaintr.o: ${MAKETOP}../export/power/kernel/include/sys/m_intr.h
mslaintr.o: ${MAKETOP}bos/kernext/msla/mslamac.h
mslaintr.o: ${MAKETOP}bos/kernext/msla/msladd.h
mslaintr.o: ${MAKETOP}../export/power/kernel/include/sys/trchkid.h
mslaintr.o: ${MAKETOP}../export/power/kernel/include/sys/trcmacros.h
mslaintr.o: ${MAKETOP}../export/power/kernel/include/sys/ioacc.h
mslaintr.o: ${MAKETOP}../export/power/kernel/include/sys/lock_alloc.h
mslaintr.o: ${MAKETOP}bos/kernext/msla/mslaextern.h
#
# dependents of mslaio.o:
mslaio.o: ${MAKETOP}../export/power/kernel/include/sys/buf.h
mslaio.o: ${MAKETOP}../export/power/kernel/include/sys/types.h
mslaio.o: ${MAKETOP}../export/power/kernel/include/standards.h
mslaio.o: ${MAKETOP}../export/power/kernel/include/sys/m_types.h
mslaio.o: ${MAKETOP}../export/power/kernel/include/sys/xmem.h
mslaio.o: ${MAKETOP}../export/power/kernel/include/sys/time.h
mslaio.o: ${MAKETOP}../export/power/kernel/include/sys/io3270.h
mslaio.o: ${MAKETOP}../export/power/kernel/include/sys/pin.h
mslaio.o: ${MAKETOP}../export/power/kernel/include/sys/malloc.h
mslaio.o: ${MAKETOP}../export/power/kernel/include/sys/intr.h
mslaio.o: ${MAKETOP}../export/power/kernel/include/sys/m_intr.h
mslaio.o: ${MAKETOP}../export/power/kernel/include/sys/dma.h
mslaio.o: ${MAKETOP}../export/power/kernel/include/sys/sysdma.h
mslaio.o: ${MAKETOP}../export/power/kernel/include/sys/errids.h
mslaio.o: ${MAKETOP}../export/power/kernel/include/sys/err_rec.h
mslaio.o: ${MAKETOP}bos/kernext/msla/msladd.h
mslaio.o: ${MAKETOP}../export/power/kernel/include/sys/trchkid.h
mslaio.o: ${MAKETOP}../export/power/kernel/include/sys/trcmacros.h
mslaio.o: ${MAKETOP}../export/power/kernel/include/sys/ioacc.h
mslaio.o: ${MAKETOP}../export/power/kernel/include/sys/lock_def.h
mslaio.o: ${MAKETOP}../export/power/kernel/include/sys/lock_alloc.h
mslaio.o: ${MAKETOP}../export/power/kernel/include/sys/param.h
mslaio.o: ${MAKETOP}../export/power/kernel/include/sys/m_param.h
mslaio.o: ${MAKETOP}../export/power/kernel/include/sys/limits.h
mslaio.o: ${MAKETOP}../export/power/kernel/include/float.h
mslaio.o: ${MAKETOP}../export/power/kernel/include/jfs/fsparam.h
mslaio.o: ${MAKETOP}../export/power/kernel/include/sys/sysmacros.h
mslaio.o: ${MAKETOP}bos/kernext/msla/msladefs.h
mslaio.o: ${MAKETOP}bos/kernext/msla/msladecls.h
mslaio.o: ${MAKETOP}bos/kernext/msla/mslamac.h
mslaio.o: ${MAKETOP}bos/kernext/msla/mslaextern.h
#
# dependents of mslaioctl.o:
mslaioctl.o: ${MAKETOP}../export/power/kernel/include/sys/errno.h
mslaioctl.o: ${MAKETOP}../export/power/kernel/include/standards.h
mslaioctl.o: ${MAKETOP}../export/power/kernel/include/fcntl.h
mslaioctl.o: ${MAKETOP}../export/power/kernel/include/sys/types.h
mslaioctl.o: ${MAKETOP}../export/power/kernel/include/sys/m_types.h
mslaioctl.o: ${MAKETOP}../export/power/kernel/include/sys/flock.h
mslaioctl.o: ${MAKETOP}../export/power/kernel/include/unistd.h
mslaioctl.o: ${MAKETOP}../export/power/kernel/include/sys/access.h
mslaioctl.o: ${MAKETOP}../export/power/kernel/include/sys/lockf.h
mslaioctl.o: ${MAKETOP}../export/power/kernel/include/sys/stat.h
mslaioctl.o: ${MAKETOP}../export/power/kernel/include/sys/mode.h
mslaioctl.o: ${MAKETOP}../export/power/kernel/include/sys/ioctl.h
mslaioctl.o: ${MAKETOP}../export/power/kernel/include/sys/ttychars.h
mslaioctl.o: ${MAKETOP}../export/power/kernel/include/sys/ttydev.h
mslaioctl.o: ${MAKETOP}../export/power/kernel/include/sys/sleep.h
mslaioctl.o: ${MAKETOP}../export/power/kernel/include/sys/io3270.h
mslaioctl.o: ${MAKETOP}../export/power/kernel/include/sys/intr.h
mslaioctl.o: ${MAKETOP}../export/power/kernel/include/sys/m_intr.h
mslaioctl.o: ${MAKETOP}../export/power/kernel/include/sys/dma.h
mslaioctl.o: ${MAKETOP}../export/power/kernel/include/sys/sysdma.h
mslaioctl.o: ${MAKETOP}../export/power/kernel/include/sys/xmem.h
mslaioctl.o: ${MAKETOP}../export/power/kernel/include/sys/malloc.h
mslaioctl.o: ${MAKETOP}../export/power/kernel/include/malloc.h
mslaioctl.o: ${MAKETOP}../export/power/kernel/include/sys/pin.h
mslaioctl.o: ${MAKETOP}../export/power/kernel/include/sys/errids.h
mslaioctl.o: ${MAKETOP}../export/power/kernel/include/sys/err_rec.h
mslaioctl.o: ${MAKETOP}../export/power/kernel/include/sys/uio.h
mslaioctl.o: ${MAKETOP}../export/power/kernel/include/sys/vmuser.h
mslaioctl.o: ${MAKETOP}../export/power/kernel/include/sys/adspace.h
mslaioctl.o: ${MAKETOP}../export/power/kernel/include/sys/seg.h
mslaioctl.o: ${MAKETOP}../export/power/kernel/include/sys/inode.h
mslaioctl.o: ${MAKETOP}../export/power/kernel/include/jfs/inode.h
mslaioctl.o: ${MAKETOP}../export/power/kernel/include/sys/param.h
mslaioctl.o: ${MAKETOP}../export/power/kernel/include/sys/m_param.h
mslaioctl.o: ${MAKETOP}../export/power/kernel/include/sys/limits.h
mslaioctl.o: ${MAKETOP}../export/power/kernel/include/float.h
mslaioctl.o: ${MAKETOP}../export/power/kernel/include/jfs/fsparam.h
mslaioctl.o: ${MAKETOP}../export/power/kernel/include/sys/sysmacros.h
mslaioctl.o: ${MAKETOP}../export/power/kernel/include/jfs/ino.h
mslaioctl.o: ${MAKETOP}../export/power/kernel/include/sys/time.h
mslaioctl.o: ${MAKETOP}../export/power/kernel/include/jfs/fsdefs.h
mslaioctl.o: ${MAKETOP}../export/power/kernel/include/jfs/filsys.h
mslaioctl.o: ${MAKETOP}../export/power/kernel/include/jfs/jfsmount.h
mslaioctl.o: ${MAKETOP}../export/power/kernel/include/sys/vnode.h
mslaioctl.o: ${MAKETOP}../export/power/kernel/include/sys/lockl.h
mslaioctl.o: ${MAKETOP}../export/power/kernel/include/sys/lock_def.h
mslaioctl.o: ${MAKETOP}../export/power/kernel/include/sys/cred.h
mslaioctl.o: ${MAKETOP}../export/power/kernel/include/sys/priv.h
mslaioctl.o: ${MAKETOP}../export/power/kernel/include/sys/tcb.h
mslaioctl.o: ${MAKETOP}../export/power/kernel/include/sys/pcl.h
mslaioctl.o: ${MAKETOP}../export/power/kernel/include/jfs/quota.h
mslaioctl.o: ${MAKETOP}../export/power/kernel/include/sys/acl.h
mslaioctl.o: ${MAKETOP}../export/power/kernel/include/sys/systemcfg.h
mslaioctl.o: ${MAKETOP}../export/power/kernel/include/sys/ioacc.h
mslaioctl.o: ${MAKETOP}../export/power/kernel/include/sys/iocc.h
mslaioctl.o: ${MAKETOP}../export/power/kernel/include/sys/mdio.h
mslaioctl.o: ${MAKETOP}../export/power/kernel/include/sys/conf.h
mslaioctl.o: ${MAKETOP}../export/power/kernel/include/sys/device.h
mslaioctl.o: ${MAKETOP}../export/power/kernel/include/sys/file.h
mslaioctl.o: ${MAKETOP}../export/power/kernel/include/sys/low.h
mslaioctl.o: ${MAKETOP}../export/power/kernel/include/sys/syspest.h
mslaioctl.o: ${MAKETOP}../export/power/kernel/include/sys/pri.h
mslaioctl.o: ${MAKETOP}../export/power/kernel/include/sys/proc.h
mslaioctl.o: ${MAKETOP}../export/power/kernel/include/sys/ptrace.h
mslaioctl.o: ${MAKETOP}../export/power/kernel/include/sys/thread.h
mslaioctl.o: ${MAKETOP}../export/power/kernel/include/sys/mstsave.h
mslaioctl.o: ${MAKETOP}../export/power/kernel/include/sys/processor.h
mslaioctl.o: ${MAKETOP}../export/power/kernel/include/sys/var.h
mslaioctl.o: ${MAKETOP}../export/power/kernel/include/sys/atomic_op.h
mslaioctl.o: ${MAKETOP}../export/power/kernel/include/sys/timer.h
mslaioctl.o: ${MAKETOP}../export/power/kernel/include/sys/resource.h
mslaioctl.o: ${MAKETOP}../export/power/kernel/include/sys/except.h
mslaioctl.o: ${MAKETOP}../export/power/kernel/include/sys/m_except.h
mslaioctl.o: ${MAKETOP}bos/kernext/msla/msladefs.h
mslaioctl.o: ${MAKETOP}bos/kernext/msla/msladecls.h
mslaioctl.o: ${MAKETOP}bos/kernext/msla/msladd.h
mslaioctl.o: ${MAKETOP}../export/power/kernel/include/sys/trchkid.h
mslaioctl.o: ${MAKETOP}../export/power/kernel/include/sys/trcmacros.h
mslaioctl.o: ${MAKETOP}../export/power/kernel/include/sys/lock_alloc.h
mslaioctl.o: ${MAKETOP}bos/kernext/msla/mslamac.h
mslaioctl.o: ${MAKETOP}bos/kernext/msla/mslaextern.h
mslaioctl.o: ${MAKETOP}bos/kernext/msla/io5080.h
#
# dependents of mslamisc.o:
mslamisc.o: ${MAKETOP}../export/power/kernel/include/sys/buf.h
mslamisc.o: ${MAKETOP}../export/power/kernel/include/sys/types.h
mslamisc.o: ${MAKETOP}../export/power/kernel/include/standards.h
mslamisc.o: ${MAKETOP}../export/power/kernel/include/sys/m_types.h
mslamisc.o: ${MAKETOP}../export/power/kernel/include/sys/xmem.h
mslamisc.o: ${MAKETOP}../export/power/kernel/include/sys/time.h
mslamisc.o: ${MAKETOP}../export/power/kernel/include/sys/errno.h
mslamisc.o: ${MAKETOP}../export/power/kernel/include/sys/io3270.h
mslamisc.o: ${MAKETOP}../export/power/kernel/include/sys/pin.h
mslamisc.o: ${MAKETOP}../export/power/kernel/include/sys/malloc.h
mslamisc.o: ${MAKETOP}../export/power/kernel/include/sys/dma.h
mslamisc.o: ${MAKETOP}../export/power/kernel/include/sys/sysdma.h
mslamisc.o: ${MAKETOP}../export/power/kernel/include/sys/intr.h
mslamisc.o: ${MAKETOP}../export/power/kernel/include/sys/m_intr.h
mslamisc.o: ${MAKETOP}../export/power/kernel/include/sys/iocc.h
mslamisc.o: ${MAKETOP}../export/power/kernel/include/sys/errids.h
mslamisc.o: ${MAKETOP}../export/power/kernel/include/sys/err_rec.h
mslamisc.o: ${MAKETOP}../export/power/kernel/include/sys/m_except.h
mslamisc.o: ${MAKETOP}../export/power/kernel/include/sys/adspace.h
mslamisc.o: ${MAKETOP}../export/power/kernel/include/sys/seg.h
mslamisc.o: ${MAKETOP}../export/power/kernel/include/sys/inode.h
mslamisc.o: ${MAKETOP}../export/power/kernel/include/jfs/inode.h
mslamisc.o: ${MAKETOP}../export/power/kernel/include/sys/param.h
mslamisc.o: ${MAKETOP}../export/power/kernel/include/sys/m_param.h
mslamisc.o: ${MAKETOP}../export/power/kernel/include/sys/limits.h
mslamisc.o: ${MAKETOP}../export/power/kernel/include/float.h
mslamisc.o: ${MAKETOP}../export/power/kernel/include/jfs/fsparam.h
mslamisc.o: ${MAKETOP}../export/power/kernel/include/sys/sysmacros.h
mslamisc.o: ${MAKETOP}../export/power/kernel/include/jfs/ino.h
mslamisc.o: ${MAKETOP}../export/power/kernel/include/jfs/fsdefs.h
mslamisc.o: ${MAKETOP}../export/power/kernel/include/jfs/filsys.h
mslamisc.o: ${MAKETOP}../export/power/kernel/include/jfs/jfsmount.h
mslamisc.o: ${MAKETOP}../export/power/kernel/include/sys/vnode.h
mslamisc.o: ${MAKETOP}../export/power/kernel/include/sys/stat.h
mslamisc.o: ${MAKETOP}../export/power/kernel/include/sys/mode.h
mslamisc.o: ${MAKETOP}../export/power/kernel/include/sys/lockl.h
mslamisc.o: ${MAKETOP}../export/power/kernel/include/sys/lock_def.h
mslamisc.o: ${MAKETOP}../export/power/kernel/include/sys/uio.h
mslamisc.o: ${MAKETOP}../export/power/kernel/include/sys/cred.h
mslamisc.o: ${MAKETOP}../export/power/kernel/include/sys/priv.h
mslamisc.o: ${MAKETOP}../export/power/kernel/include/sys/tcb.h
mslamisc.o: ${MAKETOP}../export/power/kernel/include/sys/pcl.h
mslamisc.o: ${MAKETOP}../export/power/kernel/include/jfs/quota.h
mslamisc.o: ${MAKETOP}../export/power/kernel/include/sys/vmuser.h
mslamisc.o: ${MAKETOP}../export/power/kernel/include/sys/acl.h
mslamisc.o: ${MAKETOP}../export/power/kernel/include/sys/access.h
mslamisc.o: ${MAKETOP}../export/power/kernel/include/sys/systemcfg.h
mslamisc.o: ${MAKETOP}bos/kernext/msla/msladd.h
mslamisc.o: ${MAKETOP}../export/power/kernel/include/sys/trchkid.h
mslamisc.o: ${MAKETOP}../export/power/kernel/include/sys/trcmacros.h
mslamisc.o: ${MAKETOP}../export/power/kernel/include/sys/ioacc.h
mslamisc.o: ${MAKETOP}../export/power/kernel/include/sys/lock_alloc.h
mslamisc.o: ${MAKETOP}bos/kernext/msla/msladefs.h
mslamisc.o: ${MAKETOP}bos/kernext/msla/msladecls.h
mslamisc.o: ${MAKETOP}bos/kernext/msla/mslaextern.h
mslamisc.o: ${MAKETOP}bos/kernext/msla/mslamac.h
#
# dependents of mslampx.o:
mslampx.o: ${MAKETOP}../export/power/kernel/include/sys/devinfo.h
mslampx.o: ${MAKETOP}../export/power/kernel/include/sys/types.h
mslampx.o: ${MAKETOP}../export/power/kernel/include/standards.h
mslampx.o: ${MAKETOP}../export/power/kernel/include/sys/m_types.h
mslampx.o: ${MAKETOP}../export/power/kernel/include/sys/errno.h
mslampx.o: ${MAKETOP}../export/power/kernel/include/fcntl.h
mslampx.o: ${MAKETOP}../export/power/kernel/include/sys/flock.h
mslampx.o: ${MAKETOP}../export/power/kernel/include/unistd.h
mslampx.o: ${MAKETOP}../export/power/kernel/include/sys/access.h
mslampx.o: ${MAKETOP}../export/power/kernel/include/sys/lockf.h
mslampx.o: ${MAKETOP}../export/power/kernel/include/sys/stat.h
mslampx.o: ${MAKETOP}../export/power/kernel/include/sys/mode.h
mslampx.o: ${MAKETOP}../export/power/kernel/include/stdio.h
mslampx.o: ${MAKETOP}../export/power/kernel/include/va_list.h
mslampx.o: ${MAKETOP}../export/power/kernel/include/sys/limits.h
mslampx.o: ${MAKETOP}../export/power/kernel/include/float.h
mslampx.o: ${MAKETOP}../export/power/kernel/include/sys/ioctl.h
mslampx.o: ${MAKETOP}../export/power/kernel/include/sys/ttychars.h
mslampx.o: ${MAKETOP}../export/power/kernel/include/sys/ttydev.h
mslampx.o: ${MAKETOP}../export/power/kernel/include/sys/file.h
mslampx.o: ${MAKETOP}../export/power/kernel/include/sys/param.h
mslampx.o: ${MAKETOP}../export/power/kernel/include/sys/m_param.h
mslampx.o: ${MAKETOP}../export/power/kernel/include/jfs/fsparam.h
mslampx.o: ${MAKETOP}../export/power/kernel/include/sys/sysmacros.h
mslampx.o: ${MAKETOP}../export/power/kernel/include/sys/lock_def.h
mslampx.o: ${MAKETOP}../export/power/kernel/include/sys/cred.h
mslampx.o: ${MAKETOP}../export/power/kernel/include/sys/priv.h
mslampx.o: ${MAKETOP}../export/power/kernel/include/sys/tcb.h
mslampx.o: ${MAKETOP}../export/power/kernel/include/sys/pcl.h
mslampx.o: ${MAKETOP}../export/power/kernel/include/sys/lockl.h
mslampx.o: ${MAKETOP}../export/power/kernel/include/sys/signal.h
mslampx.o: ${MAKETOP}../export/power/kernel/include/sys/context.h
mslampx.o: ${MAKETOP}../export/power/kernel/include/sys/mstsave.h
mslampx.o: ${MAKETOP}../export/power/kernel/include/sys/io3270.h
mslampx.o: ${MAKETOP}../export/power/kernel/include/sys/intr.h
mslampx.o: ${MAKETOP}../export/power/kernel/include/sys/m_intr.h
mslampx.o: ${MAKETOP}bos/kernext/msla/msladefs.h
mslampx.o: ${MAKETOP}bos/kernext/msla/msladecls.h
mslampx.o: ${MAKETOP}../export/power/kernel/include/sys/xmem.h
mslampx.o: ${MAKETOP}../export/power/kernel/include/sys/err_rec.h
mslampx.o: ${MAKETOP}bos/kernext/msla/mslamac.h
mslampx.o: ${MAKETOP}bos/kernext/msla/msladd.h
mslampx.o: ${MAKETOP}../export/power/kernel/include/sys/trchkid.h
mslampx.o: ${MAKETOP}../export/power/kernel/include/sys/trcmacros.h
mslampx.o: ${MAKETOP}../export/power/kernel/include/sys/ioacc.h
mslampx.o: ${MAKETOP}../export/power/kernel/include/sys/lock_alloc.h
mslampx.o: ${MAKETOP}bos/kernext/msla/mslaextern.h
#
# dependents of mslaofflv.o:
mslaofflv.o: ${MAKETOP}../export/power/kernel/include/sys/buf.h
mslaofflv.o: ${MAKETOP}../export/power/kernel/include/sys/types.h
mslaofflv.o: ${MAKETOP}../export/power/kernel/include/standards.h
mslaofflv.o: ${MAKETOP}../export/power/kernel/include/sys/m_types.h
mslaofflv.o: ${MAKETOP}../export/power/kernel/include/sys/xmem.h
mslaofflv.o: ${MAKETOP}../export/power/kernel/include/sys/time.h
mslaofflv.o: ${MAKETOP}../export/power/kernel/include/sys/intr.h
mslaofflv.o: ${MAKETOP}../export/power/kernel/include/sys/m_intr.h
mslaofflv.o: ${MAKETOP}../export/power/kernel/include/sys/io3270.h
mslaofflv.o: ${MAKETOP}../export/power/kernel/include/sys/malloc.h
mslaofflv.o: ${MAKETOP}../export/power/kernel/include/malloc.h
mslaofflv.o: ${MAKETOP}../export/power/kernel/include/sys/dma.h
mslaofflv.o: ${MAKETOP}../export/power/kernel/include/sys/sysdma.h
mslaofflv.o: ${MAKETOP}../export/power/kernel/include/sys/errids.h
mslaofflv.o: ${MAKETOP}../export/power/kernel/include/sys/err_rec.h
mslaofflv.o: ${MAKETOP}../export/power/kernel/include/sys/sleep.h
mslaofflv.o: ${MAKETOP}../export/power/kernel/include/sys/errno.h
mslaofflv.o: ${MAKETOP}../export/power/kernel/include/sys/poll.h
mslaofflv.o: ${MAKETOP}../export/power/kernel/include/sys/sysmacros.h
mslaofflv.o: ${MAKETOP}../export/power/kernel/include/sys/param.h
mslaofflv.o: ${MAKETOP}../export/power/kernel/include/sys/m_param.h
mslaofflv.o: ${MAKETOP}../export/power/kernel/include/sys/limits.h
mslaofflv.o: ${MAKETOP}../export/power/kernel/include/float.h
mslaofflv.o: ${MAKETOP}../export/power/kernel/include/jfs/fsparam.h
mslaofflv.o: ${MAKETOP}bos/kernext/msla/msladd.h
mslaofflv.o: ${MAKETOP}../export/power/kernel/include/sys/trchkid.h
mslaofflv.o: ${MAKETOP}../export/power/kernel/include/sys/trcmacros.h
mslaofflv.o: ${MAKETOP}../export/power/kernel/include/sys/ioacc.h
mslaofflv.o: ${MAKETOP}../export/power/kernel/include/sys/lock_def.h
mslaofflv.o: ${MAKETOP}../export/power/kernel/include/sys/lock_alloc.h
mslaofflv.o: ${MAKETOP}bos/kernext/msla/msladefs.h
mslaofflv.o: ${MAKETOP}bos/kernext/msla/msladecls.h
mslaofflv.o: ${MAKETOP}bos/kernext/msla/mslamac.h
mslaofflv.o: ${MAKETOP}bos/kernext/msla/mslaextern.h
#
# dependents of mslaopen.o:
mslaopen.o: ${MAKETOP}../export/power/kernel/include/sys/devinfo.h
mslaopen.o: ${MAKETOP}../export/power/kernel/include/sys/types.h
mslaopen.o: ${MAKETOP}../export/power/kernel/include/standards.h
mslaopen.o: ${MAKETOP}../export/power/kernel/include/sys/m_types.h
mslaopen.o: ${MAKETOP}../export/power/kernel/include/sys/errno.h
mslaopen.o: ${MAKETOP}../export/power/kernel/include/fcntl.h
mslaopen.o: ${MAKETOP}../export/power/kernel/include/sys/flock.h
mslaopen.o: ${MAKETOP}../export/power/kernel/include/unistd.h
mslaopen.o: ${MAKETOP}../export/power/kernel/include/sys/access.h
mslaopen.o: ${MAKETOP}../export/power/kernel/include/sys/lockf.h
mslaopen.o: ${MAKETOP}../export/power/kernel/include/sys/stat.h
mslaopen.o: ${MAKETOP}../export/power/kernel/include/sys/mode.h
mslaopen.o: ${MAKETOP}../export/power/kernel/include/stdio.h
mslaopen.o: ${MAKETOP}../export/power/kernel/include/va_list.h
mslaopen.o: ${MAKETOP}../export/power/kernel/include/sys/limits.h
mslaopen.o: ${MAKETOP}../export/power/kernel/include/float.h
mslaopen.o: ${MAKETOP}../export/power/kernel/include/sys/ioctl.h
mslaopen.o: ${MAKETOP}../export/power/kernel/include/sys/ttychars.h
mslaopen.o: ${MAKETOP}../export/power/kernel/include/sys/ttydev.h
mslaopen.o: ${MAKETOP}../export/power/kernel/include/sys/file.h
mslaopen.o: ${MAKETOP}../export/power/kernel/include/sys/param.h
mslaopen.o: ${MAKETOP}../export/power/kernel/include/sys/m_param.h
mslaopen.o: ${MAKETOP}../export/power/kernel/include/jfs/fsparam.h
mslaopen.o: ${MAKETOP}../export/power/kernel/include/sys/sysmacros.h
mslaopen.o: ${MAKETOP}../export/power/kernel/include/sys/lock_def.h
mslaopen.o: ${MAKETOP}../export/power/kernel/include/sys/cred.h
mslaopen.o: ${MAKETOP}../export/power/kernel/include/sys/priv.h
mslaopen.o: ${MAKETOP}../export/power/kernel/include/sys/tcb.h
mslaopen.o: ${MAKETOP}../export/power/kernel/include/sys/pcl.h
mslaopen.o: ${MAKETOP}../export/power/kernel/include/sys/lockl.h
mslaopen.o: ${MAKETOP}../export/power/kernel/include/sys/signal.h
mslaopen.o: ${MAKETOP}../export/power/kernel/include/sys/context.h
mslaopen.o: ${MAKETOP}../export/power/kernel/include/sys/mstsave.h
mslaopen.o: ${MAKETOP}../export/power/kernel/include/sys/sleep.h
mslaopen.o: ${MAKETOP}../export/power/kernel/include/sys/pin.h
mslaopen.o: ${MAKETOP}../export/power/kernel/include/sys/malloc.h
mslaopen.o: ${MAKETOP}../export/power/kernel/include/malloc.h
mslaopen.o: ${MAKETOP}../export/power/kernel/include/sys/io3270.h
mslaopen.o: ${MAKETOP}../export/power/kernel/include/sys/intr.h
mslaopen.o: ${MAKETOP}../export/power/kernel/include/sys/m_intr.h
mslaopen.o: ${MAKETOP}../export/power/kernel/include/sys/iocc.h
mslaopen.o: ${MAKETOP}../export/power/kernel/include/sys/errids.h
mslaopen.o: ${MAKETOP}../export/power/kernel/include/sys/err_rec.h
mslaopen.o: ${MAKETOP}bos/kernext/msla/msladefs.h
mslaopen.o: ${MAKETOP}bos/kernext/msla/msladecls.h
mslaopen.o: ${MAKETOP}../export/power/kernel/include/sys/xmem.h
mslaopen.o: ${MAKETOP}bos/kernext/msla/mslamac.h
mslaopen.o: ${MAKETOP}bos/kernext/msla/mslaextern.h
mslaopen.o: ${MAKETOP}bos/kernext/msla/msladd.h
mslaopen.o: ${MAKETOP}../export/power/kernel/include/sys/trchkid.h
mslaopen.o: ${MAKETOP}../export/power/kernel/include/sys/trcmacros.h
mslaopen.o: ${MAKETOP}../export/power/kernel/include/sys/ioacc.h
mslaopen.o: ${MAKETOP}../export/power/kernel/include/sys/lock_alloc.h
#
# dependents of mslaread.o:
mslaread.o: ${MAKETOP}../export/power/kernel/include/sys/errno.h
mslaread.o: ${MAKETOP}../export/power/kernel/include/standards.h
mslaread.o: ${MAKETOP}../export/power/kernel/include/fcntl.h
mslaread.o: ${MAKETOP}../export/power/kernel/include/sys/types.h
mslaread.o: ${MAKETOP}../export/power/kernel/include/sys/m_types.h
mslaread.o: ${MAKETOP}../export/power/kernel/include/sys/flock.h
mslaread.o: ${MAKETOP}../export/power/kernel/include/unistd.h
mslaread.o: ${MAKETOP}../export/power/kernel/include/sys/access.h
mslaread.o: ${MAKETOP}../export/power/kernel/include/sys/lockf.h
mslaread.o: ${MAKETOP}../export/power/kernel/include/sys/stat.h
mslaread.o: ${MAKETOP}../export/power/kernel/include/sys/mode.h
mslaread.o: ${MAKETOP}../export/power/kernel/include/sys/sleep.h
mslaread.o: ${MAKETOP}../export/power/kernel/include/sys/uio.h
mslaread.o: ${MAKETOP}../export/power/kernel/include/sys/xmem.h
mslaread.o: ${MAKETOP}../export/power/kernel/include/sys/pin.h
mslaread.o: ${MAKETOP}../export/power/kernel/include/sys/malloc.h
mslaread.o: ${MAKETOP}../export/power/kernel/include/sys/io3270.h
mslaread.o: ${MAKETOP}../export/power/kernel/include/sys/intr.h
mslaread.o: ${MAKETOP}../export/power/kernel/include/sys/m_intr.h
mslaread.o: ${MAKETOP}bos/kernext/msla/msladefs.h
mslaread.o: ${MAKETOP}bos/kernext/msla/msladecls.h
mslaread.o: ${MAKETOP}../export/power/kernel/include/sys/err_rec.h
mslaread.o: ${MAKETOP}bos/kernext/msla/mslamac.h
mslaread.o: ${MAKETOP}bos/kernext/msla/msladd.h
mslaread.o: ${MAKETOP}../export/power/kernel/include/sys/trchkid.h
mslaread.o: ${MAKETOP}../export/power/kernel/include/sys/trcmacros.h
mslaread.o: ${MAKETOP}../export/power/kernel/include/sys/ioacc.h
mslaread.o: ${MAKETOP}../export/power/kernel/include/sys/lock_def.h
mslaread.o: ${MAKETOP}../export/power/kernel/include/sys/lock_alloc.h
mslaread.o: ${MAKETOP}../export/power/kernel/include/sys/param.h
mslaread.o: ${MAKETOP}../export/power/kernel/include/sys/m_param.h
mslaread.o: ${MAKETOP}../export/power/kernel/include/sys/limits.h
mslaread.o: ${MAKETOP}../export/power/kernel/include/float.h
mslaread.o: ${MAKETOP}../export/power/kernel/include/jfs/fsparam.h
mslaread.o: ${MAKETOP}../export/power/kernel/include/sys/sysmacros.h
mslaread.o: ${MAKETOP}bos/kernext/msla/mslaextern.h
#
# dependents of mslaselect.o:
mslaselect.o: ${MAKETOP}../export/power/kernel/include/sys/poll.h
mslaselect.o: ${MAKETOP}../export/power/kernel/include/standards.h
mslaselect.o: ${MAKETOP}../export/power/kernel/include/sys/types.h
mslaselect.o: ${MAKETOP}../export/power/kernel/include/sys/m_types.h
mslaselect.o: ${MAKETOP}../export/power/kernel/include/fcntl.h
mslaselect.o: ${MAKETOP}../export/power/kernel/include/sys/flock.h
mslaselect.o: ${MAKETOP}../export/power/kernel/include/unistd.h
mslaselect.o: ${MAKETOP}../export/power/kernel/include/sys/access.h
mslaselect.o: ${MAKETOP}../export/power/kernel/include/sys/lockf.h
mslaselect.o: ${MAKETOP}../export/power/kernel/include/sys/stat.h
mslaselect.o: ${MAKETOP}../export/power/kernel/include/sys/mode.h
mslaselect.o: ${MAKETOP}../export/power/kernel/include/sys/file.h
mslaselect.o: ${MAKETOP}../export/power/kernel/include/sys/param.h
mslaselect.o: ${MAKETOP}../export/power/kernel/include/sys/m_param.h
mslaselect.o: ${MAKETOP}../export/power/kernel/include/sys/limits.h
mslaselect.o: ${MAKETOP}../export/power/kernel/include/float.h
mslaselect.o: ${MAKETOP}../export/power/kernel/include/jfs/fsparam.h
mslaselect.o: ${MAKETOP}../export/power/kernel/include/sys/sysmacros.h
mslaselect.o: ${MAKETOP}../export/power/kernel/include/sys/lock_def.h
mslaselect.o: ${MAKETOP}../export/power/kernel/include/sys/cred.h
mslaselect.o: ${MAKETOP}../export/power/kernel/include/sys/priv.h
mslaselect.o: ${MAKETOP}../export/power/kernel/include/sys/tcb.h
mslaselect.o: ${MAKETOP}../export/power/kernel/include/sys/pcl.h
mslaselect.o: ${MAKETOP}../export/power/kernel/include/sys/lockl.h
mslaselect.o: ${MAKETOP}../export/power/kernel/include/sys/systm.h
mslaselect.o: ${MAKETOP}../export/power/kernel/include/sys/mstsave.h
mslaselect.o: ${MAKETOP}../export/power/kernel/include/sys/vnode.h
mslaselect.o: ${MAKETOP}../export/power/kernel/include/sys/uio.h
mslaselect.o: ${MAKETOP}../export/power/kernel/include/sys/xmem.h
mslaselect.o: ${MAKETOP}../export/power/kernel/include/sys/proc.h
mslaselect.o: ${MAKETOP}../export/power/kernel/include/sys/ptrace.h
mslaselect.o: ${MAKETOP}../export/power/kernel/include/sys/thread.h
mslaselect.o: ${MAKETOP}../export/power/kernel/include/sys/processor.h
mslaselect.o: ${MAKETOP}../export/power/kernel/include/sys/var.h
mslaselect.o: ${MAKETOP}../export/power/kernel/include/sys/atomic_op.h
mslaselect.o: ${MAKETOP}../export/power/kernel/include/sys/timer.h
mslaselect.o: ${MAKETOP}../export/power/kernel/include/sys/time.h
mslaselect.o: ${MAKETOP}../export/power/kernel/include/sys/resource.h
mslaselect.o: ${MAKETOP}../export/power/kernel/include/sys/pri.h
mslaselect.o: ${MAKETOP}../export/power/kernel/include/sys/inode.h
mslaselect.o: ${MAKETOP}../export/power/kernel/include/jfs/inode.h
mslaselect.o: ${MAKETOP}../export/power/kernel/include/jfs/ino.h
mslaselect.o: ${MAKETOP}../export/power/kernel/include/jfs/fsdefs.h
mslaselect.o: ${MAKETOP}../export/power/kernel/include/jfs/filsys.h
mslaselect.o: ${MAKETOP}../export/power/kernel/include/jfs/jfsmount.h
mslaselect.o: ${MAKETOP}../export/power/kernel/include/jfs/quota.h
mslaselect.o: ${MAKETOP}../export/power/kernel/include/sys/vmuser.h
mslaselect.o: ${MAKETOP}../export/power/kernel/include/sys/acl.h
mslaselect.o: ${MAKETOP}../export/power/kernel/include/sys/buf.h
mslaselect.o: ${MAKETOP}../export/power/kernel/include/sys/filsys.h
mslaselect.o: ${MAKETOP}../export/power/kernel/include/sys/low.h
mslaselect.o: ${MAKETOP}../export/power/kernel/include/sys/device.h
mslaselect.o: ${MAKETOP}../export/power/kernel/include/sys/intr.h
mslaselect.o: ${MAKETOP}../export/power/kernel/include/sys/m_intr.h
mslaselect.o: ${MAKETOP}../export/power/kernel/include/sys/syspest.h
mslaselect.o: ${MAKETOP}../export/power/kernel/include/sys/errno.h
mslaselect.o: ${MAKETOP}../export/power/kernel/include/sys/io3270.h
mslaselect.o: ${MAKETOP}bos/kernext/msla/msladd.h
mslaselect.o: ${MAKETOP}../export/power/kernel/include/sys/trchkid.h
mslaselect.o: ${MAKETOP}../export/power/kernel/include/sys/trcmacros.h
mslaselect.o: ${MAKETOP}../export/power/kernel/include/sys/ioacc.h
mslaselect.o: ${MAKETOP}../export/power/kernel/include/sys/lock_alloc.h
mslaselect.o: ${MAKETOP}bos/kernext/msla/msladefs.h
mslaselect.o: ${MAKETOP}bos/kernext/msla/msladecls.h
mslaselect.o: ${MAKETOP}../export/power/kernel/include/sys/err_rec.h
mslaselect.o: ${MAKETOP}bos/kernext/msla/mslamac.h
mslaselect.o: ${MAKETOP}bos/kernext/msla/mslaextern.h
#
# dependents of mslawrite.o:
mslawrite.o: ${MAKETOP}../export/power/kernel/include/sys/devinfo.h
mslawrite.o: ${MAKETOP}../export/power/kernel/include/sys/types.h
mslawrite.o: ${MAKETOP}../export/power/kernel/include/standards.h
mslawrite.o: ${MAKETOP}../export/power/kernel/include/sys/m_types.h
mslawrite.o: ${MAKETOP}../export/power/kernel/include/sys/errno.h
mslawrite.o: ${MAKETOP}../export/power/kernel/include/fcntl.h
mslawrite.o: ${MAKETOP}../export/power/kernel/include/sys/flock.h
mslawrite.o: ${MAKETOP}../export/power/kernel/include/unistd.h
mslawrite.o: ${MAKETOP}../export/power/kernel/include/sys/access.h
mslawrite.o: ${MAKETOP}../export/power/kernel/include/sys/lockf.h
mslawrite.o: ${MAKETOP}../export/power/kernel/include/sys/stat.h
mslawrite.o: ${MAKETOP}../export/power/kernel/include/sys/mode.h
mslawrite.o: ${MAKETOP}../export/power/kernel/include/stdio.h
mslawrite.o: ${MAKETOP}../export/power/kernel/include/va_list.h
mslawrite.o: ${MAKETOP}../export/power/kernel/include/sys/limits.h
mslawrite.o: ${MAKETOP}../export/power/kernel/include/float.h
mslawrite.o: ${MAKETOP}../export/power/kernel/include/sys/ioctl.h
mslawrite.o: ${MAKETOP}../export/power/kernel/include/sys/ttychars.h
mslawrite.o: ${MAKETOP}../export/power/kernel/include/sys/ttydev.h
mslawrite.o: ${MAKETOP}../export/power/kernel/include/sys/file.h
mslawrite.o: ${MAKETOP}../export/power/kernel/include/sys/param.h
mslawrite.o: ${MAKETOP}../export/power/kernel/include/sys/m_param.h
mslawrite.o: ${MAKETOP}../export/power/kernel/include/jfs/fsparam.h
mslawrite.o: ${MAKETOP}../export/power/kernel/include/sys/sysmacros.h
mslawrite.o: ${MAKETOP}../export/power/kernel/include/sys/lock_def.h
mslawrite.o: ${MAKETOP}../export/power/kernel/include/sys/cred.h
mslawrite.o: ${MAKETOP}../export/power/kernel/include/sys/priv.h
mslawrite.o: ${MAKETOP}../export/power/kernel/include/sys/tcb.h
mslawrite.o: ${MAKETOP}../export/power/kernel/include/sys/pcl.h
mslawrite.o: ${MAKETOP}../export/power/kernel/include/sys/lockl.h
mslawrite.o: ${MAKETOP}../export/power/kernel/include/sys/signal.h
mslawrite.o: ${MAKETOP}../export/power/kernel/include/sys/context.h
mslawrite.o: ${MAKETOP}../export/power/kernel/include/sys/mstsave.h
mslawrite.o: ${MAKETOP}../export/power/kernel/include/sys/sleep.h
mslawrite.o: ${MAKETOP}../export/power/kernel/include/sys/uio.h
mslawrite.o: ${MAKETOP}../export/power/kernel/include/sys/xmem.h
mslawrite.o: ${MAKETOP}../export/power/kernel/include/sys/pin.h
mslawrite.o: ${MAKETOP}../export/power/kernel/include/sys/malloc.h
mslawrite.o: ${MAKETOP}../export/power/kernel/include/sys/io3270.h
mslawrite.o: ${MAKETOP}../export/power/kernel/include/sys/errids.h
mslawrite.o: ${MAKETOP}../export/power/kernel/include/sys/err_rec.h
mslawrite.o: ${MAKETOP}bos/kernext/msla/msladefs.h
mslawrite.o: ${MAKETOP}bos/kernext/msla/msladecls.h
mslawrite.o: ${MAKETOP}../export/power/kernel/include/sys/intr.h
mslawrite.o: ${MAKETOP}../export/power/kernel/include/sys/m_intr.h
mslawrite.o: ${MAKETOP}bos/kernext/msla/msladd.h
mslawrite.o: ${MAKETOP}../export/power/kernel/include/sys/trchkid.h
mslawrite.o: ${MAKETOP}../export/power/kernel/include/sys/trcmacros.h
mslawrite.o: ${MAKETOP}../export/power/kernel/include/sys/ioacc.h
mslawrite.o: ${MAKETOP}../export/power/kernel/include/sys/lock_alloc.h
mslawrite.o: ${MAKETOP}bos/kernext/msla/mslamac.h
mslawrite.o: ${MAKETOP}bos/kernext/msla/mslaextern.h
