hiadd: ${MAKETOP}../../export/power/kernel/lib/libsys.a(timeout.o)
hiadd: ${MAKETOP}../../export/power/kernel/lib/libsysp.a(pioutil.o)
hiadd: ${MAKETOP}../../export/power/kernel/lib/libcsys.a(ptrgl.o)
hiadd: ${MAKETOP}../../export/power/kernel/lib/libcsys.a(bzero.o)
hiadd: ${MAKETOP}../../export/power/kernel/lib/libcsys.a(moveeq.o)
hiadd: ${MAKETOP}../../export/power/kernel/lib/libcsys.a(strncpy.o)
