# @(#)45	1.1  src/bos/usr/lib/ncs/lib/compat1.1/Makefile, libncs, bos411, 9428A410j 3/25/94 20:03:54
#
#   COMPONENT_NAME: libncs
#
#   FUNCTIONS: none
#
#   ORIGINS: 27
#
#   IBM CONFIDENTIAL -- (IBM Confidential Restricted when
#   combined with the aggregated modules for this product)
#                    SOURCE MATERIALS
#
#   (C) COPYRIGHT International Business Machines Corp. 1994
#   All Rights Reserved
#   US Government Users Restricted Rights - Use, duplication or
#   disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#

ILIST		= libnck.a
IDIR		= /usr/lib/


.include <${RULES_MK}>

libnck.a:	libnck.aB
	${CP} ${libnck.aB:P} ${.TARGET}
