# @(#)19	1.3  src/bos/diag/tu/scsi/Makefile, tu_scsi, bos411, 9428A410j 1/7/94 10:13:47
#
#   COMPONENT_NAME: TU_SCSI
#
#   FUNCTIONS: 
#
#   ORIGINS: 27
#
#   IBM CONFIDENTIAL -- (IBM Confidential Restricted when
#   combined with the aggregated modules for this product)
#                    SOURCE MATERIALS
#
#   (C) COPYRIGHT International Business Machines Corp. 1992, 1994
#   All Rights Reserved
#   US Government Users Restricted Rights - Use, duplication or
#   disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#

#-------------------------------------------------------------------------#
#                                                                         #
#     This Makefile builds the library libscsitu.a for the DA application #
#                                                                         #
#-------------------------------------------------------------------------#

LIBRARIES       =   libscsitu.a

EXPLIB_TARGETS  =   export_libscsitu.a
EXPDIR          =   /usr/lib/

OFILES		=   scsi_atu.o

.include <${RULES_MK}>
