$ @(#)36	1.1  src/bos/usr/ccs/lib/libbsd/libbsd.msg, libbsd, bos411, 9428A410j 7/26/91 14:12:00
$
$  COMPONENT_NAME: (LIBBSD) Berkeley compatibility library
$
$  FUNCTIONS: libbsd messages
$
$  ORIGINS: 27,9
$
$  IBM CONFIDENTIAL -- (IBM Confidential Restricted when
$  combined with the aggregated modules for this product)
$                   SOURCE MATERIALS
$  (C) COPYRIGHT International Business Machines Corp. 1989
$  All Rights Reserved
$
$  US Government Users Restricted Rights - Use, duplication or
$  disclosure restricted by GSA ADP Schedule Contract with IBM Corp.

$set MS_LIBBSD
$quote "

$ The following messages are for util.c
M_NOSPACE	"1202-001 xalloc: no free space"
