# @(#)40	1.1  src/bos/kernext/rcm/inc/gai/Makefile, rcm, bos411, 9428A410j 1/10/94 15:41:52
#
#   COMPONENT_NAME: RCM
#
#   FUNCTIONS: none
#
#   ORIGINS: 27
#
#   IBM CONFIDENTIAL -- (IBM Confidential Restricted when
#   combined with the aggregated modules for this product)
#                    SOURCE MATERIALS
#
#   (C) COPYRIGHT International Business Machines Corp. 1993
#   All Rights Reserved
#   US Government Users Restricted Rights - Use, duplication or
#   disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#

INCLUDES	= gai.h

EXPDIR		= /kernel/include/gai/

.include <${RULES_MK}>
