# @(#)61	1.2  src/bos/usr/lib/pios/bidi/fonts/Makefile, cmdpios, bos411, 9428A410j 4/28/94 07:37:34
#
# COMPONENT_NAME: (CMDPIOS) Printer Backend
#
# ORIGINS: 27, 83
#
# IBM CONFIDENTIAL -- (IBM Confidential Restricted when
# combined with the aggregated modules for this product)
#                  SOURCE MATERIALS
# (C) COPYRIGHT International Business Machines Corp. 1989, 1994
# All Rights Reserved
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#
# LEVEL 1, 5 Years Bull Confidential Information
#

SUBDIRS	= 4019 4234 970

.include <${RULES_MK}>
