# @(#) 36 1.1 src/bos/usr/lpp/bosinst/Get_RVG_Disks/Makefile, bosinst, bos411, 9428A410j 6/30/93 17:25:13
# COMPONENT_NAME: bosinst
#
# FUNCTIONS: Makefile for Get_RVG_Disks
#
# ORIGINS: 27
#
# IBM CONFIDENTIAL -- (IBM Confidential Restricted when
# combined with the aggregated modules for this product)
#                  SOURCE MATERIALS
# (C) COPYRIGHT International Business Machines Corp. 1993
# All Rights Reserved
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#

SCRIPTS		= Get_RVG_Disks

ILIST		= ${SCRIPTS}
IDIR		= /usr/lpp/bosinst/

.include <${RULES_MK}>
