# @(#)18        1.1  src/bldenv/gos/desktop/canon1/Makefile, desktop, bos412, GOLDA411a 5/3/94 16:49:35
#
#   COMPONENT_NAME: ade_build
#
#   FUNCTIONS: 
#
#   ORIGINS: 27
#
#
#   (C) COPYRIGHT International Business Machines Corp. 1993
#   All Rights Reserved
#   Licensed Materials - Property of IBM
#   US Government Users Restricted Rights - Use, duplication or
#   disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#

EXPINC_SUBDIRS	= util

EXPLIB_SUBDIRS	= util

SUBDIRS		= util build eltdef parser

.include <${RULES_MK}>

