# COMPONENT_NAME:
#
# FUNCTIONS:
#
# ORIGINS: 27
#
# IBM CONFIDENTIAL -- (IBM Confidential Restricted when
# combined with the aggregated modules for this product)
#                                  
# (C) COPYRIGHT International Business Machines Corp. 1988, 1989
# All Rights Reserved
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#

#
#NOTE - libori2.a is from the RSC build obj/power/bos/usr/ccs/lib/libori2
#

EXPLIB		= libori2.a

EXPLIB_TARGETS	= export_libori2.a

EXPDIR	= /usr/ccs/lib/

.include <${RULES_MK}>
