# @(#)53        1.3  src/bos/etc/rc/Makefile, cfgetc, bos411, 9428A410j 5/16/94 15:23:24
# COMPONENT_NAME:
#
# FUNCTIONS:
#
# ORIGINS: 27
#
# IBM CONFIDENTIAL -- (IBM Confidential Restricted when
# combined with the aggregated modules for this product)
#                  SOURCE MATERIALS
# (C) COPYRIGHT International Business Machines Corp. 1988, 1994
# All Rights Reserved
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#

SCRIPTS		= rc
CATFILES	= rc.cat

ILIST		= rc
IDIR		= /etc/

.include <${RULES_MK}>
