# @(#)90        1.1  src/bldenv/env/Makefile, ade_build, bos41J, 9509A_all 2/27/95 12:43:13
#
#   COMPONENT_NAME: BOSBUILD
#
#   FUNCTIONS:
#
#   ORIGINS: 27
#
#   IBM CONFIDENTIAL -- (IBM Confidential Restricted when
#   combined with the aggregated modules for this product)
#                    SOURCE MATERIALS
#
#   (C) COPYRIGHT International Business Machines Corp. 1993
#   All Rights Reserved
#   US Government Users Restricted Rights - Use, duplication or
#   disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#

VPATH		= ${MAKETOP}/bos/usr/bin/env

PROGRAMS	= env
MSGHDRS		= env_msg.h
CATFILES	= env.cat
HFILES		= ${MSGHDRS}

ILIST		= env
IDIR		= /usr/bin/


.include <${RULES_MK}>
