# @(#)55	1.2  src/bos/kernext/disp/sky/inc/Makefile, sysxdispsky, bos411, 9428A410j 4/18/94 14:01:38
#
#   COMPONENT_NAME: sysxdispsky
#
#   FUNCTIONS: 
#
#   ORIGINS: 27
#
#   IBM CONFIDENTIAL -- (IBM Confidential Restricted when
#   combined with the aggregated modules for this product)
#                    SOURCE MATERIALS
#
#   (C) COPYRIGHT International Business Machines Corp. 1988,1993
#   All Rights Reserved
#   US Government Users Restricted Rights - Use, duplication or
#   disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#
INCLUDES        = ddsent.h

EXPDIR		= /kernel/include/

.include <${RULES_MK}>
