$ @(#)15	1.2  src/bos/kernel/sys/msg/unixset.msg, sysproc, bos411, 9428A410j 5/7/91 17:39:11
$
$ COMPONENT_NAME:  (SYSPFS) syspfs.msg
$
$ FUNCTIONS: (none)
$
$ ORIGINS: 27
$
$ (C) COPYRIGHT International Business Machines Corp. 1989
$ All Rights Reserved
$ Licensed Materials - Property of IBM
$
$ US Government Users Restricted Rights - Use, duplication or
$ disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
$

$set 1
$quote "

$
$ set for unixset (place holder)
$
SET_NONE 1

$
$ setno for syspfs
$
SET_SYSPFS 2



