# @(#)66	1.1  src/bldenv/gos/xdt2cde/Makefile, xdt2cde, gos411, 9428A410i 2/4/94 16:03:58
#
#   COMPONENT_NAME: XDT2CDE
#
#   FUNCTIONS: none
#
#   ORIGINS: 27
#
#
#   (C) COPYRIGHT International Business Machines Corp. 1994
#   All Rights Reserved
#   Licensed Materials - Property of IBM
#   US Government Users Restricted Rights - Use, duplication or
#   disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#

SUBDIRS	= osal utils

.include <${RULES_MK}>

