# @(#)42        1.4  src/bos/kernel/lfs/Makefile, syslfs, bos411, 9428A410j 10/27/93 16:33:55
# COMPONENT_NAME:
#
# FUNCTIONS:
#
# ORIGINS: 27
#
# IBM CONFIDENTIAL -- (IBM Confidential Restricted when
# combined with the aggregated modules for this product)
#                  SOURCE MATERIALS
# (C) COPYRIGHT International Business Machines Corp. 1988, 1993
# All Rights Reserved
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#

.include <${MAKETOP}bos/kernel/Kernel.mk>


PAGED_OFILES_PRIM	=	\
	close.o			\
	fsync.o			\
	lookuppn.o		\
	rdwr.o			\
	seek.o

PAGED_OFILES		=	\
	chdir.o			\
	chmod.o			\
	chown.o			\
	chownx.o		\
	closef.o		\
	fclear.o		\
	fd.o			\
	fee.o			\
	fio.o			\
	fp_io.o			\
	fscntl.o		\
	fs_hooks.o		\
	fs_locks.o		\
	ftruncate.o		\
	getdevno.o		\
	getdirent.o		\
	gfs.o			\
	gpai.o			\
	ioctl.o			\
	link.o			\
	lockctl.o		\
	lockf.o			\
	lockrlse.o		\
	mkdir.o			\
	mknod.o			\
	mntctl.o		\
	mount.o			\
	open.o			\
	pathname.o		\
	quotactl.o		\
	rename.o		\
	rmdir.o			\
	stat.o			\
	symlink.o		\
	sync.o			\
	umask.o			\
	umount.o		\
	uname.o			\
	unlink.o		\
	ustat.o			\
	utimes.o		\
	vfsdata.o		\
	vn_create.o		\
	vno_fops.o		\
	vnget.o			\
	vfsops.o		\
	vnops.o

PAGED_OFILES_BACK	=	\
	access.o		\
	fcntl.o			\
	setattr.o		\
	vfs.o			\
	vfs_access.o		\
	vfsinit.o

.include <${RULES_MK}>
