# @(#)32        1.1  src/bos/usr/lib/bugfiler/Makefile, cmdmailx, bos411, 9428A410j 8/5/92 17:19:41
# COMPONENT_NAME:
#
# FUNCTIONS:
#
# ORIGINS: 27
#
# IBM CONFIDENTIAL -- (IBM Confidential Restricted when
# combined with the aggregated modules for this product)
#                  SOURCE MATERIALS
# (C) COPYRIGHT International Business Machines Corp. 1988, 1989
# All Rights Reserved
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#

PROGRAMS	= bugfiler
MSGHDRS		= bf_msg.h
CATFILES	= bf.cat
HFILES		= ${MSGHDRS}

ILIST		= bugfiler
IDIR		= /usr/lib/

CFLAGS		= -D_BSD -DBSD42 -DBERK -DUNIXCOMP

.include <${RULES_MK}>
