# @(#)77        1.1  src/bos/usr/include/netns/Makefile, Makefiles, bos410, bos4.11193 8/5/92 16:18:30
# COMPONENT_NAME:
#
# FUNCTIONS:
#
# ORIGINS: 10,27
#
# IBM CONFIDENTIAL -- (IBM Confidential Restricted when
# combined with the aggregated modules for this product)
#                  SOURCE MATERIALS
# (C) COPYRIGHT International Business Machines Corp. 1988, 1989
# All Rights Reserved
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#

VPATH		=${MAKETOP}/bos/kernext/xns

IDIR		= /usr/include/netns/

DATAFILES	= \
	idp.h \
	idp_var.h \
	ns.h \
	ns_error.h \
	ns_if.h \
	ns_pcb.h \
	proto_ns.h \
	sp.h \
	spidp.h \
	spp_debug.h \
	spp_timer.h \
	spp_var.h

INCLUDES	= ${DATAFILES}

ILIST		= ${DATAFILES}

.include <${RULES_MK}>
