$ @(#)86	1.2  src/bos/usr/lbin/tty/stty/POWER/stty-rs.msg, cmdtty, bos411, 9428A410j 7/19/91 10:33:48

$
$ COMPONENT_NAME: CMDTTY terminal messuages for tty
$
$ FUNCTIONS:
$
$ ORIGINS: 27
$
$ IBM CONFIDENTIAL -- (IBM Confidential Restricted when
$ combined with the aggregated modules for this product)
$                  SOURCE MATERIALS
$ (C) COPYRIGHT International Business Machines Corp. 1988, 1989
$ All Rights Reserved
$
$ US Government Users Restricted Rights - Use, duplication or
$ disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
$

$
$ messages for command sysline
$

$set MS_STTY_RS

$quote "

UNKNOWN    "%s: %s unknown\n"
DMAUSAGE   "Usage %s dma level\n"
RTRIGUSAGE "Usage %s rtrig level\n"
TBCUSAGE   "Usage %s tbc level\n"
MILUSAGE   "Usage %s mil level\n"
