$
$ @(#)58  1.1  R2/cmd/tty/stty/stty-cxma.msg, cmdtty, bos320, 9241320c 9/12/92 09:51:02
$
$ COMPONENT_NAME: (cmdtty) terminal control command
$
$ FUNCTIONS:
$
$ ORIGINS: 80
$
$ This software contains proprietary and confidential information of Digi
$ International Inc.  By accepting transfer of this copy, Recipient agrees
$ to retain this software in confidence, to prevent disclosure to others, and
$ to make no use of this software other than that for which it was delivered.
$ This is an unpublished copyright work Digi International Inc.  Execpt as
$ permitted by federal law, 17 USC 117, copying is strictly prohibited.
$
$ Digi International Inc. CONFIDENTIAL - (Digi International Inc. Confidential
$ when combined with the aggregated modules for this product)
$                  SOURCE MATERIALS
$ (C) COPYRIGHT Digi International Inc. 1988-1992
$ All Rights Reserved
$
$ US Government Users Restircted Rights - Use, duplication or disclosure
$ restricted by GSA ADP Schedule Contract with Digi International Inc.
$

$
$ messages for command sysline
$

$set MS_STTY_CXMA

$quote "

NOPRNTR         "stty-cxma: No printer on/off strings for term %s in terminfo.\n"
INVLDTRM        "stty-cxma: invalid terminal type: %s\n"
VALTRM          "stty-cxma: some of the valid terminal types are: "
XSDEVS          "%s: too many tty devices given!\n"
XSPARAM         "%s: too many stty parameters given!\n"
WAITING         "%s: another process waiting on open\n"





