#  @(#)83   1.1  src/bos/usr/fvcioem/ddt/Makefile, fvcioem, bos411, 9428A410j 4/26/94 13:53:46
#
#  COMPONENT_NAME: (sysxcie_tc) COMIO Emulator Test Tools
#
#  DESCRIPTION:
#     Subsystem makefile to build all three test tools
#
#  ORIGINS: 27
#
#  (C) COPYRIGHT International Business Machines Corp. 1988, 1994
#  All Rights Reserved
#  Licensed Materials - Property of IBM
#
#  US Government Users Restricted Rights - Use, duplication or
#  disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#

SUBDIRS 	= ent tok fddi

.include <${RULES_MK}>
