# @(#)15	1.13  src/bos/usr/ccs/lib/libc/profiled/Makefile, libc, bos411, 9428A410j 10/20/93 14:39:54
#
#   COMPONENT_NAME: LIBC
#
#   FUNCTIONS: none
#
#   ORIGINS: 27
#
#   IBM CONFIDENTIAL -- (IBM Confidential Restricted when
#   combined with the aggregated modules for this product)
#                    SOURCE MATERIALS
#
#   (C) COPYRIGHT International Business Machines Corp. 1993
#   All Rights Reserved
#   US Government Users Restricted Rights - Use, duplication or
#   disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#
#

PROFILED=yes

.include <${MAKETOP}/bos/usr/ccs/lib/libc/Makefile>
