# @(#)95        1.1  src/bldenv/cut/Makefile, ade_build, bos412, GOLDA411a 2/17/93 07:52:09
#
#   COMPONENT_NAME: BOSBUILD
#
#   FUNCTIONS: 
#
#   ORIGINS: 27
#
#   IBM CONFIDENTIAL -- (IBM Confidential Restricted when
#   combined with the aggregated modules for this product)
#                    SOURCE MATERIALS
#
#   (C) COPYRIGHT International Business Machines Corp. 1993
#   All Rights Reserved
#   US Government Users Restricted Rights - Use, duplication or
#   disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#

VPATH		= ${MAKETOP}/bos/usr/bin/cut

PROGRAMS	= cut
MSGHDRS		= cut_msg.h
CATFILES	= cut.cat
HFILES		= ${MSGHDRS}

ILIST		= cut
IDIR		= /usr/bin/


.include <${RULES_MK}>
