# @(#)65        1.1  src/bos/usr/lpp/bosinst/rda/Makefile, bosinst, bos411, 9428A410j 9/3/92 09:35:51
# COMPONENT_NAME:
#
# FUNCTIONS:
#
# ORIGINS: 27
#
# IBM CONFIDENTIAL -- (IBM Confidential Restricted when
# combined with the aggregated modules for this product)
#                  SOURCE MATERIALS
# (C) COPYRIGHT International Business Machines Corp. 1988, 1989
# All Rights Reserved
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#

PROGRAMS	= rda

OFILES		= rda.o extract.o dback.o pindex.o

LIBS		= -lodm -lcfg

ILIST		= rda
IDIR		= /usr/lpp/bosinst/

.include <${RULES_MK}>
