# @(#)16        1.1  src/bldenv/gos/desktop/pass2/Makefile, desktop, bos412, GOLDA411a 5/3/94 16:48:20
#
#   COMPONENT_NAME: ade_build
#
#   FUNCTIONS: 
#
#   ORIGINS: 27
#
#
#   (C) COPYRIGHT International Business Machines Corp. 1993
#   All Rights Reserved
#   Licensed Materials - Property of IBM
#   US Government Users Restricted Rights - Use, duplication or
#   disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#

PROGRAMS	= htag2

CFLAGS		= -D_HPUX_SOURCE  -DANSI_CPP

OFILES		= htag2.o

ILIST		= ${PROGRAMS}
IDIR		=/opt/dt/etc/

.include <${RULES_MK}>

