# @(#)10	1.4  src/bos/usr/lib/bugformat/bugformat.S, cmdmailx, bos411, 9428A410j 1/21/94 18:22:11
#
#   COMPONENT_NAME: CMDMAILX
#
#   FUNCTIONS: 
#
#   ORIGINS: 26,27
#
#
#   (C) COPYRIGHT International Business Machines Corp. 1993
#   All Rights Reserved
#   Licensed Materials - Property of IBM
#   US Government Users Restricted Rights - Use, duplication or
#   disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#

Subject: Short summary of the problem
Index:	<source directory>/<source file> AIX4.1

Description:
	Detailed description of the problem, suggestion, or complaint.
Repeat-By:
	Procedure to repeat the problem.
Fix:
	Description of how to fix the problem.
	If you don't know the fix, don't include this section or "Fix:".

---------- Remove this line and what's below it. (only for reference) ------
<source directory> ::=  bin | etc | games | ideas | include | lib | local |
			man | misc | new | sys | ucb | usr.bin | usr.lib
