$
$  COMPONENT_NAME: (LIBDBM) 
$
$  FUNCTIONS: libdbm messages
$
$  ORIGINS: 27
$
$  IBM CONFIDENTIAL -- (IBM Confidential Restricted when
$  combined with the aggregated modules for this product)
$                   SOURCE MATERIALS
$  (C) COPYRIGHT International Business Machines Corp. 1991
$  All Rights Reserved
$
$  US Government Users Restricted Rights - Use, duplication or
$  disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
$quote "
$set LIBDBM
DBM1 "dbm: 1832-001 no open database\n"
