# @(#)88        1.2  src/bos/kernext/disp/ccm/inc/Makefile, dispccm, bos411, 9428A410j 12/9/93 09:40:50
#
# COMPONENT_NAME: SYSXDISPCCM
#
# FUNCTIONS:
#
# ORIGINS: 27
#
# IBM CONFIDENTIAL -- (IBM Confidential Restricted when
# combined with the aggregated modules for this product)
#                  SOURCE MATERIALS
#
# (C) COPYRIGHT International Business Machines Corp. 1993
# All Rights Reserved
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#
#

EXPDIR		= /kernel/include/

DATAFILES     	= ccm.h ccm_macros.h ccm_trchkid.h ccmdd_tools.h \
		  cdd.h cdd_intr.h cdd_intr_macros.h cdd_macros.h \
		  frs.h frs_60x.h frs_display.h frs_display_macs.h \
		  frs_macs.h

INCLUDES	= ${DATAFILES} 

.include <${RULES_MK}>
