# @(#)12        1.8  src/bos/usr/lib/boot/network/Makefile, cmdnim, bos411, 9428A410j 6/20/94 16:03:29
#
#   COMPONENT_NAME: CMDNIM
#
#   FUNCTIONS: ./lib/boot/network/Makefile
#
#   ORIGINS: 27
#
#
#   (C) COPYRIGHT International Business Machines Corp. 1993
#   All Rights Reserved
#   Licensed Materials - Property of IBM
#   US Government Users Restricted Rights - Use, duplication or
#   disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#

SCRIPTS =	\
		rc.bos_inst \
		rc.dd_boot \
		rc.diag \
		rs6k.ent.proto \
		rs6k.fddi.proto \
		rs6k.tok.proto \
		rs6ksmp.ent.proto \
		rs6ksmp.fddi.proto \
		rs6ksmp.tok.proto \
		rspc.ent.proto \
		rspc.fddi.proto \
		rspc.tok.proto

ILIST		= ${SCRIPTS}

IDIR		= /usr/lib/boot/network/

.include <${RULES_MK}>
