# @(#)13        1.17  src/bldenv/includes/Makefile, ade_build, bos412, GOLDA411a 6/30/94 17:18:12
#
#   COMPONENT_NAME: BOSBUILD
#
#   FUNCTIONS:
#
#   ORIGINS: 27
#
#   IBM CONFIDENTIAL -- (IBM Confidential Restricted when
#   combined with the aggregated modules for this product)
#                    SOURCE MATERIALS
#
#   (C) COPYRIGHT International Business Machines Corp. 1993
#   All Rights Reserved
#   US Government Users Restricted Rights - Use, duplication or
#   disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#

VPATH			= ${MAKETOP}/bos/usr/include:${MAKETOP}/bos/usr/bin/odmget:${MAKETOP}/bos/usr/sbin/fsck

EXPINC_SUBDIRS		= sys jfs X11 XTOP Xm uil

INCLUDES		= ras.h odmcmd.h odmroutine.h odmcmd_msg.h \
			  swvpd0.h swvpd.h fsck.h imP.h iconvTable.h \
			  odmi.h storclass.h syms.h typchk.h nl_types.h \
			  mesg.h dim.h bim.h swvpd1.h reloc.h filehdr.h \
			  scnhdr.h aouthdr.h \
			  iconvP.h iconv932.h

EXPDIR			= /usr/include/

.include <${RULES_MK}>
