# @(#)19  1.2  src/bos/usr/lib/methods/ucfgcommo/Makefile, cfgmethods, bos411, 9428A410j 3/16/94 09:53:43
#
# COMPONENT_NAME: CFGMETHODS
#
# FUNCTIONS: Makefile
#
# ORIGINS: 27
#
# IBM CONFIDENTIAL -- (IBM Confidential Restricted when
# combined with the aggregated modules for this product)
#                  SOURCE MATERIALS
# (C) COPYRIGHT International Business Machines Corp. 1993
# All Rights Reserved
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#

PROGRAMS        = ucfgcommo

INCFLAGS	= -I../common

OFILES          = ucfgcommo.o ucfggen.o

ILIST           = ucfgcommo
IDIR		= /usr/lib/methods/

LIBS		= -ls -lodm -lcfg -lrts

.include <${RULES_MK}>
