# @(#)45        1.4  src/bldenv/p20makemsgs/Makefile, bldprocess, bos412, GOLDA411a 1/10/94 14:18:05
#
#   COMPONENT_NAME: BOSBUILD
#
#   FUNCTIONS:
#
#   ORIGINS: 27
#
#   IBM CONFIDENTIAL -- (IBM Confidential Restricted when
#   combined with the aggregated modules for this product)
#                    SOURCE MATERIALS
#
#   (C) COPYRIGHT International Business Machines Corp. 1993
#   All Rights Reserved
#   US Government Users Restricted Rights - Use, duplication or
#   disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#

VPATH		= ${MAKETOP}bos/usr/bin/panel20
PROGRAMS	= makemsgs

INCFLAGS	=-I${MAKETOP}bos/usr/bin/panel20

ILIST		= ${PROGRAMS}
IDIR		= /usr/bin/

.include <${RULES_MK}>
