#
# dependents of dnep.o:
dnep.o: ${MAKETOP}../export/power/usr/include/stdio.h
dnep.o: ${MAKETOP}../export/power/usr/include/standards.h
dnep.o: ${MAKETOP}../export/power/usr/include/va_list.h
dnep.o: ${MAKETOP}../export/power/usr/include/sys/types.h
dnep.o: ${MAKETOP}../export/power/usr/include/sys/m_types.h
dnep.o: ${MAKETOP}../export/power/usr/include/sys/limits.h
dnep.o: ${MAKETOP}../export/power/usr/include/float.h
dnep.o: ${MAKETOP}../export/power/usr/include/errno.h
dnep.o: ${MAKETOP}../export/power/usr/include/sys/errno.h
dnep.o: ${MAKETOP}../export/power/usr/include/sys/signal.h
dnep.o: ${MAKETOP}../export/power/usr/include/sys/context.h
dnep.o: ${MAKETOP}../export/power/usr/include/sys/m_param.h
dnep.o: ${MAKETOP}../export/power/usr/include/sys/mstsave.h
dnep.o: ${MAKETOP}../export/power/usr/include/sys/errids.h
dnep.o: ${MAKETOP}../export/power/usr/include/sys/err_rec.h
dnep.o: ${MAKETOP}../export/power/usr/include/locale.h
dnep.o: ${MAKETOP}../export/power/usr/include/fcntl.h
dnep.o: ${MAKETOP}../export/power/usr/include/sys/flock.h
dnep.o: ${MAKETOP}../export/power/usr/include/unistd.h
dnep.o: ${MAKETOP}../export/power/usr/include/sys/access.h
dnep.o: ${MAKETOP}../export/power/usr/include/sys/lockf.h
dnep.o: ${MAKETOP}../export/power/usr/include/sys/stat.h
dnep.o: ${MAKETOP}../export/power/usr/include/sys/mode.h
dnep.o: ${MAKETOP}../export/power/usr/include/sys/cfgodm.h
dnep.o: ${MAKETOP}../export/power/usr/include/odmi.h
dnep.o: ${MAKETOP}../export/power/usr/include/sys/dir.h
dnep.o: ${MAKETOP}../export/power/usr/include/sys/lkup.h
dnep.o: ${MAKETOP}../export/power/usr/include/limits.h
dnep.o: ${MAKETOP}../export/power/usr/include/diag/tm_input.h
dnep.o: ${MAKETOP}../export/power/usr/include/diag/tmdefs.h
dnep.o: ${MAKETOP}../export/power/usr/include/diag/da.h
dnep.o: ${MAKETOP}../export/power/usr/include/sys/cfgdb.h
dnep.o: ${MAKETOP}../export/power/usr/include/diag/diag.h
dnep.o: ${MAKETOP}../export/power/usr/include/diag/diag_define.h
dnep.o: ${MAKETOP}../export/power/usr/include/diag/diag_exit.h
dnep.o: ${MAKETOP}../export/power/usr/include/diag/diago.h
dnep.o: ${MAKETOP}../export/power/usr/include/asl.h
dnep.o: ${MAKETOP}../export/power/usr/include/stdarg.h
dnep.o: ${MAKETOP}bos/diag/da/nep/dnep.h
dnep.o: ${MAKETOP}bos/diag/tu/nep/nep_tu_type.h
dnep.o: ${MAKETOP}bos/diag/tu/nep/nepdef.h
dnep.o: dnep_msg.h
dnep.o: ${MAKETOP}../export/power/usr/include/nl_types.h
dnep.o: ${MAKETOP}../export/power/usr/include/mesg.h
