# @(#)37	1.14  src/bos/usr/lib/microcode/Makefile, Makefiles, bos41J, 9512A_all 3/22/95 08:37:56
#
# COMPONENT_NAME: MAKEFILES
#
# FUNCTIONS:
#
# ORIGINS: 27
#
# IBM CONFIDENTIAL -- (IBM Confidential Restricted when
# combined with the aggregated modules for this product)
#                  SOURCE MATERIALS
# (C) COPYRIGHT International Business Machines Corp. 1988, 1993
# All Rights Reserved
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#

POWER_SUBDIRS   = cat fddi ffe1 bb tok serdasd gem1 ped_ccm pga lga nga l2ga l3ga ssla ruby cxia
EXPINC_SUBDIRS  = ruby

SUBDIRS         = ${${TARGET_MACHINE}_SUBDIRS}

.include <${RULES_MK}>
