# @(#)51	1.1  src/bos/usr/lbin/trmon/Makefile, sysxtok, bos411, 9428A410j 3/31/94 13:51:06
#
#   COMPONENT_NAME: SYSXTOK
#
#   FUNCTIONS: none
#
#   ORIGINS: 27
#
#   IBM CONFIDENTIAL -- (IBM Confidential Restricted when
#   combined with the aggregated modules for this product)
#                    SOURCE MATERIALS
#
#   (C) COPYRIGHT International Business Machines Corp. 1994
#   All Rights Reserved
#   US Government Users Restricted Rights - Use, duplication or
#   disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#

PROGRAMS	= trmon

OFILES		= main.o trmon_dmp.o 

INCFLAGS	= -I${MAKETOP}/bos/kernext/tok

ILIST           = trmon

IDIR		= /usr/lib/ras/dmprtns/

.include <${RULES_MK}>
