$ @(#)56        1.9  src/bos/usr/lib/assist/softlic.msg, cmdassist, bos41J, 9523A_all 6/1/95 17:19:28
$
$ COMPONENT_NAME:  
$
$ FUNCTIONS:  Message catalog for Software License Agreement
$
$ ORIGINS:  27
$
$  (C) COPYRIGHT International Business Machines Corp. 1994
$   All Rights Reserved
$   Licensed Materials - Property of IBM
$   US Government Users Restricted Rights - Use, duplication or
$   disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
$ --------------------------------------------------------------------

$quote "
$
$set 1

$
$ NOTE to translators:
$   The following messages should be able to be displayed on
$   a 80 column screen.
$

1 "\
                  RISC SYSTEM/6000 MICROCODE LICENSE\n\
\n\
AIX Version 4 is packaged with Microcode files developed for use with the IBM\n\
RISC System/6000. . IBM owns all copyright rights to this Microcode.  IBM\n\
hereby licenses user to execute this Microcode only on RISC System/6000\n\
machines or other machines authorized by IBM.  No license is given to modify,\n\
display, adapt, electronically distribute, reverse assemble, reverse compile,\n\
decode, otherwise translate, sublicense, assign or lease the Microcode.\n\
\n\
NOTE: This Microcode will not be automatically installed on your IBM machine\n\
unless it is a RISC System/6000.  Each file and media containing Microcode\n\
will be marked with an indicating legend.\n\
\n"

2 "\
		IBM License Agreement for Programs\n\
\n\
NOTICE: IF YOU ARE ACQUIRING THIS PROGRAM FROM IBM AND HAVE A SIGNED LICENSE\n\
AGREEMENT WITH IBM, THAT AGREEMENT WILL GOVERN THIS PROGRAM.  OTHERWISE,\n\
PLEASE READ THIS AGREEMENT CAREFULLY BEFORE USING THE PROGRAM.  IBM WILL ONLY\n\
LICENSE THIS PROGRAM TO YOU IF YOU FIRST ACCEPT THE TERMS OF THIS AGREEMENT.\n\
BY USING THE PROGRAM, YOU AGREE TO ABIDE BY THESE TERMS AND APPLICABLE\n\
COPYRIGHT LAWS.  IF YOU DO NOT AGREE, PROMPTLY NOTIFY THE PROVIDER OF THE\n\
PROGRAM AND REQUEST A REFUND OF THE AMOUNT YOU PAID.\n\
\n\
This Program is owned by the International Business Machines Corporation or\n\
its subsidiaries (IBM) or IBM's suppliers, and is copyrighted and licensed,\n\
not sold IBM does not transfer title to a Program to you.  The terms of this\n\
Agreement apply to any additional license copy of a Program IBM authorizes\n\
you to make.\n\
\n\
The term \"Program\" means the original program and all whole or partial copies\n\
of it, including portions merged with other programs.  A Program consists of\n\
machine-readable instructions and related licensed materials, including\n\
documentation.\n\
\n\
IBM grants you a non-exclusive license to the Program in the country in which\n\
you acquired the Program.  Specifications (which consist of Licensed Program\n\
Specifications and a document called a \"Notice of Availability\") which are\n\
part of the documentatio IBM provides with the Program, may contain\n\
additional terms that are part of this Agreement.\n\
\n\
Unless you have a signed license agreement with IBM, in which case that\n\
agreement will govern, this Agreement and its applicable Transaction\n\
Documents (such as an invoice or supplement) are the complete and exclusive\n\
agreement regarding the Program and replace any prior oral or written\n\
communications between you and IBM For a change to be valid, both you and IBM\n\
must sign it.\n\
\n\
You accept the additional terms in a Transaction Document by using th Program\n\
or making any payment for it.  If there is a conflict among terms, those of a\n\
Transaction Document prevail.\n"

3 "\
LICENSE\n\
\n\
Under this license, you may 1) use the Program on only one machine at any one\n\
time, 2) copy the Program for backup, and 3) modify the Program or merge it\n\
into another Program.\n\
\n\
You agree to reproduce the copyright notice and any other legend of ownership\n\
on each copy or partial copy.\n\
\n\
You may use any portion of the Program IBM marks restricted (for example,\n\
\"Restricted Materials of IBM\") only to 1) resolve problems related to the use\n\
of the Program and 2) modify the Program so that it will work together with\n\
other products.\n\
\n\
You agree not to do any of the following: 1) use, copy, or merge the Program\n\
except as provided in this Agreement; 2) reverse assemble, reverse compile,\n\
or otherwise translate the Program; 3) transfer the license for the Program,\n\
except as specifically permitted by IBM in its Specifications; 4) sublicense,\n\
rent, lease, or assign the license for the Program; or 5) distribute the\n\
Program to any third party.\n\
\n\
DISTRIBUTED FEATURES\n\
\n\
Some Programs have features that are designed for use on machines\n\
other than the machine on which the Program is used.  You may make a copy of\n\
a feature and its documentation.  You agree to use the copy on only one\n\
machine at a time.  A person using a machine outside of your business\n\
enterprise may use the copy only to access the Program.  Use of some of these\n\
features is chargeable.  When it is, IBM refers to that feature as a\n\
\"Distributed Feature,\" and you must pay IBM for each copy you make of it.\n\
  \n\
PROGRAM PROTECTION \n\
                \n\
You agree to 1) maintain a record of all copies of a Program and 2) ensure\n\
that anyone who uses this Program does so only for your authorized use and\n\
complies with this Agreement.\n\
                   \n\
CHARGES, PAYMENT, AND TAXES \n\
       \n\
Charges for Programs may be one-time, recurring, or a combination of both.\n\
\n\
Charges may be based on a machine group that IBM specifies.  In such case,\n\
you agree to inform IBM or its reseller of the machine (model and type) on\n\
which the Program will be used and to pay the applicable charge.  Charges may\n\
also be based on a unit of measurement (such as number of users), which will\n\
be identified in the Specifications.  In that case, you agree to inform IBM\n\
or its reseller of the units of measurement and to pay the applicable charge.\n\
              \n\
If you change the machine on which the Program will be used or the units of\n\
measurement, you agree to inform IBM or its reseller and pay any applicable\n\
charges.  IBM does not give refunds for charges already due or paid.\n\
              \n\
Payment should be made to the party (either IBM or its reseller) from whom\n\
you acquired the Program.  If you acquired the Program from IBM, you agree to\n\
pay as IBM specifies.  If any authority imposes a duty, tax or fee (excluding\n\
those based on IBM's net income) on this Agreement or on the Program itself,\n\
you agree to pay that amount as IBM specifies.\n\
                       \n\
IBM may change recurring charges for Programs acquired from IBM (and not its\n\
reseller) by giving you three months written notice.\n\
      \n\
RECURRING-CHARGE PROGRAMS      \n\
    \n\
The license for a recurring-charge Program, which you acquired from a\n\
reseller, terminates if the relationship between IBM and its reseller ends,\n\
unless you keep the Program.  If you do so, you must pay IBM the applicable\n\
charges.\n\
\n"

4 "\
LIMITED WARRANTY     \n\
              \n\
For each warranted IBM Program, IBM warrants that 1) IBM has the right to\n\
license it and 2) it conforms to its Specifications.  The warranty period for\n\
a Program expires when its Program services are no longer available.\n\
\n\
During the warranty period, IBM provides warranty service, without charge,\n\
for a Program through Program services.  Program services are available for a\n\
warranted Program for at least one year following its general availability.\n\
Therefore, the duration of warranty service depends on when you obtain your\n\
license.  If a Program does not function as warranted during the first year\n\
after you obtain your license, and IBM is unable to make it do so, you may\n\
return it to IBM (or its reseller) and your money will be refunded.  To be\n\
eligible, you must have acquired the Program while Program services\n\
(regardless of the remaining duration) were available for it.\n\
\n\
Operation in other than the specified operating environment may void the\n\
warranties.\n\
\n\
THESE WARRANTIES REPLACE ALL OTHER WARRANTIES OR CONDITIONS, EXPRESS OR\n\
IMPLIED, INCLUDING THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR\n\
A PARTICULAR PURPOSE.\n\
\n\
IBM does not warrant uninterrupted or error-free operation of a Program.  IBM\n\
will identify IBM Programs that it does not warrant.\n\
\n\
These warranties give you specific legal rights, and you may have other\n\
rights which vary from jurisdiction to jurisdiction.  Some jurisdictions do\n\
not allow the exclusion of implied warranties, so the above exclusion may not\n\
apply to you.  In that event, such warranties are limited in duration to the\n\
warranty period.  No warranties apply after that period.\n\
\n\
PROGRAM SERVICES\n\
\n\
IBM provides Program services for warranted Programs and for selected other\n\
Programs.  If IBM can reproduce your reported problem in the specified\n\
operating environment, IBM will issue defect correction information, a\n\
restriction, or a bypass.  IBM provides Program services for only the\n\
unmodified portion of a current release of a Program.\n\
\n\
If you acquired the Program from IBM, IBM will provide Program services to\n\
you.  If you acquired the Program from IBM's reseller, IBM provides Program\n\
services only to its reseller (who provides such services to you).\n\
\n\
IBM provides Program services 1) on an on-going basis (with at least six\n\
months' written notice before IBM terminates services for a Program), 2)\n\
until the date IBM specifies, or 3) for a period IBM specifies.\n\
\n\
                        \n\
PATENTS AND COPYRIGHTS \n\
            \n\
If a third party claims that a Program IBM provides to you infringes that\n\
party's patent or copyright, IBM will, at its expense, defend you against\n\
that claim and pay all costs, damages, and attorney's fees that a court\n\
finally awards, provided that you 1) promptly notify IBM in writing of the\n\
claim and 2) allow IBM to control, and cooperate with IBM in, the defense and\n\
any related settlement negotiations.\n\
          \n\
If such a claim is made or appears likely to be made, you agree to permit IBM\n\
to enable you to continue to use the Program, or to modify it, or replace it\n\
with one that is at least functionally equivalent.  If IBM determines that\n\
none of these alternatives is reasonably available, you agree to return the\n\
Program to IBM on IBM's written request.  IBM will then give you a credit for\n\
a one-time charge Program, provided its total charges have been fully paid.\n\
     \n\
This is IBM's entire obligation to you regarding any claim of infringement.\n\
                      \n\
IBM has no obligation regarding any claim based on any of the following: 1)\n\
your modification of a Program; 2) the combination, operation, or use of a\n\
Program with any programs, data, or apparatus that IBM did not provide; or 3)\n\
infringement by a non-IBM Program.\n\
\n\
LIMITATION OF LIABILITY \n\
           \n\
Circumstances may arise where, because of a default on IBM's part (including\n\
fundamental breach) or other liability (including negligence and\n\
misrepresentation), you are entitled to recover damages from IBM. In each\n\
such instance, regardless of the basis on which you are entitled to claim\n\
damages, IBM is liable only for: 1) payments referred to in the patent and\n\
copyright terms described above; 2) bodily injury (including death), and\n\
damage to real property and tangible personal property; and 3) the amount of\n\
any other actual loss or damage, up to the greater of U.S.$100,000 or the\n\
charges (if recurring, 12 months' charges apply) for the Program.  \n\
\n\
This limitation of liability also applies to any developer of a Program\n\
supplied to IBM.  It is the maximum for which we are collectively\n\
responsible.  \n\
\n\
Under no circumstances is IBM liable for 1) third party claims against you\n\
for losses or damages (other than those under the first two items listed\n\
above) or 2) loss of, or damage to, your records or data.\n\
\n\
IBM WILL NOT BE LIABLE FOR ANY LOST PROFITS, LOST SAVINGS, OR ANY INCIDENTAL,\n\
SPECIAL, OR INDIRECT DAMAGES OR OTHER ECONOMIC CONSEQUENTIAL DAMAGES, EVEN IF\n\
IBM OR ITS RESELLER HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES.\n\
SOME JURISDICTIONS DO NOT ALLOW THE EXCLUSION OR LIMITATION OF INCIDENTAL OR\n\
CONSEQUENTIAL DAMAGES, SO THE ABOVE LIMITATION OR EXCLUSION MAY NOT APPLY TO\n\
YOU.\n\
\n"

5 "\
GENERAL\
\n\
Please retain a copy of your receipt or invoice to establish proof of\n\
license.\n\
\n\
You may terminate your license on one month's notice.  IBM may terminate your\n\
license if you fail to comply with the terms of this license.  In either\n\
event, you must destroy all your copies of the Program.  However, you may\n\
keep a copy in your archives.\n\
\n\
Neither of us will bring a legal action, under this Agreement, more than two\n\
years after the cause of action arose.\n\
\n\
This Agreement is governed by the laws of the country in which you acquired\n\
the Program except that: 1) if you acquired the Program in the United States\n\
or Puerto Rico, this Agreement is governed by the laws of the State of New\n\
York; and 2) if you acquired the Program in Canada, this Agreement is\n\
governed by the laws of the Province of Ontario."

6 "\n\n\nPress Enter to proceed to sign the License Agreement.\n"

7 "Software License Agreement"

8 "For programs purchased in Europe, Latin America,\n\
the Middle East, or Africa.\n"

9 "For programs purchased in North America or in a location other \n\
than Australia, Europe, Latin America, the Middle East, or Africa.\n"

10 "As stated on the package, IBM will only license this software program to you if you first accept all the TERMS AND CONDITIONS of the IBM LICENSE AGREEMENT FOR PROGRAMS which you have just viewed.\n\nDo you accept all the TERMS AND CONDITIONS of this agreement?\n\nIf so, sign this document by entering your name in the field below. If you do NOT wish to accept these TERMS AND CONDITIONS, you may EXIT this software program without entering name and return the software program for a full refund."
$ Note: Message 10 should all be translated in one line, in other words
$ do not break it up into three different lines.

11 "No further action needed.  Press Enter to continue."

12 "Enter your name"

13 "Sign License"

14 " Cancel"

15 "  Save"

16 "Enter your name:"

17 "You must enter data in the input field."

18 "Ok"

19 "For programs purchased in Australia.\n"

$set 2

$
$ NOTE to translators:
$   The following messages should be able to be displayed on
$   a 80 column screen.
$

1 "\
                  RISC SYSTEM/6000 MICROCODE LICENSE\n\
\n\
AIX Version 4 is packaged with Microcode files developed for use with the IBM\n\
RISC System/6000. . IBM owns all copyright rights to this Microcode.  IBM\n\
hereby licenses user to execute this Microcode only on RISC System/6000\n\
machines or other machines authorized by IBM.  No license is given to modify,\n\
display, adapt, electronically distribute, reverse assemble, reverse compile,\n\
decode, otherwise translate, sublicense, assign or lease the Microcode.\n\
\n\
NOTE: This Microcode will not be automatically installed on your IBM machine\n\
unless it is a RISC System/6000.  Each file and media containing Microcode\n\
will be marked with an indicating legend.\n\
\n"

2 "\
IBM License Agreement for Programs\n\
\n\
NOTICE: IF YOU ARE ACQUIRING THIS PROGRAM FROM IBM AND HAVE A SIGNED LICENSE\n\
AGREEMENT WITH IBM, THAT AGREEMENT WILL GOVERN THIS PROGRAM.  OTHERWISE,\n\
PLEASE READ THIS AGREEMENT CAREFULLY BEFORE USING THE PROGRAM.  IBM WILL ONLY\n\
LICENSE THIS PROGRAM TO YOU IF YOU FIRST ACCEPT THE TERMS OF THIS AGREEMENT.\n\
BY USING THE PROGRAM, YOU AGREE TO ABIDE BY THESE TERMS AND APPLICABLE\n\
COPYRIGHT LAWS.  IF YOU DO NOT AGREE, WITHIN THIRTY (30) DAYS OF RECEIPT OF\n\
THE PROGRAM PROMPTLY NOTIFY THE PROVIDER OF THE PROGRAM AND REQUEST A REFUND\n\
OF THE AMOUNT YOU PAID.\n\
\n\
This Program is owned by the International Business Machines Corporation or\n\
its subsidiaries (IBM) or IBM's suppliers, and is copyrighted and licensed,\n\
not sold IBM does not transfer title to a Program to you.  The terms of this\n\
Agreement apply to any additional license copy of a Program IBM authorizes\n\
you to make.\n\
\n\
The term \"Program\" means the original program and all whole or partial copies\n\
of it, including portions merged with other programs.  A Program consists of\n\
machine-readable instructions and related licensed materials, including\n\
documentation.\n\
\n\
IBM grants you a non-exclusive license to the Program in the country in which\n\
you acquired the Program.  Specifications (which consist of Licensed Program\n\
Specifications and a document called a \"Notice of Availability\") which are\n\
part of the documentatio IBM provides with the Program, may contain\n\
additional terms that are part of this Agreement.\n\
\n\
Unless you have a signed license agreement with IBM, in which case that\n\
agreement will govern, this Agreement and its applicable Transaction\n\
Documents (such as an invoice or supplement) are the complete and exclusive\n\
agreement regarding the Program and replace any prior oral or written\n\
communications between you and IBM For a change to be valid, both you and IBM\n\
must sign it.\n\
\n\
You accept the additional terms in a Transaction Document by using the Program\n\
or making any payment for it.  If there is a conflict among terms, those of a\n\
Transaction Document prevail.\n"

3 "\
LICENSE\n\
\n\
Under this license, you may 1) use the Program on only one machine at any one\n\
time, 2) copy the Program for backup, and 3) modify the Program or merge it\n\
into another Program.\n\
\n\
You agree to reproduce the copyright notice and any other legend of ownership\n\
on each copy or partial copy.\n\
\n\
You may use any portion of the Program IBM marks restricted (for example,\n\
\"Restricted Materials of IBM\") only to 1) resolve problems related to the use\n\
of the Program and 2) modify the Program so that it will work together with\n\
other products.\n\
\n\
You agree not to do any of the following: 1) use, copy, or merge the Program\n\
except as provided in this Agreement; 2) reverse assemble, reverse compile,\n\
or otherwise translate the Program; 3) transfer the license for the Program,\n\
except as specifically permitted by IBM in its Specifications; 4) sublicense,\n\
rent, lease, or assign the license for the Program; or 5) distribute the\n\
Program to any third party.\n\
\n\
DISTRIBUTED FEATURES\n\
\n\
Some Programs have features that are designed for use on machines\n\
other than the machine on which the Program is used.  You may make a copy of\n\
a feature and its documentation.  You agree to use the copy on only one\n\
machine at a time.  A person using a machine outside of your business\n\
enterprise may use the copy only to access the Program.  Use of some of these\n\
features is chargeable.  When it is, IBM refers to that feature as a\n\
\"Distributed Feature,\" and you must pay IBM for each copy you make of it.\n\
  \n\
PROGRAM PROTECTION \n\
                \n\
You agree to 1) maintain a record of all copies of a Program and 2) ensure\n\
that anyone who uses this Program does so only for your authorized use and\n\
complies with this Agreement.\n\
                   \n\
CHARGES, PAYMENT, AND TAXES \n\
       \n\
Charges for Programs may be one-time, recurring, or a combination of both.\n\
\n\
Charges may be based on a machine group that IBM specifies.  In such case,\n\
you agree to inform IBM or its reseller of the machine (model and type) on\n\
which the Program will be used and to pay the applicable charge.  Charges may\n\
also be based on a unit of measurement (such as number of users), which will\n\
be identified in the Specifications.  In that case, you agree to inform IBM\n\
or its reseller of the units of measurement and to pay the applicable charge.\n\
              \n\
If you change the machine on which the Program will be used or the units of\n\
measurement, you agree to inform IBM or its reseller and pay any applicable\n\
charges.  IBM does not give refunds for charges already due or paid.\n\
              \n\
Payment should be made to the party (either IBM or its reseller) from whom\n\
you acquired the Program.  If you acquired the Program from IBM, you agree to\n\
pay as IBM specifies.  If any authority imposes a duty, tax or fee (excluding\n\
those based on IBM's net income) on this Agreement or on the Program itself,\n\
you agree to pay that amount as IBM specifies.\n\
                       \n\
IBM may change recurring charges for Programs acquired from IBM (and not its\n\
reseller) by giving you three months written notice.\n\
      \n\
RECURRING-CHARGE PROGRAMS      \n\
    \n\
The license for a recurring-charge Program, which you acquired from a\n\
reseller, terminates if the relationship between IBM and its reseller ends,\n\
unless you keep the Program.  If you do so, you must pay IBM the applicable\n\
charges.\n\
\n"

4 "\
LIMITED WARRANTY     \n\
              \n\
For each warranted IBM Program, IBM warrants that 1) IBM has the right to\n\
license it and 2) it conforms to its Specifications.  The warranty period for\n\
a Program expires when its Program services are no longer available.\n\
\n\
During the warranty period, IBM provides warranty service, without charge,\n\
for a Program through Program services.  Program services are available for a\n\
warranted Program for at least one year following its general availability.\n\
Therefore, the duration of warranty service depends on when you obtain your\n\
license.  If a Program does not function as warranted during the first year\n\
after you obtain your license, and IBM is unable to make it do so, you may\n\
return it to IBM (or its reseller) and your money will be refunded.  To be\n\
eligible, you must have acquired the Program while Program services\n\
(regardless of the remaining duration) were available for it.\n\
\n\
Operation in other than the specified operating environment may void the\n\
warranties.\n\
\n\
THESE WARRANTIES REPLACE ALL OTHER WARRANTIES OR CONDITIONS, EXPRESS OR\n\
IMPLIED, INCLUDING THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR\n\
A PARTICULAR PURPOSE.\n\
\n\
IBM does not warrant uninterrupted or error-free operation of a Program.  IBM\n\
will identify IBM Programs where conformity to specifications is not\n\
warranted.\n\
\n\
These warranties give you specific legal rights, and you may have other\n\
rights which vary from jurisdiction to jurisdiction.  Some jurisdictions do\n\
not allow the exclusion of implied warranties, so the above exclusion may not\n\
apply to you.  In that event, such warranties are limited in duration to the\n\
warranty period.  No warranties apply after that period.\n\
\n\
PROGRAM SERVICES\n\
\n\
IBM provides Program services for warranted Programs and for selected other\n\
Programs.  If IBM can reproduce your reported problem in the specified\n\
operating environment, IBM will issue defect correction information, a\n\
restriction, or a bypass.  IBM provides Program services for only the\n\
unmodified portion of a current release of a Program.\n\
\n\
If you acquired the Program from IBM, IBM will provide Program services to\n\
you.  If you acquired the Program from IBM's reseller, IBM provides Program\n\
services only to its reseller (who provides such services to you).\n\
\n\
IBM provides Program services 1) on an on-going basis (with at least six\n\
months' written notice before IBM terminates services for a Program), 2)\n\
until the date IBM specifies, or 3) for a period IBM specifies.\n\
\n\
                        \n\
PATENTS AND COPYRIGHTS \n\
            \n\
If a third party claims that a Program IBM provides to you infringes that\n\
party's patent or copyright, IBM will, at its expense, defend you against\n\
that claim and pay all costs, damages, and attorney's fees that a court\n\
finally awards, provided that you 1) promptly notify IBM in writing of the\n\
claim and 2) allow IBM to control, and cooperate with IBM in, the defense and\n\
any related settlement negotiations.\n\
          \n\
If such a claim is made or appears likely to be made, you agree to permit IBM\n\
to enable you to continue to use the Program, or to modify it, or replace it\n\
with one that is at least functionally equivalent.  If IBM determines that\n\
none of these alternatives is reasonably available, you agree to return the\n\
Program to IBM on IBM's written request.  IBM will then give you a credit for\n\
a one-time charge Program, provided its total charges have been fully paid.\n\
     \n\
This is IBM's entire obligation to you regarding any claim of infringement.\n\
                      \n\
IBM has no obligation regarding any claim based on any of the following: 1)\n\
your modification of a Program; 2) the combination, operation, or use of a\n\
Program with any programs, data, or apparatus that IBM did not provide; or 3)\n\
infringement by a non-IBM Program.\n\
\n\
LIMITATION OF LIABILITY \n\
           \n\
Circumstances may arise where, because of a default on IBM's part (including\n\
fundamental breach) or other liability (including negligence and\n\
misrepresentation), you are entitled to recover damages from IBM. In each\n\
such instance, regardless of the basis on which you are entitled to claim\n\
damages, IBM is liable only for: 1) payments referred to in the patent and\n\
copyright terms described above; 2) bodily injury (including death), and\n\
damage to real property and tangible personal property; and 3) the amount of\n\
any other actual loss or damage, up to the greater of U.S.$100,000 or the\n\
charges (if recurring, 12 months' charges apply) for the Program.  \n\
\n\
This limitation of liability also applies to any developer of a Program\n\
supplied to IBM.  It is the maximum for which we are collectively\n\
responsible.  \n\
\n\
Under no circumstances is IBM liable for 1) third party claims against you\n\
for losses or damages (other than those under the first two items listed\n\
above) or 2) loss of, or damage to, your records or data.\n\
\n\
IBM WILL NOT BE LIABLE FOR ANY LOST PROFITS, LOST SAVINGS, OR ANY INCIDENTAL,\n\
SPECIAL, OR INDIRECT DAMAGES OR OTHER ECONOMIC CONSEQUENTIAL DAMAGES, EVEN IF\n\
IBM OR ITS RESELLER HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES.\n\
SOME JURISDICTIONS DO NOT ALLOW THE EXCLUSION OR LIMITATION OF INCIDENTAL OR\n\
CONSEQUENTIAL DAMAGES, SO THE ABOVE LIMITATION OR EXCLUSION MAY NOT APPLY TO\n\
YOU.\n\
\n\
Where we are in breach of a condition or warranty implied by the Trade\n\
Practices Act 1974 our liability is limited to:\n\
\n\
1) where we supplied services - the cost of having the services supplied\n\
again; or 2) where we supplied goods - the repair or replacement of the\n\
goods, or the supply of equivalent goods;\n\
\n\
and where this condition or warranty relates to right to sell, quiet\n\
possession or clear title, or the goods are of a kind ordinarily acquired for\n\
personal, domestic or household use or consumption, then none of the\n\
limitations in this clause apply.\n\
"

5 "\
GENERAL\
\n\
Please retain a copy of your receipt or invoice to establish proof of\n\
license.\n\
\n\
You may terminate your license on one month's notice.  IBM may terminate your\n\
license if you fail to comply with the terms of this license.  In either\n\
event, you must destroy all your copies of the Program.  However, you may\n\
keep a copy in your archives.\n\
\n\
Neither of us will bring a legal action, under this Agreement, more than two\n\
years after the cause of action arose.\n\
\n\
This Agreement is governed by the laws of the country in which you acquired\n\
the Program except that: 1) if you acquired the Program in the United States\n\
or Puerto Rico, this Agreement is governed by the laws of the State of New\n\
York; and 2) if you acquired the Program in Canada, this Agreement is\n\
governed by the laws of the Province of Ontario."
