# @(#)40	1.2  src/bos/diag/tu/async/Makefile, tu_async, bos411, 9428A410j 4/7/93 13:45:15
#
#   COMPONENT_NAME: TU_ASYNC
#
#   FUNCTIONS: 
#
#   ORIGINS: 27
#
#   IBM CONFIDENTIAL -- (IBM Confidential Restricted when
#   combined with the aggregated modules for this product)
#                    SOURCE MATERIALS
#
#   (C) COPYRIGHT International Business Machines Corp. 1992, 1993.
#   All Rights Reserved
#   US Government Users Restricted Rights - Use, duplication or
#   disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#


OBJECTS		= exectu.o crc.o
LIBS		= -lc

.include <${RULES_MK}>
