# @(#)61	1.3  src/bos/kernext/rcm/inc/Makefile, rcm, bos411, 9428A410j 1/10/94 15:36:59
#
#   COMPONENT_NAME: RCM
#
#   FUNCTIONS: none
#
#   ORIGINS: 27
#
#   IBM CONFIDENTIAL -- (IBM Confidential Restricted when
#   combined with the aggregated modules for this product)
#                    SOURCE MATERIALS
#
#   (C) COPYRIGHT International Business Machines Corp. 1993
#   All Rights Reserved
#   US Government Users Restricted Rights - Use, duplication or
#   disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#
#

EXPINC_SUBDIRS  = sys gai

INCLUDES	=  rcmdds.h rcm_mac.h rcm_trc.h

EXPDIR		= /kernel/include/

.include <${RULES_MK}>
