# @(#)91        1.1  src/bldenv/soelim/Makefile, ade_build, bos41J, 9509A_all 2/27/95 12:43:15
#
# COMPONENT_NAME: CMDTEXT
#
# ORIGINS: 27
#
# IBM CONFIDENTIAL -- (IBM Confidential Restricted when
# combined with the aggregated modules for this product)
#                  SOURCE MATERIALS
# (C) COPYRIGHT International Business Machines Corp. 1993
# All Rights Reserved
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#

VPATH	= ${MAKETOP}cmdtext/usr/bin/soelim

PROGRAMS = soelim

LIBS = -ly

IDIR = /usr/bin/

ILIST = ${PROGRAMS}

.include <${RULES_MK}>
