# @(#)25 1.59 src/bos/usr/lib/methods/Makefile, cfgmethods, bos41J, 9518A_all 5/1/95 12:55:06
#
# COMPONENT_NAME: CFGMETHODS
#
# FUNCTIONS: none
#
# ORIGINS: 27, 83
#
# IBM CONFIDENTIAL -- (IBM Confidential Restricted when
# combined with the aggregated modules for this product)
#                  SOURCE MATERIALS
# (C) COPYRIGHT International Business Machines Corp. 1988, 1994
# All Rights Reserved
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#
# LEVEL 1, 5 Years Bull Confidential Information
#

EXPLIB_SUBDIRS	= common
EXPINC_SUBDIRS	= common

SUBDIRS		= \
	common cfgif cfginet chgif chginet defif definet stpinet \
	sttinet ucfgif ucfginet udefif udefinet \
	cfg3270 cfgaio cfgasync cfgbadisk cfgchk \
	cfgcon cfgent cfggem cfgeth cfgeu cfgfda cfgfdd \
	cfggio cfggiodev cfgktsm cfgkbd cfgtablet cfgmouse \
	cfgkbd_std cfgkma cfgmouse_std cfgtablet_std ucfgktm_std \
	cfglft cfghia cfghscsi cfglvdd cfgmid \
	cfgmsla cfgops cfgpp cfgppa cfgpscsi \
	cfgpsla cfgpty chgpty cfgrcm cfgsccd cfgscdisk cfgsctape cfgserdasda \
	cfgserdasdc cfgserdasdd cfgsga cfgsio cfgsky cfgsol cfgswpnfs \
	cfgsys cfgsys_p cfgtmscsi cfgtok cfgmps cfgtty chgaio chgdisk \
	chgent chggen chghia chghscsi chgtok chgtty cleantty \
	convert_scdisk defaio define deflvm defops defsys instdbcln \
	ptynode sdd showled startlft startrcm starttty ucfgaio ucfgasync \
	ucfgdevice ucfglft ucfgtty undefine cfgbus ucfgcommo cfg_sgabus \
	ucfgtok ucfgfddi ucfgent ucfgpty \
	cfgdiag ucfgdiag graphics cfg_wga cfgmag cfg_rby	\
	cfgdmxtok cfgdmxeth cfg_mid \
	cfgapm cfgmpqp cfgmpqd defmpqd cfgmpaa cfgmpa cfgdgric cfgampx \
	cfgcat chgcat cfgdmpa \
	baud \
	cfgascsi cfgvscsi chgascsi chgvscsi \
	cfgddtok cfgddent cfgddeth cfgddfddi \
	cfgfddi chgfddi cfgdmxfddi ucfggraphics cfg_graphics cfg_bbl \
	cfgdlc chgdlc defdlc ucfgdlc udefdlc cfgcxma cfgsync chgcxma \
	ucfgsync ucfgcxma ucfgpp cfgcie ucfgfdd cfgfan \
	cfgdac cfgdar cfgscarray defscarray darcfgrule ucfgdac ucfgdar \
	chgdar cfgsgio startsgio convert_sgio

.include <${RULES_MK}>
