# @(#)16        1.2  src/bos/usr/ccs/lib/libplot/Makefile, libplot, bos411, 9428A410j 9/1/92 19:36:14
# COMPONENT_NAME:
#
# FUNCTIONS:
#
# ORIGINS: 27
#
# IBM CONFIDENTIAL -- (IBM Confidential Restricted when
# combined with the aggregated modules for this product)
#                  SOURCE MATERIALS
# (C) COPYRIGHT International Business Machines Corp. 1988, 1989
# All Rights Reserved
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#



LIBRARIES	= libplot.a
MSGHDRS         =
CATFILES        =
HFILES          = ${MSGHDRS}

EXPLIB_TARGETS  = export_libplot.a

ILIST           = libplot.a
IDIR            = /usr/lib/


OFILES		= \
	arc.o box.o circle.o close.o cont.o dot.o erase.o \
	label.o line.o linmod.o move.o open.o point.o \
	putsi.o space.o

.include <${RULES_MK}>
