# @(#)92        1.1  src/bldenv/cpio/Makefile, cmdarch, bos412, GOLDA411a 4/6/93 16:56:11
#
# COMPONENT_NAME: CMDARCH
#
# FUNCTIONS:
#
# ORIGINS: 27
#
# IBM CONFIDENTIAL -- (IBM Confidential Restricted when
# combined with the aggregated modules for this product)
#                  SOURCE MATERIALS
# (C) COPYRIGHT International Business Machines Corp. 1988, 1989
# All Rights Reserved
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#

VPATH		= ${MAKETOP}/bos/usr/bin/cpio

PROGRAMS	= cpio
MSGHDRS		= cpio_msg.h
CATFILES	= cpio.cat
HFILES		= ${MSGHDRS}

ILIST		= cpio
IDIR		= /usr/bin/


.include <${RULES_MK}>
