# @(#)09	1.2  src/bos/usr/lib/netls/adk/include/Makefile, libnetls, bos410 1/18/94 13:30:05
# COMPONENT_NAME:  libnetls
#
# FUNCTIONS:
#
# ORIGINS: 27
#
# IBM CONFIDENTIAL -- (IBM Confidential Restricted when
# combined with the aggregated modules for this product)
#                  SOURCE MATERIALS
# (C) COPYRIGHT International Business Machines Corp. 1988, 1992
# All Rights Reserved
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#

# Put in export trees
EXPDIR		= /usr/include/

INCLUDES	= ex_message.h \
		  libnetls.h \
                  ncflib.h

.include <${RULES_MK}>

