# @(#)38        1.4  src/bos/diag/tu/siosl/tableta/Makefile, tu_siosl, bos411, 9428A410j 1/27/94 11:24:53
#
#   COMPONENT_NAME: TU_SIOSL
#
#   FUNCTIONS: 
#
#   ORIGINS: 27
#
#   IBM CONFIDENTIAL -- (IBM Confidential Restricted when
#   combined with the aggregated modules for this product)
#                    SOURCE MATERIALS
#
#   (C) COPYRIGHT International Business Machines Corp. 1994
#   All Rights Reserved
#   US Government Users Restricted Rights - Use, duplication or
#   disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#

LIBRARIES	= libtabletatu.a

EXPLIB_TARGETS  = export_libtabletatu.a
EXPDIR		= /usr/lib/

CFLAGS		= -DDIAGNOSTICS
INCFLAGS        = -I${MAKETOP}/bos/diag/tu/siosl

OFILES		= tableta.o

.include <${RULES_MK}>
