# COMPONENT_NAME:
#
# FUNCTIONS:
#
# ORIGINS: 27
#
# IBM CONFIDENTIAL -- (IBM Confidential Restricted when
# combined with the aggregated modules for this product)
#                  SOURCE MATERIALS
# (C) COPYRIGHT International Business Machines Corp. 1988, 1989
# All Rights Reserved
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#


ILIST		= 8ffdc2.00.04 8ffdgu.00.04 8ffdgt.00.04 8ffdgv.00.04 8ffdsh.00.04 8ffdvp.00.03

IDIR		= /usr/lib/microcode/

OTHERS=

OTHERS+=8ffdc2.00.04
8ffdc2.00.04:8ffdc2.00.04.ibmstub
	-${RM} -f ${.TARGET}
	${CP} -f ${.ALLSRC} ${.TARGET}

OTHERS+=8ffdgu.00.04
8ffdgu.00.04:8ffdgu.00.04.ibmstub
	-${RM} -f ${.TARGET}
	${CP} -f ${.ALLSRC} ${.TARGET}

OTHERS+=8ffdgt.00.04
8ffdgt.00.04:8ffdgt.00.04.ibmstub
	-${RM} -f ${.TARGET}
	${CP} -f ${.ALLSRC} ${.TARGET}

OTHERS+=8ffdgv.00.04
8ffdgv.00.04:8ffdgv.00.04.ibmstub
	-${RM} -f ${.TARGET}
	${CP} -f ${.ALLSRC} ${.TARGET}

OTHERS+=8ffdsh.00.04
8ffdsh.00.04:8ffdsh.00.04.ibmstub
	-${RM} -f ${.TARGET}
	${CP} -f ${.ALLSRC} ${.TARGET}

OTHERS+=8ffdvp.00.03
8ffdvp.00.03:8ffdvp.00.03.ibmstub
	-${RM} -f ${.TARGET}
	${CP} -f ${.ALLSRC} ${.TARGET}

.include <${RULES_MK}>

