#!/unix
* @(#)20        1.1  src/bos/diag/tu/corv/slih/corvette_intr.exp, tu_corv, bos411, 9428A410j 7/22/93 18:52:57
*
*   COMPONENT_NAME: TU_CORV
*
*   FUNCTIONS: none
*
*   ORIGINS: 27
*
*
*   (C) COPYRIGHT International Business Machines Corp. 1993,1993
*   All Rights Reserved
*   Licensed Materials - Property of IBM
*   US Government Users Restricted Rights - Use, duplication or
*   disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
*
corvette_interrupt
