# @(#)56        1.4  src/bos/usr/lib/nls/loc/imt/tfep/Makefile, libtw, bos411, 9428A410j 4/21/94 00:56:09
#
#   COMPONENT_NAME: LIBTW
#
#   FUNCTIONS: none
#
#   ORIGINS: 27
#
#   IBM CONFIDENTIAL -- (IBM Confidential Restricted when
#   combined with the aggregated modules for this product)
#                    SOURCE MATERIALS
#
#   (C) COPYRIGHT International Business Machines Corp. 1992,1993
#   All Rights Reserved
#   US Government Users Restricted Rights - Use, duplication or
#   disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#

LIBRARIES = libtimfep.a

INCFLAGS  = -I${MAKETOP}/bos/usr/include

OFILES    = \
	tedacc.o tedclear.o tedclose.o tedctrl.o tedic.o tedinit.o \
	tedmisc.o tedph.o tedproc.o tedstj.o tedtj.o tedlearn.o timclose.o \
	timcreat.o timdest.o timdisp.o timinit.o timioctl.o timproca.o \
	timproce.o timprof.o timprof1.o tedconv.o

HFILES = taiwan.h ted.h tedacc.h tedinit.h message.h msgextrn.h

.include <${RULES_MK}>
