# @(#)38	1.2  src/bos/usr/lib/asw/Makefile, Makefiles, bos411, 9428A410j 8/23/93 08:36:50
# COMPONENT_NAME:
#
# FUNCTIONS:
#
# ORIGINS: 27
#
# IBM CONFIDENTIAL -- (IBM Confidential Restricted when
# combined with the aggregated modules for this product)
#                  SOURCE MATERIALS
# (C) COPYRIGHT International Business Machines Corp. 1988, 1989
# All Rights Reserved
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#


SUBDIRS		= mpqp artic

.include <${RULES_MK}>
