# @(#)47	1.3  src/bos/kernext/lft/inc/sys/Makefile, lftdd, bos411, 9428A410j 5/24/94 13:01:58
# COMPONENT_NAME: (LFTDD) Low function Terminal
#
# FUNCTIONS:
#
# ORIGINS: 27
#
# IBM CONFIDENTIAL -- (IBM Confidential Restricted when
# combined with the aggregated modules for this product)
# (C) COPYRIGHT International Business Machines Corp. 1993
# All Rights Reserved
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#
#

INCLUDES	= display.h aixfont.h font.h lft_ioctl.h pwr_mgr.h

EXPDIR		= /kernel/include/sys/

.include <${RULES_MK}>
