# @(#)83	1.2  src/bos/diag/tu/lega/mcode_binary/Makefile, tu_lega, bos411, 9428A410j 11/3/93 10:49:29
#
#   COMPONENT_NAME: tu_lega
#
#   FUNCTIONS: 
#
#   ORIGINS: 27
#
#   IBM CONFIDENTIAL -- (IBM Confidential Restricted when
#   combined with the aggregated modules for this product)
#                    SOURCE MATERIALS
#
#   (C) COPYRIGHT International Business Machines Corp. 1992, 1993
#   All Rights Reserved
#   US Government Users Restricted Rights - Use, duplication or
#   disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#


ILIST	= \
		8ee3ld1.00.04 \
		8ee3ld2.00.04 \
		8ee3ld3.00.04 \
		8ee3ld4.00.04 \
		8ee3ld5.00.04

IDIR		= /usr/lib/microcode/


OTHERS=

OTHERS+=8ee3ld1.00.04
8ee3ld1.00.04:8ee3ld1.00.04.ibmstub
	-${RM} -f ${.TARGET}
	${CP} -f ${.ALLSRC} ${.TARGET}

OTHERS+=8ee3ld2.00.04
8ee3ld2.00.04:8ee3ld2.00.04.ibmstub
	-${RM} -f ${.TARGET}
	${CP} -f ${.ALLSRC} ${.TARGET}

OTHERS+=8ee3ld3.00.04
8ee3ld3.00.04:8ee3ld3.00.04.ibmstub
	-${RM} -f ${.TARGET}
	${CP} -f ${.ALLSRC} ${.TARGET}

OTHERS+=8ee3ld4.00.04
8ee3ld4.00.04:8ee3ld4.00.04.ibmstub
	-${RM} -f ${.TARGET}
	${CP} -f ${.ALLSRC} ${.TARGET}

OTHERS+=8ee3ld5.00.04
8ee3ld5.00.04:8ee3ld5.00.04.ibmstub
	-${RM} -f ${.TARGET}
	${CP} -f ${.ALLSRC} ${.TARGET}

.include <${RULES_MK}>
