# @(#)51        1.1  src/bos/etc/motd/Makefile, cfgetc, bos411, 9428A410j 9/2/92 13:56:02
# COMPONENT_NAME:
#
# FUNCTIONS:
#
# ORIGINS: 27
#
# IBM CONFIDENTIAL -- (IBM Confidential Restricted when
# combined with the aggregated modules for this product)
#                  SOURCE MATERIALS
# (C) COPYRIGHT International Business Machines Corp. 1988, 1989
# All Rights Reserved
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#

SCRIPTS		= motd

ILIST		= motd
IDIR		= /etc/

.include <${RULES_MK}>
