# @(#)43	1.6.1.1  src/bos/etc/motd/motd.S, cfgetc, bos411, 9428A410j 7/7/93 15:20:49
#  COMPONENT_NAME: CFGETC
#
#  ORIGINS: 3, 26, 27
#
#  (C) COPYRIGHT International Business Machines Corp. 1989, 1993
#  All Rights Reserved
#  Licensed Materials - Property of IBM
#
#  US Government Users Restricted Rights - Use, duplication or
#  disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#
*******************************************************************************
*                                                                             *
*                                                                             *
*  Welcome to AIX Version 4.1!                                                *
*                                                                             *
*                                                                             *
*  Please see the README file in /usr/lpp/bos for information pertinent to    *
*  this release of the AIX Operating System.                                  *
*                                                                             *
*                                                                             *
*******************************************************************************
