# @(#)79        1.3  src/bos/usr/include/pse/Makefile, Makefiles, bos411, 9428A410j 4/12/94 18:18:20
#
#   COMPONENT_NAME: SYSXPSE
#
#   FUNCTIONS: none
#
#   ORIGINS: 27,83
#
#   This module contains IBM CONFIDENTIAL code. -- (IBM
#   Confidential Restricted when combined with the aggregated
#   modules for this product)
#                    SOURCE MATERIALS
#
#   (C) COPYRIGHT International Business Machines Corp. 1994
#   All Rights Reserved
#   US Government Users Restricted Rights - Use, duplication or
#   disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#
#   LEVEL 1, 5 Years Bull Confidential Information

VPATH           =${MAKETOP}bos/kernel/include/pse

IDIR		= /usr/include/pse/

DATAFILES	= \
		mi.h \
		nd.h \
		common.h \
		led.h \
		clib.h \
		cpp.h \
		q.h \
		echo.h \
		tmod.h

INCLUDES	= ${DATAFILES} str_stream.h str_lock.h str_debug.h \
		str_system.h

ILIST		= ${DATAFILES}

.include <${RULES_MK}>
