# @(#)11        1.2  src/bos/usr/lib/learn/eqn/Makefile, cmdlearn, bos411, 9428A410j 1/15/93 13:11:53
# COMPONENT_NAME:
#
# FUNCTIONS:
#
# ORIGINS: 27
#
# IBM CONFIDENTIAL -- (IBM Confidential Restricted when
# combined with the aggregated modules for this product)
#                  SOURCE MATERIALS
# (C) COPYRIGHT International Business Machines Corp. 1988, 1989
# All Rights Reserved
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#

DATAFILES	= Init L0 L0.1a L1.1a L1.1b L1.1c L1.1d L1.1e \
		  L1.1f L10.1a L10.1b L10.1c L10.2c L11.1a L11.1b \
		  L11.1c L11.1d L11.1e L11.1f L11.1g L12.1a L12.1b \
		  L12.1c L12.1d L12.1e L2.1a L2.1b L2.1c L2.1d L2.1e \
		  L2.1f L2.2a L2.2b L2.2e L3.1a L3.1b L3.1c L3.1d L3.1e \
		  L3.2a L3.2c L3.2d L4.1a L4.1b L4.1c L4.1d L4.2a L4.2c \
		  L5.1a L5.1b L5.1c L5.1d L5.1e L5.1f L5.1g L5.1h L5.2b \
		  L5.2d L5.2g L6.1a L6.1b L6.1c L6.1d L7.1a L7.1b L7.1c \
		  L7.1d L7.2b L7.2c L8.1a L8.1b L8.2b L9.1a L9.1b L9.2a \
		  L9.2b L9.3b tinyms

ILIST		= ${DATAFILES}
IDIR		= /usr/share/lib/learn/eqn/


.include <${RULES_MK}>
