# @(#)55	1.1  src/bos/usr/lib/methods/convert_sgio/Makefile, inputdd, bos41J, 9518A_all 5/1/95 12:53:49
# COMPONENT_NAME: INPUTDD
#
# FUNCTIONS: none
#
# ORIGINS: 27
#
# IBM CONFIDENTIAL -- (IBM Confidential Restricted when
# combined with the aggregated modules for this product)
#                  SOURCE MATERIALS
# (C) COPYRIGHT International Business Machines Corp. 1995
# All Rights Reserved
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#

CATFILES			 = convert_sgio.cat

SCRIPTS				 = convert_sgio

IDIR                 = /usr/lib/methods/
ILIST                = convert_sgio

.include <${RULES_MK}>
