# @(#)70        1.1  src/bldenv/hostname/Makefile, ade_build, bos412, GOLDA411a 2/23/93 15:17:44
#
#   COMPONENT_NAME: BOSBUILD
#
#   FUNCTIONS: 
#
#   ORIGINS: 27
#
#   IBM CONFIDENTIAL -- (IBM Confidential Restricted when
#   combined with the aggregated modules for this product)
#                    SOURCE MATERIALS
#
#   (C) COPYRIGHT International Business Machines Corp. 1993
#   All Rights Reserved
#   US Government Users Restricted Rights - Use, duplication or
#   disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#

VPATH		= ${MAKETOP}/bos/usr/bin/hostname

PROGRAMS	= hostname
MSGHDRS		= hostname_msg.h
CATFILES	= hostname.cat
HFILES		= ${MSGHDRS}

ILIST		= hostname
IDIR		= /usr/bin/


.include <${RULES_MK}>
