# @(#)76        1.1  src/bos/usr/lpp/bosinst/printers/Makefile, cmdpios, bos411, 9428A410j 3/23/94 10:56:34
# COMPONENT_NAME: CMDPIOS
#
# FUNCTIONS:
#
# ORIGINS: 27
#
# IBM CONFIDENTIAL -- (IBM Confidential Restricted when
# combined with the aggregated modules for this product)
#                  SOURCE MATERIALS
# (C) COPYRIGHT International Business Machines Corp. 1994
# All Rights Reserved
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#

SCRIPTS		= getprtpkgs modprtdevs

ILIST		= ${SCRIPTS}
 
IDIR		= /usr/lpp/bosinst/

.include <${RULES_MK}>
