#
# dependents of Sigmom.o:
Sigmom.o: ${MAKETOP}../export/power/usr/include/stdio.h
Sigmom.o: ${MAKETOP}../export/power/usr/include/standards.h
Sigmom.o: ${MAKETOP}../export/power/usr/include/va_list.h
Sigmom.o: ${MAKETOP}../export/power/usr/include/sys/types.h
Sigmom.o: ${MAKETOP}../export/power/usr/include/sys/m_types.h
Sigmom.o: ${MAKETOP}../export/power/usr/include/sys/limits.h
Sigmom.o: ${MAKETOP}../export/power/usr/include/float.h
Sigmom.o: ${MAKETOP}../export/power/usr/include/stdlib.h
Sigmom.o: ${MAKETOP}../export/power/usr/include/sys/wait.h
Sigmom.o: ${MAKETOP}../export/power/usr/include/sys/resource.h
Sigmom.o: ${MAKETOP}../export/power/usr/include/sys/time.h
Sigmom.o: ${MAKETOP}../export/power/usr/include/sys/localedef.h
Sigmom.o: ${MAKETOP}../export/power/usr/include/sys/lc_core.h
Sigmom.o: ${MAKETOP}../export/power/usr/include/locale.h
Sigmom.o: ${MAKETOP}../export/power/usr/include/sys/localedef31.h
Sigmom.o: ${MAKETOP}../export/power/usr/include/string.h
Sigmom.o: ${MAKETOP}../export/power/usr/include/fcntl.h
Sigmom.o: ${MAKETOP}../export/power/usr/include/sys/flock.h
Sigmom.o: ${MAKETOP}../export/power/usr/include/unistd.h
Sigmom.o: ${MAKETOP}../export/power/usr/include/sys/access.h
Sigmom.o: ${MAKETOP}../export/power/usr/include/sys/lockf.h
Sigmom.o: ${MAKETOP}../export/power/usr/include/sys/stat.h
Sigmom.o: ${MAKETOP}../export/power/usr/include/sys/mode.h
Sigmom.o: ${MAKETOP}../export/power/usr/include/errno.h
Sigmom.o: ${MAKETOP}../export/power/usr/include/sys/errno.h
Sigmom.o: ${MAKETOP}../export/power/usr/include/sys/termio.h
Sigmom.o: ${MAKETOP}../export/power/usr/include/sys/ioctl.h
Sigmom.o: ${MAKETOP}../export/power/usr/include/sys/ttychars.h
Sigmom.o: ${MAKETOP}../export/power/usr/include/sys/ttydev.h
Sigmom.o: ${MAKETOP}../export/power/usr/include/sys/ttmap.h
Sigmom.o: ${MAKETOP}../export/power/usr/include/termios.h
Sigmom.o: ${MAKETOP}../export/power/usr/include/sys/rcm_win.h
Sigmom.o: ${MAKETOP}../export/power/usr/include/sys/aixgsc.h
Sigmom.o: ${MAKETOP}../export/power/usr/include/sys/rcmioctl.h
Sigmom.o: ${MAKETOP}bos/kernext/disp/sga/inc/sga_reg.h
Sigmom.o: ${MAKETOP}bos/diag/tu/sgasl/sgamisc.h
Sigmom.o: ${MAKETOP}bos/diag/tu/sgasl/exectu.h
Sigmom.o: ${MAKETOP}../export/power/usr/include/diag/atu.h
Sigmom.o: ${MAKETOP}bos/kernext/disp/sga/inc/sga.h
#
# dependents of at.o:
at.o: ${MAKETOP}../export/power/usr/include/sys/types.h
at.o: ${MAKETOP}../export/power/usr/include/standards.h
at.o: ${MAKETOP}../export/power/usr/include/sys/m_types.h
at.o: ${MAKETOP}../export/power/usr/include/stdio.h
at.o: ${MAKETOP}../export/power/usr/include/va_list.h
at.o: ${MAKETOP}../export/power/usr/include/sys/limits.h
at.o: ${MAKETOP}../export/power/usr/include/float.h
at.o: ${MAKETOP}../export/power/usr/include/math.h
at.o: ${MAKETOP}../export/power/usr/include/stdlib.h
at.o: ${MAKETOP}../export/power/usr/include/sys/wait.h
at.o: ${MAKETOP}../export/power/usr/include/sys/resource.h
at.o: ${MAKETOP}../export/power/usr/include/sys/time.h
at.o: ${MAKETOP}../export/power/usr/include/sys/localedef.h
at.o: ${MAKETOP}../export/power/usr/include/sys/lc_core.h
at.o: ${MAKETOP}../export/power/usr/include/locale.h
at.o: ${MAKETOP}../export/power/usr/include/sys/localedef31.h
at.o: ${MAKETOP}bos/kernext/disp/sga/inc/sga_reg.h
at.o: ${MAKETOP}bos/diag/tu/sgasl/sgamisc.h
at.o: ${MAKETOP}bos/diag/tu/sgasl/exectu.h
at.o: ${MAKETOP}../export/power/usr/include/diag/atu.h
at.o: ${MAKETOP}bos/kernext/disp/sga/inc/sga_regval.h
#
# dependents of bentpintu.o:
bentpintu.o: ${MAKETOP}../export/power/usr/include/sys/types.h
bentpintu.o: ${MAKETOP}../export/power/usr/include/standards.h
bentpintu.o: ${MAKETOP}../export/power/usr/include/sys/m_types.h
bentpintu.o: ${MAKETOP}../export/power/usr/include/stdio.h
bentpintu.o: ${MAKETOP}../export/power/usr/include/va_list.h
bentpintu.o: ${MAKETOP}../export/power/usr/include/sys/limits.h
bentpintu.o: ${MAKETOP}../export/power/usr/include/float.h
bentpintu.o: ${MAKETOP}../export/power/usr/include/math.h
bentpintu.o: ${MAKETOP}../export/power/usr/include/stdlib.h
bentpintu.o: ${MAKETOP}../export/power/usr/include/sys/wait.h
bentpintu.o: ${MAKETOP}../export/power/usr/include/sys/resource.h
bentpintu.o: ${MAKETOP}../export/power/usr/include/sys/time.h
bentpintu.o: ${MAKETOP}../export/power/usr/include/sys/localedef.h
bentpintu.o: ${MAKETOP}../export/power/usr/include/sys/lc_core.h
bentpintu.o: ${MAKETOP}../export/power/usr/include/locale.h
bentpintu.o: ${MAKETOP}../export/power/usr/include/sys/localedef31.h
bentpintu.o: ${MAKETOP}bos/diag/tu/sgasl/sgamisc.h
bentpintu.o: ${MAKETOP}bos/diag/tu/sgasl/exectu.h
bentpintu.o: ${MAKETOP}../export/power/usr/include/diag/atu.h
bentpintu.o: ${MAKETOP}bos/kernext/disp/sga/inc/sga_reg.h
bentpintu.o: ${MAKETOP}bos/kernext/disp/sga/inc/sga_regval.h
#
# dependents of colorbartu.o:
colorbartu.o: ${MAKETOP}../export/power/usr/include/sys/types.h
colorbartu.o: ${MAKETOP}../export/power/usr/include/standards.h
colorbartu.o: ${MAKETOP}../export/power/usr/include/sys/m_types.h
colorbartu.o: ${MAKETOP}../export/power/usr/include/stdio.h
colorbartu.o: ${MAKETOP}../export/power/usr/include/va_list.h
colorbartu.o: ${MAKETOP}../export/power/usr/include/sys/limits.h
colorbartu.o: ${MAKETOP}../export/power/usr/include/float.h
colorbartu.o: ${MAKETOP}../export/power/usr/include/math.h
colorbartu.o: ${MAKETOP}../export/power/usr/include/stdlib.h
colorbartu.o: ${MAKETOP}../export/power/usr/include/sys/wait.h
colorbartu.o: ${MAKETOP}../export/power/usr/include/sys/resource.h
colorbartu.o: ${MAKETOP}../export/power/usr/include/sys/time.h
colorbartu.o: ${MAKETOP}../export/power/usr/include/sys/localedef.h
colorbartu.o: ${MAKETOP}../export/power/usr/include/sys/lc_core.h
colorbartu.o: ${MAKETOP}../export/power/usr/include/locale.h
colorbartu.o: ${MAKETOP}../export/power/usr/include/sys/localedef31.h
colorbartu.o: ${MAKETOP}bos/diag/tu/sgasl/sgamisc.h
colorbartu.o: ${MAKETOP}bos/diag/tu/sgasl/exectu.h
colorbartu.o: ${MAKETOP}../export/power/usr/include/diag/atu.h
colorbartu.o: ${MAKETOP}bos/kernext/disp/sga/inc/sga_reg.h
colorbartu.o: ${MAKETOP}bos/kernext/disp/sga/inc/sga_regval.h
#
# dependents of crosstu.o:
crosstu.o: ${MAKETOP}../export/power/usr/include/sys/types.h
crosstu.o: ${MAKETOP}../export/power/usr/include/standards.h
crosstu.o: ${MAKETOP}../export/power/usr/include/sys/m_types.h
crosstu.o: ${MAKETOP}../export/power/usr/include/stdio.h
crosstu.o: ${MAKETOP}../export/power/usr/include/va_list.h
crosstu.o: ${MAKETOP}../export/power/usr/include/sys/limits.h
crosstu.o: ${MAKETOP}../export/power/usr/include/float.h
crosstu.o: ${MAKETOP}bos/diag/tu/sgasl/sgamisc.h
crosstu.o: ${MAKETOP}bos/diag/tu/sgasl/exectu.h
crosstu.o: ${MAKETOP}../export/power/usr/include/diag/atu.h
crosstu.o: ${MAKETOP}bos/kernext/disp/sga/inc/sga_reg.h
crosstu.o: ${MAKETOP}bos/kernext/disp/sga/inc/sga_regval.h
#
# dependents of cursortu.o:
cursortu.o: ${MAKETOP}../export/power/usr/include/sys/types.h
cursortu.o: ${MAKETOP}../export/power/usr/include/standards.h
cursortu.o: ${MAKETOP}../export/power/usr/include/sys/m_types.h
cursortu.o: ${MAKETOP}../export/power/usr/include/stdio.h
cursortu.o: ${MAKETOP}../export/power/usr/include/va_list.h
cursortu.o: ${MAKETOP}../export/power/usr/include/sys/limits.h
cursortu.o: ${MAKETOP}../export/power/usr/include/float.h
cursortu.o: ${MAKETOP}../export/power/usr/include/math.h
cursortu.o: ${MAKETOP}../export/power/usr/include/stdlib.h
cursortu.o: ${MAKETOP}../export/power/usr/include/sys/wait.h
cursortu.o: ${MAKETOP}../export/power/usr/include/sys/resource.h
cursortu.o: ${MAKETOP}../export/power/usr/include/sys/time.h
cursortu.o: ${MAKETOP}../export/power/usr/include/sys/localedef.h
cursortu.o: ${MAKETOP}../export/power/usr/include/sys/lc_core.h
cursortu.o: ${MAKETOP}../export/power/usr/include/locale.h
cursortu.o: ${MAKETOP}../export/power/usr/include/sys/localedef31.h
cursortu.o: ${MAKETOP}bos/diag/tu/sgasl/sgamisc.h
cursortu.o: ${MAKETOP}bos/diag/tu/sgasl/exectu.h
cursortu.o: ${MAKETOP}../export/power/usr/include/diag/atu.h
cursortu.o: ${MAKETOP}bos/kernext/disp/sga/inc/sga_reg.h
cursortu.o: ${MAKETOP}bos/kernext/disp/sga/inc/sga_regval.h
#
# dependents of exectu.o:
exectu.o: ${MAKETOP}../export/power/usr/include/sys/types.h
exectu.o: ${MAKETOP}../export/power/usr/include/standards.h
exectu.o: ${MAKETOP}../export/power/usr/include/sys/m_types.h
exectu.o: ${MAKETOP}../export/power/usr/include/stdio.h
exectu.o: ${MAKETOP}../export/power/usr/include/va_list.h
exectu.o: ${MAKETOP}../export/power/usr/include/sys/limits.h
exectu.o: ${MAKETOP}../export/power/usr/include/float.h
exectu.o: ${MAKETOP}../export/power/usr/include/fcntl.h
exectu.o: ${MAKETOP}../export/power/usr/include/sys/flock.h
exectu.o: ${MAKETOP}../export/power/usr/include/unistd.h
exectu.o: ${MAKETOP}../export/power/usr/include/sys/access.h
exectu.o: ${MAKETOP}../export/power/usr/include/sys/lockf.h
exectu.o: ${MAKETOP}../export/power/usr/include/sys/stat.h
exectu.o: ${MAKETOP}../export/power/usr/include/sys/mode.h
exectu.o: ${MAKETOP}../export/power/usr/include/errno.h
exectu.o: ${MAKETOP}../export/power/usr/include/sys/errno.h
exectu.o: ${MAKETOP}../export/power/usr/include/string.h
exectu.o: ${MAKETOP}bos/diag/tu/sgasl/sgamisc.h
exectu.o: ${MAKETOP}bos/diag/tu/sgasl/exectu.h
exectu.o: ${MAKETOP}../export/power/usr/include/diag/atu.h
exectu.o: ${MAKETOP}bos/kernext/disp/sga/inc/sga_reg.h
exectu.o: ${MAKETOP}bos/diag/tu/sgasl/vpd.h
#
# dependents of inttu.o:
inttu.o: ${MAKETOP}../export/power/usr/include/sys/types.h
inttu.o: ${MAKETOP}../export/power/usr/include/standards.h
inttu.o: ${MAKETOP}../export/power/usr/include/sys/m_types.h
inttu.o: ${MAKETOP}../export/power/usr/include/stdio.h
inttu.o: ${MAKETOP}../export/power/usr/include/va_list.h
inttu.o: ${MAKETOP}../export/power/usr/include/sys/limits.h
inttu.o: ${MAKETOP}../export/power/usr/include/float.h
inttu.o: ${MAKETOP}bos/diag/tu/sgasl/sgamisc.h
inttu.o: ${MAKETOP}bos/diag/tu/sgasl/exectu.h
inttu.o: ${MAKETOP}../export/power/usr/include/diag/atu.h
inttu.o: ${MAKETOP}bos/kernext/disp/sga/inc/sga_reg.h
inttu.o: ${MAKETOP}bos/kernext/disp/sga/inc/sga_regval.h
#
# dependents of meminfo.o:
meminfo.o: ${MAKETOP}../export/power/usr/include/sys/types.h
meminfo.o: ${MAKETOP}../export/power/usr/include/standards.h
meminfo.o: ${MAKETOP}../export/power/usr/include/sys/m_types.h
meminfo.o: ${MAKETOP}../export/power/usr/include/stdio.h
meminfo.o: ${MAKETOP}../export/power/usr/include/va_list.h
meminfo.o: ${MAKETOP}../export/power/usr/include/sys/limits.h
meminfo.o: ${MAKETOP}../export/power/usr/include/float.h
meminfo.o: ${MAKETOP}../export/power/usr/include/setjmp.h
meminfo.o: ${MAKETOP}../export/power/usr/include/errno.h
meminfo.o: ${MAKETOP}../export/power/usr/include/sys/errno.h
meminfo.o: ${MAKETOP}../export/power/usr/include/string.h
meminfo.o: ${MAKETOP}bos/diag/tu/sgasl/sgamisc.h
meminfo.o: ${MAKETOP}bos/diag/tu/sgasl/exectu.h
meminfo.o: ${MAKETOP}../export/power/usr/include/diag/atu.h
meminfo.o: ${MAKETOP}bos/kernext/disp/sga/inc/sga_reg.h
meminfo.o: ${MAKETOP}bos/diag/tu/sgasl/vpd.h
#
# dependents of memtest.o:
memtest.o: ${MAKETOP}../export/power/usr/include/sys/types.h
memtest.o: ${MAKETOP}../export/power/usr/include/standards.h
memtest.o: ${MAKETOP}../export/power/usr/include/sys/m_types.h
memtest.o: ${MAKETOP}../export/power/usr/include/stdio.h
memtest.o: ${MAKETOP}../export/power/usr/include/va_list.h
memtest.o: ${MAKETOP}../export/power/usr/include/sys/limits.h
memtest.o: ${MAKETOP}../export/power/usr/include/float.h
memtest.o: ${MAKETOP}../export/power/usr/include/math.h
memtest.o: ${MAKETOP}../export/power/usr/include/stdlib.h
memtest.o: ${MAKETOP}../export/power/usr/include/sys/wait.h
memtest.o: ${MAKETOP}../export/power/usr/include/sys/resource.h
memtest.o: ${MAKETOP}../export/power/usr/include/sys/time.h
memtest.o: ${MAKETOP}../export/power/usr/include/sys/localedef.h
memtest.o: ${MAKETOP}../export/power/usr/include/sys/lc_core.h
memtest.o: ${MAKETOP}../export/power/usr/include/locale.h
memtest.o: ${MAKETOP}../export/power/usr/include/sys/localedef31.h
memtest.o: ${MAKETOP}bos/diag/tu/sgasl/sgamisc.h
memtest.o: ${MAKETOP}bos/diag/tu/sgasl/exectu.h
memtest.o: ${MAKETOP}../export/power/usr/include/diag/atu.h
memtest.o: ${MAKETOP}bos/kernext/disp/sga/inc/sga_reg.h
memtest.o: ${MAKETOP}bos/kernext/disp/sga/inc/sga_regval.h
memtest.o: ${MAKETOP}bos/diag/tu/sgasl/vpd.h
#
# dependents of palettetu.o:
palettetu.o: ${MAKETOP}../export/power/usr/include/sys/types.h
palettetu.o: ${MAKETOP}../export/power/usr/include/standards.h
palettetu.o: ${MAKETOP}../export/power/usr/include/sys/m_types.h
palettetu.o: ${MAKETOP}../export/power/usr/include/stdio.h
palettetu.o: ${MAKETOP}../export/power/usr/include/va_list.h
palettetu.o: ${MAKETOP}../export/power/usr/include/sys/limits.h
palettetu.o: ${MAKETOP}../export/power/usr/include/float.h
palettetu.o: ${MAKETOP}../export/power/usr/include/math.h
palettetu.o: ${MAKETOP}../export/power/usr/include/stdlib.h
palettetu.o: ${MAKETOP}../export/power/usr/include/sys/wait.h
palettetu.o: ${MAKETOP}../export/power/usr/include/sys/resource.h
palettetu.o: ${MAKETOP}../export/power/usr/include/sys/time.h
palettetu.o: ${MAKETOP}../export/power/usr/include/sys/localedef.h
palettetu.o: ${MAKETOP}../export/power/usr/include/sys/lc_core.h
palettetu.o: ${MAKETOP}../export/power/usr/include/locale.h
palettetu.o: ${MAKETOP}../export/power/usr/include/sys/localedef31.h
palettetu.o: ${MAKETOP}bos/diag/tu/sgasl/sgamisc.h
palettetu.o: ${MAKETOP}bos/diag/tu/sgasl/exectu.h
palettetu.o: ${MAKETOP}../export/power/usr/include/diag/atu.h
palettetu.o: ${MAKETOP}bos/kernext/disp/sga/inc/sga_reg.h
palettetu.o: ${MAKETOP}bos/kernext/disp/sga/inc/sga_regval.h
#
# dependents of parmstu.o:
parmstu.o: ${MAKETOP}../export/power/usr/include/sys/types.h
parmstu.o: ${MAKETOP}../export/power/usr/include/standards.h
parmstu.o: ${MAKETOP}../export/power/usr/include/sys/m_types.h
parmstu.o: ${MAKETOP}../export/power/usr/include/stdio.h
parmstu.o: ${MAKETOP}../export/power/usr/include/va_list.h
parmstu.o: ${MAKETOP}../export/power/usr/include/sys/limits.h
parmstu.o: ${MAKETOP}../export/power/usr/include/float.h
parmstu.o: ${MAKETOP}../export/power/usr/include/errno.h
parmstu.o: ${MAKETOP}../export/power/usr/include/sys/errno.h
parmstu.o: ${MAKETOP}bos/diag/tu/sgasl/sgamisc.h
parmstu.o: ${MAKETOP}bos/diag/tu/sgasl/exectu.h
parmstu.o: ${MAKETOP}../export/power/usr/include/diag/atu.h
parmstu.o: ${MAKETOP}bos/kernext/disp/sga/inc/sga_reg.h
parmstu.o: ${MAKETOP}bos/kernext/disp/sga/inc/sga_regval.h
parmstu.o: ${MAKETOP}bos/diag/tu/sgasl/vpd.h
#
# dependents of regtu.o:
regtu.o: ${MAKETOP}../export/power/usr/include/sys/types.h
regtu.o: ${MAKETOP}../export/power/usr/include/standards.h
regtu.o: ${MAKETOP}../export/power/usr/include/sys/m_types.h
regtu.o: ${MAKETOP}../export/power/usr/include/stdio.h
regtu.o: ${MAKETOP}../export/power/usr/include/va_list.h
regtu.o: ${MAKETOP}../export/power/usr/include/sys/limits.h
regtu.o: ${MAKETOP}../export/power/usr/include/float.h
regtu.o: ${MAKETOP}../export/power/usr/include/math.h
regtu.o: ${MAKETOP}../export/power/usr/include/stdlib.h
regtu.o: ${MAKETOP}../export/power/usr/include/sys/wait.h
regtu.o: ${MAKETOP}../export/power/usr/include/sys/resource.h
regtu.o: ${MAKETOP}../export/power/usr/include/sys/time.h
regtu.o: ${MAKETOP}../export/power/usr/include/sys/localedef.h
regtu.o: ${MAKETOP}../export/power/usr/include/sys/lc_core.h
regtu.o: ${MAKETOP}../export/power/usr/include/locale.h
regtu.o: ${MAKETOP}../export/power/usr/include/sys/localedef31.h
regtu.o: ${MAKETOP}bos/diag/tu/sgasl/sgamisc.h
regtu.o: ${MAKETOP}bos/diag/tu/sgasl/exectu.h
regtu.o: ${MAKETOP}../export/power/usr/include/diag/atu.h
regtu.o: ${MAKETOP}bos/kernext/disp/sga/inc/sga_reg.h
regtu.o: ${MAKETOP}bos/kernext/disp/sga/inc/sga_regval.h
regtu.o: ${MAKETOP}bos/diag/tu/sgasl/vpd.h
#
# dependents of rgbtu.o:
rgbtu.o: ${MAKETOP}../export/power/usr/include/sys/types.h
rgbtu.o: ${MAKETOP}../export/power/usr/include/standards.h
rgbtu.o: ${MAKETOP}../export/power/usr/include/sys/m_types.h
rgbtu.o: ${MAKETOP}../export/power/usr/include/stdio.h
rgbtu.o: ${MAKETOP}../export/power/usr/include/va_list.h
rgbtu.o: ${MAKETOP}../export/power/usr/include/sys/limits.h
rgbtu.o: ${MAKETOP}../export/power/usr/include/float.h
rgbtu.o: ${MAKETOP}bos/diag/tu/sgasl/sgamisc.h
rgbtu.o: ${MAKETOP}bos/diag/tu/sgasl/exectu.h
rgbtu.o: ${MAKETOP}../export/power/usr/include/diag/atu.h
#
# dependents of scrolltu.o:
scrolltu.o: ${MAKETOP}../export/power/usr/include/sys/types.h
scrolltu.o: ${MAKETOP}../export/power/usr/include/standards.h
scrolltu.o: ${MAKETOP}../export/power/usr/include/sys/m_types.h
scrolltu.o: ${MAKETOP}../export/power/usr/include/stdio.h
scrolltu.o: ${MAKETOP}../export/power/usr/include/va_list.h
scrolltu.o: ${MAKETOP}../export/power/usr/include/sys/limits.h
scrolltu.o: ${MAKETOP}../export/power/usr/include/float.h
scrolltu.o: ${MAKETOP}../export/power/usr/include/fcntl.h
scrolltu.o: ${MAKETOP}../export/power/usr/include/sys/flock.h
scrolltu.o: ${MAKETOP}../export/power/usr/include/unistd.h
scrolltu.o: ${MAKETOP}../export/power/usr/include/sys/access.h
scrolltu.o: ${MAKETOP}../export/power/usr/include/sys/lockf.h
scrolltu.o: ${MAKETOP}../export/power/usr/include/sys/stat.h
scrolltu.o: ${MAKETOP}../export/power/usr/include/sys/mode.h
scrolltu.o: ${MAKETOP}../export/power/usr/include/errno.h
scrolltu.o: ${MAKETOP}../export/power/usr/include/sys/errno.h
scrolltu.o: ${MAKETOP}bos/diag/tu/sgasl/sgamisc.h
scrolltu.o: ${MAKETOP}bos/diag/tu/sgasl/exectu.h
scrolltu.o: ${MAKETOP}../export/power/usr/include/diag/atu.h
scrolltu.o: ${MAKETOP}bos/kernext/disp/sga/inc/sga_reg.h
scrolltu.o: ${MAKETOP}bos/kernext/disp/sga/inc/sga_regval.h
#
# dependents of sqrboxtu.o:
sqrboxtu.o: ${MAKETOP}../export/power/usr/include/sys/types.h
sqrboxtu.o: ${MAKETOP}../export/power/usr/include/standards.h
sqrboxtu.o: ${MAKETOP}../export/power/usr/include/sys/m_types.h
sqrboxtu.o: ${MAKETOP}../export/power/usr/include/stdio.h
sqrboxtu.o: ${MAKETOP}../export/power/usr/include/va_list.h
sqrboxtu.o: ${MAKETOP}../export/power/usr/include/sys/limits.h
sqrboxtu.o: ${MAKETOP}../export/power/usr/include/float.h
sqrboxtu.o: ${MAKETOP}../export/power/usr/include/math.h
sqrboxtu.o: ${MAKETOP}../export/power/usr/include/stdlib.h
sqrboxtu.o: ${MAKETOP}../export/power/usr/include/sys/wait.h
sqrboxtu.o: ${MAKETOP}../export/power/usr/include/sys/resource.h
sqrboxtu.o: ${MAKETOP}../export/power/usr/include/sys/time.h
sqrboxtu.o: ${MAKETOP}../export/power/usr/include/sys/localedef.h
sqrboxtu.o: ${MAKETOP}../export/power/usr/include/sys/lc_core.h
sqrboxtu.o: ${MAKETOP}../export/power/usr/include/locale.h
sqrboxtu.o: ${MAKETOP}../export/power/usr/include/sys/localedef31.h
sqrboxtu.o: ${MAKETOP}bos/diag/tu/sgasl/sgamisc.h
sqrboxtu.o: ${MAKETOP}bos/diag/tu/sgasl/exectu.h
sqrboxtu.o: ${MAKETOP}../export/power/usr/include/diag/atu.h
sqrboxtu.o: ${MAKETOP}bos/kernext/disp/sga/inc/sga_reg.h
sqrboxtu.o: ${MAKETOP}bos/kernext/disp/sga/inc/sga_regval.h
#
# dependents of vpdtu.o:
vpdtu.o: ${MAKETOP}../export/power/usr/include/sys/types.h
vpdtu.o: ${MAKETOP}../export/power/usr/include/standards.h
vpdtu.o: ${MAKETOP}../export/power/usr/include/sys/m_types.h
vpdtu.o: ${MAKETOP}../export/power/usr/include/stdio.h
vpdtu.o: ${MAKETOP}../export/power/usr/include/va_list.h
vpdtu.o: ${MAKETOP}../export/power/usr/include/sys/limits.h
vpdtu.o: ${MAKETOP}../export/power/usr/include/float.h
vpdtu.o: ${MAKETOP}bos/diag/tu/sgasl/sgamisc.h
vpdtu.o: ${MAKETOP}bos/diag/tu/sgasl/exectu.h
vpdtu.o: ${MAKETOP}../export/power/usr/include/diag/atu.h
vpdtu.o: ${MAKETOP}bos/diag/tu/sgasl/vpd.h
#
# dependents of vramtu.o:
vramtu.o: ${MAKETOP}../export/power/usr/include/stdio.h
vramtu.o: ${MAKETOP}../export/power/usr/include/standards.h
vramtu.o: ${MAKETOP}../export/power/usr/include/va_list.h
vramtu.o: ${MAKETOP}../export/power/usr/include/sys/types.h
vramtu.o: ${MAKETOP}../export/power/usr/include/sys/m_types.h
vramtu.o: ${MAKETOP}../export/power/usr/include/sys/limits.h
vramtu.o: ${MAKETOP}../export/power/usr/include/float.h
vramtu.o: ${MAKETOP}../export/power/usr/include/math.h
vramtu.o: ${MAKETOP}../export/power/usr/include/stdlib.h
vramtu.o: ${MAKETOP}../export/power/usr/include/sys/wait.h
vramtu.o: ${MAKETOP}../export/power/usr/include/sys/resource.h
vramtu.o: ${MAKETOP}../export/power/usr/include/sys/time.h
vramtu.o: ${MAKETOP}../export/power/usr/include/sys/localedef.h
vramtu.o: ${MAKETOP}../export/power/usr/include/sys/lc_core.h
vramtu.o: ${MAKETOP}../export/power/usr/include/locale.h
vramtu.o: ${MAKETOP}../export/power/usr/include/sys/localedef31.h
vramtu.o: ${MAKETOP}bos/diag/tu/sgasl/sgamisc.h
vramtu.o: ${MAKETOP}bos/diag/tu/sgasl/exectu.h
vramtu.o: ${MAKETOP}../export/power/usr/include/diag/atu.h
vramtu.o: ${MAKETOP}bos/kernext/disp/sga/inc/sga_reg.h
vramtu.o: ${MAKETOP}bos/kernext/disp/sga/inc/sga_regval.h
#
# dependents of wclip.o:
wclip.o: ${MAKETOP}../export/power/usr/include/sys/types.h
wclip.o: ${MAKETOP}../export/power/usr/include/standards.h
wclip.o: ${MAKETOP}../export/power/usr/include/sys/m_types.h
wclip.o: ${MAKETOP}../export/power/usr/include/stdio.h
wclip.o: ${MAKETOP}../export/power/usr/include/va_list.h
wclip.o: ${MAKETOP}../export/power/usr/include/sys/limits.h
wclip.o: ${MAKETOP}../export/power/usr/include/float.h
wclip.o: ${MAKETOP}../export/power/usr/include/math.h
wclip.o: ${MAKETOP}../export/power/usr/include/stdlib.h
wclip.o: ${MAKETOP}../export/power/usr/include/sys/wait.h
wclip.o: ${MAKETOP}../export/power/usr/include/sys/resource.h
wclip.o: ${MAKETOP}../export/power/usr/include/sys/time.h
wclip.o: ${MAKETOP}../export/power/usr/include/sys/localedef.h
wclip.o: ${MAKETOP}../export/power/usr/include/sys/lc_core.h
wclip.o: ${MAKETOP}../export/power/usr/include/locale.h
wclip.o: ${MAKETOP}../export/power/usr/include/sys/localedef31.h
wclip.o: ${MAKETOP}bos/diag/tu/sgasl/sgamisc.h
wclip.o: ${MAKETOP}bos/diag/tu/sgasl/exectu.h
wclip.o: ${MAKETOP}../export/power/usr/include/diag/atu.h
wclip.o: ${MAKETOP}bos/kernext/disp/sga/inc/sga_reg.h
wclip.o: ${MAKETOP}bos/kernext/disp/sga/inc/sga_regval.h
#
# dependents of worig.o:
worig.o: ${MAKETOP}../export/power/usr/include/sys/types.h
worig.o: ${MAKETOP}../export/power/usr/include/standards.h
worig.o: ${MAKETOP}../export/power/usr/include/sys/m_types.h
worig.o: ${MAKETOP}../export/power/usr/include/stdio.h
worig.o: ${MAKETOP}../export/power/usr/include/va_list.h
worig.o: ${MAKETOP}../export/power/usr/include/sys/limits.h
worig.o: ${MAKETOP}../export/power/usr/include/float.h
worig.o: ${MAKETOP}../export/power/usr/include/math.h
worig.o: ${MAKETOP}../export/power/usr/include/stdlib.h
worig.o: ${MAKETOP}../export/power/usr/include/sys/wait.h
worig.o: ${MAKETOP}../export/power/usr/include/sys/resource.h
worig.o: ${MAKETOP}../export/power/usr/include/sys/time.h
worig.o: ${MAKETOP}../export/power/usr/include/sys/localedef.h
worig.o: ${MAKETOP}../export/power/usr/include/sys/lc_core.h
worig.o: ${MAKETOP}../export/power/usr/include/locale.h
worig.o: ${MAKETOP}../export/power/usr/include/sys/localedef31.h
worig.o: ${MAKETOP}bos/diag/tu/sgasl/sgamisc.h
worig.o: ${MAKETOP}bos/diag/tu/sgasl/exectu.h
worig.o: ${MAKETOP}../export/power/usr/include/diag/atu.h
worig.o: ${MAKETOP}bos/kernext/disp/sga/inc/sga_reg.h
worig.o: ${MAKETOP}bos/kernext/disp/sga/inc/sga_regval.h
