# @(#)39       1.1  src/bldenv/odmget/Makefile, ade_build, bos412, GOLDA411a 9/7/94 18:34:13
#
# COMPONENT_NAME: ADE_BUILD
#
# FUNCTIONS:
#
# ORIGINS: 27
#
# IBM CONFIDENTIAL -- (IBM Confidential Restricted when
# combined with the aggregated modules for this product)
#                  SOURCE MATERIALS
# (C) COPYRIGHT International Business Machines Corp. 1988, 1989
# All Rights Reserved
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#

VPATH		= ${MAKETOP}bos/usr/bin/odmget

PROGRAMS	= odmget

ILIST		= odmget
IDIR		= /usr/bin/

LIBS		= -lodm

.include <${RULES_MK}>
