# @(#)54        1.1  src/bos/etc/swapspaces/Makefile, cmdps, bos411, 9428A410j 9/2/92 14:49:30
# COMPONENT_NAME:
#
# FUNCTIONS:
#
# ORIGINS: 27
#
# IBM CONFIDENTIAL -- (IBM Confidential Restricted when
# combined with the aggregated modules for this product)
#                  SOURCE MATERIALS
# (C) COPYRIGHT International Business Machines Corp. 1988, 1989
# All Rights Reserved
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#

SCRIPTS		= swapspaces

ILIST		= swapspaces
IDIR		= /etc/

.include <${RULES_MK}>
