# @(#)99      1.5  src/bos/usr/lib/piosk/Makefile, cmdpiosk, bos411, 9428A410j 8/16/93 01:22:42
#
#   COMPONENT_NAME: CMDPIOSK
#
#   FUNCTIONS: 
#
#   ORIGINS: 27
#
#   IBM CONFIDENTIAL -- (IBM Confidential Restricted when
#   combined with the aggregated modules for this product)
#                    SOURCE MATERIALS
#
#   (C) COPYRIGHT International Business Machines Corp. 1993
#   All Rights Reserved
#   US Government Users Restricted Rights - Use, duplication or
#   disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#

SUBDIRS = msg libR5 fmtrs predef nls
EXPINC_SUBDIRS = msg libR5
EXPLIB_SUBDIRS = libR5

.include <${RULES_MK}>
