$ @(#)86	1.2  src/bos/usr/lib/methods/cfgdmpa/dmpa.msg, mpacfg, bos411, 9428A410j 5/26/93 08:29:08
$
$   COMPONENT_NAME: (MPAMSG) MP/A MESSAGE FILES
$
$   FUNCTIONS: 
$		
$
$   ORIGINS: 27
$
$   IBM CONFIDENTIAL -- (IBM Confidential Restricted when
$   combined with the aggregated modules for this product)
$                    SOURCE MATERIALS
$
$   (C) COPYRIGHT International Business Machines Corp. 1993
$   All Rights Reserved
$   US Government Users Restricted Rights - Use, duplication or
$   disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
$

$ This is the msg src file for the mpa.cat message catalog
$quote "    Use a double quote to delimit text
$delset 1   Clean up the set first by deleteing it
$set 1
1      "Single Port Multiprotocol Adapter/A (MP/A)"
2      "Base Address For Bus I/O Access"
3      "Interrupt Level"
4      "Dma Level"
5      "Interrupt Priority"
6      "Driver to Load"
7      "MP/A Diagnostic Device Driver"
8      "MP/A SDLC Device Driver"
9      "MP/A X.25 Device Driver"
