# @(#)89	1.2  src/bos/usr/lib/ncs/idl/c/Makefile, libncs, bos410 1/18/94 13:32:16
# COMPONENT_NAME:  libncs
#
# FUNCTIONS:
#
# ORIGINS: 27
#
# IBM CONFIDENTIAL -- (IBM Confidential Restricted when
# combined with the aggregated modules for this product)
#                  SOURCE MATERIALS
# (C) COPYRIGHT International Business Machines Corp. 1988, 1992
# All Rights Reserved
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#

# Put into the export tree
EXPDIR		= /usr/include/
INCLUDES	= \
	base.h \
	conv.h \
	fault.h \
	glb.h \
	idl_base.h \
	lb.h \
	llb.h \
	name.h \
	nbase.h \
	ncastat.h \
	pfm.h \
	ppfm.h \
	rpc.h \
	rproc.h \
	rrpc.h \
	socket.h \
	timebase.h \
	uuid.h
.include <${RULES_MK}>

