#
#
#   ORIGINS: 27
#
#


EXPDIR	= /usr/include/X11/

DATAFILES	= \
	aix_keysym.h \
	keysym.h \
	keysymdef.h \
	Xos.h \
	Xosdefs.h \
	Xfuncs.h \
	Xmd.h \
	Xprotostr.h \
	Xproto.h

INCLUDES	= ${DATAFILES}

.include <${RULES_MK}>
