#
#
#
#   ORIGINS: 27
#
#
#

#VPATH	= ${MAKETOP}gos/2d/MOTIF/clients/uil

EXPDIR	= /usr/include/uil/

DATAFILES	= \
	UilDef.h \
	UilDBDef.h \
	UilSymGl.h \
	Uil.h \
	UilSymDef.h

INCLUDES	= ${DATAFILES}

.include <${RULES_MK}>

