# @(#)03        1.22 2/6/94 src/bos/kernext/disp/Makefile, sysxdisp, bos411, 9428A410j 12:24:38
# COMPONENT_NAME:  SYSXDISP
#
# FUNCTIONS:
#
# ORIGINS: 27
#
# IBM CONFIDENTIAL -- (IBM Confidential Restricted when
# combined with the aggregated modules for this product)
#                  SOURCE MATERIALS
# (C) COPYRIGHT International Business Machines Corp. 1992, 1993, 1994
# All Rights Reserved
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#

EXPINC_SUBDIRS  = inc trace sky ccm sga ped wga gem  bbl rby

SUBDIRS		= sky ccm sga ped wga gem  bbl rby

.include <${RULES_MK}>
