# @(#)57        1.4  src/bldenv/odmcreate/Makefile, ade_build, bos412, GOLDA411a 6/20/94 18:16:07
#
#   COMPONENT_NAME: BOSBUILD
#
#   FUNCTIONS:
#
#   ORIGINS: 27
#
#   IBM CONFIDENTIAL -- (IBM Confidential Restricted when
#   combined with the aggregated modules for this product)
#                    SOURCE MATERIALS
#
#   (C) COPYRIGHT International Business Machines Corp. 1993
#   All Rights Reserved
#   US Government Users Restricted Rights - Use, duplication or
#   disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#

VPATH		= ${MAKETOP}/bos/usr/bin/odmcreate

PROGRAMS	= odmcreate
MSGHDRS		=
CATFILES	=
HFILES		=

CFLAGS		= -DMACH -DCMU -D_NO_PROTO 
ILIST		= ${PROGRAMS}
IDIR		= /usr/bin/

LIBS		= -lodm

.include <${RULES_MK}>
