# @(#)29        1.1  src/bos/usr/ccs/lib/libmi/Makefile, Makefiles, bos411, 9428A410j 8/5/92 16:25:09
# COMPONENT_NAME:
#
# FUNCTIONS:
#
# ORIGINS: 27
#
# IBM CONFIDENTIAL -- (IBM Confidential Restricted when
# combined with the aggregated modules for this product)
#                  SOURCE MATERIALS
# (C) COPYRIGHT International Business Machines Corp. 1988, 1989
# All Rights Reserved
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#

LIBRARIES	= libmi.a
MSGHDRS		= 
CATFILES	= 
HFILES		= ${MSGHDRS}

EXPLIB_TARGETS	= export_libmi.a

ILIST		=
IDIR		= /usr/ccs/lib/

libmi.a_OFILES		= \
		ccread.o ccwrite.o cpp.o ecalloc.o emalloc.o errmsg.o \
		errstr.o estrdup.o fatal.o getopt.o getprogn.o hextostr.o \
		memory.o ndget.o ndset.o q.o setprogn.o strecat.o strecpy.o \
		strtohex.o tdb.o usage.o warn.o


.include <${RULES_MK}>
