$ @(#)83        1.1  src/bos/usr/lpp/kls/dictutil/hdict.msg, cmdkr, bos411, 9428A410j 5/25/92 14:39:49
$
$ COMPONENT_NAME: (CMDKR) - Korean Dictionary Utility
$
$ FUNCTIONS :	hdict.msg
$
$ ORIGINS: 27
$
$ IBM CONFIDENTIAL -- (IBM Confidential Restricted when
$ combined with the aggregated modules for this product)
$                  SOURCE MATERIALS
$ (C) COPYRIGHT International Business Machines Corp. 1989, 1992
$ All Rights Reserved
$
$ US Government Users Restricted Rights - Use, duplication or
$ disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
$
$set 1
$
1 Initial loading...
2 The dictionary file is updated
3 All data is correct
4 The dictionary file needs recovering
5 Nothing is required for recovery
6 Can not access user dictionary
7 Invalid key has been pressed
8 There is no data in user dictionary
9 Some data has been deleted
10 Input Candidate
11 Input Key and its Candidates
12 Input Key
13 The registration has been completed
14 Already exists in user dictionary
15 Already exists in system dictionary
16 Invalid characters exist in Key
17 The dictionary file size exceeds the limit
18 Number of candidates exceeds the limit
19 The Key and the Candidate should not be the same
20 The data will be deleted. Press Enter to continue
21 All update has been cancelled. Enter = End  F12 = Cancel
22 Enter the Key
23 Not Regist this Key
24 Length of the Key exceeds the limit(10 char)
25 The Key and the Candidate should not be the same
26 Failed in dictionary file recovery!!!
27 There is no data in user dictionary, so you can't update
28 Already exists data in user dictionary
29 The Key must consist of only Hanguls or only numerics
30 The data will be deleted. Press Enter to continue
31 Now Searching... Please wait a moment
32 Now Updating...  Please wait a moment
33 Can not access user dictionary
34 Can not access system dictionary
35 Can not access profile
36 Length of the Key exceeds the limit(10 char)
37 The dictionary is now in use
38 Your update will not be applied.  Enter = Start F12 = Exit
39 All update has been cancelled
40 No data left in dictionary file
41 Please press F3 or F12 key
42 No data could be recovered
43 Recovering...
44 Please input file name
45 File name already exists. Enter = Do  F12 = Cancel
46 File access permission denied
47 Combining...
48 The file combination was completed
49 Additional dictionary does not exist
50 It is not allowed to combine the same files
51 Second file is not user dictionary
52 Finished writing user dictionary to the above file
53 Finished printing user dictionary
54 File access permission denied
55 Printing Error occurred
56 The dictionary file needs recovering
57 New dictionary file is now in use
58 This file name is invalid
59 File combination successed, but some data deleted
60 Length of the Candidate exceeds the limit(10 char)
61 Additional dictionary and new dictionary should not be the same
62 Total length of candidates of A Key exceeds the limit
63 display size err
64 ** User Dictionary Utility **
65 Move cursor to desired item and press Enter
66 Enter = Do
67  1. Registration                  
68  2. Update(replacement, deletion) 
69  3. List                          
70  4. Combination                   
71  5. Recovery                      
72  9. Exit                          
73 File Seek Error 
74 Status Write Error 
75 File Write Error 
76 (dictionary : 
77 ** User Dictionary Registration **
78 Enter after key and candidate input
79 key : [                    ]
80 candidate : [                    ]
81 Enter = Register
82 F3 = End
83 F5 = Clear
84 ** User Dictionary Combination **
85 This function combines two user dictionaries
86 Enter the file names
87 Original User Dictionary
88 Additional User Dictionary
89 New User Dictionary
90 Enter = Combine  F3 = End
91 ** User Dictionary Update **
92 F2 = Delete
93 F3 = End
94 F7 = Previous
95 F8 = Next
96 F9 = Search
97 F12 = Cancel
98 ** User Dictionary List **
99  1. Screen  
100  2. Printer 
101  3. File    
102 This function lists content of dictionary
103 Move cursor to desired item and press Enter
104 ** User Dictionary Display **
$
