# @(#)17        1.1 8/15/94 src/bos/usr/include/graphics/bl/Makefile, bluedd, bos411, 9433B411a 13:14:38
#
# COMPONENT_NAME: (bluedd) BL Device Driver
#
# FUNCTIONS: Export BL usr include files to usr export tree
#
# ORIGINS: 27
#
# IBM CONFIDENTIAL -- (IBM Confidential Restricted when
# combined with the aggregated modules for this product)
# (C) COPYRIGHT International Business Machines Corp. 1994
# All Rights Reserved
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#
#

VPATH           = ${MAKETOP}bos/kernext/disp/bl/inc

EXPDIR		= /usr/include/graphics/
bldds.h_EXPDIR	= /usr/include/

DATAFILES	= bldds.h bl_bview.h bl_bview_regs.h bl_gp.h \
		  bl_hw.h bl_prsm.h bl_prsm_regs.h

INCLUDES	= ${DATAFILES} 

.include <${RULES_MK}>
