# @(#)14        1.2  src/bos/usr/lib/learn/files/Makefile, cmdlearn, bos411, 9428A410j 1/15/93 13:12:32
# COMPONENT_NAME:
#
# FUNCTIONS:
#
# ORIGINS: 27
#
# IBM CONFIDENTIAL -- (IBM Confidential Restricted when
# combined with the aggregated modules for this product)
#                  SOURCE MATERIALS
# (C) COPYRIGHT International Business Machines Corp. 1988, 1989
# All Rights Reserved
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#

DATAFILES	= L0 L0.01a L0.1a L0.1b L0.1c L0.1d L1.1a L1.2a \
		  L1.2b L10.1a L10.2a L10.2b L10.3a L10.3b L10.3c \
		  L10.3d L11.1a L11.2a L11.2b L11.3a L11.3b L11.3c \
		  L12.1a L12.2a L12.2b L12.2c L12.3a L12.3b L12.3c \
		  L13.01a L13.1a L13.1b L13.1c L13.1d L13.1e L13.1f \
		  L13.1g L2.1a L2.2a L2.2b L3.1a L3.2a L3.2b L3.3a \
		  L3.3b L4.1a L4.2a L4.2b L4.3a L4.3b L4.3c L5.1a \
		  L5.1b L5.1c L5.1d L5.1e L6.1a L6.1b L6.1c L6.1d \
		  L6.1e L6.2a L6.2b L7.1a L7.2a L7.2b L7.3a L7.3b \
		  L7.3c L8.1a L8.2a L8.2b L8.2c L9.1a L9.2a L9.2b \
		  L9.2c

ILIST		= ${DATAFILES}
IDIR		= /usr/share/lib/learn/files/


.include <${RULES_MK}>
