# @(#)06        1.7  src/bos/usr/lbin/Makefile, Makefiles, bos41J, 9511A_all 3/3/95 14:19:25
# COMPONENT_NAME:
#
# FUNCTIONS:
#
# ORIGINS: 27
#
# IBM CONFIDENTIAL -- (IBM Confidential Restricted when
# combined with the aggregated modules for this product)
#                  SOURCE MATERIALS
# (C) COPYRIGHT International Business Machines Corp. 1988, 1989
# All Rights Reserved
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#

SUBDIRS		= \
	calprog diff3prog diffh fddi_dd en3com getNAME mkwhatis trmon tty \
	ient_dd trmps kent_dd

.include <${RULES_MK}>
