$ @(#)48	1.3  src/bos/usr/ccs/lib/libtermcap/termc.msg, libtermcap, bos411, 9428A410j 6/16/90 02:40:53
$ COMPONENT_NAME: (LIBTERMC) Termcap Library
$
$ FUNCTIONS: 
$
$ ORIGINS: 27 
$
$ IBM CONFIDENTIAL -- (IBM Confidential Restricted when
$ combined with the aggregated modules for this product)
$                  SOURCE MATERIALS
$ (C) COPYRIGHT International Business Machines Corp. 1989
$ All Rights Reserved
$
$ US Government Users Restricted Rights - Use, duplication or
$ disclosure restricted by GSA ADP Schedule Contract with IBM Corp.

$set MS_TERMC
$quote "
MS_TOOLONG 1235-001 "Termcap entry too long\n"
MS_INFINITE 1235-002 "Infinite tc= loop\n"
MS_BAD 1235-003 "Bad termcap entry\n"
