# @(#)61        1.2  src/bldenv/strip/Makefile, ade_build, bos412, GOLDA411a 4/1/93 13:52:43
#
#   COMPONENT_NAME: BOSBUILD
#
#   FUNCTIONS:
#
#   ORIGINS: 27
#
#   IBM CONFIDENTIAL -- (IBM Confidential Restricted when
#   combined with the aggregated modules for this product)
#                    SOURCE MATERIALS
#
#   (C) COPYRIGHT International Business Machines Corp. 1993
#   All Rights Reserved
#   US Government Users Restricted Rights - Use, duplication or
#   disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#

VPATH			= ${MAKETOP}/bos/usr/ccs/bin/strip

PROGRAMS		= strip
MSGHDRS                 = strip_msg.h
CATFILES                = strip.cat

ILIST			= strip
IDIR			= /usr/bin/
HFILES			= ${MSGHDRS} 

.include <${RULES_MK}>
