# @(#)52	1.2  src/bos/usr/lib/nls/bidi/maps/Makefile, bos, bos410 8/31/93 09:06:46
#
# COMPONENT_NAME: CFGNLS
#
# FUNCTIONS:
#
# ORIGINS: 27
#
# IBM CONFIDENTIAL -- (IBM Confidential Restricted when
# combined with the aggregated modules for this product)
#                  SOURCE MATERIALS
# (C) COPYRIGHT International Business Machines Corp. 1988, 1993
# All Rights Reserved
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#


SUBDIRS		= iw_IL.7-bit iw_IL.ibm3151 iw_IL.ibm3151-7-bit iw_IL.ibmaadu \
                  iw_IL.ISO8859-8 iw_IL.ISO8859-8@alt iw_IL.vt100 \
		  iw_IL.vt100-7-bit Iw_IL.IBM-856 Iw_IL.IBM-856@alt \
		  ar_AA.ibm3151 ar_AA.ibm3151@alt


.include <${RULES_MK}>
