# @(#)28	1.1  src/bos/usr/ccs/lib/libc_r/profiled/Makefile, libcthrd, bos411, 9428A410j 10/20/93 14:48:32
#
#   COMPONENT_NAME: LIBC
#
#   FUNCTIONS: none
#
#   ORIGINS: 27
#
#   IBM CONFIDENTIAL -- (IBM Confidential Restricted when
#   combined with the aggregated modules for this product)
#                    SOURCE MATERIALS
#
#   (C) COPYRIGHT International Business Machines Corp. 1993
#   All Rights Reserved
#   US Government Users Restricted Rights - Use, duplication or
#   disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#

PROFILED=yes

.include "${MAKETOP}/bos/usr/ccs/lib/libc_r/Makefile"
