# @(#)61	1.2  src/bos/diag/tu/niopp/Makefile, tu_niopp, bos411, 9428A410j 4/7/93 14:27:01
#
#   COMPONENT_NAME: TU_NIOPP
#
#   FUNCTIONS: 
#
#   ORIGINS: 27
#
#   IBM CONFIDENTIAL -- (IBM Confidential Restricted when
#   combined with the aggregated modules for this product)
#                    SOURCE MATERIALS
#
#   (C) COPYRIGHT International Business Machines Corp. 1992, 1993.
#   All Rights Reserved
#   US Government Users Restricted Rights - Use, duplication or
#   disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#


OBJECTS		= 	niopptu.o

LIBS		= -lc

.include <${RULES_MK}>
