# @(#)97	1.2  src/bldenv/meth/Makefile, cfgnls, bos41B, 9504A 12/16/94 16:51:12
#
#   COMPONENT_NAME: CFGNLS
#
#   FUNCTIONS:
#
#   ORIGINS: 27
#
#   IBM CONFIDENTIAL -- (IBM Confidential Restricted when
#   combined with the aggregated modules for this product)
#                    SOURCE MATERIALS
#
#   (C) COPYRIGHT International Business Machines Corp. 1994
#   All Rights Reserved
#   US Government Users Restricted Rights - Use, duplication or
#   disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#

SUBDIRS		= ko_KR zh_CN ZH_CN zh_TW Unicode

.include <${RULES_MK}>

