#
# dependents of dd_nep.o:
dd_nep.o: ${MAKETOP}../export/power/usr/include/stdio.h
dd_nep.o: ${MAKETOP}../export/power/usr/include/standards.h
dd_nep.o: ${MAKETOP}../export/power/usr/include/va_list.h
dd_nep.o: ${MAKETOP}../export/power/usr/include/sys/types.h
dd_nep.o: ${MAKETOP}../export/power/usr/include/sys/m_types.h
dd_nep.o: ${MAKETOP}../export/power/usr/include/sys/limits.h
dd_nep.o: ${MAKETOP}../export/power/usr/include/float.h
dd_nep.o: ${MAKETOP}../export/power/usr/include/fcntl.h
dd_nep.o: ${MAKETOP}../export/power/usr/include/sys/flock.h
dd_nep.o: ${MAKETOP}../export/power/usr/include/unistd.h
dd_nep.o: ${MAKETOP}../export/power/usr/include/sys/access.h
dd_nep.o: ${MAKETOP}../export/power/usr/include/sys/lockf.h
dd_nep.o: ${MAKETOP}../export/power/usr/include/sys/stat.h
dd_nep.o: ${MAKETOP}../export/power/usr/include/sys/mode.h
dd_nep.o: ${MAKETOP}../export/power/usr/include/sys/rcm_win.h
dd_nep.o: ${MAKETOP}../export/power/usr/include/sys/aixgsc.h
dd_nep.o: ${MAKETOP}../export/power/usr/include/sys/rcmioctl.h
dd_nep.o: ${MAKETOP}../export/power/usr/include/mid/mid.h
dd_nep.o: ${MAKETOP}../export/power/usr/include/sys/sysconfig.h
dd_nep.o: ${MAKETOP}../export/power/usr/include/sys/lockl.h
dd_nep.o: ${MAKETOP}../export/power/usr/include/sys/lock_def.h
dd_nep.o: ${MAKETOP}../export/power/usr/include/sys/device.h
dd_nep.o: ${MAKETOP}../export/power/usr/include/sys/file.h
dd_nep.o: ${MAKETOP}../export/power/usr/include/sys/param.h
dd_nep.o: ${MAKETOP}../export/power/usr/include/sys/m_param.h
dd_nep.o: ${MAKETOP}../export/power/usr/include/jfs/fsparam.h
dd_nep.o: ${MAKETOP}../export/power/usr/include/sys/sysmacros.h
dd_nep.o: ${MAKETOP}../export/power/usr/include/sys/cred.h
dd_nep.o: ${MAKETOP}../export/power/usr/include/sys/priv.h
dd_nep.o: ${MAKETOP}../export/power/usr/include/sys/tcb.h
dd_nep.o: ${MAKETOP}../export/power/usr/include/sys/pcl.h
dd_nep.o: ${MAKETOP}../export/power/usr/include/sys/intr.h
dd_nep.o: ${MAKETOP}../export/power/usr/include/sys/m_intr.h
dd_nep.o: ${MAKETOP}../export/power/usr/include/sys/low.h
dd_nep.o: ${MAKETOP}../export/power/usr/include/sys/syspest.h
dd_nep.o: ${MAKETOP}../export/power/usr/include/errno.h
dd_nep.o: ${MAKETOP}../export/power/usr/include/sys/errno.h
dd_nep.o: ${MAKETOP}../export/power/usr/include/sys/cfgodm.h
dd_nep.o: ${MAKETOP}../export/power/usr/include/odmi.h
dd_nep.o: ${MAKETOP}../export/power/usr/include/sys/dir.h
dd_nep.o: ${MAKETOP}../export/power/usr/include/sys/lkup.h
dd_nep.o: ${MAKETOP}../export/power/usr/include/limits.h
dd_nep.o: ${MAKETOP}../export/power/usr/include/cf.h
dd_nep.o: ${MAKETOP}../export/power/usr/include/sys/mdio.h
dd_nep.o: ${MAKETOP}../export/power/usr/include/signal.h
dd_nep.o: ${MAKETOP}../export/power/usr/include/sys/signal.h
dd_nep.o: ${MAKETOP}../export/power/usr/include/sys/context.h
dd_nep.o: ${MAKETOP}../export/power/usr/include/sys/mstsave.h
dd_nep.o: ${MAKETOP}bos/diag/tu/nep/nep_tu.h
dd_nep.o: ${MAKETOP}bos/diag/tu/nep/nepdef.h
dd_nep.o: ${MAKETOP}neptune/nepdd/kernext/nep/inc/nepddf.h
dd_nep.o: ${MAKETOP}neptune/nepdd/kernext/nep/inc/nepstruct.h
dd_nep.o: ${MAKETOP}../export/power/usr/include/sys/xmem.h
dd_nep.o: ${MAKETOP}neptune/nepdd/kernext/nep/inc/nepRmm.h
dd_nep.o: ${MAKETOP}bos/diag/tu/nep/nep_tu_type.h
#
# dependents of exectu.o:
exectu.o: ${MAKETOP}../export/power/usr/include/stdio.h
exectu.o: ${MAKETOP}../export/power/usr/include/standards.h
exectu.o: ${MAKETOP}../export/power/usr/include/va_list.h
exectu.o: ${MAKETOP}../export/power/usr/include/sys/types.h
exectu.o: ${MAKETOP}../export/power/usr/include/sys/m_types.h
exectu.o: ${MAKETOP}../export/power/usr/include/sys/limits.h
exectu.o: ${MAKETOP}../export/power/usr/include/float.h
exectu.o: ${MAKETOP}../export/power/usr/include/signal.h
exectu.o: ${MAKETOP}../export/power/usr/include/sys/signal.h
exectu.o: ${MAKETOP}../export/power/usr/include/sys/context.h
exectu.o: ${MAKETOP}../export/power/usr/include/sys/m_param.h
exectu.o: ${MAKETOP}../export/power/usr/include/sys/mstsave.h
exectu.o: ${MAKETOP}../export/power/usr/include/fcntl.h
exectu.o: ${MAKETOP}../export/power/usr/include/sys/flock.h
exectu.o: ${MAKETOP}../export/power/usr/include/unistd.h
exectu.o: ${MAKETOP}../export/power/usr/include/sys/access.h
exectu.o: ${MAKETOP}../export/power/usr/include/sys/lockf.h
exectu.o: ${MAKETOP}../export/power/usr/include/sys/stat.h
exectu.o: ${MAKETOP}../export/power/usr/include/sys/mode.h
exectu.o: ${MAKETOP}../export/power/usr/include/cf.h
exectu.o: ${MAKETOP}bos/diag/tu/nep/nep_tu_type.h
