# @(#)58	1.2  src/bos/usr/ccs/lib/libnetsvc_r/Makefile, libcnet, bos411, 9428A410j 11/30/93 14:26:35
#
#   COMPONENT_NAME: libcnet
#
#   FUNCTIONS: none
#
#   ORIGINS: 27
#
#
#   (C) COPYRIGHT International Business Machines Corp. 1993
#   All Rights Reserved
#   Licensed Materials - Property of IBM
#   US Government Users Restricted Rights - Use, duplication or
#   disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#

THREAD_SAFE=yes

.include "${MAKETOP}/bos/usr/ccs/lib/libnetsvc/Makefile"

