# @(#)51	1.5  src/bos/usr/lib/netls/conf/Makefile, libnetls, bos411, 9428A410j 5/27/94 10:08:58
# COMPONENT_NAME:  libnetls
#
# FUNCTIONS:
#
# ORIGINS: 27
#
# IBM CONFIDENTIAL -- (IBM Confidential Restricted when
# combined with the aggregated modules for this product)
#                  SOURCE MATERIALS
#   (C) COPYRIGHT International Business Machines Corp. 1994
# All Rights Reserved
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#

IDIR		= /usr/lib/netls/conf/
ILIST		= rc.netls netls_config auto_config

rc.netls_IDIR	= /etc/
 

.include <${RULES_MK}>

