# @(#)64        1.21  src/bos/usr/lpp/Makefile, Makefiles, bos41B, 9504A 12/20/94 10:28:03
#
# COMPONENT_NAME:  BOSBUILD
#
# FUNCTIONS:
#
# ORIGINS: 27, 83
#
# IBM CONFIDENTIAL -- (IBM Confidential Restricted when
# combined with the aggregated modules for this product)
#                  SOURCE MATERIALS
# (C) COPYRIGHT International Business Machines Corp. 1988, 1994
# All Rights Reserved
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#

SUBDIRS         = bos bosinst fonts kls tls jls cnls zhls Unicode \
		  blkmux perfagent

EXPINC_SUBDIRS  = bosinst

EXPLIB_SUBDIRS	= Unicode

.include <${RULES_MK}>




