# @(#)57    1.3  src/bos/kernext/disp/trace/Makefile, sysxdisp, bos411, 9428A410j  10/12/93  14:27:59

# COMPONENT_NAME: (sysxdisp) Display Sub-System
#
# FUNCTIONS:
#
# ORIGINS: 27
#
# IBM CONFIDENTIAL -- (IBM Confidential Restricted when
# combined with the aggregated modules for this product)
# (C) COPYRIGHT International Business Machines Corp. 1993
# All Rights Reserved
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#
#

.include <${MAKETOP}/bos/kernext/Kernext.mk>

EXPDIR		= /kernel/include/graphics/
gs_io_trcfmt.s_EXPDIR = /kernel/include/graphics/trace/

INCLUDES     	= gs_trace.h 		\
		  gshkid.h 		\
		  gs_io_trace.h		\
		  gs_io_trcfmt.s

.include <${RULES_MK}>
