# @(#)00	1.2  src/bos/kernext/dlc/trace/Makefile, sysxdlcg, bos411, 9428A410j 2/25/93 15:53:12
# COMPONENT_NAME: SYSXDLCG   trace facility
#
# FUNCTIONS: Makefile to ship trace format files
#
# ORIGINS: 27
#
# IBM CONFIDENTIAL -- (IBM Confidential Restricted when
# combined with the aggregated modules for this product)
#                  SOURCE MATERIALS
# (C) COPYRIGHT International Business Machines Corp. 1993
# All Rights Reserved
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.

#.include <${MAKETOP}bos/kernext/Kernext.mk>

VPATH = ${TARGET_MACHINE}

IDIR = /usr/lpp/bos.dlc/com/

DATAFILES = dlcfmt.trc

ILIST =  ${DATAFILES}

IMODE = 644

.include <${RULES_MK}>
