# @(#)65        1.10  src/bos/usr/lpp/bosinst/Makefile, bosinst, bos41J, 9514A_all 4/5/95 09:16:42
# COMPONENT_NAME:  bosinst
#
# FUNCTIONS: Makefile for all bosinst directories
#
# ORIGINS: 27
#
# IBM CONFIDENTIAL -- (IBM Confidential Restricted when
# combined with the aggregated modules for this product)
#                  SOURCE MATERIALS
# (C) COPYRIGHT International Business Machines Corp. 1993, 1995
# All Rights Reserved
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#

SUBDIRS		= Animate \
			BosMenus \
			Get_RVG_Disks \
			berror \
			bi_main \
			adjfs \
			bicfgsup \
			blvset \
			bosinst.template \
			image.template \
			preserve.list \
			printers \
			rda \
			bi_io \
			tape \
			bin \
			db \
			ninst \
			scripts \
			turbocr \
			cdeject

EXPINC_SUBDIRS	= BosMenus

.include <${RULES_MK}>
