# @(#)08	1.1  src/bos/usr/lib/piosCN/predef/Makefile, ils-zh_CN, bos41J, 9507B 1/26/95 09:56:55
#
#   COMPONENT_NAME: ils-zh_CN
#
#   FUNCTIONS: none
#
#   ORIGINS: 27
#
#   IBM CONFIDENTIAL -- (IBM Confidential Restricted when
#   combined with the aggregated modules for this product)
#                    SOURCE MATERIALS
#
#   (C) COPYRIGHT International Business Machines Corp. 1995
#   All Rights Reserved
#   US Government Users Restricted Rights - Use, duplication or
#   disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#

ILIST = \
	ar2463.ehsc \
	ar2463.essc \
	laserjet2.UTF-8 \
	laserjet2.essc \
	lq1600k.UTF-8 \
	lq1600k.ehsc \
	lq1600k.essc

IDIR = /usr/lib/lpd/pio/predef/

.include <${RULES_MK}>
