# @(#)03	1.2  src/bos/usr/lib/methods/startlft/Makefile, lftdd, bos411, 9428A410j 11/22/93 12:16:52
# COMPONENT_NAME:
#
# FUNCTIONS:
#
# ORIGINS: 27
#
# IBM CONFIDENTIAL -- (IBM Confidential Restricted when
# combined with the aggregated modules for this product)
#                  SOURCE MATERIALS
# (C) COPYRIGHT International Business Machines Corp. 1988, 1993
# All Rights Reserved
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#

VPATH       = ../common

PROGRAMS	= startlft

OFILES      = startlft.o cfg_lfterr.o

INCFLAGS    = -I../common 

ILIST		= startlft
IDIR		= /usr/lib/methods/

LIBS		= -ls -lodm -lcfg -lrts

.include <${RULES_MK}>
