# @(#)51	1.2  src/bos/diag/tu/sdisk/Makefile, tu_sdisk, bos411, 9428A410j 4/5/93 09:27:23
#
#   COMPONENT_NAME: TU_SDISK
#
#   FUNCTIONS: 
#
#   ORIGINS: 27
#
#   IBM CONFIDENTIAL -- (IBM Confidential Restricted when
#   combined with the aggregated modules for this product)
#                    SOURCE MATERIALS
#
#   (C) COPYRIGHT International Business Machines Corp. 1992, 1993.
#   All Rights Reserved
#   US Government Users Restricted Rights - Use, duplication or
#   disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#


OBJECTS		= har2_atu.o har2_mfg.o

CFLAGS		= -D DIAG
LIBS		= -lc

.include <${RULES_MK}>
