# @(#)43        1.8  src/bos/kernel/lib/Makefile, Makefiles, bos411, 9428A410j 12/9/93 11:59:26
#
# COMPONENT_NAME:  Makefiles
#
# FUNCTIONS:
#
# ORIGINS: 27
#
# IBM CONFIDENTIAL -- (IBM Confidential Restricted when
# combined with the aggregated modules for this product)
#                  SOURCE MATERIALS
# (C) COPYRIGHT International Business Machines Corp. 1988, 1993
# All Rights Reserved
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#


EXPLIB_SUBDIRS	= libcsys libsysp libsys

SUBDIRS		= libcsys libsys 

.include <${RULES_MK}>


