# @(#)15        1.2  src/bos/usr/lib/learn/macros/Makefile, cmdlearn, bos411, 9428A410j 1/15/93 13:13:08
# COMPONENT_NAME:
#
# FUNCTIONS:
#
# ORIGINS: 27
#
# IBM CONFIDENTIAL -- (IBM Confidential Restricted when
# combined with the aggregated modules for this product)
#                  SOURCE MATERIALS
# (C) COPYRIGHT International Business Machines Corp. 1988, 1989
# All Rights Reserved
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#

DATAFILES	= L0 L1.1a L10.1a L11.1a L12.1a L13.1a L14.1a \
		  L15.1a L2.1a L3.1a L4.1a L5.1a L6.1a L7.1a \
		  L8.1a L9.1a

ILIST		= ${DATAFILES}
IDIR		= /usr/share/lib/learn/macros/


.include <${RULES_MK}>
