# @(#)72        1.1  src/bos/usr/lpp/kls/Makefile, cmdkr, bos411, 9428A410j 1/13/93 15:27:34
#
# COMPONENT_NAME: CMDKR
#
# FUNCTIONS:
#
# ORIGINS: 27
#
# IBM CONFIDENTIAL -- (IBM Confidential Restricted when
# combined with the aggregated modules for this product)
#                  SOURCE MATERIALS
# (C) COPYRIGHT International Business Machines Corp. 1988, 1993
# All Rights Reserved
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#

SUBDIRS		= defaults dict dictutil fonts

.include <${RULES_MK}>
