# @(#)02        1.1  src/bos/usr/lbin/diff3prog/Makefile, cmdfiles, bos411, 9428A410j 8/5/92 16:55:47
# COMPONENT_NAME:
#
# FUNCTIONS:
#
# ORIGINS: 27
#
# IBM CONFIDENTIAL -- (IBM Confidential Restricted when
# combined with the aggregated modules for this product)
#                  SOURCE MATERIALS
# (C) COPYRIGHT International Business Machines Corp. 1988, 1989
# All Rights Reserved
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#

PROGRAMS	= diff3prog
MSGHDRS		= diff3_msg.h
CATFILES	= diff3.cat
HFILES		= ${MSGHDRS}

ILIST		= diff3prog
IDIR		= /usr/lbin/


.include <${RULES_MK}>
