# @(#)94	1.4  src/bos/kernext/disp/gem/com/Makefile, sysxdispgem, bos411, 9428A410j 4/29/94 13:57:47
#
#   COMPONENT_NAME: SYSXDISPGEM
#
#   FUNCTIONS: 
#
#   ORIGINS: 27
#
#   IBM CONFIDENTIAL -- (IBM Confidential Restricted when
#   combined with the aggregated modules for this product)
#                    SOURCE MATERIALS
#
#   (C) COPYRIGHT International Business Machines Corp. 1993
#   All Rights Reserved
#   US Government Users Restricted Rights - Use, duplication or
#   disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#


VPATH           =${MAKETOP}bos/kernext/inc/POWER

EXPDIR	      = /kernel/include/

DATAFILES     =	gmasl.h         \
 		gmcomm.h	\
		gmshr.h

INCLUDES      = ${DATAFILES} 

.include <${RULES_MK}>
