# @(#)51	1.4  src/bos/usr/lib/microcode/ruby/Makefile, rbyxucode, bos411, 9428A410j 4/28/94 15:42:13
#
#   COMPONENT_NAME: RBYXUCODE
#
#   FUNCTIONS: none
#
#   ORIGINS: 27
#
#   IBM CONFIDENTIAL -- (IBM Confidential Restricted when
#   combined with the aggregated modules for this product)
#                    SOURCE MATERIALS
#
#   (C) COPYRIGHT International Business Machines Corp. 1993
#   All Rights Reserved
#   US Government Users Restricted Rights - Use, duplication or
#   disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#
#############################  IMPORTANT  ######################################

ILIST		= 8fbcap.00.00 8fbccp.00.00 8fbchigp.00.00 8fbclogp.00.00   \
			  8fbcap1.00.00 8fbccp1.00.00 8fbchigp1.00.00 8fbclogp1.00.00

IDIR		= /usr/lib/microcode/


OTHERS=

OTHERS+=8fbcap.00.00
8fbcap.00.00:8fbcap.00.00.ibmstub
	-${RM} -f ${.TARGET}
	${CP} -f ${.ALLSRC} ${.TARGET}

OTHERS+=8fbccp.00.00
8fbccp.00.00:8fbccp.00.00.ibmstub
	-${RM} -f ${.TARGET}
	${CP} -f ${.ALLSRC} ${.TARGET}

OTHERS+=8fbchigp.00.00
8fbchigp.00.00:8fbchigp.00.00.ibmstub
	-${RM} -f ${.TARGET}
	${CP} -f ${.ALLSRC} ${.TARGET}

OTHERS+=8fbclogp.00.00
8fbclogp.00.00:8fbclogp.00.00.ibmstub
	-${RM} -f ${.TARGET}
	${CP} -f ${.ALLSRC} ${.TARGET}

OTHERS+=8fbcap1.00.00
8fbcap1.00.00:8fbcap1.00.00.ibmstub
	-${RM} -f ${.TARGET}
	${CP} -f ${.ALLSRC} ${.TARGET}

OTHERS+=8fbccp1.00.00
8fbccp1.00.00:8fbccp1.00.00.ibmstub
	-${RM} -f ${.TARGET}
	${CP} -f ${.ALLSRC} ${.TARGET}

OTHERS+=8fbchigp1.00.00
8fbchigp1.00.00:8fbchigp1.00.00.ibmstub
	-${RM} -f ${.TARGET}
	${CP} -f ${.ALLSRC} ${.TARGET}

OTHERS+=8fbclogp1.00.00
8fbclogp1.00.00:8fbclogp1.00.00.ibmstub
	-${RM} -f ${.TARGET}
	${CP} -f ${.ALLSRC} ${.TARGET}

.include <${RULES_MK}>

