# @(#)07        1.6  src/bos/usr/lib/pios/predef/Makefile, cmdpios, bos41J, 9512A_all 3/16/95 15:54:24
#
# COMPONENT_NAME: CMDPIOS
#
# FUNCTIONS:
#
# ORIGINS: 27, 83
#
# IBM CONFIDENTIAL -- (IBM Confidential Restricted when
# combined with the aggregated modules for this product)
#                  SOURCE MATERIALS
# (C) COPYRIGHT International Business Machines Corp. 1988, 1995
# All Rights Reserved
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#
# LEVEL 1, 5 Years Bull Confidential Information
#

DATAFILES	= \
	master \
	generic.asc generic.ps generic.gl generic.pcl \
	remote.remote \
	ibm2380.asc ibm2381.asc ibm2390.asc ibm2391.asc ibm3812-2.asc \
	ibm3816.asc ibm4019.asc ibm4019.gl ibm4019.pcl ibm4019.ps \
	ibm4029.asc ibm4029.gl ibm4029.pcl ibm4029.ps ibm4072.asc \
	ibm4201-2.asc ibm4201-3.asc ibm4202-2.asc ibm4202-3.asc \
	ibm4207-2.asc ibm4208-2.asc ibm4212.asc ibm4216-31.630 \
	ibm4216-31.asc ibm4216-31.pcl ibm4216-31.ps ibm4224.asc \
	ibm4226.asc ibm4234.asc ibm5202.asc ibm5204.asc ibm6180.gl \
	ibm6182.gl ibm6184.gl ibm6185-1.gl ibm6185-2.gl ibm6186.gl \
	ibm6252.asc ibm6262.asc ibm7372.gl ibm4079.gl ibm4070.asc \
	ibm4079.ps ibm2380-2.asc ibm2391-2.asc ibm2390-2.asc ibm2381-2.asc \
	ibm4037.asc ibm4037.pcl ibm4039.pcl ibm4039.ps ibm4076.asc \
	ibm4076.pcl ibm3112.pcl ibm3112.ps ibm3116.pcl ibm3116.ps \
	ibm3930.pcl ibm3930.ps ibm4230.asc ibm6408.asc ibm6412.asc \
	lex4039+.pcl lex4039+.ps lex4047.pcl lex4049.pcl lex4049.ps \
	lex4076-2c.col lex4076-2c.pcl lex4079+.gl lex4079+.ps \
	bullpr88.asc bull201.pcl bull411.pcl bull422.pcl bull422.ps \
	bull721.pcl bull1021.pcl bull1070.asc bull451.asc bull454.asc \
	bull922.asc bull923.asc bull924.asc bull924N.asc bull970.asc \
	1072 bull1015.gl2 bull1015.pcl bull1015.ps \
	bull1025.gl2 bull1025.pcl bull1025.ps bull1070.eps \
	bull1625.gl2 bull1625.ps bull1625.pcl bull200.pcl \
	bull413.gl2 bull413.pcl bull413.ps \
	bull451.eps bull454.eps bull815.gl2 bull815.pcl bull815.ps \
	bull825.gl2 bull825.pcl bull825.ps bull9142.asc bull9142.eps \
	bull9148.asc bull9148.eps bull922.eps bull923.eps \
	bull924.eps bull924N.eps bull956.asc bull956.eps \
	bull970.eps bullpr88-vfu.asc bullpr90.asc epson \
	hp-pcl5 hp-pgl2 mastervfu prvfu \
	hplj-2.pcl hplj-3.pcl hplj-3.ps hplj-3.gl hplj-3si.pcl hplj-3si.ps \
	hplj-3si.gl hplj-4.pcl hplj-4.ps hplj-4.gl hplj-4+.gl hplj-4+.pcl \
	hplj-4+.ps hplj-4si.gl hplj-4si.pcl hplj-4si.ps hplj-4v.gl \
	hplj-4v.pcl hplj-4v.ps hplj-c.gl hplj-c.pcl hplj-c.ps \
	qms100.gl qms100.ps \
	ti2115.630 ti2115.855 ti2115.gl ti2115.pcl ti2115.ps \
	dp2000.asc dp2665.630 dp2665.ps \
	p9012.asc


ILIST		= ${DATAFILES}
IDIR		= /usr/lib/lpd/pio/predef/


.include <${RULES_MK}>
