# @(#)89        1.1  src/bldenv/dirname/Makefile, ade_build, bos41J, 9509A_all 2/27/95 12:43:10
#
#   COMPONENT_NAME: BOSBUILD
#
#   FUNCTIONS:
#
#   ORIGINS: 27
#
#   IBM CONFIDENTIAL -- (IBM Confidential Restricted when
#   combined with the aggregated modules for this product)
#                    SOURCE MATERIALS
#
#   (C) COPYRIGHT International Business Machines Corp. 1993
#   All Rights Reserved
#   US Government Users Restricted Rights - Use, duplication or
#   disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#

VPATH		= ${MAKETOP}/bos/usr/bin/dirname

PROGRAMS	= dirname
MSGHDRS		= dirname_msg.h
CATFILES	= dirname.cat
HFILES		= ${MSGHDRS}

ILIST		= dirname
IDIR		= /usr/bin/


.include <${RULES_MK}>
