# @(#)23        1.3  src/bos/usr/ccs/lib/libg/Makefile, libg, bos411, 9428A410j 1/18/93 09:47:42
# COMPONENT_NAME:
#
# FUNCTIONS:
#
# ORIGINS: 27
#
# IBM CONFIDENTIAL -- (IBM Confidential Restricted when
# combined with the aggregated modules for this product)
#                  SOURCE MATERIALS
# (C) COPYRIGHT International Business Machines Corp. 1988, 1989
# All Rights Reserved
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#

VPATH		= ${TARGET_MACHINE}

LIBRARIES	= libg.a
MSGHDRS         =
CATFILES        =
HFILES          = ${MSGHDRS}

EXPLIB_TARGETS  = export_libg.a

ILIST           = libg.a libg.exp
IDIR            = /usr/lib/

OFILES		= dbxxx.o

.include <${RULES_MK}>
