# @(#)81	1.6  src/bos/usr/lib/netls/Makefile, libnetls, bos411, 9428A410j 4/15/94 17:15:53
# COMPONENT_NAME:  libnetls
#
# FUNCTIONS:
#
# ORIGINS: 27
#
# IBM CONFIDENTIAL -- (IBM Confidential Restricted when
# combined with the aggregated modules for this product)
#                  SOURCE MATERIALS
# (C) COPYRIGHT International Business Machines Corp. 1988, 1992
# All Rights Reserved
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#

SUBDIRS		= ark adk conf common
EXPINC_SUBDIRS	= adk common
EXPLIB_SUBDIRS	= adk
.include <${RULES_MK}>
