# @(#)95        1.1  src/bos/usr/lib/nls/loc/jim/jmnt/Makefile, libKJI, bos411, 9428A410j 1/20/93 10:58:59
#
# COMPONENT_NAME: libKJI
#
# FUNCTIONS: Japanese Input Method
#
# ORIGINS: 27
#
# IBM CONFIDENTIAL -- (IBM Confidential Restricted when
# combined with the aggregated modules for this product)
#                  SOURCE MATERIALS
# (C) COPYRIGHT International Business Machines Corp. 1989, 1991, 1993
# All Rights Reserved
# Licensed Materials - Property of IBM
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#

LIBRARIES	= libjmnt.a

CFLAGS		= -DNDEBUG -D_NO_PROTO -D_NONSTD_TYPES
DEBUG		=

OFILES		= _Jclos.o \
			_Jclr.o \
			_Jcrst.o \
			_Jinit.o \
			_Jinpr.o \
			_Jopen.o \
			_Jshrs.o \
			_Jterm.o \
			_Jtrak.o \
			_MCN_rs.o \
			_MC_rtn.o \
			_MD_rtn.o \
			_ME_01.o \
			_ME_02.o \
			_ME_03.o \
			_ME_04.o \
			_ME_05.o \
			_ME_06.o \
			_ME_07.o \
			_ME_09.o \
			_ME_0a.o \
			_ME_0b.o \
			_ME_0c.o \
			_ME_0d.o \
			_ME_0e.o \
			_ME_rtn.o \
			_MKL_rs.o \
			_MK_a2.o \
			_MK_b4a.o \
			_MK_b4b.o \
			_MK_c1.o \
			_MK_c1f.o \
			_MK_c3.o \
			_MK_e3.o \
			_MK_e4.o \
			_MK_rtn.o \
			_MMSG_rs.o \
			_MM_09.o \
			_MM_rtn.o \
			_MRG_a.o \
			_MRG_b.o \
			_MRM_rs.o \
			_MR_rtn.o \
			_MS_rtn.o \
			_Macaxst.o \
			_Macifst.o \
			_Maddch.o \
			_Mansave.o \
			_Maxcrmv.o \
			_Maxmst.o \
			_Mbsins.o \
			_Mbsrepn.o \
			_Mbsrepr.o \
			_Mckbk.o \
			_Mcrmv.o \
			_Mdagend.o \
			_Mdagmsg.o \
			_Mdagst.o \
			_Mdaha.o \
			_Mdelins.o \
			_Mdelrep.o \
			_Mdisv.o \
			_Mecho.o \
			_Mexchng.o \
			_Mflycnv.o \
			_Mflypro.o \
			_Mflyrst.o \
			_Mfmrst.o \
			_Mgetchm.o \
			_Mhrktsw.o \
			_Mhtdc.o \
			_Midecid.o \
			_Mifmst.o \
			_Mindset.o \
			_Minsch.o \
			_Minssv.o \
			_Mkanagt.o \
			_Mkanasd.o \
			_Mkcflcn.o \
			_Mkcnxpr.o \
			_Mkjgrst.o \
			_Mkkcclr.o \
			_Mktec.o \
			_Mktnc.o \
			_Mlfrtc.o \
			_Mlock.o \
			_Mmvch.o \
			_Mnumgt.o \
			_Mnxprps.o \
			_Mnxtopn.o \
			_Mnxtpre.o \
			_Mregrs.o \
			_Mrepch.o \
			_Mreset.o \
			_Mrscvym.o \
			_Mrsstrh.o \
			_Mrstym.o \
			_Msetch.o \
			_Msglbw.o \
			_Msglfw.o \
			_Msglop.o \
			_Mstlcvl.o \
			_Mstrl.o \
			_Mymstl.o \
			_Myomic.o \
			_Rkc.o \
			_Traced.o \
			_Tracef.o \
			_Tracep.o \
			_toJIS83.o \
			HostCode.o

.include <${RULES_MK}>
