# @(#)32 1.2 src/bos/usr/lib/pios/bidi/fonts/970/Makefile, cmdpios, bos41B, 412_41B_sync 1/6/95 14:26:23
#
# COMPONENT_NAME: (CMDPIOS) Printer Backend
#
# FUNCTIONS: For ge0300.dll fonts
#
# ORIGINS: 83
#
# LEVEL 1, 5 Years Bull Confidential Information
#

DATAFILES   = ge0300.dll

ILIST       = ${DATAFILES}
IDIR        = /usr/lib/lpd/pio/fonts/bull970/

.include <${RULES_MK}>
