# @(#)31        1.1  src/bos/usr/lpp/bosinst/adjfs/Makefile, bosinst, bos411, 9433B411a 8/8/94 15:45:25
# COMPONENT_NAME:
#
# FUNCTIONS:
#
# ORIGINS: 27
#
# IBM CONFIDENTIAL -- (IBM Confidential Restricted when
# combined with the aggregated modules for this product)
#                  SOURCE MATERIALS
# (C) COPYRIGHT International Business Machines Corp. 1988, 1989
# All Rights Reserved
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#

PROGRAMS	= adjfs

OFILES		= adjfs.o 

#LIBS		= -lodm -lcfg

ILIST		= adjfs
IDIR		= /usr/lpp/bosinst/

.include <${RULES_MK}>
