# @(#)91        1.2  src/bos/usr/ccs/lib/libl/Makefile, libl, bos411, 9428A410j 1/19/93 16:41:50
# COMPONENT_NAME:
#
# FUNCTIONS:
#
# ORIGINS: 27
#
# IBM CONFIDENTIAL -- (IBM Confidential Restricted when
# combined with the aggregated modules for this product)
#                  SOURCE MATERIALS
# (C) COPYRIGHT International Business Machines Corp. 1988, 1989
# All Rights Reserved
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#

LIBRARIES	= libl.a

EXPLIB_TARGETS	= export_libl.a

ILIST		= libl.a ncform
IDIR		= /usr/ccs/lib/
ncform_IDIR	= /usr/ccs/lib/lex/

OFILES = \
	allprint.o main.o reject.o yyless.o \
	yywrap.o callprint.o

.include <${RULES_MK}>
