# @(#)26	1.3  src/bos/usr/lpp/blkmux/test/Makefile, sysxcat, bos411, 9428A410j 1/20/94 08:50:13
#
#   COMPONENT_NAME: 370PCA_DD
#
#   FUNCTIONS: none
#
#   ORIGINS: 27
#
#
#   (C) COPYRIGHT International Business Machines Corp. 1993
#   All Rights Reserved
#   Licensed Materials - Property of IBM
#   US Government Users Restricted Rights - Use, duplication or
#   disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#

VPATH		= ${TARGET_MACHINE}


ILIST		= catcsx 

IDIR 		= /usr/lpp/blkmux/test/

PROGRAMS	= catcsx

.include <${RULES_MK}>
