# @(#)24        1.1  src/bos/usr/bin/test/Makefile, cmdsh, bos410, aix4.34 8/5/92 16:36:47
# COMPONENT_NAME:
#
# FUNCTIONS:
#
# ORIGINS: 27
#
# IBM CONFIDENTIAL -- (IBM Confidential Restricted when
# combined with the aggregated modules for this product)
#                  SOURCE MATERIALS
# (C) COPYRIGHT International Business Machines Corp. 1988, 1989
# All Rights Reserved
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#

VPATH		= ${MAKETOP}/bos/usr/bin/test

PROGRAMS	= test
MSGHDRS		= test_msg.h
CATFILES	= test.cat
HFILES		= ${MSGHDRS}

ILIST		= test
IDIR		= /bin/


.include <${RULES_MK}>
