# @(#)45	1.1  src/bldenv/gos/desktop/dthelp/parser/pass1/Makefile, desktop, bos412, GOLDA411a 4/14/94 17:37:03
#
#   COMPONENT_NAME: ade_build
#
#   FUNCTIONS: none
#
#   ORIGINS: 27
#
#
#   (C) COPYRIGHT International Business Machines Corp. 1993
#   All Rights Reserved
#   Licensed Materials - Property of IBM
#   US Government Users Restricted Rights - Use, duplication or
#   disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#

EXPLIB_SUBDIRS	= util 

SUBDIRS		= util build eltdef parser

.include <${RULES_MK}>
