#
# @(#)52  1.1  src/bos/usr/lib/methods/cfgfan/Makefile, cfgmethods, bos41B, 412_41B_sync 1/11/95 07:51:24
#
# COMPONENT_NAME: CFGMETHODS
#
# FUNCTIONS: none
#
# ORIGINS: 27, 83
#
# IBM CONFIDENTIAL -- (IBM Confidential Restricted when
# combined with the aggregated modules for this product)
#                  SOURCE MATERIALS
# (C) COPYRIGHT International Business Machines Corp. 1995
# All Rights Reserved
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#
# LEVEL 1,  5 Years Bull Confidential Information
#

PROGRAMS	= cfgfan

OFILES		= cfgfan.o

ILIST		= cfgfan
IDIR		= /usr/lib/methods/

LIBS		= -lodm -lcfg

.include <${RULES_MK}>
