# @(#)31        1.3  src/bos/usr/include/graphics/trace/Makefile, sysxdisp, bos411, 9428A410j 4/22/94 13:29:58
#
# COMPONENT_NAME: (sysxdisp) Display Sub-System
#
# FUNCTIONS:
#
# ORIGINS: 27
#
# IBM CONFIDENTIAL -- (IBM Confidential Restricted when
# combined with the aggregated modules for this product)
# (C) COPYRIGHT International Business Machines Corp. 1994
# All Rights Reserved
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#
#

VPATH 		=${MAKETOP}bos/kernext/disp/trace

EXPDIR		= /usr/include/graphics/
gs_io_trcfmt.s_EXPDIR = /usr/include/graphics/trace/

DATAFILES     =	gs_trace.h gshkid.h gs_io_trace.h gs_io_trcfmt.s

INCLUDES	= ${DATAFILES} 

IDIR            = /usr/include/graphics/
ILIST           = gshkid.h

.include <${RULES_MK}>
