# @(#)90	1.1  src/bos/usr/lib/rcm/Makefile, Makefiles, bos411, 9428A410j 6/3/94 14:35:49
# COMPONENT_NAME:
#
# FUNCTIONS:
#
# ORIGINS: 27
#
# IBM CONFIDENTIAL -- (IBM Confidential Restricted when
# combined with the aggregated modules for this product)
#                  SOURCE MATERIALS
# (C) COPYRIGHT International Business Machines Corp. 1994
# All Rights Reserved
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#

VPATH		= ${MAKETOP}/bos/kernext/exp

INCLUDES	= rcm.exp
EXPDIR		= /usr/lib/

ILIST		= rcm.exp
IDIR		= /usr/lib/

.include <${RULES_MK}>
