# @(#)91	1.3  src/bos/usr/lib/pioskr/msg/Makefile, cmdpioskr, bos411, 9428A410j 4/15/93 17:48:58
#
#   COMPONENT_NAME: CMDPIOSKR
#
#   FUNCTIONS: 
#
#   ORIGINS: 27
#
#   IBM CONFIDENTIAL -- (IBM Confidential Restricted when
#   combined with the aggregated modules for this product)
#                    SOURCE MATERIALS
#
#   (C) COPYRIGHT International Business Machines Corp. 1993
#   All Rights Reserved
#   US Government Users Restricted Rights - Use, duplication or
#   disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#

MSGHDRS = kfmtrs_msg.h pioattr3_msg.h
CATFILES = kfmtrs.cat pioattr3.cat
HFILES = ${MSGHDRS}
OTHERS = ${CATFILES} ${HFILES}

INCLUDES = kfmtrs_msg.h
EXPDIR = /usr/include/

IDIR = /usr/lib/lpd/pio/etc/
ILIST = pioattr3.cat

.include <${RULES_MK}>
