$ @(#)94	1.3  src/bos/usr/lib/pioskr/msg/pioattr3.msg, cmdpioskr, bos411, 9428A410j 8/30/93 15:34:35
$
$   COMPONENT_NAME: CMDPIOSKR
$
$   FUNCTIONS: NONE
$
$   ORIGINS: 27
$
$   IBM CONFIDENTIAL -- (IBM Confidential Restricted when
$   combined with the aggregated modules for this product)
$                    SOURCE MATERIALS
$
$   (C) COPYRIGHT International Business Machines Corp. 1989, 1993
$   All Rights Reserved
$   US Government Users Restricted Rights - Use, duplication or
$   disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
$
$
$       Descriptions Of Printer Backend Data Base Attributes
$
$
$ Translation Note :
$  This message file is used by Japanese printer backends.
$  This file need not be translated to exept Japanese.
$
$
$set 1
1 Command Line Flags Prohibited For Input Data Str "a"; Ignored: cmnorCDMPRT
2 Command Line Flags prohibited For Input Data Str "k"; Ignored: cmnorCMDPRT
3 (not used)
4 (not used)
5 (not used)
6 (not used)
7 (not used)
8 (not used)
9 (not used)
10 (not used)
11 (not used)
12 (not used)
13 stderr returned ? 0: no; 1: yes, & pipelines; 2: yes & values, pipelines
14 stderr returned? 0: no;  1: yes, & pipelines;  2: yes, & values, pipelines
15 Reserved For Spooler (burst pages)
16 Reserved For Spooler (mail messages instead of displaying them)
17 Reserved for Spooler (mail message instead of displaying them)
18 Deliver Printed Output to Specified User Instead of to Submitter
19 Double-High Print (!: no; +: yes) 
20 Double-High Print (!: no; +: yes) 
21 Double-High Print. (!: no;  +: yes)
22 (not used) Font file name
23 Use-defined Font File Name              
24 (reserved for future use)
25 Name To Replace Host Name On Burst Page
26 Name To Replace Host Name On Burst Page   
27 (not used) Font ID
28 (not used) Font ID (overrides pitch and type style)
29 Restore the Printer at the End of the Print Job ?
30 Restore the Printer at the End of the Print Job? (!: no;  +: yes)
31 Condensed Print (!: no;  +: yes)
32 Condensed Print (!: no; +: yes)
33 Wrap Long Lines (!: no;  +: yes)
34 Wrap Long Lines (!: no; +: yes)
35 Reserved For Spooler (message to operator from file)
36 Reserved For Spooler (message to operator from file) 
37 Reserved For Spooler (number of copies)
38 (not used) Type of Input Paper Handling (1: manual, 2: pinwheel, 3: sheetfeed)
39 (not used) Type of Input Paper Handling (manual, pinwheel, sheetfeed)
40 Type of Input Paper Handling (1: manual, 2: pinwheel, 3: sheetfeed)
41 Reserved For Spooler (queue name & opt. virtual printer (queue dev.) name)
42 Reserved For Spooler (queue name & opt. virtual printer (queue dev.) name)
43 (reserved for future use)
44 Reserved For Spooler (print job priority)
45 (not used) High Speed Print (!: no; +: yes)
46 (not used) High speed printing
47 High Speed Print (!: no; +: yes)
48 Reserved For Spooler (title for header page & queue status)
49 (not used) Unidirectional Printing (!: no; +: yes)
50 (not used) Unidirectional printing
51 Unidirectional Printing (!: no; +: yes)
52 (not used) Vertical printing
53 Vertical Printing (!: no; +: yes)
54 Double-Wide Print (!: no;  +: yes)
55 Double-Wide Print (!; no; +: yes)
56 (not used) Code Page Name For Print Data Stream (file with same name in dir."dl")
57 Code Page Name For Print Data Stream (file with same name in dir. "d1")
58 (not used) Duplex Output
59 Issue Form Feed Between Copies & At Job End (!: no;  +: yes)
60 Issue Form Feeds Between Copies & At Job End (!: no; +: yes)
61 COMMAND AGGREGATES
62 CONTROL CODES (ASCII)
63 DIRECTORIES
64 ESCAPE SEQUENCES
65 COMMAND STRINGS FOR FILTER FLAGS (2 char, 1st="f", 2nd=flag)
66 COMMAND STRINGS FOR FILTER FLAGS (2 char, 1st="f",2nd=flag)
67 VALUES THAT MAY BE OVERRIDDEN WITH FLAGS ON THE COMMAND LINE
68 PIPELINES FOR INPUT DATA STREAMS (2 char, 1st="i", 2nd=data stream name)
69 PIPELINES FOR INPUT DATA STREAMS (2 char, 1st="i",2nd=data stream name)
70 MISCELLANEOUS
71 FLAGS PROHIBITED FOR INPUT DATA STREAMS (2 char, 1st="I", 2nd=data stream name)
72 FLAGS PROHIBITED FOR INPUT DATA STREAMS (2 char,1st="I",2nd=data str name)
73 OTHER VALUES OF INTEREST TO THE SYSTEM ADMINISTRATOR
74 TRANSLATE TABLES
75 WORK VARIABLES
76 0: Normal Print;  1: Return Flag Values & Pipeline, But Don't Print
77 0: Normal Print; 1: Return Flag Values & pipeline, But Don't Print
78 Bottom Margin (number of blank lines); Sometimes Called Skip Perf.
79 Bottom Margin (number of blank lines); Sometimes Called Skip Perf.
80 Reserved For Spooler (copy file and print from copy)
81 Input Data Stream Type
82 Emphasized Print
83 Emphasized Print (!: no;  +: yes)
84 (not used) Single-Character BSD-type Filter Name (e.g.,"p" for "pr" filter)
85 Single-Character BSD-type Filter Name (e.g., "p" for "pr" filter)
86 Page Number Where Printing Should Begin
87 (not used) Title Used For "pr" Filter When "-f p" Is Specified (not used) 
88 Title Used For "pr" Filter When "-f p" Is Specified
89 Indent Value (character)
90 Indent Value (characters)
91 Initialize the printer (for each print file)? (!:no; +:yes)
92 Initialize the printer (for each print file)? (!: no;  +: yes)
93 (not used) Print Color
94 Page Length (lines; 0 means ignore page length)
95 Reserved For Spooler (msg to operator using cmd line text)
96 Reserved For Spooler (notify submitter (if -D, that user, too) when done)
97 Reserved For Spooler (protects backend flags passed to "enq" cmd)
98 Pitch (characters per inch)
99 (not used) Print Quality (1: draft; 2: letter)
100 Print Quality (1: draft;  2: letter)
101 Reserved For Spooler (remove print file when done)
102 Reserved for Spooler (remove print file when done)
103 (not used) Type Style (name)
104 Type Style (m10, m12, courier, elite, gothic)
105 Top Margin (number of blank lines)
106 (not used) Paper Source Drawer
107 (not used) Paper Source Drawer (1: Upper  2: Lower)
108 Paper Source Drawer (1: Upper  2: Lower)
109 Line Density (lines per inch)   
110 Line Density (lines per inch) examples: 6, 8
111 Page Width (characters)
112 0: CR->CR, LF->LF, VT->VT;  1: CR->CRLF  2: LF->CRLF, VT->CRVT;
113 (not used) Double-Strike Print (!: no;  +: yes)
114 (not used) Double-Strike Print (!: no; +: yes)
115 Double-Strike Print (!: no;  +: yes)
116 Double-Strike Print (!: no; +: yes)
117 (not used) Rotate Page Printer Output 
118 (not used) Rotate Page Printer Output (# quarter turns clockwise: 0-3)
119 Rotate Page Printer Output 
120 ASCII Control Code to Backspace One Character
121 ASCII Control Code to Return to the Left Margin (CR without LF)
122 ASCII Control Code to Cancel Double-Wide Printing by Line
123 ASCII Control Code to Disable the Printer (Device Control 3)                
124 ASCII Control Code to Enable the Printer (Device Control 1) 
125 ASCII Control Code to Advance the Paper to Top of Next Page (FF)
126 (not used; handled by formatter) Horizontal Tab
127 ASCII Control Code to Shift In (i.e., start condensed printing)
128 ASCII Control Code to Advance the Paper One Line (LF without CR)
129 Null
130 ASCII Control Code to Shift Out (i.e., set double-wide for the line)
131 ASCII Control Code to Ring the Bell Once
132 ASCII Control Code to Cancel the Print Job (Cancel)
133 ASCII Control Code to Select 10 Char per Inch; Cancels Cond., 12 CPI
134 (not used; handled by formatter) Vertical Tab
135 Select Primary (ROM) Font
136 Select Alternate (downloaded) Font
137 Italics not available
138 Set Condensed Mode On/Off
139 Command To Space Horizontally In Hres Units (used for ident, LF w/o CR)
140 Space Horizontally In Hres Units (used for ident, LF w/o CR)
141 Commands To Initialize the Printer 
142 Initialize the Printer
143 Command To Send Carrier Return & Line Feed Controls
144 Send Carriage Return & Line Feed Controls
145 Command When Switching Between Pri. Mode & Alt. (security label) Mode
146 Set Pitch
147 Set Print Quality (0: fastfont; 1: draft; 2:NLQ; 3:enhanced)
148 Restore the Printer at Job End
149 Initialize Character Scale
150 Set Proportional Spacing On/Off
151 Set Vertical Spacing
152 (not used) Directory Containing Stage 1 Translate Tables (data stream to intermed.)
153 Directory Containing Stage 1 Translate Tables (data stream to intermed.)
154 (not used) Directory Containing Stage 2 Translate Tables (intermediate to printer)
155 Directory Containing Stage 2 Translate Tables (intermediate to printer)
156 Directory Containing Header & Trailer Files
157 Directory Containing Header & Trailer Text Files
158 Directory Containing Digested Data Base Files
159 Directory Containing Miscellaneous Modules
160 Directory Containing Loadable Formatter Routines
161 Directory Containing Fonts To Be Downloaded
162 Directory For Temporary Files
163 (not used) Set Paper Source Drawer 
164 Set Line Spacing to 8 Lines Per Inch
165 Set Paper Source Drawer 
166 (not used) Text Rotation Command
167 Set Line Spacing to 7/72 Inch Per Line
168 Text Rotation Command
169 (not used) Set Number of Copy Command
170 Set Number of Copy Command
171 Turn On Line Spacing Specified With SET_LS_CMD
172 (not used) Set Logical Page Command
173 Set Graphics Line Spacing
174 Set Logical Page Command
175 (not used) Set Line Type Command
176 (not used) Set Top of Form
177 Set Line Type Command
178 (not used) Set Line Width Command
179 (used only for pass-through init) Turn On/Off Automatic Line Feed With CR
180 Set Line Width Command
181 (not used) Draw Box Command
182 (used only for init/restore) Select Character Set 2
183 Draw Box Command
184 (not used) Overlay Command
185 (not used) Select Character Set 1
186 Overlay Command
187 (not used) Segment Command
188 Print All Characters
189 Segment Command
190 (not used) Page Map Primitive Command
191 (not used; would conflict with formatter processing) Set Code Page
192 Page Map Primitive Command
193 Command to Set Text Line Spacing
194 Set DBCS Data Stream Mode (used only for init/restore)
195 (used only for init/restore) Set Vertical Tab Stops
196 Initialize Left/Right Margin (used only for init/restore)
197 (used only for init/restore) Set Page Length
198 Initialize Printers (used only for init/restore)
199 (not used) Set/Reset Uni-directional Print Mode 
200 (used only for init/restore) Set Horizontal Tabs
201 Set/Reset Uni-directional Print Mode 
202 (not used) Set/Reset High Speed Print Mode
203 Set/Reset High Speed Print Mode
204 Turn On/Off Emphasized Printing
205 Set/Reset Condensed Print Mode
206 (not used) Turn On/Off Double-Strike Printing
207 Set/Reset Double Wide Print Mode
208 Turn On/Off Double-Strike Printing
209 Set/Reset Vertical Print Mode
210 Select Pitch, Type Style, and Quality
211 Set/Reset Emphasized Print Mode
212 (not used) Set/Reset Double Strike Print Mode
213 Advance the Paper by a Variable Amount
214 Set/Reset Double Strike Print Mode
215 Print Graphics at 60 dots/inch hor. & 72 dots/inch vert.
216 Set/Reset Under Score
217 Print Graphics at 120 dots/inch hor. & 72 dots/inch vert. (low speed)
218 Set/Reset Over Strike
219 (used only for init/restore) Initialize Horizontal Tabs
220 (not used; handled by formatter) Set Automatic Perforation Skip
221 (used only for init/restore) Initialize Vertical Tabs
222 (used only at init/restore) Cancel Automatic Perforation Skip
223 Set Character Per Inch
224 Set Lines Per Inch
225 Turn On/Off Proportional Spacing
226 Set Page Length in 1/6 unit
227 (not used; handled by formatter) Reset Hor. Tabs to Every 8 Pos. & Clear Vert. Tabs
228 Change Font Style
229 Change Character Scaling
230 Turn On/Off Subscript Printing
231 Cut Form Insert
232 Turn On/Off Superscript Printing
233 (not used) Change From/To Left-to-Right To/From Two-Direction Printing
234 Change From/To Left-to-Right To/From Two-Direction Printing
235 Cut Form Eject
236 Set/Reset Super/Sub Script Mode
237 Turn On/Off Continuous Double-Wide Printing
238 Set Left and Right Margins
239 Print Graphics at 120 dots/inch hor. & 72 dots/inch vert. (normal spd)
240 Print Graphics at 240 dots/inch hor. & 72 dots/inch vert.
241 (used only at init/restore) Turn Off Automatic Line Feed With CR
242 Image Transmission 
243 Image Transmission and Enlarge
244 Print a Single Character From the All Characters Chart
245 Forward Horizontal Skip
246 Set Character Spacing to 12 Characters Per Inch
247 Backward Horizontal Skip
248 Move to the Right n/120 Inch
249 Forward Vertical Step Feed
250 Move to the Left n/120 Inch
251 CR To Specified Dot Position
252 Turn On Double-High and/or Double-Wide Printing
253 Backward Vertical Step Feed
254 Set Line Feed Increment Value
255 Turn On/Off Continuous Overscore
256 (not used) Change Form Handling 
257 Change Form Handling 
258 Print All Characters
259 Stop Printing
260 Partial Index Up
261 Turn On/Off Continuous Underscore
262 Partial Index Down
263 Set 3/2 Bytes Image Transmission Mode
264 Set Vertical Units for VAR_LS_CMD and SET_GRA_LS_CMD
265 (not used) Set Grid Line Attribute
266 (not used) Set printer aspect ratio
267 Set Grid Line Attribute
268 (not used) Gaiji Load Command    
269 Gaiji Load Command    
270 High-Resolution Graphics
271 (not used) Set Horizontal Margins
272 Download Character Fonts
273 Horizontal Column Skip
274 Reverse Line Feed
275 Vertical Line Skip
276 (not used) Write Image Control Command
277 Write Image Control Command
278 (not used) Write Image Command
279 Write Image Command
280 (not used) Load Font Pattern Command
281 Load Font Pattern Command
282 (not used) Load Font Control Command
283 (not used) Printer initialization - this will override formatter initialization - DO NOT USE !!!
284 Load Font Control Command 
285 (not used) Set Font Local Command
286 Set Font Local Command
287 (not used) Delete Font Local Command
288 Delete Local Font Command
289 (not used) Character Rotation Command
290 Alternate Graphics Mode: Print Graphics In Specified Mode
291 Character Rotation Command
292 (not used) Character Baseline Offset Command
293 Character Baseline Offset Command
294 Set SBCS Data Stream Mode
295 (not used) Command String for the "c" Filter.
296 Command String for the "c" Filter.
297 (not used) Command String for the "d" Filter.
298 Command String for the "d" Filter.
299 (not used) Command String for the "f" Filter.
300 Command String for the "f" Filter.
301 (not used) Command String for the "g" Filter.
302 Command String for the "g" Filter.
303 (not used) Command String for the "l" Filter.
304 Command String for the "l" Filter.
305 (not used) Command String for the "n" Filter.
306 Command String for the "n" Filter.
307 (not used) Command String for the "p" Filter.
308 Command String for the "p" Filter.
309 (not used) Command String for the "t" Filter.
310 Command String for the "t" Filter.
311 (not used) Command String for the "v" Filter.
312 Command String for the "v" Filter.
313 Pipeline for Input Data Stream "a" (extended ASCII)
314 Pipeline for Input Data Stream "k" (kanji)
315 Pipeline for Input Data Stream "t" (pass-through)
316 (not used) Path Name of Stage 2 Translate Table For Resident Font
317 (not used) Path Name of Stage 2 Translate Table For Download Font
318 Condensed mode type          1;4207m2  2;4201m3
319 (not used) Path Name of Font File To Be Downloaded (must include download commands)
320 Path Name of Font File To Be Downloaded (must include download commands)
321 Graphic unit handling flag   1;4207m2  2;4201m3
322 Number of Units Into Which a Horizontal Inch Is Divided
323 Esc I processing flag        1;4207m2  2;4201m3
324 Printer model number        4201      4207
325 Percentage of Perf. Skip Value For Top Margin (rest for bottom margin)
326 (not used) Character To Be Used When Real One Can't Be Printed
327 Character To Be Used When Real One Can't Be Printed
328 Number of Units Into Which a Vertical Inch Is Divided
329 Number of Units Into Which a Vertical Inch Is Divided
330 (not used) Name of PostScript Data Base File; If Null, Search In "dd" Dir.
331 (not used) Name of Postscript Data Base File; If Null, Search In "dd" Dir.
332 String to Send to Printer "mz" Times When Job Is Cancelled
333 Output Data Stream Type (example: ascii); Initialized By "piodigest"
334 Output Data Stream Type (example: kanji); Initialized By "piodigest"
335 Path Name of the Default Formatter (used when running stand alone)
336 Path Name of the Default Formatter (used when running stand alone)
337 Input Data Stream Name For PostScript (one character) 
338 Input Data Stream Name For Postscript (one character)
339 File Name Of (Digested) Data Base; Init. By "piodigest" (mt.md.mn.mq:mv)
340 Device Name (example: lp0); Initialized By "piodigest"
341 Device name (example: lp0); Initialized By "piodigest"
342 Command String to Invoke Device Driver I/F Program (end of pipeline)
343 String That Identifies a PostScript (instead of ASCII) Data Stream
344 Queue Name; Initialized By "piodigest"
345 (not used) Path Name of "read printer" routine ('load'ed by Dev. Dri. I/F pgm)
346 Printer Type (example: 5327); Initialized By "piodigest"
347 Printer Type (example: 5575); Initialized By "piodigest"
348 Printer Type (example: 5577); Initialized By "piodigest"
349 Printer Type (example: 5587); Initialized By "piodigest"
350 Printer type (example: 5575); Initialized By "piodigest"
351 Printer type (example: 5587); Initialized By "piodigest"
352 To Print Multiple Copies:  0: Return Pipeline;  1: Reprint Saved Copy
353 To Print Multiple Copies:  0: Rerun Pipeline;  1: Reprint Saved Copy
354 Virtual Printer (i.e., queue device) Name; Initialized By "piodigest"
355 Virtual Printer (i.e.,queue device) Name; Initialized By "piodigest"
356 Maximum Number of Horizontal Tabs That Can Be Defined
357 Maximum Number of Vertical Tabs That Can Be Defined
358 Number of Times To Send String "mc" to Printer When Job Is Cancelled
359 (not used) Code page number
360 Pipeline for Header Page
361 User Who Receives Intervention Req'd Msgs (default: job submitter)
362 Command Line Flags Prohibited For All Input Data Str; Ignored: cmnorCDMPRT
363 Command Line Flags Prohibited For All Input Data Str; Ignored: cmnorCMDPRT
364 Pipeline for Trailer Page
365 Width of Attribute Value Area On Header Page (0 means ignore width)
366 Path Name of Stage 2 Translate Table
367 Path Name of First Alternate Stage 2 Translate Table
368 Path Name of Next Alternate Translate Stage 2 Translate Table
369 ditto
370 ditto
371 ditto
372 ditto
373 ditto
374 ditto
375 ditto
376 Integer Set By Formatter For Use By Various Commands
377 Portrait
378 Landscape right
379 Portrait upside-down 
380 Landscape left
381 The Remaining of Characters for Print All Command
382 The Remaining of Image Data 
383 Work Variable For Vertical Decrement (in Vres units)
384 Work Variable In Which To Save Horizontal Position From Previous Line
385 Vertical Index Increment Used By ESC J & ESC 3
386 Work Variable For Horizontal Increment Per Character (in Hres units)
387 Image Transmission Mode (3: 3-byte transmission, 2: 2-byte transmission)
388 Italics not available for this printer
389 Image Data Width (used by FS Command)
390 Page Length In Chars, Using Length From Data Base (used in pipelines)
391 Left Margin in Hres Unit
392 Vertical Index Increment Used By ESC A
393 Work Variable For Vertical Increment (in Vres units)
394 Page Width In Characters, Using Width From Data Base (used in pipelines)
395 Work Integer
396 Currently In Subscript Mode? (!: no;  +: yes)
397 Currently In Subscript Mode? (!:no; +:yes)
398 Character Code for Over Strike Command (1byte code: 0x0000XX00; 2byte code: 0x0000XXXX) 
399 Currently In "line" Doublewide Mode? (!: no;  +: yes)
400 Name of Forward Vertical Step Feed
401 Currently In Superscript Mode? (!: no;  +: yes)
402 Currently In Superscript Mode? (!:no; +:yes)
403 Name of Current Form Feed Command
404 Character Flag for Over Strike Command (3: Hankaku; 4: Zenkaku; 1: Cancel) 
405 Graphics Line Spacing Used By SET_GRA_LS_CMD
406 Current Horizontal Tab Settings (terminated by null)
407 Name of Current Vertical Increment Command
408 Number of Lines to Space Down For Each Line Feed
409 Current Vertical Spacing Mode (0: ESC 0; 1: ESC 1; 2: ESC 2; 3: ESC 3)
410 Mode Flag for Over Strike Command (B'0000 00nm)
411 Currently In Continuous Overscore Mode? (!: no;  +: yes)
412 Pass-Through Instead of Formatting (i.e., data stream is not modified)?
413 Pass-Through Instead of Formatting (i.e., data stream is not modified) ?
414 Currently In One-Direction Print Mode? (!: no;  +: yes)
415 Currently In Proportional Spacing Mode? (!: no;  +: yes)
416 Line Spacing: (value/Tunits) inches per line; used by SET_LS_CMD
417 Name of Backward Vertical Step Feed
418 Currently In Continuous Underscore Mode ? (B'0000 00nm; n: 1:on 0:off; m: 1:blank
419 Currently In Continuous Underscore Mode? (!: no;  +: yes)
420 Current Vertical Tab Settings (terminated by null)
421 Work Variable For Page Width (in Hres units)
422 Name of Particial Index Down Command
423 Name of Current Vert. Decrement Command
424 Name of Particial Index Up Command
425 Printer Data Stream Description
426 Name of Message Catalog Containing Attribute Descriptors
427 Printer Description
$
429 Pipeline for Input Data Stream "s" (PostScript)
430 (not used)Command Line Flags Prohibited For Input Data Stream; Ignored: cmnrBDMPRT
431 Command Line Flags Prohibited For Input Data Stream; Ignored: cmnrBDMPRT
432 (not used)Smallest legal sheetfeeder drawer number
433 Smallest legal sheetfeeder drawer number
434 (not used)Largest legal sheetfeeder drawer number
435 Largest legal sheetfeeder drawer number
436 (not used)Path Name of Font File To Be Downloaded (must include download commands)
437 Path Name of Font File To Be Downloaded (must include download commands)
$
456 (not used) Code Page Name For Print Data Stream (the same name used by iconv)
457 Code Page Name For Print Data Stream (the same name used by iconv)
458 (not used)Kanji In Code
459 Kanji In Code
460 (not used)Kanji Out Code
461 Kanji Out Code
$
500 (not used)Work Variable for Specifying the Escape Sequences Length
501 Work Variable for Specifying the Escape Sequences Length
502 (not used) Set Media Size Command
503 Set Media Size Command
504 (not used) Draw Box 2 Command
505 Draw Box 2 Command
506 (not used) Draw Box 3 Command
507 Draw Box 3 Command
508 (not used) Draw Relative Line Command
509 Draw Relative Line Command
510 (not used) Set Media Axis Zero Point Command
511 Set Media Axis Zero Point Command
512 (not used) Set Page Format Command
513 Set Page Format Command
514 (not used) Set Page Descriptor Command
515 Set Page Descriptor Command
516 (not used) Set Logical Zero Point Command
517 Set Logical Zero Point Command
518 (not used) Set Composed Character Command
519 Set Composed Character Command
520 (not used) Set Mesh Command
521 Set Mesh Command
522 (not used) Set Mesh Reference Point Command
523 Set Mesh Reference Point Command
524 (not used) Clear Mesh Command
525 Clear Mesh Command
526 (not used) Record Mesh Command
527 Record Mesh Command
528 (not used) Graphic Control Command
529 Graphic Control Command
530 (not used) Graphic Draw Command
531 Graphic Draw Command
$
551 1 byte work variable
553 2 bytes work variable
555 4 bytes work variable
557 8 bytes work variable
559 Work string variable
561 Temporary Code Page Name
563 LIPS Command Level
565 LIPS Job Name
567 Size Unit( 2: 1/720 inch(default), 6: 1/1000mm, 7:dot, ?6: 1/100mm )
569 Page Format
571 Auto CR/LF when Wrap( +: Yes, !: No )
573 Auto Form Feed( +: Yes, !: No )
575 Move to Upper Margin When Form Feed( +: Yes, !: No )
577 Auto CR/LF when CR( +: Yes, !: No )
579 Auto CR/LF when LF( +: Yes, !: No )
581 Auto CR when FF( +: Yes, !: No )
591 Auto CAP Move( +: Yes, !:No )
593 Proportional Spacing( +:Yes, !: No )
595 Auto HMI Change( +: Yes, !:No )
597 Proportional Offset
599 Print Position Offset
601 Line-Colomn Mode( +: Yes, !: No )
603 Auto CR when VT( +: Yes, !:No )
605 Graphic Set Table GL
607 Graphic Set Table GR
609 Graphic Set Table G0
611 Graphic Set Table G1
613 Graphic Set Table G2
615 Graphic Set Table G3
617 Graphic Set Table GL( 2 bytes )
619 Graphic Set Table GR( 2 bytes )
621 Graphic Set Table G0( 2 bytes )
623 Graphic Set Table G1( 2 bytes )
625 Graphic Set Table G2( 2 byte )
627 Graphic Set Table G3( 2 bytes )
629 Charcter Style( 0: Normal, 1: Oblique )
631 Stroke Weight
633 Font Style
635 Restore Character Attributes Mode( +: Yes, !: No )
637 Vertical Printing( +: Yes, !: No( Horizontal Printing ) )
639 Character Convert When Vertical Printing( +: Yes, !: No )
641 Single/Double Underline Mode
643 Underline Attributes
645 Filled Pattern( +: Yes, !: No )
647 Character Shadow( +: Yes, !: No )
649 Character Outline( +: Yes, !: No )
651 Filled Pattern Number
653 Filled Pattern Modifyer
655 Shadow Pattern Number
657 Shadow Pattern Modifyer
659 Shadow Direction
661 Shadow Length
663 Outline Thickness
665 Mesh Mode( +: Yes, !: No )
667 Mesh Pattern Number
669 Mesh Pattern Modifyer
671 Color Reverse( +: Yes, !: No )
673 Character Set Enlarge Mode( +: Yes, !: No( Character String Enlarge Mode ))
675 Auto Emphasized Printing( +: Yes, !: No )
677 Secret Printing( +: Yes, !: No )
679 Mesh in Frame Area( +: Yes, !: No )
681 Mesh Operation Mode
683 Grid Line( +: Yes, !: No )
685 Grid Line Width
687 Grid Line Type
689 Grid Line Position
691 Grid Line is Frame( +: Yes, !: No )
693 Grid Line Round
695 Decorated Grid Line Pattern Number
697 Decorated Grid Line Pattern Rotation
699 Decorated Grid Line Start Point Offset
701 Decorated Grid Line Start Style
703 Decorated Grid Line End Style
705 Vector Mode( +: Yes, !: No( Text Mode or other ) )
707 Picture Name( LIPS Vector Mode )
709 Position Unit( LIPS Vector Mode )
711 Position Unit Expansion Rate( LIPS Vector Mode )
713 Clipping On( LIPS Vector Mode, +: Yes, !: No )
715 Drawing Logic( LIPS Vector Mode )
717 Line Type( LIPS Vector Mode )
719 Line Expantion Ratio( LIPS Vector Mode )
721 Line Width( LIPS Vector Mode )
723 Drawing Style( LIPS Vector Mode )
725 Paint Pattern( LIPS Vector Mode )
727 Paint Pattern Rotation( LIPS Vector Mode )
729 Paint Pattern Left-Right Reverse( LIPS Vector Mode )
731 Paint Pattern Color Reverse( LIPS Vector Mode )
733 Line Conection Style( LIPS Vector Mode )
735 Line End Style( LIPS Vector Mode )
737 Marker Type( LIPS Vector Mode )
739 Marker Size( LIPS Vector Mode )
741 Draw Paint Pattern Outline( LIPS Vector Mode )
743 Rounding Radius when Drawing Frames( LIPS Vector Mode )
745 Gray Scale( LIPS Vector Mode )
747 Character Rotation Up Vector( LIPS Vector Mode )
749 Character Rotation Base Vector( LIPS Vector Mode )
751 Character Height( LIPS Vector Mode )
753 Character Height Unit( LIPS Vector Mode )
755 Character Height Unit Expansion Ratio( LIPS Vector Mode )
757 Character Width Expansion Ratio( LIPS Vector Mode )
759 Character Prining Direction( LIPS Vector Mode )
761 Space between Characters( LIPS Vector Mode )
763 Character Attributes Level( LIPS Vector Mode )
765 Character Paint Pattern( LIPS Vector Mode )
767 Character Outline( LIPS Vector Mode )
769 Character Paint Pattern Rotation( LIPS Vector Mode )
771 Character Paint Pattern Left-Right Reverse( LIPS Vector Mode )
773 Character Paint Pattern Color Reverse( LIPS Vector Mode )
$
801 Text Mode Start Command
803 Vector Mode In Command
805 Emulation Mode In Command
807 Shift JIS Start Command
809 Job Start Command
811 Job End Command
813 Hard Reset Command
815 Soft Reset Command
817 Parameters Reset Command
819 Free Memory Command
821 Select Page Format Command
823 Page Rotation Command
825 Margin Set Command
827 Margin Reset Command
829 Auto CR/LF when Wrap Command
831 Auto Form Feed Command
833 Move to Upper Margin When Form Feed  Command
835 Auto CR/LF when CR Command
837 Auto CR/LF when LF Command
839 Auto CR when FF Command
841 Carrige Return and Line Feed Command
843 Harf Line Feed Command
845 Reverse Line Feed Command
847 Reverse Harf Line Feed Command
849 Select Line Pitch Command
851 Specify Spacing Value Command
853 Auto CAP Move Command
855 Proportional Spacing Command
857 Auto HMI Change Command
859 Set Proportional Offset Command
861 Set Print Position Offset Command
863 Line-Colomn Mode Command
865 Absolute Vertical & Horizontal Move Command
867 Absolute Vertical Move Command
869 Absolute Horizaontal Move Command
871 Relative Upper Move Command
873 Relative Lower Move Command
875 Relative Left Move Command
877 Relative Right Move Command
879 Store or Restore CAP Command
881 Auto CR when VT Command
883 Ascii Control Code Shift In
885 Ascii Control Code Shift Out
887 LS2 Command
889 LS3 Command
891 SS2 Command
893 SS3 Command
895 LS1R Command
897 LS2R Command
899 LS3R Command
901 Specify Pairs Command
903 Specify G0 Graphic Set Command
905 Specify G1 Graphic Set Command
907 Specify G2 Graphic Set Command
909 Specify G3 Graphic Set Command
911 Specify G0 Graphic Set Command( 2 bytes )
913 Specify G1 Graphic Set Command( 2 bytes )
915 Specify G2 Graphic Set Command( 2 bytes )
917 Specify G3 Graphic Set Command( 2 bytes )
919 Select Line Pitch Command
921 Select Character Size Command
923 Select Character Style Command
925 Select Stroke Weight Command
927 Select Font Command
929 Select Graphic Set Name Command
931 Asign Graphic Set Number to Table Command
933 Select Graphic Set Asign Number Command 1
935 Select Graphic Set Asign Number Command 2
937 Restore Character Attributes Mode Command
939 Record Graphic Set Command( binary )
941 Record Graphic Set Command( hexa )
943 Record One Character Command( binary )
945 Record One Character Command( hexa )
947 Copy Graphic Set Command
949 Copy One Character Command
951 Support Recording Graphic Set Command
953 Delete Graphic Set Command
955 Print Control Characters Command( binary )
957 Print Control Characters Command( hexa )
959 Set Vertical/Horizontal Printing Command
961 Character Convert when Vertical Printing Command
963 Composed Character Printing Command
965 Single/Double Underline Command
967 Underline Attributes Command
969 Fill Pattern Command
971 Character Shadow Command
973 Character Outline Command
975 Decoration Attributes Command
977 Mesh Command
979 Mesh Pattern Command
981 Color Reverse Command
983 Character Enlarge Command
985 Switch Character Set Enlarge/ Character String Enlarge Mode Command
987 Auto Emphasized Printing Command
989 Secret Printing Command
991 Character Rotation Command
993 Mesh in Frame Area Command
995 Mesh Operation Mode Command
997 Record Mesh Pattern Command( binary )
999 Record Mesh Pattern Command( hexa )
1001 Start Grid Line Command
1003 End Grid Line Command
1005 Start Decorated Grid Line Command
1007 End Decorated Grid Line Command
1009 Record Decorated Grid Line Pattern Command( binary )
1011 Record Decorated Grid Line Pattern Command( hexa )
1013 Draw Raster Image Command( binary )
1015 Draw Raster Image Command( hexa )
1017 Allocate Image Data Memory Command
1019 Draw WireDot Image Command 1( binary )
1021 Draw WireDot Image Command 1( hexa )
1023 Draw WireDot Image Command 2( binary )
1025 Draw WireDot Image Command 2( hexa )
1027 Start Overlay Page Recording Command
1029 End Overlay Page Recording Command
1031 Start Overlay Printing Command
1033 End Overlay Printing Command
1035 Record Macro Command( binary )
1037 Record Macro Command( hexa )
1039 Execute Macro Command
1041 Specify Startup Macro Command
1043 Store Printing Environment Command
1045 Restore Printing Environment Command
1047 Undo Command
1049 Display Comment Command 1
1051 Display Comment Command 2
1053 Display Comment Command 3
1055 Request Status Command 1( Ignored )
1057 Specify Graphic Set Key Command( Ignored )
1059 Request Status Command 2( Ignored )
1061 Request Character Pitch Command( Ignored )
1063 Ascii Character of Text Block End
1065 Ascii Character of ACK
1067 Ascii Character of XON
1069 Ascii Character of XOFF
1071 Ascii Character of DEL
$
1101 Text Mode In Command( LIPS Vector Mode )
1103 Declare Font List Command( LIPS Vector Mode )
1105 Declare Graphic Set List Command( LIPS Vector Mode )
1107 Set Page Orientation Command( LIPS Vector Mode )
1109 Start Picture Command( LIPS Vector Mode )
1111 Position Unit Command( LIPS Vector Mode )
1113 Start Drawing Command( LIPS Vector Mode )
1115 End Picture Command( LIPS Vector Mode )
1117 Set Drawing Area Command( LIPS Vector Mode )
1119 Move Zero Point Command( LIPS Vector Mode )
1121 Set Clipping Area Command( LIPS Vector Mode )
1123 Clipping Command( LIPS Vector Mode )
1125 Set Drawing Logic Command( LIPS Vector Mode )
1127 Line Style Command( LIPS Vector Mode )
1129 Line Width Command( LIPS Vector Mode )
1131 Line Attributes Command( LIPS Vector Mode )
1133 Line Conection Style Command( LIPS Vector Mode )
1135 Line End Style Command( LIPS Vector Mode )
1137 Marker Type Command( LIPS Vector Mode )
1139 Marker Size Command( LIPS Vector Mode )
1141 Paint Pattern Command( LIPS Vector Mode )
1143 Rounding Radius when Drawing Frames Command( LIPS Vector Mode )
1145 Gray Scale Command( LIPS Vector Mode )
1147 Screen Command( LIPS Vector Mode )
1149 Record Line Pattern Command( LIPS Vector Mode )
1151 Record Marker Pattern Command( LIPS Vector Mode )
1153 Record Paint Pattern Command( LIPS Vector Mode )
1155 Draw Marker Command( LIPS Vector Mode )
1157 Draw Lines Command( LIPS Vector Mode )
1159 Draw Frame Command( LIPS Vector Mode )
1161 Draw Polygon Command 1( LIPS Vector Mode )
1163 Draw Polygon Command 2( LIPS Vector Mode )
1165 Draw polygon Command 3( LIPS Vector Mode )
1167 Draw Circle Command( LIPS Vector Mode )
1169 Draw Arc Command 1( LIPS Vector Mode )
1171 Draw Arc Command 2( LIPS Vector Mode )
1173 Draw Ellipse Command( LIPS Vector Mode )
1175 Draw Ellipse Arc Command( LIPS Vector Mode )
1177 Draw Quater Ellipse Command( LIPS Vector Mode )
1179 Paint Command( LIPS Vector Mode )
1181 Specify G0 Font Command( LIPS Vector Mode )
1183 Specify G1 Font Command( LIPS Vector Mode )
1185 Specify G2 Font Command( LIPS Vector Mode )
1187 Specify G3 Font Command( LIPS Vector Mode )
1189 Specify G0 Graphic Set Command( LIPS Vector Mode )
1191 Specify G1 Graphic Set Command( LIPS Vector Mode )
1193 Specify G2 Graphic Set Command( LIPS Vector Mode )
1195 Specify G3 Graphic Set Command( LIPS Vector Mode )
1197 Character Rotation Command( LIPS Vector Mode )
1199 Character Height Command( LIPS Vector Mode )
1201 Character Height Unit Command( LIPS Vector Mode )
1203 Character Width Expansion Command( LIPS Vector Mode )
1205 Character Printing Direction Command( LIPS Vector Mode )
1207 Character Space Command( LIPS Vector Mode )
1209 Character Attributes Level Command( LIPS Vector Mode )
1211 Decorated Character Attributes Command( LIPS Vector Mode )
1213 Start Printing Characters Command( LIPS Vector Mode )
1215 Continue Printing Characters Command( LIPS Vector Mode )
1217 Continue Printing Control Characters Command( LIPS Vector Mode )
1219 Allocate Image Area Command( LIPS Vector Mode )
1221 Draw Image Command( LIPS Vector Mode )
$
2001 Resolution ( Dot per Inch )
2003 Page width ( In mH unit )
2005 Page length ( In mV unit )
2007 Page orientation
2009 Left Margin ( In mH unit )
2011 Right Margin ( In mH unit )
2013 Top Margin ( In mV unit )
2015 Bottom Margin ( In mV unit )
2017 Page end ( In mV unit )
2019 VMI
2021 HMI
2023 Character Width
2025 Character Height
2027 Stroke Value
2029 Horizontal Tab Length
2031 Vertical Tab Length
2033 Code Page Value in Laser Shot ( 127: IBM-932, 2: IBM-eucJP, 1: JIS )
2035 mH / 720
2037 VMI when no Auto CAP move
2039 HMI when no Auto CAP move
2041 Offset between Logical and Phisical Y value ( unit is dot )
2043 Maximum Page Width
2045 Maximum Page Height
2047 Minimum Page Width
2049 Minimum Page Height
2051 Maximum VMI
2053 Maximum HMI
2055 Maximum X value
2057 Maximum Y value
2059 Maximum Number of Points to save
2061 Page White Space Width
2063 Print File Code Page List
2065 Processing Locale List
2067 Processing Code Page List
2069 Kanji-in = Kanji-out Initial State Value List ( -1: No-State, 0: Kanji-out, 1: Kanji-in )
2071 Code Page Value List in Laser Shot ( 127: IBM-932, 2: IBM-eucJP, 1: JIS )
2073 Printer Code Page List
2075 Kata-kana Code Page Name
2077 User-defined Code Page Name
2079 Maximum Character Size ( unit is dot )
2081 Horizontal Tab Code
2083 Vertical Tab Code
2085 Cariage Return Code
2087 Ascii Character of EM
2089 Ascii Character of GS
2091 Ascii Character of Space
2093 Character Code of HTS
2095 Character Code of VTS
2097 Character Code of DCS
2099 Character Code of CSI
2101 Character Code of ST
2103 Select Unit Command
2105 Initial VMI Command
2107 Initial HMI Command
2109 Initial Horizontal Tab Command
2111 Initial Vertical Tab Command
2113 Initial Margin Command
2115 Initial Orientation Command
2117 Paper Tray Command
2119 Copy Number Command
2121 Work Variables Not Referenced by Formatter Filter
