# @(#)59        1.4  src/bos/diag/util/udsense/dsense.lib.S, dsaudsense, bos411, 9435D411a 9/1/94 17:23:14
#
#   COMPONENT_NAME: DSAUDSENSE
#
#   FUNCTIONS: none
#
#   ORIGINS: 27
#
#
#   (C) COPYRIGHT International Business Machines Corp. 1993, 1994
#   All Rights Reserved
#   Licensed Materials - Property of IBM
#   US Government Users Restricted Rights - Use, duplication or
#   disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#
~rtypes.dsense
~labels.dsense
~arrays.dsense
