# @(#)68        1.1  src/bos/usr/lib/methods/cfgdmxtok/Makefile, sysxtok, bos411, 9428A410j 9/17/93 09:40:15
#
# COMPONENT_NAME: (SYSXTOK)
#
# FUNCTIONS:
#
# ORIGINS: 27
#
# IBM CONFIDENTIAL -- (IBM Confidential Restricted when
# combined with the aggregated modules for this product)
#                  SOURCE MATERIALS
# (C) COPYRIGHT International Business Machines Corp. 1988, 1989
# All Rights Reserved
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#

VPATH		= ../common

PROGRAMS        = cfgdmxtok

OFILES          = cfgdmxtok.o

INCFLAGS	= -I../common

ILIST           = cfgdmxtok
IDIR		= /usr/lib/methods/


LIBS		= -ls -lodm -lcfg -lrts

.include <${RULES_MK}>
