# @(#)30        1.1  src/bos/kernext/inputdd/inc/sys/Makefile, inputdd, bos411, 9428A410j 11/30/93 13:22:18
# COMPONENT_NAME: INPUTDD
#
# FUNCTIONS: none
#
# ORIGINS: 27
#
# IBM CONFIDENTIAL -- (IBM Confidential Restricted when
# combined with the aggregated modules for this product)
#                  SOURCE MATERIALS
# (C) COPYRIGHT International Business Machines Corp. 1993
# All Rights Reserved
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#

INCLUDES         = inputdd.h

EXPDIR           = /kernel/include/sys/

.include <${RULES_MK}>
