# @(#)04	1.12.1.1  src/bos/etc/group/group.S, cfgsadm, bos411, 9428A410j 6/2/94 09:40:05
#  COMPONENT_NAME: CFGSADM
#
#  ORIGINS: 3, 26, 27
#
#  (C) COPYRIGHT International Business Machines Corp. 1989, 1994
#  All Rights Reserved
#  Licensed Materials - Property of IBM
#
#  US Government Users Restricted Rights - Use, duplication or
#  disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#
system:!:0:root
staff:!:1:
bin:!:2:root,bin
sys:!:3:root,bin,sys
adm:!:4:bin,adm
uucp:!:5:uucp
mail:!:6:
security:!:7:root
cron:!:8:root
printq:!:9:
audit:!:10:root
ecs:!:28:
nobody:!:4294967294:nobody,lpd
usr:!:100:guest
