# @(#)94        1.3  src/bldenv/findfile/Makefile, bldprocess, bos412, GOLDA411a 2/17/93 08:04:32
# COMPONENT_NAME:
#
# FUNCTIONS:
#
# ORIGINS: 27
#
# IBM CONFIDENTIAL -- (IBM Confidential Restricted when
# combined with the aggregated modules for this product)
#                  SOURCE MATERIALS
# (C) COPYRIGHT International Business Machines Corp. 1988, 1989
# All Rights Reserved
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#

PROGRAMS	= findfile
SCRIPTS		= findshipfile

ILIST           = ${PROGRAMS} ${SCRIPTS}
IDIR            = /usr/bin/

.include <${RULES_MK}>
