# @(#)22	1.2  src/bos/usr/lib/learn/Linfo.S, cmdlearn, bos411, 9428A410j 8/6/91 15:39:06
#
# COMPONENT_NAME: (CMDMAN) commands that allow users to read online
# documentation 
#
# FUNCTIONS: none 
#
# ORIGINS: 26, 27 
#
# IBM CONFIDENTIAL -- (IBM Confidential Restricted when
# combined with the aggregated modules for this product)
#                  SOURCE MATERIALS
# (C) COPYRIGHT International Business Machines Corp. 1989 
# All Rights Reserved
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
  files
  editor
  morefiles
  macros
  eqn
  C
