# @(#)12        1.2  src/bos/usr/lib/learn/Makefile, cmdlearn, bos411, 9428A410j 1/15/93 13:09:26
# COMPONENT_NAME:
#
# FUNCTIONS:
#
# ORIGINS: 27
#
# IBM CONFIDENTIAL -- (IBM Confidential Restricted when
# combined with the aggregated modules for this product)
#                  SOURCE MATERIALS
# (C) COPYRIGHT International Business Machines Corp. 1988, 1989
# All Rights Reserved
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#

SUBDIRS		= C editor eqn files macros morefiles bin

SCRIPTS		= Xinfo Linfo

ILIST		= ${SCRIPTS}
IDIR		= /usr/share/lib/learn/

.include <${RULES_MK}>
