# @(#)23	1.2  src/bos/usr/lib/learn/Xinfo.S, cmdlearn, bos411, 9428A410j 8/6/91 15:38:38
#
# COMPONENT_NAME: (CMDMAN) commands that allow users to read online
# documentation 
#
# FUNCTIONS: none 
#
# ORIGINS: 26, 27 
#
# IBM CONFIDENTIAL -- (IBM Confidential Restricted when
# combined with the aggregated modules for this product)
#                  SOURCE MATERIALS
# (C) COPYRIGHT International Business Machines Corp. 1989 
# All Rights Reserved
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
files     - basic file handling commands
editor    - text editor; must know about files first
morefiles - more on file manipulations and other useful stuff
macros    - "-ms" macros for BTL memos & papers;  must know editor
eqn       - typing mathematics;  must know editor
C         - writing programs in the C language;  must know editor

This is probably the proper order, but after you have the "files" course
and know the basics of "editor", try anything you like. 

You can always leave learn by typing "bye" (and a RETURN).
You can stop it from typing by pushing interrupt
(or break or rubout or delete, depending on your terminal).

If it won't accept your answer, and you _k_n_o_w you're
right, answer "no" when it asks whether you
want to try again, and it will go on to the next lesson.
