static char sccsid[] = "@(#)42	1.1.1.1  src/bos/usr/lpp/jls/dictutil/kjinit.c, cmdKJI, bos411, 9428A410j 7/23/92 00:57:39";
/*
 * COMPONENT_NAME: User Dictionary Utility
 *
 * FUNCTIONS: kjinit
 *
 * ORIGINS: 27
 *
 * IBM CONFIDENTIAL -- (IBM Confidential Restricted when
 * comb/m/messined with the aggregated modules for this product)
 *                  SOURCE MATERIALS
 * (C) COPYRIGHT International Business Machines Corp. 1991
 * All Rights Reserved
 * Licensed Material - Property of IBM
 *
 * US Government Users Restricted Rights - Use, duplication or
 * disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
 *
 * COPYRIGHT:           5756-030 COPYRIGHT IBM CORP 1991
 *                      LICENSED MATERIAL-PROGRAM PROPERTY OF IBM
 *                      REFER TO COPYRIGHT INSTRUCTIONS FORM NO.G120-2083
 *
 * STATUS:              User Dictionary Maintenance for AIX 3.2
 *
 * CLASSIFICATION:    OCO Source Material - IBM Confidential.
 *                    (IBM Confidential-Restricted when aggregated)
 *
 * FUNCTION:
 *
 * NOTES:               NA.
 *
 */

#include "kje.h"
#include "kjdict.msg.h"
#include "kjdict.euc.h"

char *CU_MSGTIL;
char *CU_MSGCPL;
char *CU_MSGTRE;
char *CU_MSGIVT;
char *CU_MSGCUR;
char *CU_MSGHME;
char *CU_MSGNUD;
char *CU_MSGWER;
char *CU_MSGRER;
char *CU_MSGINU;
char *CU_MSGINP;
char *CU_MSGIV0;
char *CU_MSGIV1;
char *CU_MSGIV2;
char *CU_MSGLOV;
char *CU_MSGNDW;
char *CU_MSGFWE;
char *CU_MSGROT;
char *CU_MSGDPD;
char *CU_MSGDPP;
char *CU_MSGNYM;
char *CU_MSGNGK;
char *CU_MSGIDY;
char *CU_MSGIDG;
char *CU_MSGIGP;
char *CU_MSGNXY;
char *CU_MSGNXG;
char *CU_MSGNFY;
char *CU_MSGNFG;
char *CU_MSGSUC;
char *CU_MSGYOR;
char *CU_MSGHAM;
char *CU_MSGIYM;
char *CU_MSGYGE;
char *CU_MSGERG;
char *CU_MSGSER;
char *CU_MSGSAE;
char *CU_MSGUAE;
char *CU_MSGUUP;
char *CU_MSGURC;
char *CU_MSGEFL;
char *CU_MSGESE;
char *CU_MSGNYR;
char *CU_MSGETE;
char *CU_MSGONC;
char *CU_MSGMAE;
char *CU_MSGUPD;
char *CU_MSGYDT;
char *CU_MSGGDT;
char *CU_MNTITL;
char *CU_MNUFNM;
char *CU_MNSMSG;
char *CU_MNFMSG;
char *CU_MNDAT1;
char *CU_MNDAT2;
char *CU_MNDAT3;
char *CU_MNDAT4;
char *CU_MNDAT5;
char *CU_MNDAT6;
char *CU_MNMAE1;
char *CU_MNDERR;
char *CU_MNBLNK;
char *CU_MNATIT;
char *CU_MNYGEM;
char *CU_MNYOMI;
char *CU_MNGOKU;
char *CU_MNCMGT;
char *CU_MNCMGK;
char *CU_MNCMGF;
char *CU_MNCMGO;
char *CU_MNADIC;
char *CU_MNKAK1;
char *CU_MNNDIC;
char *CU_MNKMSG;
char *CU_MNCTIT;
char *CU_MNKEYE;
char *CU_MNKEY2;
char *CU_MNKEY3;
char *CU_MNKEY5;
char *CU_MNKEY7;
char *CU_MNKEY8;
char *CU_MNKEY9;
char *CU_MNKY12;
char *CU_MNKAK2;
char *CU_MNKAK3;
char *CU_MNYAG1;
char *CU_MNYAG2;
char *CU_MNUTIT;
char *CU_MNDTIT;
char *CU_MNLTIT;
char *CU_MNFMSS;
char *CU_MNPDT1;
char *CU_MNPDT2;
char *CU_MNPDT3;
char *CU_MNPMSG;
char *CU_MNQMSG;
char *CU_AMSGN;
char *CU_BMSGN;
char *CU_CMSGN;
char *CU_DMSGN;
char *CU_EMSGN;
char *CU_FMSGN;
char *CU_GMSGN;
char *CU_HMSGN;
char *CU_IMSGN;
char *CU_JMSGN;
char *CU_KMSGN;
char *CU_LMSGN;
char *CU_MMSGN;
char *CU_NMSGN;
char *CU_OMSGN;
char *CU_PMSGN;
char *CU_QMSGN;
char *CU_RMSGN;
char *CU_SMSGN;
char *CU_TMSGN;
char *CU_UMSGN;
char *CU_VMSGN;
char *CU_WMSGN;
char *CU_XMSGN;
char *CU_YMSGN;
char *CU_ZMSGN;
char *CU_AAMSGN;
char *CU_ABMSGN;
char *CU_ACMSGN;
char *CU_ADMSGN;
char *CU_AEMSGN;
char *CU_AFMSGN;
char *CU_AGMSGN;
char *CU_AHMSGN;
char *CU_AIMSGN;
char *CU_AJMSGN;
char *CU_AKMSGN;
char *CU_ALMSGN;
char *CU_AMMSGN;
char *CU_ANMSGN;
char *CU_AOMSGN;
char *CU_APMSGN;
char *CU_AQMSGN;
char *CU_ARMSGN;
char *CU_ASMSGN;
char *CU_ATMSGN;
char *CU_AUMSGN;
char *CU_AVMSGN;
char *CU_AWMSGN;
char *CU_AXMSGN;
char *CU_AYMSGN;
char *CU_AZMSGN;
char *CU_BAMSGN;
char *CU_BBMSGN;
char *CU_BCMSGN;
char *CU_BDMSGN;
char *CU_BEMSGN;
char *CU_BFMSGN;
char *CU_BGMSGN;
char *CU_ADDING;
char *CU_UPDATING;
char *CU_WRERROR;
char *CU_WRFORCE;

kjinit(convert)
int	convert;	/* Conversion Flag	*/
{
	if(convert == U_SJIS){
		CU_MSGTIL = PC932_MSGTIL;
		CU_MSGCPL = PC932_MSGCPL;
		CU_MSGTRE = PC932_MSGTRE;
		CU_MSGIVT = PC932_MSGIVT;
		CU_MSGCUR = PC932_MSGCUR;
		CU_MSGHME = PC932_MSGHME;
		CU_MSGNUD = PC932_MSGNUD;
		CU_MSGWER = PC932_MSGWER;
		CU_MSGRER = PC932_MSGRER;
		CU_MSGINU = PC932_MSGINU;
		CU_MSGINP = PC932_MSGINP;
		CU_MSGIV0 = PC932_MSGIV0;
		CU_MSGIV1 = PC932_MSGIV1;
		CU_MSGIV2 = PC932_MSGIV2;
		CU_MSGLOV = PC932_MSGLOV;
		CU_MSGNDW = PC932_MSGNDW;
		CU_MSGFWE = PC932_MSGFWE;
		CU_MSGROT = PC932_MSGROT;
		CU_MSGDPD = PC932_MSGDPD;
		CU_MSGDPP = PC932_MSGDPP;
		CU_MSGNYM = PC932_MSGNYM;
		CU_MSGNGK = PC932_MSGNGK;
		CU_MSGIDY = PC932_MSGIDY;
		CU_MSGIDG = PC932_MSGIDG;
		CU_MSGIGP = PC932_MSGIGP;
		CU_MSGNXY = PC932_MSGNXY;
		CU_MSGNXG = PC932_MSGNXG;
		CU_MSGNFY = PC932_MSGNFY;
		CU_MSGNFG = PC932_MSGNFG;
		CU_MSGSUC = PC932_MSGSUC;
		CU_MSGYOR = PC932_MSGYOR;
		CU_MSGHAM = PC932_MSGHAM;
		CU_MSGIYM = PC932_MSGIYM;
		CU_MSGYGE = PC932_MSGYGE;
		CU_MSGERG = PC932_MSGERG;
		CU_MSGSER = PC932_MSGSER;
		CU_MSGSAE = PC932_MSGSAE;
		CU_MSGUAE = PC932_MSGUAE;
		CU_MSGUUP = PC932_MSGUUP;
		CU_MSGURC = PC932_MSGURC;
		CU_MSGEFL = PC932_MSGEFL;
		CU_MSGESE = PC932_MSGESE;
		CU_MSGNYR = PC932_MSGNYR;
		CU_MSGETE = PC932_MSGETE;
		CU_MSGONC = PC932_MSGONC;
		CU_MSGMAE = PC932_MSGMAE;
		CU_MSGUPD = PC932_MSGUPD;
		CU_MSGYDT = PC932_MSGYDT;
		CU_MSGGDT = PC932_MSGGDT;
		CU_MNTITL = PC932_MNTITL;
		CU_MNUFNM = PC932_MNUFNM;
		CU_MNSMSG = PC932_MNSMSG;
		CU_MNFMSG = PC932_MNFMSG;
		CU_MNDAT1 = PC932_MNDAT1;
		CU_MNDAT2 = PC932_MNDAT2;
		CU_MNDAT3 = PC932_MNDAT3;
		CU_MNDAT4 = PC932_MNDAT4;
		CU_MNDAT5 = PC932_MNDAT5;
		CU_MNDAT6 = PC932_MNDAT6;
		CU_MNMAE1 = PC932_MNMAE1;
		CU_MNDERR = PC932_MNDERR;
		CU_MNBLNK = PC932_MNBLNK;
		CU_MNATIT = PC932_MNATIT;
		CU_MNYGEM = PC932_MNYGEM;
		CU_MNYOMI = PC932_MNYOMI;
		CU_MNGOKU = PC932_MNGOKU;
		CU_MNCMGT = PC932_MNCMGT;
		CU_MNCMGK = PC932_MNCMGK;
		CU_MNCMGF = PC932_MNCMGF;
		CU_MNCMGO = PC932_MNCMGO;
		CU_MNADIC = PC932_MNADIC;
		CU_MNKAK1 = PC932_MNKAK1;
		CU_MNNDIC = PC932_MNNDIC;
		CU_MNKMSG = PC932_MNKMSG;
		CU_MNCTIT = PC932_MNCTIT;
		CU_MNKEYE = PC932_MNKEYE;
		CU_MNKEY2 = PC932_MNKEY2;
		CU_MNKEY3 = PC932_MNKEY3;
		CU_MNKEY5 = PC932_MNKEY5;
		CU_MNKEY7 = PC932_MNKEY7;
		CU_MNKEY8 = PC932_MNKEY8;
		CU_MNKEY9 = PC932_MNKEY9;
		CU_MNKY12 = PC932_MNKY12;
		CU_MNKAK2 = PC932_MNKAK2;
		CU_MNKAK3 = PC932_MNKAK3;
		CU_MNYAG1 = PC932_MNYAG1;
		CU_MNYAG2 = PC932_MNYAG2;
		CU_MNUTIT = PC932_MNUTIT;
		CU_MNDTIT = PC932_MNDTIT;
		CU_MNLTIT = PC932_MNLTIT;
		CU_MNFMSS = PC932_MNFMSS;
		CU_MNPDT1 = PC932_MNPDT1;
		CU_MNPDT2 = PC932_MNPDT2;
		CU_MNPDT3 = PC932_MNPDT3;
		CU_MNPMSG = PC932_MNPMSG;
		CU_MNQMSG = PC932_MNQMSG;
		CU_AMSGN  = PC932_AMSGN;
		CU_BMSGN  = PC932_BMSGN;
		CU_CMSGN  = PC932_CMSGN;
		CU_DMSGN  = PC932_DMSGN;
		CU_EMSGN  = PC932_EMSGN;
		CU_FMSGN  = PC932_FMSGN;
		CU_GMSGN  = PC932_GMSGN;
		CU_HMSGN  = PC932_HMSGN;
		CU_IMSGN  = PC932_IMSGN;
		CU_JMSGN  = PC932_JMSGN;
		CU_KMSGN  = PC932_KMSGN;
		CU_LMSGN  = PC932_LMSGN;
		CU_MMSGN  = PC932_MMSGN;
		CU_NMSGN  = PC932_NMSGN;
		CU_OMSGN  = PC932_OMSGN;
		CU_PMSGN  = PC932_PMSGN;
		CU_QMSGN  = PC932_QMSGN;
		CU_RMSGN  = PC932_RMSGN;
		CU_SMSGN  = PC932_SMSGN;
		CU_TMSGN  = PC932_TMSGN;
		CU_UMSGN  = PC932_UMSGN;
		CU_VMSGN  = PC932_VMSGN;
		CU_WMSGN  = PC932_WMSGN;
		CU_XMSGN  = PC932_XMSGN;
		CU_YMSGN  = PC932_YMSGN;
		CU_ZMSGN  = PC932_ZMSGN;
		CU_AAMSGN = PC932_AAMSGN;
		CU_ABMSGN = PC932_ABMSGN;
		CU_ACMSGN = PC932_ACMSGN;
		CU_ADMSGN = PC932_ADMSGN;
		CU_AEMSGN = PC932_AEMSGN;
		CU_AFMSGN = PC932_AFMSGN;
		CU_AGMSGN = PC932_AGMSGN;
		CU_AHMSGN = PC932_AHMSGN;
		CU_AIMSGN = PC932_AIMSGN;
		CU_AJMSGN = PC932_AJMSGN;
		CU_AKMSGN = PC932_AKMSGN;
		CU_ALMSGN = PC932_ALMSGN;
		CU_AMMSGN = PC932_AMMSGN;
		CU_ANMSGN = PC932_ANMSGN;
		CU_AOMSGN = PC932_AOMSGN;
		CU_APMSGN = PC932_APMSGN;
		CU_AQMSGN = PC932_AQMSGN;
		CU_ARMSGN = PC932_ARMSGN;
		CU_ASMSGN = PC932_ASMSGN;
		CU_ATMSGN = PC932_ATMSGN;
		CU_AUMSGN = PC932_AUMSGN;
		CU_AVMSGN = PC932_AVMSGN;
		CU_AWMSGN = PC932_AWMSGN;
		CU_AXMSGN = PC932_AXMSGN;
		CU_AYMSGN = PC932_AYMSGN;
		CU_AZMSGN = PC932_AZMSGN;
		CU_BAMSGN = PC932_BAMSGN;
		CU_BBMSGN = PC932_BBMSGN;
		CU_BCMSGN = PC932_BCMSGN;
		CU_BDMSGN = PC932_BDMSGN;
		CU_BEMSGN = PC932_BEMSGN;
		CU_BFMSGN = PC932_BFMSGN;
		CU_BGMSGN = PC932_BGMSGN;
		CU_ADDING = PC932_ADDING;
		CU_UPDATING = PC932_UPDATING;
		CU_WRERROR = PC932_WRERROR;
		CU_WRFORCE = PC932_WRFORCE;
	} else {
		CU_MSGTIL = EUCJP_MSGTIL;
		CU_MSGCPL = EUCJP_MSGCPL;
		CU_MSGTRE = EUCJP_MSGTRE;
		CU_MSGIVT = EUCJP_MSGIVT;
		CU_MSGCUR = EUCJP_MSGCUR;
		CU_MSGHME = EUCJP_MSGHME;
		CU_MSGNUD = EUCJP_MSGNUD;
		CU_MSGWER = EUCJP_MSGWER;
		CU_MSGRER = EUCJP_MSGRER;
		CU_MSGINU = EUCJP_MSGINU;
		CU_MSGINP = EUCJP_MSGINP;
		CU_MSGIV0 = EUCJP_MSGIV0;
		CU_MSGIV1 = EUCJP_MSGIV1;
		CU_MSGIV2 = EUCJP_MSGIV2;
		CU_MSGLOV = EUCJP_MSGLOV;
		CU_MSGNDW = EUCJP_MSGNDW;
		CU_MSGFWE = EUCJP_MSGFWE;
		CU_MSGROT = EUCJP_MSGROT;
		CU_MSGDPD = EUCJP_MSGDPD;
		CU_MSGDPP = EUCJP_MSGDPP;
		CU_MSGNYM = EUCJP_MSGNYM;
		CU_MSGNGK = EUCJP_MSGNGK;
		CU_MSGIDY = EUCJP_MSGIDY;
		CU_MSGIDG = EUCJP_MSGIDG;
		CU_MSGIGP = EUCJP_MSGIGP;
		CU_MSGNXY = EUCJP_MSGNXY;
		CU_MSGNXG = EUCJP_MSGNXG;
		CU_MSGNFY = EUCJP_MSGNFY;
		CU_MSGNFG = EUCJP_MSGNFG;
		CU_MSGSUC = EUCJP_MSGSUC;
		CU_MSGYOR = EUCJP_MSGYOR;
		CU_MSGHAM = EUCJP_MSGHAM;
		CU_MSGIYM = EUCJP_MSGIYM;
		CU_MSGYGE = EUCJP_MSGYGE;
		CU_MSGERG = EUCJP_MSGERG;
		CU_MSGSER = EUCJP_MSGSER;
		CU_MSGSAE = EUCJP_MSGSAE;
		CU_MSGUAE = EUCJP_MSGUAE;
		CU_MSGUUP = EUCJP_MSGUUP;
		CU_MSGURC = EUCJP_MSGURC;
		CU_MSGEFL = EUCJP_MSGEFL;
		CU_MSGESE = EUCJP_MSGESE;
		CU_MSGNYR = EUCJP_MSGNYR;
		CU_MSGETE = EUCJP_MSGETE;
		CU_MSGONC = EUCJP_MSGONC;
		CU_MSGMAE = EUCJP_MSGMAE;
		CU_MSGUPD = EUCJP_MSGUPD;
		CU_MSGYDT = EUCJP_MSGYDT;
		CU_MSGGDT = EUCJP_MSGGDT;
		CU_MNTITL = EUCJP_MNTITL;
		CU_MNUFNM = EUCJP_MNUFNM;
		CU_MNSMSG = EUCJP_MNSMSG;
		CU_MNFMSG = EUCJP_MNFMSG;
		CU_MNDAT1 = EUCJP_MNDAT1;
		CU_MNDAT2 = EUCJP_MNDAT2;
		CU_MNDAT3 = EUCJP_MNDAT3;
		CU_MNDAT4 = EUCJP_MNDAT4;
		CU_MNDAT5 = EUCJP_MNDAT5;
		CU_MNDAT6 = EUCJP_MNDAT6;
		CU_MNMAE1 = EUCJP_MNMAE1;
		CU_MNDERR = EUCJP_MNDERR;
		CU_MNBLNK = EUCJP_MNBLNK;
		CU_MNATIT = EUCJP_MNATIT;
		CU_MNYGEM = EUCJP_MNYGEM;
		CU_MNYOMI = EUCJP_MNYOMI;
		CU_MNGOKU = EUCJP_MNGOKU;
		CU_MNCMGT = EUCJP_MNCMGT;
		CU_MNCMGK = EUCJP_MNCMGK;
		CU_MNCMGF = EUCJP_MNCMGF;
		CU_MNCMGO = EUCJP_MNCMGO;
		CU_MNADIC = EUCJP_MNADIC;
		CU_MNKAK1 = EUCJP_MNKAK1;
		CU_MNNDIC = EUCJP_MNNDIC;
		CU_MNKMSG = EUCJP_MNKMSG;
		CU_MNCTIT = EUCJP_MNCTIT;
		CU_MNKEYE = EUCJP_MNKEYE;
		CU_MNKEY2 = EUCJP_MNKEY2;
		CU_MNKEY3 = EUCJP_MNKEY3;
		CU_MNKEY5 = EUCJP_MNKEY5;
		CU_MNKEY7 = EUCJP_MNKEY7;
		CU_MNKEY8 = EUCJP_MNKEY8;
		CU_MNKEY9 = EUCJP_MNKEY9;
		CU_MNKY12 = EUCJP_MNKY12;
		CU_MNKAK2 = EUCJP_MNKAK2;
		CU_MNKAK3 = EUCJP_MNKAK3;
		CU_MNYAG1 = EUCJP_MNYAG1;
		CU_MNYAG2 = EUCJP_MNYAG2;
		CU_MNUTIT = EUCJP_MNUTIT;
		CU_MNDTIT = EUCJP_MNDTIT;
		CU_MNLTIT = EUCJP_MNLTIT;
		CU_MNFMSS = EUCJP_MNFMSS;
		CU_MNPDT1 = EUCJP_MNPDT1;
		CU_MNPDT2 = EUCJP_MNPDT2;
		CU_MNPDT3 = EUCJP_MNPDT3;
		CU_MNPMSG = EUCJP_MNPMSG;
		CU_MNQMSG = EUCJP_MNQMSG;
		CU_AMSGN  = EUCJP_AMSGN;
		CU_BMSGN  = EUCJP_BMSGN;
		CU_CMSGN  = EUCJP_CMSGN;
		CU_DMSGN  = EUCJP_DMSGN;
		CU_EMSGN  = EUCJP_EMSGN;
		CU_FMSGN  = EUCJP_FMSGN;
		CU_GMSGN  = EUCJP_GMSGN;
		CU_HMSGN  = EUCJP_HMSGN;
		CU_IMSGN  = EUCJP_IMSGN;
		CU_JMSGN  = EUCJP_JMSGN;
		CU_KMSGN  = EUCJP_KMSGN;
		CU_LMSGN  = EUCJP_LMSGN;
		CU_MMSGN  = EUCJP_MMSGN;
		CU_NMSGN  = EUCJP_NMSGN;
		CU_OMSGN  = EUCJP_OMSGN;
		CU_PMSGN  = EUCJP_PMSGN;
		CU_QMSGN  = EUCJP_QMSGN;
		CU_RMSGN  = EUCJP_RMSGN;
		CU_SMSGN  = EUCJP_SMSGN;
		CU_TMSGN  = EUCJP_TMSGN;
		CU_UMSGN  = EUCJP_UMSGN;
		CU_VMSGN  = EUCJP_VMSGN;
		CU_WMSGN  = EUCJP_WMSGN;
		CU_XMSGN  = EUCJP_XMSGN;
		CU_YMSGN  = EUCJP_YMSGN;
		CU_ZMSGN  = EUCJP_ZMSGN;
		CU_AAMSGN = EUCJP_AAMSGN;
		CU_ABMSGN = EUCJP_ABMSGN;
		CU_ACMSGN = EUCJP_ACMSGN;
		CU_ADMSGN = EUCJP_ADMSGN;
		CU_AEMSGN = EUCJP_AEMSGN;
		CU_AFMSGN = EUCJP_AFMSGN;
		CU_AGMSGN = EUCJP_AGMSGN;
		CU_AHMSGN = EUCJP_AHMSGN;
		CU_AIMSGN = EUCJP_AIMSGN;
		CU_AJMSGN = EUCJP_AJMSGN;
		CU_AKMSGN = EUCJP_AKMSGN;
		CU_ALMSGN = EUCJP_ALMSGN;
		CU_AMMSGN = EUCJP_AMMSGN;
		CU_ANMSGN = EUCJP_ANMSGN;
		CU_AOMSGN = EUCJP_AOMSGN;
		CU_APMSGN = EUCJP_APMSGN;
		CU_AQMSGN = EUCJP_AQMSGN;
		CU_ARMSGN = EUCJP_ARMSGN;
		CU_ASMSGN = EUCJP_ASMSGN;
		CU_ATMSGN = EUCJP_ATMSGN;
		CU_AUMSGN = EUCJP_AUMSGN;
		CU_AVMSGN = EUCJP_AVMSGN;
		CU_AWMSGN = EUCJP_AWMSGN;
		CU_AXMSGN = EUCJP_AXMSGN;
		CU_AYMSGN = EUCJP_AYMSGN;
		CU_AZMSGN = EUCJP_AZMSGN;
		CU_BAMSGN = EUCJP_BAMSGN;
		CU_BBMSGN = EUCJP_BBMSGN;
		CU_BCMSGN = EUCJP_BCMSGN;
		CU_BDMSGN = EUCJP_BDMSGN;
		CU_BEMSGN = EUCJP_BEMSGN;
		CU_BFMSGN = EUCJP_BFMSGN;
		CU_BGMSGN = EUCJP_BGMSGN;
		CU_ADDING = EUCJP_ADDING;
		CU_UPDATING = EUCJP_UPDATING;
		CU_WRERROR = EUCJP_WRERROR;
		CU_WRFORCE = EUCJP_WRFORCE;
	}

#if defined(_DSPMSG)
        printf( "CU_MSGTIL[] = %s\n", CU_MSGTIL );
        printf( "CU_MSGCPL[] = %s\n", CU_MSGCPL );
        printf( "CU_MSGTRE[] = %s\n", CU_MSGTRE );
        printf( "CU_MSGIVT[] = %s\n", CU_MSGIVT );
        printf( "CU_MSGCUR[] = %s\n", CU_MSGCUR );
        printf( "CU_MSGHME[] = %s\n", CU_MSGHME );
        printf( "CU_MSGNUD[] = %s\n", CU_MSGNUD );
        printf( "CU_MSGWER[] = %s\n", CU_MSGWER );
        printf( "CU_MSGRER[] = %s\n", CU_MSGRER );
        printf( "CU_MSGINU[] = %s\n", CU_MSGINU );
        printf( "CU_MSGINP[] = %s\n", CU_MSGINP );
        printf( "CU_MSGIV0[] = %s\n", CU_MSGIV0 );
        printf( "CU_MSGIV1[] = %s\n", CU_MSGIV1 );
        printf( "CU_MSGIV2[] = %s\n", CU_MSGIV2 );
        printf( "CU_MSGLOV[] = %s\n", CU_MSGLOV );
        printf( "CU_MSGNDW[] = %s\n", CU_MSGNDW );
        printf( "CU_MSGFWE[] = %s\n", CU_MSGFWE );
        printf( "CU_MSGROT[] = %s\n", CU_MSGROT );
        printf( "CU_MSGDPD[] = %s\n", CU_MSGDPD );
        printf( "CU_MSGDPP[] = %s\n", CU_MSGDPP );
        printf( "CU_MSGNYM[] = %s\n", CU_MSGNYM );
        printf( "CU_MSGNGK[] = %s\n", CU_MSGNGK );
        printf( "CU_MSGIDY[] = %s\n", CU_MSGIDY );
        printf( "CU_MSGIDG[] = %s\n", CU_MSGIDG );
        printf( "CU_MSGIGP[] = %s\n", CU_MSGIGP );
        printf( "CU_MSGNXY[] = %s\n", CU_MSGNXY );
        printf( "CU_MSGNXG[] = %s\n", CU_MSGNXG );
        printf( "CU_MSGNFY[] = %s\n", CU_MSGNFY );
        printf( "CU_MSGNFG[] = %s\n", CU_MSGNFG );
        printf( "CU_MSGSUC[] = %s\n", CU_MSGSUC );
        printf( "CU_MSGYOR[] = %s\n", CU_MSGYOR );
        printf( "CU_MSGHAM[] = %s\n", CU_MSGHAM );
        printf( "CU_MSGIYM[] = %s\n", CU_MSGIYM );
        printf( "CU_MSGYGE[] = %s\n", CU_MSGYGE );
        printf( "CU_MSGERG[] = %s\n", CU_MSGERG );
        printf( "CU_MSGSER[] = %s\n", CU_MSGSER );
        printf( "CU_MSGSAE[] = %s\n", CU_MSGSAE );
        printf( "CU_MSGUAE[] = %s\n", CU_MSGUAE );
        printf( "CU_MSGUUP[] = %s\n", CU_MSGUUP );
        printf( "CU_MSGURC[] = %s\n", CU_MSGURC );
        printf( "CU_MSGEFL[] = %s\n", CU_MSGEFL );
        printf( "CU_MSGESE[] = %s\n", CU_MSGESE );
        printf( "CU_MSGNYR[] = %s\n", CU_MSGNYR );
        printf( "CU_MSGETE[] = %s\n", CU_MSGETE );
        printf( "CU_MSGONC[] = %s\n", CU_MSGONC );
        printf( "CU_MSGMAE[] = %s\n", CU_MSGMAE );
        printf( "CU_MSGUPD[] = %s\n", CU_MSGUPD );
        printf( "CU_MSGYDT[] = %s\n", CU_MSGYDT );
        printf( "CU_MSGGDT[] = %s\n", CU_MSGGDT );
        printf( "CU_MNTITL[] = %s\n", CU_MNTITL );
        printf( "CU_MNUFNM[] = %s\n", CU_MNUFNM );
        printf( "CU_MNSMSG[] = %s\n", CU_MNSMSG );
        printf( "CU_MNFMSG[] = %s\n", CU_MNFMSG );
        printf( "CU_MNDAT1[] = %s\n", CU_MNDAT1 );
        printf( "CU_MNDAT2[] = %s\n", CU_MNDAT2 );
        printf( "CU_MNDAT3[] = %s\n", CU_MNDAT3 );
        printf( "CU_MNDAT4[] = %s\n", CU_MNDAT4 );
        printf( "CU_MNDAT5[] = %s\n", CU_MNDAT5 );
        printf( "CU_MNDAT6[] = %s\n", CU_MNDAT6 );
        printf( "CU_MNMAE1[] = %s\n", CU_MNMAE1 );
        printf( "CU_MNDERR[] = %s\n", CU_MNDERR );
        printf( "CU_MNBLNK[] = %s\n", CU_MNBLNK );
        printf( "CU_MNATIT[] = %s\n", CU_MNATIT );
        printf( "CU_MNYGEM[] = %s\n", CU_MNYGEM );
        printf( "CU_MNYOMI[] = %s\n", CU_MNYOMI );
        printf( "CU_MNGOKU[] = %s\n", CU_MNGOKU );
        printf( "CU_MNCMGT[] = %s\n", CU_MNCMGT );
        printf( "CU_MNCMGK[] = %s\n", CU_MNCMGK );
        printf( "CU_MNCMGF[] = %s\n", CU_MNCMGF );
        printf( "CU_MNCMGO[] = %s\n", CU_MNCMGO );
        printf( "CU_MNADIC[] = %s\n", CU_MNADIC );
        printf( "CU_MNKAK1[] = %s\n", CU_MNKAK1 );
        printf( "CU_MNNDIC[] = %s\n", CU_MNNDIC );
        printf( "CU_MNKMSG[] = %s\n", CU_MNKMSG );
        printf( "CU_MNCTIT[] = %s\n", CU_MNCTIT );
        printf( "CU_MNKEYE[] = %s\n", CU_MNKEYE );
        printf( "CU_MNKEY2[] = %s\n", CU_MNKEY2 );
        printf( "CU_MNKEY3[] = %s\n", CU_MNKEY3 );
        printf( "CU_MNKEY5[] = %s\n", CU_MNKEY5 );
        printf( "CU_MNKEY7[] = %s\n", CU_MNKEY7 );
        printf( "CU_MNKEY8[] = %s\n", CU_MNKEY8 );
        printf( "CU_MNKEY9[] = %s\n", CU_MNKEY9 );
        printf( "CU_MNKY12[] = %s\n", CU_MNKY12 );
        printf( "CU_MNKAK2[] = %s\n", CU_MNKAK2 );
        printf( "CU_MNKAK3[] = %s\n", CU_MNKAK3 );
        printf( "CU_MNYAG1[] = %s\n", CU_MNYAG1 );
        printf( "CU_MNYAG2[] = %s\n", CU_MNYAG2 );
        printf( "CU_MNUTIT[] = %s\n", CU_MNUTIT );
        printf( "CU_MNDTIT[] = %s\n", CU_MNDTIT );
        printf( "CU_MNLTIT[] = %s\n", CU_MNLTIT );
        printf( "CU_MNFMSS[] = %s\n", CU_MNFMSS );
        printf( "CU_MNPDT1[] = %s\n", CU_MNPDT1 );
        printf( "CU_MNPDT2[] = %s\n", CU_MNPDT2 );
        printf( "CU_MNPDT3[] = %s\n", CU_MNPDT3 );
        printf( "CU_MNPMSG[] = %s\n", CU_MNPMSG );
        printf( "CU_MNQMSG[] = %s\n", CU_MNQMSG );
        printf( "CU_AMSGN[] = %s\n", CU_AMSGN );
        printf( "CU_BMSGN[] = %s\n", CU_BMSGN );
        printf( "CU_CMSGN[] = %s\n", CU_CMSGN );
        printf( "CU_DMSGN[] = %s\n", CU_DMSGN );
        printf( "CU_EMSGN[] = %s\n", CU_EMSGN );
        printf( "CU_FMSGN[] = %s\n", CU_FMSGN );
        printf( "CU_GMSGN[] = %s\n", CU_GMSGN );
        printf( "CU_HMSGN[] = %s\n", CU_HMSGN );
        printf( "CU_IMSGN[] = %s\n", CU_IMSGN );
        printf( "CU_JMSGN[] = %s\n", CU_JMSGN );
        printf( "CU_KMSGN[] = %s\n", CU_KMSGN );
        printf( "CU_LMSGN[] = %s\n", CU_LMSGN );
        printf( "CU_MMSGN[] = %s\n", CU_MMSGN );
        printf( "CU_NMSGN[] = %s\n", CU_NMSGN );
        printf( "CU_OMSGN[] = %s\n", CU_OMSGN );
        printf( "CU_PMSGN[] = %s\n", CU_PMSGN );
        printf( "CU_QMSGN[] = %s\n", CU_QMSGN );
        printf( "CU_RMSGN[] = %s\n", CU_RMSGN );
        printf( "CU_SMSGN[] = %s\n", CU_SMSGN );
        printf( "CU_TMSGN[] = %s\n", CU_TMSGN );
        printf( "CU_UMSGN[] = %s\n", CU_UMSGN );
        printf( "CU_VMSGN[] = %s\n", CU_VMSGN );
        printf( "CU_WMSGN[] = %s\n", CU_WMSGN );
        printf( "CU_XMSGN[] = %s\n", CU_XMSGN );
        printf( "CU_YMSGN[] = %s\n", CU_YMSGN );
        printf( "CU_ZMSGN[] = %s\n", CU_ZMSGN );
        printf( "CU_AAMSGN[] = %s\n", CU_AAMSGN );
        printf( "CU_ABMSGN[] = %s\n", CU_ABMSGN );
        printf( "CU_ACMSGN[] = %s\n", CU_ACMSGN );
        printf( "CU_ADMSGN[] = %s\n", CU_ADMSGN );
        printf( "CU_AEMSGN[] = %s\n", CU_AEMSGN );
        printf( "CU_AFMSGN[] = %s\n", CU_AFMSGN );
        printf( "CU_AGMSGN[] = %s\n", CU_AGMSGN );
        printf( "CU_AHMSGN[] = %s\n", CU_AHMSGN );
        printf( "CU_AIMSGN[] = %s\n", CU_AIMSGN );
        printf( "CU_AJMSGN[] = %s\n", CU_AJMSGN );
        printf( "CU_AKMSGN[] = %s\n", CU_AKMSGN );
        printf( "CU_ALMSGN[] = %s\n", CU_ALMSGN );
        printf( "CU_AMMSGN[] = %s\n", CU_AMMSGN );
        printf( "CU_ANMSGN[] = %s\n", CU_ANMSGN );
        printf( "CU_AOMSGN[] = %s\n", CU_AOMSGN );
        printf( "CU_APMSGN[] = %s\n", CU_APMSGN );
        printf( "CU_AQMSGN[] = %s\n", CU_AQMSGN );
        printf( "CU_ARMSGN[] = %s\n", CU_ARMSGN );
        printf( "CU_ASMSGN[] = %s\n", CU_ASMSGN );
        printf( "CU_ATMSGN[] = %s\n", CU_ATMSGN );
        printf( "CU_AUMSGN[] = %s\n", CU_AUMSGN );
        printf( "CU_AVMSGN[] = %s\n", CU_AVMSGN );
        printf( "CU_AWMSGN[] = %s\n", CU_AWMSGN );
        printf( "CU_AXMSGN[] = %s\n", CU_AXMSGN );
        printf( "CU_AYMSGN[] = %s\n", CU_AYMSGN );
        printf( "CU_AZMSGN[] = %s\n", CU_AZMSGN );
        printf( "CU_BAMSGN[] = %s\n", CU_BAMSGN );
        printf( "CU_BBMSGN[] = %s\n", CU_BBMSGN );
        printf( "CU_BCMSGN[] = %s\n", CU_BCMSGN );
        printf( "CU_BDMSGN[] = %s\n", CU_BDMSGN );
        printf( "CU_BEMSGN[] = %s\n", CU_BEMSGN );
        printf( "CU_BFMSGN[] = %s\n", CU_BFMSGN );
        printf( "CU_BGMSGN[] = %s\n", CU_BGMSGN );
        printf( "CU_ADDING[] = %s\n", CU_ADDING );
        printf( "CU_UPDATING[] = %s\n", CU_UPDATING );
        printf( "CU_WRERROR[] = %s\n", CU_WRERROR );
        printf( "CU_WRFORCE[] = %s\n", CU_WRFORCE );
	exit (0);
#endif /* defined(_DSPMSG) */

}
