# @(#)39        1.1  src/bos/usr/lib/boot/protoext/cd.proto.ext.scsi.disk.rte.S, bosboot, bos411, 9428A410j 6/1/94 10:16:18
#
# COMPONENT_NAME: BOSBOOT
#
# FUNCTIONS:  proto entry file
#
# ORIGINS: 27
#
# (C) COPYRIGHT International Business Machines Corp. 1993, 1994
# All Rights Reserved
# Licensed Materials - Property of IBM
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#
# -------------------------------------------------------------------------
#
# LPP_NAME: bos.dev.scsi.disk.rte
#
cfgsccd ---- 777 0 0 /usr/lib/methods/cfgsccd
scdisk    ---- 777 0 0 /usr/lib/drivers/scdisk
scdiskpin ---- 777 0 0 /usr/lib/drivers/scdiskpin
