# @(#)62        1.1  src/bos/usr/lib/boot/protoext/cd.proto.ext.mca.8efc.com.S, bosboot, bos411, 9428A410j 3/22/94 16:01:48
#
# COMPONENT_NAME: BOSBOOT
#
# FUNCTIONS:  proto entry file
#
# ORIGINS: 27
#
# (C) COPYRIGHT International Business Machines Corp. 1994
# All Rights Reserved
# Licensed Materials - Property of IBM
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#
# -------------------------------------------------------------------------
#
# LPP_NAME: bos.dev.mca.8efc.com
#
vscsidd    ---- 777 0 0 /usr/lib/drivers/vscsidd
vscsiddpin ---- 777 0 0 /usr/lib/drivers/vscsiddpin
cfgvscsi   ---- 777 0 0 /usr/lib/methods/cfgvscsi
