# @(#)68        1.1  src/bos/usr/lib/boot/protoext/cd.proto.ext.mca.8fba.rte.S, bosboot, bos411, 9428A410j 3/22/94 16:02:14
#
# COMPONENT_NAME: BOSBOOT
#
# FUNCTIONS:  proto entry file
#
# ORIGINS: 27
#
# (C) COPYRIGHT International Business Machines Corp. 1994
# All Rights Reserved
# Licensed Materials - Property of IBM
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#
# -------------------------------------------------------------------------
#
# LPP_NAME: bos.dev.mca.8fba.rte
#
pscsi720dd     ---- 777 0 0 /usr/lib/drivers/pscsi720dd
pscsi720ddpin  ---- 777 0 0 /usr/lib/drivers/pscsi720ddpin
