# @(#)62        1.1  src/bos/usr/lib/boot/protoext/disk.proto.ext.mca.8ff4.rte.S, bosboot, bos411, 9428A410j 12/9/93 13:20:28
#
# COMPONENT_NAME: BOSBOOT
#
# FUNCTIONS:  proto entry file
#
# ORIGINS: 27
#
# (C) COPYRIGHT International Business Machines Corp. 1993
# All Rights Reserved
# Licensed Materials - Property of IBM
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#
# -------------------------------------------------------------------------
#
# LPP_NAME: bos.dev.mca.8ff4.rte
#
pscsidd     ---- 777 0 0 /usr/lib/drivers/pscsidd 
pscsiddpin  ---- 777 0 0 /usr/lib/drivers/pscsiddpin
