# @(#)58        1.2  src/bos/usr/lib/boot/protoext/disk.proto.ext.mca.8efc.rte.S, bosboot, bos411, 9428A410j 4/13/94 09:52:16
#
# COMPONENT_NAME: BOSBOOT
#
# FUNCTIONS:  proto entry file
#
# ORIGINS: 27
#
# (C) COPYRIGHT International Business Machines Corp. 1993
# All Rights Reserved
# Licensed Materials - Property of IBM
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#
# -------------------------------------------------------------------------
#
# LPP_NAME: bos.dev.mca.8efc.rte
#
ascsidd    ---- 777 0 0 /usr/lib/drivers/ascsidd
ascsiddpin ---- 777 0 0 /usr/lib/drivers/ascsiddpin
cfgascsi   ---- 777 0 0 /usr/lib/methods/cfgascsi
