# @(#)59        1.1  src/bos/usr/lib/boot/protoext/disk.proto.ext.mca.8f78.rte.S, bosboot, bos411, 9428A410j 12/9/93 13:20:07
#
# COMPONENT_NAME: BOSBOOT
#
# FUNCTIONS:  proto entry file
#
# ORIGINS: 27
#
# (C) COPYRIGHT International Business Machines Corp. 1993
# All Rights Reserved
# Licensed Materials - Property of IBM
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#
# -------------------------------------------------------------------------
#
# LPP_NAME: bos.dev.mca.8f78.rte
#
sd          ---- 777 0 0 /usr/lib/drivers/sd 
sdpin       ---- 777 0 0 /usr/lib/drivers/sdpin 
cfgserdasda ---- 777 0 0 /usr/lib/methods/cfgserdasda 
cfgserdasdc ---- 777 0 0 /usr/lib/methods/cfgserdasdc 
cfgserdasdd ---- 777 0 0 /usr/lib/methods/cfgserdasdd 
