# @(#)69	1.1  src/bos/usr/lib/boot/protoext/ent.proto.ext.mca.8ef2.com.S, bosboot, bos411, 9428A410j 12/9/93 13:21:22
#
# COMPONENT_NAME: BOSBOOT
#
# FUNCTIONS:  proto entry file
#
# ORIGINS: 27
#
# (C) COPYRIGHT International Business Machines Corp. 1989, 1993
# All Rights Reserved
# Licensed Materials - Property of IBM
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#
# -------------------------------------------------------------------------
#
# LPP_NAME: bos.dev.mca.8ef2.com
#
ethdd  ---- 777 0 0 /usr/lib/drivers/ethdd 
cfgeth ---- 777 0 0 /usr/lib/methods/cfgeth 
