# @(#)04	1.1  src/bos/usr/lib/boot/protoext/ent.proto.ext.mca.8ef5.com.S, bosboot, bos411, 9428A410j 6/21/94 07:40:10
#
# COMPONENT_NAME: BOSBOOT
#
# FUNCTIONS:  proto entry file
#
# ORIGINS: 27
#
# (C) COPYRIGHT International Business Machines Corp. 1993, 1994
# All Rights Reserved
# Licensed Materials - Property of IBM
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#
# -------------------------------------------------------------------------
#
# LPP_NAME: devices.mca.8ef5.com
#
cfgdmxeth ---- 777 0 0 /usr/lib/methods/cfgdmxeth
eth_demux ---- 777 0 0 /usr/lib/drivers/eth_demux
ucfgent ---- 777 0 0 /usr/lib/methods/ucfgent
