# @(#)24 1.1 src/bos/usr/lib/boot/protoext/fddi.proto.ext.sys.mca.rte.S, bosboot, bos411, 9428A410j 2/7/94 11:36:35
#
# COMPONENT_NAME: BOSBOOT
#
# FUNCTIONS:  proto entry file
#
# ORIGINS: 27
#
# (C) COPYRIGHT International Business Machines Corp. 1993
# All Rights Reserved
# Licensed Materials - Property of IBM
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#
# -------------------------------------------------------------------------
#
# LPP_NAME: bos.dev.sys.mca.rte
#
cfgbus ---- 777 0 0 /usr/lib/methods/cfgbus
