# @(#)05	1.1  src/bos/usr/lib/boot/protoext/fddi.proto.ext.mca.8ef4.com.S, bosboot, bos411, 9428A410j 6/21/94 07:40:55
#
# COMPONENT_NAME: BOSBOOT
#
# FUNCTIONS:  proto entry file
#
# ORIGINS: 27
#
# (C) COPYRIGHT International Business Machines Corp. 1993, 1994
# All Rights Reserved
# Licensed Materials - Property of IBM
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#
# -------------------------------------------------------------------------
#
# LPP_NAME: devices.mca.8ef4.com
#
cfgdmxfddi ---- 777 0 0 /usr/lib/methods/cfgdmxfddi
fddi_demux ---- 777 0 0 /usr/lib/drivers/fddi_demux
ucfgfddi ---- 777 0 0 /usr/lib/methods/ucfgfddi
