# @(#)74        1.3  src/bos/usr/lib/boot/protoext/fddi.proto.ext.mca.8ef4.ucode.S, bosboot, bos41J, 9516B_all 4/18/95 17:10:27
#
# COMPONENT_NAME: BOSBOOT
#
# FUNCTIONS:  proto entry file
#
# ORIGINS: 27
#
# (C) COPYRIGHT International Business Machines Corp. 1993
# All Rights Reserved
# Licensed Materials - Property of IBM
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#
# -------------------------------------------------------------------------
#
# LPP_NAME: bos.dev.mca.8ef4.ucode
#
8ef4m.02.04 ---- 777 0 0 /usr/lib/microcode/8ef4m.02.04
