# @(#)53    1.19  src/bos/usr/lib/boot/protoext/Makefile, bosboot, bos41J, 9509A_all 2/17/95 09:39:41
#
# COMPONENT_NAME: BOSBOOT
#
# FUNCTIONS:
#
# ORIGINS: 27
#
# IBM CONFIDENTIAL -- (IBM Confidential Restricted when
# combined with the aggregated modules for this product)
#                  SOURCE MATERIALS
# (C) COPYRIGHT International Business Machines Corp. 1988, 1994
# All Rights Reserved
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#

SCRIPTS = \
	rs6k.pcfg \
	rs6ksmp.pcfg \
	cd.proto.ext.base.com \
	cd.proto.ext.mca.8d77.rte \
	cd.proto.ext.mca.8efc.com \
	cd.proto.ext.mca.8efc.rte \
	cd.proto.ext.mca.8fba.com \
	cd.proto.ext.mca.8fba.rte \
	cd.proto.ext.mca.8ff4.rte \
	cd.proto.ext.mca.df5f.com \
	cd.proto.ext.scsi.disk.rte \
	cd.proto.ext.sys.mca.rte \
	disk.proto.ext.base.com \
	disk.proto.ext.mca.8d77.rte \
	disk.proto.ext.mca.8efc.com \
	disk.proto.ext.mca.8efc.rte \
	disk.proto.ext.mca.8f78.rte \
	disk.proto.ext.mca.8fba.com \
	disk.proto.ext.mca.8fba.rte \
	disk.proto.ext.mca.8ff4.rte \
	disk.proto.ext.mca.df5f.com \
	disk.proto.ext.mca.df9f.rte \
	disk.proto.ext.scsi.disk.rte \
	disk.proto.ext.sys.mca.rte \
	ent.proto.ext.base.com \
	ent.proto.ext.mca.8ef2.com \
	ent.proto.ext.mca.8ef5.com \
	ent.proto.ext.mca.8ef5.rte \
	ent.proto.ext.mca.df5f.com \
	ent.proto.ext.sys.mca.rte \
	fddi.proto.ext.base.com \
	fddi.proto.ext.mca.8ef4.com \
	fddi.proto.ext.mca.8ef4.rte \
	fddi.proto.ext.mca.8ef4.ucode \
	fddi.proto.ext.mca.df5f.com \
	fddi.proto.ext.sys.mca.rte \
	tape.proto.ext.base.com \
	tape.proto.ext.graphics.com \
	tape.proto.ext.mca.8d77.rte \
	tape.proto.ext.mca.8d77.ucode \
	tape.proto.ext.mca.8ee3.rte \
	tape.proto.ext.mca.8ee3.ucode \
	tape.proto.ext.mca.8ee4.rte \
	tape.proto.ext.mca.8efc.com \
	tape.proto.ext.mca.8efc.rte \
	tape.proto.ext.mca.8f78.rte \
	tape.proto.ext.mca.8f9a.rte \
	tape.proto.ext.mca.8f9a.ucode \
	tape.proto.ext.mca.8fba.com \
	tape.proto.ext.mca.8fba.rte \
	tape.proto.ext.mca.8ff4.rte \
	tape.proto.ext.mca.8ffd.rte \
	tape.proto.ext.mca.8ffd.ucode \
	tape.proto.ext.mca.df5f.com \
	tape.proto.ext.mca.df9f.rte \
	tape.proto.ext.mca.edd0.com \
	tape.proto.ext.mca.f6f8.rte \
	tape.proto.ext.scsi.disk.rte \
	tape.proto.ext.scsi.tape.rte \
	tape.proto.ext.sio.fda.com \
	tape.proto.ext.sio.fda.rte \
	tape.proto.ext.sio.ktma.com \
	tape.proto.ext.sio.ktma.rte \
	tape.proto.ext.sys.mca.rte \
	tape.proto.ext.sys.sga.rte \
	tape.proto.ext.sys.sgabus.rte \
	tape.proto.ext.tty.rte \
	tok.proto.ext.base.com \
	tok.proto.ext.mca.8fa2.rte \
	tok.proto.ext.mca.8fc8.com \
	tok.proto.ext.mca.8fc8.rte \
	tok.proto.ext.mca.8fc8.ucode \
	tok.proto.ext.mca.df5f.com \
	tok.proto.ext.sys.mca.rte

ILIST		= ${SCRIPTS}

IDIR = /usr/lib/boot/protoext/

.include <${RULES_MK}>
