# @(#)88 1.1 src/bos/usr/lib/boot/protoext/tape.proto.ext.mca.8f9a.rte.S, bosboot, bos412, 9447B 11/17/94 09:13:59
#
# COMPONENT_NAME: BOSBOOT
#
# FUNCTIONS:  proto entry file
#
# ORIGINS: 27
#
# (C) COPYRIGHT International Business Machines Corp. 1994
# All Rights Reserved
# Licensed Materials - Property of IBM
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#
# -------------------------------------------------------------------------
#
# LPP_NAME: bos.dev.mca.8f9a.rte
#
nepdd_load  ---- 777 0 0 /usr/lib/drivers/nepdd_load
nepdd_loadpin  ---- 777 0 0 /usr/lib/drivers/nepdd_loadpin
cfg_nep ---- 777 0 0 /usr/lib/methods/cfg_nep
