# @(#)83	1.1  src/bos/usr/lib/boot/protoext/tape.proto.ext.sio.ktma.com.S, bosboot, bos41J, 9509A_all 2/17/95 10:29:46
#
# COMPONENT_NAME: BOSBOOT
#
# FUNCTIONS:  proto entry file
#
# ORIGINS: 27
#
# (C) COPYRIGHT International Business Machines Corp. 1995
# All Rights Reserved
# Licensed Materials - Property of IBM
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#
# -------------------------------------------------------------------------
#
# LPP_NAME: bos.dev.sio.ktma.com
#
cfgkbd_std  ---- 777 0 0 /usr/lib/methods/cfgkbd_std
