# @(#)97        1.2  src/bos/usr/lib/boot/protoext/tape.proto.ext.sys.sga.rte.S, bosboot, bos411, 9428A410j 2/22/94 14:16:41
#
# COMPONENT_NAME: BOSBOOT
#
# FUNCTIONS:  proto entry file
#
# ORIGINS: 27
#
# (C) COPYRIGHT International Business Machines Corp. 1993
# All Rights Reserved
# Licensed Materials - Property of IBM
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#
# -------------------------------------------------------------------------
#
# LPP_NAME: bos.dev.sys.sga.rte
#
sgadd ---- 777 0 0 /usr/lib/drivers/sgadd
cfgsga ---- 777 0 0 /usr/lib/methods/cfgsga
