# @(#)91        1.2  src/bos/usr/lib/boot/protoext/tape.proto.ext.scsi.disk.rte.S, bosboot, bos411, 9428A410j 2/24/94 15:04:05
#
# COMPONENT_NAME: BOSBOOT
#
# FUNCTIONS:  proto entry file
#
# ORIGINS: 27
#
# (C) COPYRIGHT International Business Machines Corp. 1993
# All Rights Reserved
# Licensed Materials - Property of IBM
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#
# -------------------------------------------------------------------------
#
# LPP_NAME: bos.dev.scsi.disk.rte
#
cfgscdisk ---- 777 0 0 /usr/lib/methods/cfgscdisk
scdisk    ---- 777 0 0 /usr/lib/drivers/scdisk
scdiskpin ---- 777 0 0 /usr/lib/drivers/scdiskpin
