# @(#)76        1.3  src/bos/usr/lib/boot/protoext/tape.proto.ext.graphics.com.S, bosboot, bos411, 9428A410j 6/2/94 09:36:48
#
# COMPONENT_NAME: BOSBOOT
#
# FUNCTIONS:  proto entry file
#
# ORIGINS: 27
#
# (C) COPYRIGHT International Business Machines Corp. 1993, 1994
# All Rights Reserved
# Licensed Materials - Property of IBM
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#
# -------------------------------------------------------------------------
#
# LPP_NAME: bos.dev.graphics.com
#
ccmdd  ---- 777 0 0 /usr/lib/drivers/ccmdd
ccmdd_pin  ---- 777 0 0 /usr/lib/drivers/ccmdd_pin
lft_loadpin   ---- 777 0 0 /usr/lib/drivers/lft_loadpin
cfglft  ---- 777 0 0 /usr/lib/methods/cfglft
startlft  ---- 777 0 0 /usr/lib/methods/startlft
Erg11.iso1.snf  ---- 777 0 0 /usr/lpp/fonts/Erg11.iso1.snf
Erg22.iso1.snf  ---- 777 0 0 /usr/lpp/fonts/Erg22.iso1.snf
