# @(#)78        1.3  src/bos/usr/lib/boot/protoext/tape.proto.ext.mca.8d77.ucode.S, bosboot, bos411, 9428A410j 7/9/94 15:25:21
#
# COMPONENT_NAME: BOSBOOT
#
# FUNCTIONS:  proto entry file
#
# ORIGINS: 27
#
# (C) COPYRIGHT International Business Machines Corp. 1993, 1994
# All Rights Reserved
# Licensed Materials - Property of IBM
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#
# -------------------------------------------------------------------------
#
# LPP_NAME: bos.dev.mca.8d77.ucode
#
8d77.32.54 ---- 777 0 0 /usr/lib/microcode/8d77.32.54
8d77.42.58 l--- 777 0 0 /usr/lib/microcode/8d77.44.58
8d77.44.58 ---- 777 0 0 /usr/lib/microcode/8d77.44.58
