# @(#)87        1.2  src/bos/usr/lib/boot/protoext/tape.proto.ext.mca.8ffd.ucode.S, bosboot, bos411, 9428A410j 3/24/94 11:15:14
#
# COMPONENT_NAME: BOSBOOT
#
# FUNCTIONS:  proto entry file
#
# ORIGINS: 27
#
# (C) COPYRIGHT International Business Machines Corp. 1993
# All Rights Reserved
# Licensed Materials - Property of IBM
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#
# -------------------------------------------------------------------------
#
# LPP_NAME: bos.dev.mca.8ffd.ucode
#
8ffdc2.00.04 ---- 777 0 0 /usr/lib/microcode/8ffdc2.00.04
8ffdgt.00.04 ---- 777 0 0 /usr/lib/microcode/8ffdgt.00.04
8ffdgu.00.04 ---- 777 0 0 /usr/lib/microcode/8ffdgu.00.04
8ffdgv.00.04 ---- 777 0 0 /usr/lib/microcode/8ffdgv.00.04
8ffdsh.00.04 ---- 777 0 0 /usr/lib/microcode/8ffdsh.00.04
8ffdvp.00.03 ---- 777 0 0 /usr/lib/microcode/8ffdvp.00.03 
