# @(#)94        1.2  src/bos/usr/lib/boot/protoext/tape.proto.ext.sio.ktma.rte.S, bosboot, bos41J, 9509A_all 2/17/95 09:32:13
#
# COMPONENT_NAME: BOSBOOT
#
# FUNCTIONS:  proto entry file
#
# ORIGINS: 27
#
# (C) COPYRIGHT International Business Machines Corp. 1995
# All Rights Reserved
# Licensed Materials - Property of IBM
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#
# -------------------------------------------------------------------------
#
# LPP_NAME: bos.dev.sio.ktma.rte
#
kbddd   ---- 777 0 0 /usr/lib/drivers/kbddd
ktsdd   ---- 777 0 0 /usr/lib/drivers/ktsdd
cfgktsm  ---- 777 0 0 /usr/lib/methods/cfgktsm
