# @(#)98        1.2  src/bos/usr/lib/boot/protoext/tape.proto.ext.tty.rte.S, bosboot, bos41J, 9519B_all 5/9/95 12:32:35
#
# COMPONENT_NAME: BOSBOOT
#
# FUNCTIONS:  proto entry file
#
# ORIGINS: 27
#
# (C) COPYRIGHT International Business Machines Corp. 1993
# All Rights Reserved
# Licensed Materials - Property of IBM
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#
# -------------------------------------------------------------------------
#
# LPP_NAME: bos.dev.tty.rte
#
cfgtty  ---- 777 0 0 /usr/lib/methods/cfgtty
rsddload  ---- 777 0 0 /usr/lib/methods/rsddload
chgtty  ---- 777 0 0 /usr/lib/methods/chgtty
starttty  ---- 777 0 0 /usr/lib/methods/starttty
