# @(#)89 1.1 src/bos/usr/lib/boot/protoext/tape.proto.ext.mca.8f9a.ucode.S, bosboot, bos412, 9447B 11/17/94 09:14:08
#
# COMPONENT_NAME: BOSBOOT
#
# FUNCTIONS:  proto entry file
#
# ORIGINS: 27
#
# (C) COPYRIGHT International Business Machines Corp. 1994
# All Rights Reserved
# Licensed Materials - Property of IBM
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#
# -------------------------------------------------------------------------
#
# LPP_NAME: bos.dev.mca.8f9a.ucode
#
8f9a.00.00 ---- 777 0 0 /usr/lib/microcode/8f9a.00.00
