# @(#)93	1.2  src/bos/usr/lib/boot/protoext/tape.proto.ext.sio.fda.rte.S, bosboot, bos411, 9428A410j 6/28/94 07:01:03
#
# COMPONENT_NAME: BOSBOOT
#
# FUNCTIONS:  proto entry file
#
# ORIGINS: 27
#
# (C) COPYRIGHT International Business Machines Corp. 1993
# All Rights Reserved
# Licensed Materials - Property of IBM
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#
# -------------------------------------------------------------------------
#
# LPP_NAME: bos.dev.sio.fda.rte
#
fd ---- 777 0 0 /usr/lib/drivers/fd 
cfgfda ---- 777 0 0 /usr/lib/methods/cfgfda 
