# @(#)62        1.2  src/bos/usr/lib/boot/protoext/tape.proto.ext.base.com.S, bosboot, bos411, 9428A410j 6/2/94 09:15:02
#
# COMPONENT_NAME: BOSBOOT
#
# FUNCTIONS:  proto entry file
#
# ORIGINS: 27
#
# (C) COPYRIGHT International Business Machines Corp. 1993, 1994
# All Rights Reserved
# Licensed Materials - Property of IBM
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#
# -------------------------------------------------------------------------
#
# LPP_NAME: devices.base.com
#
cfg_graphics ---- 777 0 0 /usr/lib/methods/cfg_graphics
defsys ---- 777 0 0 /usr/lib/methods/defsys
