# @(#)05        1.1  src/bos/usr/lib/boot/protoext/tape.proto.ext.mca.8ee3.rte.S, bosboot, bos411, 9428A410j 2/22/94 14:30:46
#
# COMPONENT_NAME: BOSBOOT
#
# FUNCTIONS:  proto entry file
#
# ORIGINS: 27
#
# (C) COPYRIGHT International Business Machines Corp. 1993
# All Rights Reserved
# Licensed Materials - Property of IBM
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#
# -------------------------------------------------------------------------
#
# LPP_NAME: devices.mca.8ee3.rte
#
mid_cdd ---- 777 0 0	/usr/lib/drivers/mid_cdd
mid_cdd_pin ---- 777 0 0	/usr/lib/drivers/mid_cdd_pin
cfg_mid ---- 777 0 0	/usr/lib/methods/cfg_mid
