# @(#)01        1.1  src/bos/usr/lib/boot/protoext/tok.proto.ext.mca.8fc8.ucode.S, bosboot, bos411, 9428A410j 12/9/93 13:26:02
#
# COMPONENT_NAME: BOSBOOT
#
# FUNCTIONS:  proto entry file
#
# ORIGINS: 27
#
# (C) COPYRIGHT International Business Machines Corp. 1993
# All Rights Reserved
# Licensed Materials - Property of IBM
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#
# -------------------------------------------------------------------------
#
# LPP_NAME: bos.dev.mca.8fc8.ucode
#
8fc8m.00.02 ---- 777 0 0 /usr/lib/microcode/8fc8m.00.02
8fc8p.00.01 ---- 777 0 0 /usr/lib/microcode/8fc8p.00.01
