# @(#)62        1.1  src/bos/usr/lib/boot/protoext/tok.proto.ext.mca.8fa2.rte.S, sysxmps, bos411, 9431A411a 7/15/94 15:59:26
#
# COMPONENT_NAME: BOSBOOT
#
# FUNCTIONS:  proto entry file
#
# ORIGINS: 27
#
# (C) COPYRIGHT International Business Machines Corp. 1994
# All Rights Reserved
# Licensed Materials - Property of IBM
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#
# -------------------------------------------------------------------------
#
# LPP_NAME: devices.mca.8fa2.rte
#
mpsdd ---- 777 0 0 /usr/lib/drivers/mpsdd
cfgmps ---- 777 0 0 /usr/lib/methods/cfgmps
