# @(#)06	1.1  src/bos/usr/lib/boot/protoext/tok.proto.ext.mca.8fc8.com.S, bosboot, bos411, 9428A410j 6/21/94 07:41:36
#
# COMPONENT_NAME: BOSBOOT
#
# FUNCTIONS:  proto entry file
#
# ORIGINS: 27
#
# (C) COPYRIGHT International Business Machines Corp. 1993, 1994
# All Rights Reserved
# Licensed Materials - Property of IBM
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#
# -------------------------------------------------------------------------
#
# LPP_NAME: devices.mca.8fc8.com
#
cfgdmxtok ---- 777 0 0 /usr/lib/methods/cfgdmxtok
tok_demux ---- 777 0 0 /usr/lib/drivers/tok_demux
ucfgtok ---- 777 0 0 /usr/lib/methods/ucfgtok
