# @(#)00	1.1  src/bos/usr/lib/boot/protoext/tok.proto.ext.mca.8fc8.rte.S, bosboot, bos411, 9428A410j 12/9/93 13:25:54
#
# COMPONENT_NAME: BOSBOOT
#
# FUNCTIONS:  proto entry file
#
# ORIGINS: 27
#
# (C) COPYRIGHT International Business Machines Corp. 1993
# All Rights Reserved
# Licensed Materials - Property of IBM
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#
# -------------------------------------------------------------------------
#
# LPP_NAME: bos.dev.mca.8fc8.rte
#
tokdd ---- 777 0 0 /usr/lib/drivers/tokdd 
cfgtok ---- 777 0 0 /usr/lib/methods/cfgtok 
