#
# dependents of cfgmid.o:
cfgmid.o: ${MAKETOP}../export/power/usr/include/sys/types.h
cfgmid.o: ${MAKETOP}../export/power/usr/include/standards.h
cfgmid.o: ${MAKETOP}../export/power/usr/include/sys/m_types.h
cfgmid.o: ${MAKETOP}../export/power/usr/include/sys/sysconfig.h
cfgmid.o: ${MAKETOP}../export/power/usr/include/sys/lockl.h
cfgmid.o: ${MAKETOP}../export/power/usr/include/sys/lock_def.h
cfgmid.o: ${MAKETOP}../export/power/usr/include/sys/device.h
cfgmid.o: ${MAKETOP}../export/power/usr/include/sys/file.h
cfgmid.o: ${MAKETOP}../export/power/usr/include/sys/param.h
cfgmid.o: ${MAKETOP}../export/power/usr/include/sys/m_param.h
cfgmid.o: ${MAKETOP}../export/power/usr/include/sys/limits.h
cfgmid.o: ${MAKETOP}../export/power/usr/include/float.h
cfgmid.o: ${MAKETOP}../export/power/usr/include/jfs/fsparam.h
cfgmid.o: ${MAKETOP}../export/power/usr/include/sys/sysmacros.h
cfgmid.o: ${MAKETOP}../export/power/usr/include/sys/access.h
cfgmid.o: ${MAKETOP}../export/power/usr/include/sys/cred.h
cfgmid.o: ${MAKETOP}../export/power/usr/include/sys/priv.h
cfgmid.o: ${MAKETOP}../export/power/usr/include/sys/mode.h
cfgmid.o: ${MAKETOP}../export/power/usr/include/sys/tcb.h
cfgmid.o: ${MAKETOP}../export/power/usr/include/sys/pcl.h
cfgmid.o: ${MAKETOP}../export/power/usr/include/fcntl.h
cfgmid.o: ${MAKETOP}../export/power/usr/include/sys/flock.h
cfgmid.o: ${MAKETOP}../export/power/usr/include/unistd.h
cfgmid.o: ${MAKETOP}../export/power/usr/include/sys/lockf.h
cfgmid.o: ${MAKETOP}../export/power/usr/include/sys/stat.h
cfgmid.o: ${MAKETOP}../export/power/usr/include/sys/intr.h
cfgmid.o: ${MAKETOP}../export/power/usr/include/sys/m_intr.h
cfgmid.o: ${MAKETOP}../export/power/usr/include/sys/low.h
cfgmid.o: ${MAKETOP}../export/power/usr/include/sys/syspest.h
cfgmid.o: ${MAKETOP}../export/power/usr/include/stdio.h
cfgmid.o: ${MAKETOP}../export/power/usr/include/va_list.h
cfgmid.o: ${MAKETOP}../export/power/usr/include/errno.h
cfgmid.o: ${MAKETOP}../export/power/usr/include/sys/errno.h
cfgmid.o: ${MAKETOP}../export/power/usr/include/sys/cfgodm.h
cfgmid.o: ${MAKETOP}../export/power/usr/include/odmi.h
cfgmid.o: ${MAKETOP}../export/power/usr/include/sys/dir.h
cfgmid.o: ${MAKETOP}../export/power/usr/include/sys/lkup.h
cfgmid.o: ${MAKETOP}../export/power/usr/include/limits.h
cfgmid.o: ${MAKETOP}../export/power/usr/include/cf.h
cfgmid.o: ${MAKETOP}bos/usr/lib/methods/common/cfgdebug.h
cfgmid.o: ${MAKETOP}../export/power/usr/include/ddsmid.h
#
# dependents of cfgtools.o:
cfgtools.o: ${MAKETOP}../export/power/usr/include/stdio.h
cfgtools.o: ${MAKETOP}../export/power/usr/include/standards.h
cfgtools.o: ${MAKETOP}../export/power/usr/include/va_list.h
cfgtools.o: ${MAKETOP}../export/power/usr/include/sys/types.h
cfgtools.o: ${MAKETOP}../export/power/usr/include/sys/m_types.h
cfgtools.o: ${MAKETOP}../export/power/usr/include/sys/limits.h
cfgtools.o: ${MAKETOP}../export/power/usr/include/float.h
cfgtools.o: ${MAKETOP}../export/power/usr/include/sys/errno.h
cfgtools.o: ${MAKETOP}../export/power/usr/include/sys/stat.h
cfgtools.o: ${MAKETOP}../export/power/usr/include/sys/mode.h
cfgtools.o: ${MAKETOP}../export/power/usr/include/sys/sysmacros.h
cfgtools.o: ${MAKETOP}../export/power/usr/include/sys/param.h
cfgtools.o: ${MAKETOP}../export/power/usr/include/sys/m_param.h
cfgtools.o: ${MAKETOP}../export/power/usr/include/jfs/fsparam.h
cfgtools.o: ${MAKETOP}bos/usr/lib/methods/common/cfgdebug.h
cfgtools.o: ${MAKETOP}bos/usr/lib/methods/common/pparms.h
cfgtools.o: ${MAKETOP}../export/power/usr/include/sys/cfgodm.h
cfgtools.o: ${MAKETOP}../export/power/usr/include/odmi.h
cfgtools.o: ${MAKETOP}../export/power/usr/include/sys/dir.h
cfgtools.o: ${MAKETOP}../export/power/usr/include/sys/lkup.h
cfgtools.o: ${MAKETOP}../export/power/usr/include/limits.h
cfgtools.o: ${MAKETOP}../export/power/usr/include/sys/cfgdb.h
cfgtools.o: ${MAKETOP}../export/power/usr/include/ctype.h
cfgtools.o: ${MAKETOP}../export/power/usr/include/sys/localedef.h
cfgtools.o: ${MAKETOP}../export/power/usr/include/sys/lc_core.h
cfgtools.o: ${MAKETOP}../export/power/usr/include/locale.h
cfgtools.o: ${MAKETOP}../export/power/usr/include/sys/localedef31.h
cfgtools.o: ${MAKETOP}../export/power/usr/include/cf.h
#
# dependents of chkslot.o:
chkslot.o: ${MAKETOP}../export/power/usr/include/stdio.h
chkslot.o: ${MAKETOP}../export/power/usr/include/standards.h
chkslot.o: ${MAKETOP}../export/power/usr/include/va_list.h
chkslot.o: ${MAKETOP}../export/power/usr/include/sys/types.h
chkslot.o: ${MAKETOP}../export/power/usr/include/sys/m_types.h
chkslot.o: ${MAKETOP}../export/power/usr/include/sys/limits.h
chkslot.o: ${MAKETOP}../export/power/usr/include/float.h
chkslot.o: ${MAKETOP}../export/power/usr/include/fcntl.h
chkslot.o: ${MAKETOP}../export/power/usr/include/sys/flock.h
chkslot.o: ${MAKETOP}../export/power/usr/include/unistd.h
chkslot.o: ${MAKETOP}../export/power/usr/include/sys/access.h
chkslot.o: ${MAKETOP}../export/power/usr/include/sys/lockf.h
chkslot.o: ${MAKETOP}../export/power/usr/include/sys/stat.h
chkslot.o: ${MAKETOP}../export/power/usr/include/sys/mode.h
chkslot.o: ${MAKETOP}../export/power/usr/include/cf.h
chkslot.o: ${MAKETOP}../export/power/usr/include/sys/mdio.h
chkslot.o: ${MAKETOP}../export/power/usr/include/sys/eu.h
chkslot.o: ${MAKETOP}bos/usr/lib/methods/common/cfgdebug.h
#
# dependents of ddstools.o:
ddstools.o: ${MAKETOP}../export/power/usr/include/sys/sysmacros.h
ddstools.o: ${MAKETOP}../export/power/usr/include/sys/param.h
ddstools.o: ${MAKETOP}../export/power/usr/include/sys/m_param.h
ddstools.o: ${MAKETOP}../export/power/usr/include/sys/limits.h
ddstools.o: ${MAKETOP}../export/power/usr/include/standards.h
ddstools.o: ${MAKETOP}../export/power/usr/include/float.h
ddstools.o: ${MAKETOP}../export/power/usr/include/jfs/fsparam.h
ddstools.o: ${MAKETOP}../export/power/usr/include/sys/types.h
ddstools.o: ${MAKETOP}../export/power/usr/include/sys/m_types.h
ddstools.o: ${MAKETOP}../export/power/usr/include/sys/cfgodm.h
ddstools.o: ${MAKETOP}../export/power/usr/include/odmi.h
ddstools.o: ${MAKETOP}../export/power/usr/include/sys/dir.h
ddstools.o: ${MAKETOP}../export/power/usr/include/sys/lkup.h
ddstools.o: ${MAKETOP}../export/power/usr/include/limits.h
ddstools.o: ${MAKETOP}../export/power/usr/include/sys/cfgdb.h
ddstools.o: ${MAKETOP}../export/power/usr/include/cf.h
ddstools.o: ${MAKETOP}bos/usr/lib/methods/common/cfgdebug.h
ddstools.o: ${MAKETOP}../export/power/usr/include/stdio.h
ddstools.o: ${MAKETOP}../export/power/usr/include/va_list.h
ddstools.o: ${MAKETOP}../export/power/usr/include/strings.h
ddstools.o: ${MAKETOP}../export/power/usr/include/string.h
#
# dependents of mid_cfg_load.o:
mid_cfg_load.o: ${MAKETOP}../export/power/usr/include/cf.h
mid_cfg_load.o: ${MAKETOP}../export/power/usr/include/sys/types.h
mid_cfg_load.o: ${MAKETOP}../export/power/usr/include/standards.h
mid_cfg_load.o: ${MAKETOP}../export/power/usr/include/sys/m_types.h
mid_cfg_load.o: ${MAKETOP}bos/usr/lib/methods/common/cfgdebug.h
mid_cfg_load.o: ${MAKETOP}../export/power/usr/include/sys/aixfont.h
mid_cfg_load.o: ${MAKETOP}../export/power/usr/include/sys/dir.h
mid_cfg_load.o: ${MAKETOP}../export/power/usr/include/sys/lkup.h
mid_cfg_load.o: ${MAKETOP}../export/power/usr/include/limits.h
mid_cfg_load.o: ${MAKETOP}../export/power/usr/include/sys/limits.h
mid_cfg_load.o: ${MAKETOP}../export/power/usr/include/float.h
mid_cfg_load.o: ${MAKETOP}../export/power/usr/include/sys/mdio.h
mid_cfg_load.o: ${MAKETOP}../export/power/usr/include/sys/file.h
mid_cfg_load.o: ${MAKETOP}../export/power/usr/include/sys/param.h
mid_cfg_load.o: ${MAKETOP}../export/power/usr/include/sys/m_param.h
mid_cfg_load.o: ${MAKETOP}../export/power/usr/include/jfs/fsparam.h
mid_cfg_load.o: ${MAKETOP}../export/power/usr/include/sys/sysmacros.h
mid_cfg_load.o: ${MAKETOP}../export/power/usr/include/sys/access.h
mid_cfg_load.o: ${MAKETOP}../export/power/usr/include/sys/lock_def.h
mid_cfg_load.o: ${MAKETOP}../export/power/usr/include/sys/cred.h
mid_cfg_load.o: ${MAKETOP}../export/power/usr/include/sys/priv.h
mid_cfg_load.o: ${MAKETOP}../export/power/usr/include/sys/mode.h
mid_cfg_load.o: ${MAKETOP}../export/power/usr/include/sys/tcb.h
mid_cfg_load.o: ${MAKETOP}../export/power/usr/include/sys/pcl.h
mid_cfg_load.o: ${MAKETOP}../export/power/usr/include/sys/lockl.h
mid_cfg_load.o: ${MAKETOP}../export/power/usr/include/fcntl.h
mid_cfg_load.o: ${MAKETOP}../export/power/usr/include/sys/flock.h
mid_cfg_load.o: ${MAKETOP}../export/power/usr/include/unistd.h
mid_cfg_load.o: ${MAKETOP}../export/power/usr/include/sys/lockf.h
mid_cfg_load.o: ${MAKETOP}../export/power/usr/include/sys/stat.h
mid_cfg_load.o: ${MAKETOP}../export/power/usr/include/sys/intr.h
mid_cfg_load.o: ${MAKETOP}../export/power/usr/include/sys/m_intr.h
mid_cfg_load.o: ${MAKETOP}../export/power/usr/include/sys/ioacc.h
mid_cfg_load.o: ${MAKETOP}../export/power/usr/include/sys/adspace.h
mid_cfg_load.o: ${MAKETOP}../export/power/usr/include/sys/seg.h
mid_cfg_load.o: ${MAKETOP}../export/power/usr/include/sys/inode.h
mid_cfg_load.o: ${MAKETOP}../export/power/usr/include/jfs/inode.h
mid_cfg_load.o: ${MAKETOP}../export/power/usr/include/jfs/ino.h
mid_cfg_load.o: ${MAKETOP}../export/power/usr/include/sys/time.h
mid_cfg_load.o: ${MAKETOP}../export/power/usr/include/jfs/fsdefs.h
mid_cfg_load.o: ${MAKETOP}../export/power/usr/include/jfs/filsys.h
mid_cfg_load.o: ${MAKETOP}../export/power/usr/include/jfs/jfsmount.h
mid_cfg_load.o: ${MAKETOP}../export/power/usr/include/sys/vnode.h
mid_cfg_load.o: ${MAKETOP}../export/power/usr/include/sys/uio.h
mid_cfg_load.o: ${MAKETOP}../export/power/usr/include/sys/xmem.h
mid_cfg_load.o: ${MAKETOP}../export/power/usr/include/jfs/quota.h
mid_cfg_load.o: ${MAKETOP}../export/power/usr/include/sys/vmuser.h
mid_cfg_load.o: ${MAKETOP}../export/power/usr/include/sys/acl.h
mid_cfg_load.o: ${MAKETOP}../export/power/usr/include/sys/systemcfg.h
mid_cfg_load.o: ${MAKETOP}../export/power/usr/include/vt.h
mid_cfg_load.o: ${MAKETOP}../export/power/usr/include/sys/font.h
mid_cfg_load.o: ${MAKETOP}../export/power/usr/include/cdd.h
mid_cfg_load.o: ${MAKETOP}../export/power/usr/include/cdd_macros.h
mid_cfg_load.o: ${MAKETOP}../export/power/usr/include/cdd_intr.h
mid_cfg_load.o: ${MAKETOP}../export/power/usr/include/cdd_intr_macros.h
mid_cfg_load.o: ${MAKETOP}../export/power/usr/include/ccm.h
mid_cfg_load.o: ${MAKETOP}../export/power/usr/include/ccm_macros.h
mid_cfg_load.o: ${MAKETOP}bos/usr/lib/methods/graphics/cfg_graphics.h
mid_cfg_load.o: ${MAKETOP}bos/usr/lib/methods/graphics/cfg_graphics_macros.h
