# @(#)39        1.2  src/bos/usr/lib/microcode/tok/Makefile, ucodtok, bos411, 9428A410j 10/20/92 12:41:48
# COMPONENT_NAME:
#
# FUNCTIONS:
#
# ORIGINS: 27
#
# IBM CONFIDENTIAL -- (IBM Confidential Restricted when
# combined with the aggregated modules for this product)
#                  SOURCE MATERIALS
# (C) COPYRIGHT International Business Machines Corp. 1988, 1989
# All Rights Reserved
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#


ILIST		= 8fc8m.00.02 8fc8p.00.01

IDIR		= /usr/lib/microcode/

.include <${RULES_MK}>

