# @(#)55        1.2  src/bos/kernel/s/priv/Makefile, sysspriv, bos411, 9428A410j 10/27/93 16:48:31
# COMPONENT_NAME:
#
# FUNCTIONS:
#
# ORIGINS: 27
#
# IBM CONFIDENTIAL -- (IBM Confidential Restricted when
# combined with the aggregated modules for this product)
#                  SOURCE MATERIALS
# (C) COPYRIGHT International Business Machines Corp. 1988, 1993
# All Rights Reserved
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#

.include <${MAKETOP}bos/kernel/Kernel.mk>

PAGED_OFILES	=	\
	priv.o

PAGED_OFILES_BACK =	\
	syspriv.o	\
	statpriv.o	\
	chpriv.o

.include <${RULES_MK}>
