# @(#) 80 1.1 src/bos/usr/lpp/bosinst/bi_main/Makefile, bosinst, bos411, 9428A410j 7/1/93 09:14:22
# COMPONENT_NAME: bosinst
#
# FUNCTIONS: Makefile for bi_main
#
# ORIGINS: 27
#
# IBM CONFIDENTIAL -- (IBM Confidential Restricted when
# combined with the aggregated modules for this product)
#                  SOURCE MATERIALS
# (C) COPYRIGHT International Business Machines Corp. 1993
# All Rights Reserved
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#

SCRIPTS		= bi_main

ILIST		= ${SCRIPTS}
IDIR		= /usr/lpp/bosinst/

.include <${RULES_MK}>
