# @(#)60	1.2  src/bos/kernext/tok/devices.mca.8fc8.rte.trc.S, sysxtok, bos411, 9428A410j 11/11/93 11:23:33
#
#   COMPONENT_NAME: SYSXTOK
#
#   FUNCTIONS: none
#
#   ORIGINS: 27
#
#
#   (C) COPYRIGHT International Business Machines Corp. 1993
#   All Rights Reserved
#   Licensed Materials - Property of IBM
#   US Government Users Restricted Rights - Use, duplication or
#   disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#
* /etc/trcfmt
+26A 1.0 "@tokdd" \
        "TOK DD XMT: " O2 A4.8 "d1=" X4 " d2=" X4 " d3=" X4 

+26B 1.0 "@tokdd" \
        "TOK DD RCV: " O2 A4.8 "d1=" X4 " d2=" X4 " d3=" X4

+26C 1.0 "@tokdd" \
        "TOK DD GEN: " O2 A4.8 "d1=" X4 " d2=" X4 " d3=" X4
