# @(#)48	1.1  src/bos/kernext/lft/inc/Makefile, lftdd, bos411, 9428A410j 10/25/93 15:02:54
# COMPONENT_NAME: (LFTDD) Low function Terminal
#
# FUNCTIONS:
#
# ORIGINS: 27
#
# IBM CONFIDENTIAL -- (IBM Confidential Restricted when
# combined with the aggregated modules for this product)
# (C) COPYRIGHT International Business Machines Corp. 1993
# All Rights Reserved
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#
#

EXPINC_SUBDIRS  = sys


INCLUDES	=  lftras.h lft.h lft_dds.h vt.h fkproc.h lft_swkbd.h \
		   fkprocFont.h kks.h

EXPDIR		= /kernel/include/

.include <${RULES_MK}>
