# @(#)05        1.2  src/bos/usr/lib/pios/msg/Makefile, cmdpios, bos411, 9428A410j 2/19/93 20:28:46
# COMPONENT_NAME:
#
# FUNCTIONS:
#
# ORIGINS: 27
#
# IBM CONFIDENTIAL -- (IBM Confidential Restricted when
# combined with the aggregated modules for this product)
#                  SOURCE MATERIALS
# (C) COPYRIGHT International Business Machines Corp. 1988, 1989
# All Rights Reserved
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#

MSGHDRS		= piobe_msg.h piosplp_msg.h
CATFILES	= pioattr1.cat piobe.cat piosplp.cat

OTHERS		= ${MSGHDRS} 

.include <${RULES_MK}>
