# @(#)90	1.3  src/bos/usr/lib/pioskr/Makefile, cmdpioskr, bos411, 9428A410j 7/30/93 02:47:26
#
#   COMPONENT_NAME: CMDPIOSKR
#
#   FUNCTIONS: 
#
#   ORIGINS: 27
#
#   IBM CONFIDENTIAL -- (IBM Confidential Restricted when
#   combined with the aggregated modules for this product)
#                    SOURCE MATERIALS
#
#   (C) COPYRIGHT International Business Machines Corp. 1993
#   All Rights Reserved
#   US Government Users Restricted Rights - Use, duplication or
#   disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#

SUBDIRS = fmtrsKR predef

.include <${RULES_MK}>
