# @(#)64        1.2  src/bos/usr/lbin/ient_dd/Makefile, sysxient, bos41J, 9512A_all 3/14/95 14:09:37
#
#   COMPONENT_NAME: sysxient
#
#   FUNCTIONS: none
#
#   ORIGINS: 27
#
#   IBM CONFIDENTIAL -- (IBM Confidential Restricted when
#   combined with the aggregated modules for this product)
#                    SOURCE MATERIALS
#
#   (C) COPYRIGHT International Business Machines Corp. 1994
#   All Rights Reserved
#   US Government Users Restricted Rights - Use, duplication or
#   disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#
PROGRAMS        = ient_dd

OFILES		= main.o ient_dmp.o

INCFLAGS	= -I${MAKETOP}/bos/kernext/ient

ILIST           = ient_dd

IDIR		= /usr/lib/ras/dmprtns/

.include <${RULES_MK}>

