# @(#)93        1.1  src/bldenv/xlC/include/Makefile, ade_build, bos41J, 9509A_all 2/27/95 12:43:22
#
#   COMPONENT_NAME: ade_build
#
#   FUNCTIONS: none
#
#   ORIGINS: 27
#
#
#   (C) COPYRIGHT International Business Machines Corp. 1995
#   All Rights Reserved
#   Licensed Materials - Property of IBM
#   US Government Users Restricted Rights - Use, duplication or
#   disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#

EXPINC_SUBDIRS	= sys rpc arpa

VPATH = ${MAKETOP}/xlC/usr/lpp/xlC/include

INCLUDES        = \
NLchar.h        defenv.h        iomanip.h       paths.h         task.h \
NLctype.h       demangle.h      iostream.h      piostruct.h     tcov.h \
NLregexp.h      des_crypt.h     jcode.h         poll.h          tcpip_audit.h \
NLxio.h         device.h        jctype.h        procinfo.h      term.h \
a.out.h         dirent.h        jimerrno.h      pwd.h           terminate.h \
acl.h           dumprestor.h    langinfo.h      regcmp.h        termio.h \
afmgp.h         errno.h         ldfcn.h         regex.h         termios.h \
afmnc.h         exceptab.h      libc.h          regexp.h        time.h \
afmrc.h         execargs.h      limits.h        reloc.h         tiuser.h \
afmsc.h         fatal.h         linenum.h       resolv.h        ttyent.h \
aio.h           fcntl.h         loader.h        scnhdr.h        typchk.h \
aixfont.h       filehdr.h       locale.h        search.h        uinfo.h \
aouthdr.h       float.h         login.h         setjmp.h        ulimit.h \
ar.h            fnmatch.h       lprio.h         sgtty.h         unctrl.h \
asl.h           fp.h            lvm.h           signal.h        unexpected.h \
assert.h        fptrap.h        lvmrec.h        spc.h           unistd.h \
ccsid.h         fpxcp.h         macros.h        srcerrno.h      userconf.h \
cf.h            fshelp.h        malloc.h        standards.h     userpw.h \
common.h        fstab.h         math.h          stdarg.h        usersec.h \
complex.h       fstream.h       mbstr.h         stddef.h        ustat.h \
core.h          ftw.h           memory.h        stdio.h         utime.h \
cpio.h          generic.h       mesg.h          stdiostream.h   utmp.h \
cpyrght.h       gl.h            mon.h           stdlib.h        va_list.h \
ctype.h         glob.h          monetary.h      storclass.h     values.h \
cur00.h         grp.h           mp.h            stream.h        varargs.h \
cur01.h         gslerrno.h      ndbm.h          string.h        vector.h \
cur02.h         iconv.h         netdb.h         strings.h       wchar.h \
cur03.h         im.h            netioctl.h      stropts.h       wcstr.h \
cur04.h         imerrno.h       new.h           strstream.h     wordexp.h \
cur05.h         imjim.h         nl_types.h      syms.h          wstring.h \
curses.h        imlang.h        nlist.h         sysent.h        x25sdefs.h \
dbm.h           in_extern.h     notice.h        sysexits.h      xcoff.h \
dbug.h          in_params.h     odmi.h          syslog.h \
dbxstclass.h    inuerr.h        osfcn.h         tar.h 

EXPDIR  = /usr/lpp/xlC/include/

.include <${RULES_MK}>
