# @(#)15        1.2  src/bldenv/includes/jfs/Makefile, ade_build, bos412, GOLDA411a 3/12/93 19:48:17
#
#   COMPONENT_NAME: BOSBUILD
#
#   FUNCTIONS:
#
#   ORIGINS: 27
#
#   IBM CONFIDENTIAL -- (IBM Confidential Restricted when
#   combined with the aggregated modules for this product)
#                    SOURCE MATERIALS
#
#   (C) COPYRIGHT International Business Machines Corp. 1993
#   All Rights Reserved
#   US Government Users Restricted Rights - Use, duplication or
#   disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#

VPATH		= ${MAKETOP}/bos/usr/include/jfs

INCLUDES	= log.h filsys.h

EXPDIR		= /usr/include/jfs/

.include <${RULES_MK}>
