# @(#)36        1.5  src/bos/usr/lpp/jls/Makefile, cmdKJI, bos411, 9428A410j 2/22/93 17:09:26
#
# COMPONENT_NAME: cmdKJI
#
# FUNCTIONS:
#
# ORIGINS: 27
#
# IBM CONFIDENTIAL -- (IBM Confidential Restricted when
# combined with the aggregated modules for this product)
#                  SOURCE MATERIALS
# (C) COPYRIGHT International Business Machines Corp. 1988, 1993
# All Rights Reserved
# Licensed Materials - Property of IBM
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#

SUBDIRS		= defaults dict dictutil fonts

.include <${RULES_MK}>
