# @(#)47        1.1  src/bldenv/paste/Makefile, ade_build, bos412, GOLDA411a 4/21/93 20:28:10
# COMPONENT_NAME:
#
# FUNCTIONS:
#
# ORIGINS: 27
#
# IBM CONFIDENTIAL -- (IBM Confidential Restricted when
# combined with the aggregated modules for this product)
#                  SOURCE MATERIALS
# (C) COPYRIGHT International Business Machines Corp. 1988, 1989
# All Rights Reserved
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#

VPATH           = ${MAKETOP}/bos/usr/bin/paste
PROGRAMS	= paste
MSGHDRS		= paste_msg.h
CATFILES	= paste.cat
HFILES		= ${MSGHDRS}

ILIST		= paste
IDIR		= /usr/bin/


.include <${RULES_MK}>
