# @(#)81        1.1  src/bos/usr/lib/nls/lsmle/Makefile, cmdmle, bos411, 9428A410j 4/16/94 11:26:56
#
# COMPONENT_NAME: CFGNLS
#
# FUNCTIONS: None
#
# ORIGINS: 27
#
# IBM CONFIDENTIAL -- (IBM Confidential Restricted when
# combined with the aggregated modules for this product)
#                  SOURCE MATERIALS
# (C) COPYRIGHT International Business Machines Corp. 1994
# All Rights Reserved
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#

VPATH		= ${MAKETOP}/bos/objclass

PROGRAMS        = lsmle

HFILES		= ILS.c

ILIST		= ${PROGRAMS}
IDIR		= /usr/lib/nls/

OFILES		= ILS.o lsmle.o

LIBS            = -lodm

.include <${RULES_MK}>
