# @(#)36        1.4  src/bos/diag/tu/siosl/mousea/Makefile, tu_siosl, bos411, 9428A410j 1/27/94 11:23:59
#
#   COMPONENT_NAME: TU_SIOSL
#
#   FUNCTIONS: 
#
#   ORIGINS: 27
#
#   IBM CONFIDENTIAL -- (IBM Confidential Restricted when
#   combined with the aggregated modules for this product)
#                    SOURCE MATERIALS
#
#   (C) COPYRIGHT International Business Machines Corp. 1992,1994
#   All Rights Reserved
#   US Government Users Restricted Rights - Use, duplication or
#   disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#

LIBRARIES	= libmouseatu.a

EXPLIB_TARGETS  = export_libmouseatu.a
EXPDIR		= /usr/lib/

CFLAGS		= -DDIAGNOSTICS
OFILES		= mousea.o \
		  mou_io.o \
		  tu10.o \
		  tu15.o \
		  tu20.o \
		  tu25.o \
		  tu30.o

.include <${RULES_MK}>
