# @(#)74	1.4  src/bos/usr/include/net/Makefile, Makefiles, bos411, 9428A410j 3/17/94 07:22:30
# COMPONENT_NAME:
#
# FUNCTIONS:
#
# ORIGINS: 10,27
#
# IBM CONFIDENTIAL -- (IBM Confidential Restricted when
# combined with the aggregated modules for this product)
#                  SOURCE MATERIALS
# (C) COPYRIGHT International Business Machines Corp. 1988, 1989
# All Rights Reserved
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#

VPATH		=${MAKETOP}/bos/kernel/net

IDIR		= /usr/include/net/

DATAFILES	= \
	af.h \
	bpf.h \
	bpfdesc.h \
	if.h \
	if_arp.h \
	if_dl.h \
	if_llc.h \
	if_slvar.h \
	if_types.h \
	nd_lan.h \
	net_globals.h \
	net_malloc.h \
	net_unixlock.h \
	netisr.h \
	netopt.h \
	nh.h \
	proto_net.h \
	proto_uipc.h \
	radix.h \
	raw_cb.h \
	route.h \
	slcompress.h \
	spl.h \
	rtsock.c \
	radix.c

INCLUDES	= ${DATAFILES}

ILIST		= ${DATAFILES}

.include <${RULES_MK}>
