# @(#)55        1.3  src/bldenv/mv/Makefile, ade_build, bos412, GOLDA411a 1/10/94 14:03:39
#
#   COMPONENT_NAME: BOSBUILD
#
#   FUNCTIONS:
#
#   ORIGINS: 27
#
#   IBM CONFIDENTIAL -- (IBM Confidential Restricted when
#   combined with the aggregated modules for this product)
#                    SOURCE MATERIALS
#
#   (C) COPYRIGHT International Business Machines Corp. 1993
#   All Rights Reserved
#   US Government Users Restricted Rights - Use, duplication or
#   disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#

VPATH		= ${MAKETOP}bos/usr/bin/mv

PROGRAMS	= mv
MSGHDRS		= mv_msg.h
CATFILES	= mv.cat
HFILES		= ${MSGHDRS}

INCFLAGS	= -I${MAKETOP}bos/usr/bin/mv

ILIST		= ${PROGRAMS}
IDIR		= /usr/bin/

LIBS		= -lbsd -ls

.include <${RULES_MK}>
