# @(#)68	1.1  src/bos/usr/lib/methods/startrcm/Makefile, rcm, bos411, 9428A410j 11/1/93 10:57:25
#   COMPONENT_NAME: RCM
#
#   FUNCTIONS:
#
#   ORIGINS: 27
#
# IBM CONFIDENTIAL -- (IBM Confidential Restricted when
# combined with the aggregated modules for this product)
#                  SOURCE MATERIALS
# (C) COPYRIGHT International Business Machines Corp. 1988, 1993
# All Rights Reserved
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#

PROGRAMS	= startrcm

INCFLAGS	= -I../common

ILIST		= startrcm
IDIR		= /usr/lib/methods/

LIBS		= -ls -lodm -lcfg -lrts

.include <${RULES_MK}>
