# @(#)60	1.1  src/bos/usr/lib/piosk/nls/Makefile, cmdpiosk, bos411, 9428A410j 7/21/93 00:38:00
#
#   COMPONENT_NAME: CMDPIOSK
#
#   FUNCTIONS: 
#
#   ORIGINS: 27
#
#   IBM CONFIDENTIAL -- (IBM Confidential Restricted when
#   combined with the aggregated modules for this product)
#                    SOURCE MATERIALS
#
#   (C) COPYRIGHT International Business Machines Corp. 1993
#   All Rights Reserved
#   US Government Users Restricted Rights - Use, duplication or
#   disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#

DATAFILES = nls.dir

IDIR = /usr/lib/lpd/pio/etc/
ILIST = ${DATAFILES}

.include <${RULES_MK}>
