# @(#)65        1.4  src/bldenv/gos/desktop/Makefile, desktop, bos412, GOLDA411a 6/3/94 09:51:13
#
#   COMPONENT_NAME: ade_build
#
#   FUNCTIONS: ODE_MakeSubdirs
#
#   ORIGINS: 27
#
#
#   (C) COPYRIGHT International Business Machines Corp. 1993
#   All Rights Reserved
#   Licensed Materials - Property of IBM
#   US Government Users Restricted Rights - Use, duplication or
#   disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#

EXPINC_SUBDIRS	= pass1 canon1

EXPLIB_SUBDIRS	= imageutil pass1 canon1

SUBDIRS		= imageutil merge scripts pass1 pass2 canon1

.include <${RULES_MK}>
