$ @(#)35        1.1  src/bos/usr/lib/methods/cfgfddi/fddi.msg, sysxfddi, bos411, 9428A410j 11/29/93 10:15:08
$
$  COMPONENT_NAME: SYSXFDDI
$
$  FUNCTIONS: Devices configuration message catalog
$
$  ORIGINS: 27
$
$  IBM CONFIDENTIAL -- (IBM Confidential Restricted when
$  combined with the aggregated modules for this product)
$                   SOURCE MATERIALS
$  (C) COPYRIGHT International Business Machines Corp. 1992
$  All Rights Reserved
$
$  US Government Users Restricted Rights - Use, duplication or
$  disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
$
$quote "
$
$  FDDI Adapter
$set 1
1 "FDDI Primary Card"
2 "Bus interrupt level"
3 "Address of bus memory used for DMA"
4 "Interrupt priority"
8 "Bus I/O address"
9 "Bus memory address"
10 "DMA arbitration level"
11 "Enable ALTERNATE FDDI Source address"
12 "ALTERNATE FDDI Source address"
17 "FDDI Extender Card"
18 "PMF password"
20 "USER data"
25 "MAX T-REQ (nsec)"
26 "TVX lower bound (nsec)"
34 "Transmit Queue Size (in mbufs)"
35 "Message number for the device object"
36 "FDDI Primary Card, Single Ring Fiber"
37 "FDDI Primary Card, Dual Ring Fiber"
38 "FDDI Primary Card, Single Ring Copper"
39 "FDDI Primary Card, Dual Ring Copper"
