#
#
#
#   ORIGINS: 27
#
#
#

EXPINC_SUBDIRS          = inc

IDIR		= /usr/lib/drivers/
ILIST	 	= ccmdd ccmdd_pin

OTHERS =
OTHERS += ccmdd
ccmdd: ccmdd.ibmstub
	-${RM} -f ${.TARGET}
	${CP} -f ${.ALLSRC} ${.TARGET}

OTHERS += ccmdd_pin
ccmdd_pin: ccmdd_pin.ibmstub
	-${RM} -f ${.TARGET}
	${CP} -f ${.ALLSRC} ${.TARGET}

OTHERS += ccm_close.o
ccm_close.o: ccm_close.o.ibmstub
	-${RM} -f ${.TARGET}
	${CP} -f ${.ALLSRC} ${.TARGET}

OTHERS += ccm_config.o
ccm_config.o: ccm_config.o.ibmstub
	-${RM} -f ${.TARGET}
	${CP} -f ${.ALLSRC} ${.TARGET}

OTHERS += ccm_config_init.o
ccm_config_init.o: ccm_config_init.o.ibmstub
	-${RM} -f ${.TARGET}
	${CP} -f ${.ALLSRC} ${.TARGET}

OTHERS += ccm_config_qvpd.o
ccm_config_qvpd.o: ccm_config_qvpd.o.ibmstub
	-${RM} -f ${.TARGET}
	${CP} -f ${.ALLSRC} ${.TARGET}

OTHERS += ccm_config_subrs.o
ccm_config_subrs.o: ccm_config_subrs.o.ibmstub
	-${RM} -f ${.TARGET}
	${CP} -f ${.ALLSRC} ${.TARGET}

OTHERS += ccm_config_term.o
ccm_config_term.o: ccm_config_term.o.ibmstub
	-${RM} -f ${.TARGET}
	${CP} -f ${.ALLSRC} ${.TARGET}

OTHERS += ccm_interrupt.o
ccm_interrupt.o: ccm_interrupt.o.ibmstub
	-${RM} -f ${.TARGET}
	${CP} -f ${.ALLSRC} ${.TARGET}

OTHERS += ccm_io_subrs.o
ccm_io_subrs.o: ccm_io_subrs.o.ibmstub
	-${RM} -f ${.TARGET}
	${CP} -f ${.ALLSRC} ${.TARGET}

OTHERS += ccm_ioctl.o
ccm_ioctl.o: ccm_ioctl.o.ibmstub
	-${RM} -f ${.TARGET}
	${CP} -f ${.ALLSRC} ${.TARGET}

OTHERS += ccm_open.o
ccm_open.o: ccm_open.o.ibmstub
	-${RM} -f ${.TARGET}
	${CP} -f ${.ALLSRC} ${.TARGET}

OTHERS += ccmdd.map
ccmdd.map: ccmdd.map.ibmstub
	-${RM} -f ${.TARGET}
	${CP} -f ${.ALLSRC} ${.TARGET}

OTHERS += ccmdd.out
ccmdd.out: ccmdd.out.ibmstub
	-${RM} -f ${.TARGET}
	${CP} -f ${.ALLSRC} ${.TARGET}

OTHERS += ccmdd_pin.map
ccmdd_pin.map: ccmdd_pin.map.ibmstub
	-${RM} -f ${.TARGET}
	${CP} -f ${.ALLSRC} ${.TARGET}

OTHERS += ccmdd_pin.out
ccmdd_pin.out: ccmdd_pin.out.ibmstub
	-${RM} -f ${.TARGET}
	${CP} -f ${.ALLSRC} ${.TARGET}

OTHERS += depend.mk
depend.mk: depend.mk.ibmstub
	-${RM} -f ${.TARGET}
	${CP} -f ${.ALLSRC} ${.TARGET}

OTHERS += libdepend.mk
libdepend.mk: libdepend.mk.ibmstub
	-${RM} -f ${.TARGET}
	${CP} -f ${.ALLSRC} ${.TARGET}

OTHERS += vtt_act.o
vtt_act.o: vtt_act.o.ibmstub
	-${RM} -f ${.TARGET}
	${CP} -f ${.ALLSRC} ${.TARGET}

OTHERS += vtt_cfl.o
vtt_cfl.o: vtt_cfl.o.ibmstub
	-${RM} -f ${.TARGET}
	${CP} -f ${.ALLSRC} ${.TARGET}

OTHERS += vtt_clr.o
vtt_clr.o: vtt_clr.o.ibmstub
	-${RM} -f ${.TARGET}
	${CP} -f ${.ALLSRC} ${.TARGET}

OTHERS += vtt_cpl.o
vtt_cpl.o: vtt_cpl.o.ibmstub
	-${RM} -f ${.TARGET}
	${CP} -f ${.ALLSRC} ${.TARGET}

OTHERS += vtt_dact.o
vtt_dact.o: vtt_dact.o.ibmstub
	-${RM} -f ${.TARGET}
	${CP} -f ${.ALLSRC} ${.TARGET}

OTHERS += vtt_defc.o
vtt_defc.o: vtt_defc.o.ibmstub
	-${RM} -f ${.TARGET}
	${CP} -f ${.ALLSRC} ${.TARGET}

OTHERS += vtt_init.o
vtt_init.o: vtt_init.o.ibmstub
	-${RM} -f ${.TARGET}
	${CP} -f ${.ALLSRC} ${.TARGET}

OTHERS += vtt_movc.o
vtt_movc.o: vtt_movc.o.ibmstub
	-${RM} -f ${.TARGET}
	${CP} -f ${.ALLSRC} ${.TARGET}

OTHERS += vtt_rds.o
vtt_rds.o: vtt_rds.o.ibmstub
	-${RM} -f ${.TARGET}
	${CP} -f ${.ALLSRC} ${.TARGET}

OTHERS += vtt_scr.o
vtt_scr.o: vtt_scr.o.ibmstub
	-${RM} -f ${.TARGET}
	${CP} -f ${.ALLSRC} ${.TARGET}

OTHERS += vtt_setm.o
vtt_setm.o: vtt_setm.o.ibmstub
	-${RM} -f ${.TARGET}
	${CP} -f ${.ALLSRC} ${.TARGET}

OTHERS += vtt_stct.o
vtt_stct.o: vtt_stct.o.ibmstub
	-${RM} -f ${.TARGET}
	${CP} -f ${.ALLSRC} ${.TARGET}

OTHERS += vtt_subrs.o
vtt_subrs.o: vtt_subrs.o.ibmstub
	-${RM} -f ${.TARGET}
	${CP} -f ${.ALLSRC} ${.TARGET}

OTHERS += vtt_term.o
vtt_term.o: vtt_term.o.ibmstub
	-${RM} -f ${.TARGET}
	${CP} -f ${.ALLSRC} ${.TARGET}

OTHERS += vtt_text.o
vtt_text.o: vtt_text.o.ibmstub
	-${RM} -f ${.TARGET}
	${CP} -f ${.ALLSRC} ${.TARGET}

.include <${RULES_MK}>
