#
#   COMPONENT_NAME: magdd
#
#   FUNCTIONS: none
#
#   ORIGINS: 27
#
#
#   (C) COPYRIGHT International Business Machines Corp. 1995
#   All Rights Reserved
#   Licensed Materials - Property of IBM
#   US Government Users Restricted Rights - Use, duplication or
#   disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#
VPATH           = ${MAKETOP}bos/kernext/disp/mag/mag

EXPDIR		= /usr/include/mag/
IDIR		= /usr/include/mag/

DATAFILES        =	\
	mag.h		\
	mag_abxDefs.h	\
	mag_ddf.h	\
	mag_event.h	\
	mag_hdw_def.h	\
	mag_lock.h	\
	mag_mem_map.h	\
	mag_rc.h	\
	mag_shared.h	\
	mag_wat.h

INCLUDES	= ${DATAFILES} 

.include <${RULES_MK}>
