#
# dependents of cdd_entry.o:
cdd_entry.o: ${MAKETOP}../export/power/kernel/include/sys/types.h
cdd_entry.o: ${MAKETOP}../export/power/kernel/include/standards.h
cdd_entry.o: ${MAKETOP}../export/power/kernel/include/sys/m_types.h
cdd_entry.o: ${MAKETOP}../export/power/kernel/include/sys/aixfont.h
cdd_entry.o: ${MAKETOP}../export/power/kernel/include/sys/dir.h
cdd_entry.o: ${MAKETOP}../export/power/kernel/include/sys/lkup.h
cdd_entry.o: ${MAKETOP}../export/power/kernel/include/limits.h
cdd_entry.o: ${MAKETOP}../export/power/kernel/include/sys/limits.h
cdd_entry.o: ${MAKETOP}../export/power/kernel/include/float.h
cdd_entry.o: ${MAKETOP}../export/power/kernel/include/jfs/dir.h
cdd_entry.o: ${MAKETOP}../export/power/kernel/include/sys/mdio.h
cdd_entry.o: ${MAKETOP}../export/power/kernel/include/sys/file.h
cdd_entry.o: ${MAKETOP}../export/power/kernel/include/sys/param.h
cdd_entry.o: ${MAKETOP}../export/power/kernel/include/sys/m_param.h
cdd_entry.o: ${MAKETOP}../export/power/kernel/include/jfs/fsparam.h
cdd_entry.o: ${MAKETOP}../export/power/kernel/include/sys/sysmacros.h
cdd_entry.o: ${MAKETOP}../export/power/kernel/include/sys/access.h
cdd_entry.o: ${MAKETOP}../export/power/kernel/include/sys/lock_def.h
cdd_entry.o: ${MAKETOP}../export/power/kernel/include/sys/cred.h
cdd_entry.o: ${MAKETOP}../export/power/kernel/include/sys/priv.h
cdd_entry.o: ${MAKETOP}../export/power/kernel/include/sys/mode.h
cdd_entry.o: ${MAKETOP}../export/power/kernel/include/sys/tcb.h
cdd_entry.o: ${MAKETOP}../export/power/kernel/include/sys/pcl.h
cdd_entry.o: ${MAKETOP}../export/power/kernel/include/sys/lockl.h
cdd_entry.o: ${MAKETOP}../export/power/kernel/include/fcntl.h
cdd_entry.o: ${MAKETOP}../export/power/kernel/include/sys/flock.h
cdd_entry.o: ${MAKETOP}../export/power/kernel/include/unistd.h
cdd_entry.o: ${MAKETOP}../export/power/kernel/include/sys/lockf.h
cdd_entry.o: ${MAKETOP}../export/power/kernel/include/sys/stat.h
cdd_entry.o: ${MAKETOP}../export/power/kernel/include/sys/intr.h
cdd_entry.o: ${MAKETOP}../export/power/kernel/include/sys/m_intr.h
cdd_entry.o: ${MAKETOP}../export/power/kernel/include/vt.h
cdd_entry.o: ${MAKETOP}../export/power/kernel/include/sys/font.h
cdd_entry.o: ${MAKETOP}../export/power/kernel/include/cdd.h
cdd_entry.o: ${MAKETOP}../export/power/kernel/include/cdd_macros.h
cdd_entry.o: ${MAKETOP}../export/power/kernel/include/ccmdd_tools.h
cdd_entry.o: ${MAKETOP}../export/power/kernel/include/sys/syspest.h
cdd_entry.o: ${MAKETOP}../export/power/kernel/include/sys/trchkid.h
cdd_entry.o: ${MAKETOP}../export/power/kernel/include/sys/trcmacros.h
cdd_entry.o: ${MAKETOP}../export/power/kernel/include/ccm_trchkid.h
cdd_entry.o: ${MAKETOP}../export/power/kernel/include/sys/disptrc.h
cdd_entry.o: ${MAKETOP}../export/power/kernel/include/sys/except.h
cdd_entry.o: ${MAKETOP}../export/power/kernel/include/sys/m_except.h
cdd_entry.o: ${MAKETOP}../export/power/kernel/include/mid/mid.h
cdd_entry.o: ${MAKETOP}../export/power/kernel/include/mid/hw_model.h
cdd_entry.o: ${MAKETOP}../export/power/kernel/include/sys/rcm_win.h
cdd_entry.o: ${MAKETOP}../export/power/kernel/include/sys/aixgsc.h
cdd_entry.o: ${MAKETOP}../export/power/kernel/include/mid/hw_addrs.h
cdd_entry.o: ${MAKETOP}../export/power/kernel/include/mid/hw_trace.h
cdd_entry.o: ${MAKETOP}../export/power/kernel/include/sys/trcctl.h
cdd_entry.o: ${MAKETOP}../export/power/kernel/include/mid/hw_macros.h
cdd_entry.o: ${MAKETOP}../export/power/kernel/include/string.h
cdd_entry.o: ${MAKETOP}../export/power/kernel/include/mid/hw_locks.h
cdd_entry.o: ${MAKETOP}../export/power/kernel/include/mid/hw_seops.h
cdd_entry.o: ${MAKETOP}../export/power/kernel/include/mid/hw_defer.h
cdd_entry.o: ${MAKETOP}../export/power/kernel/include/mid/hw_ind_mac.h
cdd_entry.o: ${MAKETOP}../export/power/kernel/include/mid/hw_regs_u.h
cdd_entry.o: ${MAKETOP}../export/power/kernel/include/mid/hw_dd_io_trace.h
cdd_entry.o: ${MAKETOP}../export/power/kernel/include/mid/hw_regs_k.h
cdd_entry.o: ${MAKETOP}../export/power/kernel/include/mid/hw_dsp.h
cdd_entry.o: ${MAKETOP}../export/power/kernel/include/bidefs.h
cdd_entry.o: ${MAKETOP}bos/kernext/disp/ped/cdd/mid_cdd_hw_defs.h
cdd_entry.o: ${MAKETOP}bos/kernext/disp/ped/cdd/cdd_subrs.c
cdd_entry.o: ${MAKETOP}bos/kernext/disp/ped/cdd/cdd_init.c
cdd_entry.o: ${MAKETOP}bos/kernext/disp/ped/cdd/cdd_enable.c
cdd_entry.o: ${MAKETOP}bos/kernext/disp/ped/cdd/cdd_set_POS.c
cdd_entry.o: ${MAKETOP}bos/kernext/disp/ped/cdd/cdd_load_ucode.c
cdd_entry.o: ${MAKETOP}bos/kernext/disp/ped/cdd/cdd_qvpd.c
cdd_entry.o: ${MAKETOP}bos/kernext/disp/ped/cdd/cdd_blit.c
#
# dependents of cdd_interrupt.o:
cdd_interrupt.o: ${MAKETOP}../export/power/kernel/include/sys/types.h
cdd_interrupt.o: ${MAKETOP}../export/power/kernel/include/standards.h
cdd_interrupt.o: ${MAKETOP}../export/power/kernel/include/sys/m_types.h
cdd_interrupt.o: ${MAKETOP}../export/power/kernel/include/sys/aixfont.h
cdd_interrupt.o: ${MAKETOP}../export/power/kernel/include/sys/dir.h
cdd_interrupt.o: ${MAKETOP}../export/power/kernel/include/sys/lkup.h
cdd_interrupt.o: ${MAKETOP}../export/power/kernel/include/limits.h
cdd_interrupt.o: ${MAKETOP}../export/power/kernel/include/sys/limits.h
cdd_interrupt.o: ${MAKETOP}../export/power/kernel/include/float.h
cdd_interrupt.o: ${MAKETOP}../export/power/kernel/include/jfs/dir.h
cdd_interrupt.o: ${MAKETOP}../export/power/kernel/include/sys/mdio.h
cdd_interrupt.o: ${MAKETOP}../export/power/kernel/include/sys/file.h
cdd_interrupt.o: ${MAKETOP}../export/power/kernel/include/sys/param.h
cdd_interrupt.o: ${MAKETOP}../export/power/kernel/include/sys/m_param.h
cdd_interrupt.o: ${MAKETOP}../export/power/kernel/include/jfs/fsparam.h
cdd_interrupt.o: ${MAKETOP}../export/power/kernel/include/sys/sysmacros.h
cdd_interrupt.o: ${MAKETOP}../export/power/kernel/include/sys/access.h
cdd_interrupt.o: ${MAKETOP}../export/power/kernel/include/sys/lock_def.h
cdd_interrupt.o: ${MAKETOP}../export/power/kernel/include/sys/cred.h
cdd_interrupt.o: ${MAKETOP}../export/power/kernel/include/sys/priv.h
cdd_interrupt.o: ${MAKETOP}../export/power/kernel/include/sys/mode.h
cdd_interrupt.o: ${MAKETOP}../export/power/kernel/include/sys/tcb.h
cdd_interrupt.o: ${MAKETOP}../export/power/kernel/include/sys/pcl.h
cdd_interrupt.o: ${MAKETOP}../export/power/kernel/include/sys/lockl.h
cdd_interrupt.o: ${MAKETOP}../export/power/kernel/include/fcntl.h
cdd_interrupt.o: ${MAKETOP}../export/power/kernel/include/sys/flock.h
cdd_interrupt.o: ${MAKETOP}../export/power/kernel/include/unistd.h
cdd_interrupt.o: ${MAKETOP}../export/power/kernel/include/sys/lockf.h
cdd_interrupt.o: ${MAKETOP}../export/power/kernel/include/sys/stat.h
cdd_interrupt.o: ${MAKETOP}../export/power/kernel/include/sys/intr.h
cdd_interrupt.o: ${MAKETOP}../export/power/kernel/include/sys/m_intr.h
cdd_interrupt.o: ${MAKETOP}../export/power/kernel/include/vt.h
cdd_interrupt.o: ${MAKETOP}../export/power/kernel/include/sys/font.h
cdd_interrupt.o: ${MAKETOP}../export/power/kernel/include/cdd.h
cdd_interrupt.o: ${MAKETOP}../export/power/kernel/include/cdd_macros.h
cdd_interrupt.o: ${MAKETOP}../export/power/kernel/include/cdd_intr.h
cdd_interrupt.o: ${MAKETOP}../export/power/kernel/include/cdd_intr_macros.h
cdd_interrupt.o: ${MAKETOP}../export/power/kernel/include/mid/mid.h
cdd_interrupt.o: ${MAKETOP}../export/power/kernel/include/mid/hw_model.h
cdd_interrupt.o: ${MAKETOP}../export/power/kernel/include/sys/rcm_win.h
cdd_interrupt.o: ${MAKETOP}../export/power/kernel/include/sys/aixgsc.h
cdd_interrupt.o: ${MAKETOP}../export/power/kernel/include/mid/hw_addrs.h
cdd_interrupt.o: ${MAKETOP}../export/power/kernel/include/mid/hw_trace.h
cdd_interrupt.o: ${MAKETOP}../export/power/kernel/include/sys/trcctl.h
cdd_interrupt.o: ${MAKETOP}../export/power/kernel/include/sys/trcmacros.h
cdd_interrupt.o: ${MAKETOP}../export/power/kernel/include/sys/trchkid.h
cdd_interrupt.o: ${MAKETOP}../export/power/kernel/include/mid/hw_macros.h
cdd_interrupt.o: ${MAKETOP}../export/power/kernel/include/string.h
cdd_interrupt.o: ${MAKETOP}../export/power/kernel/include/mid/hw_locks.h
cdd_interrupt.o: ${MAKETOP}../export/power/kernel/include/mid/hw_seops.h
cdd_interrupt.o: ${MAKETOP}../export/power/kernel/include/mid/hw_defer.h
cdd_interrupt.o: ${MAKETOP}../export/power/kernel/include/mid/hw_ind_mac.h
cdd_interrupt.o: ${MAKETOP}../export/power/kernel/include/mid/hw_regs_u.h
cdd_interrupt.o: ${MAKETOP}../export/power/kernel/include/mid/hw_dd_io_trace.h
cdd_interrupt.o: ${MAKETOP}../export/power/kernel/include/sys/disptrc.h
cdd_interrupt.o: ${MAKETOP}../export/power/kernel/include/sys/syspest.h
cdd_interrupt.o: ${MAKETOP}../export/power/kernel/include/mid/hw_regs_k.h
cdd_interrupt.o: ${MAKETOP}../export/power/kernel/include/mid/hw_dsp.h
cdd_interrupt.o: ${MAKETOP}../export/power/kernel/include/bidefs.h
cdd_interrupt.o: ${MAKETOP}bos/kernext/disp/ped/cdd/mid_cdd_hw_defs.h
