# @(#)94        1.1  src/bldenv/xlC/include/sys/Makefile, ade_build, bos41J, 9509A_all 2/27/95 12:43:25
#
#   COMPONENT_NAME: ade_build
#
#   FUNCTIONS: none
#
#   ORIGINS: 27
#
#
#   (C) COPYRIGHT International Business Machines Corp. 1995
#   All Rights Reserved
#   Licensed Materials - Property of IBM
#   US Government Users Restricted Rights - Use, duplication or
#   disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#

VPATH = ${MAKETOP}/xlC/usr/lpp/xlC/include/sys

INCLUDES        = \
FP.h            entdisp.h       ldr.h           rcm.h           termio.h \
NLchar.h        entuser.h       li.h            rcm_win.h       tihdr.h \
access.h        erec.h          limits.h        reboot.h        time.h \
acct.h          err_rec.h       lkup.h          reg.h           timeb.h \
acl.h           errids.h        lldebug.h       resource.h      timer.h \
acpa.h          errno.h         localedef.h     rosinfo.h       timers.h \
adspace.h       eu.h            localedef31.h   rs.h            times.h \
aio.h           events.h        lock.h          sad.h           timod.h \
aixgsc.h        except.h        lock_def.h      scdisk.h        tiuser.h \
audio.h         fblk.h          lockf.h         sched.h         tmscsi.h \
audit.h         fd.h            lockl.h         scsi.h          tokuser.h \
auditk.h        file.h          low.h           sdlextcb.h      trcctl.h \
badisk.h        filsys.h        lpio.h          seg.h           trchdr.h \
bbdir.h         flock.h         ltypes.h        select.h        trchkid.h \
bootrecord.h    fp_cpusync.h    lvdd.h          sem.h           trcmacros.h \
buf.h           fp_io.h         m_except.h      serdasd.h       trlextcb.h \
cblock.h        fs_hooks.h      m_intr.h        shm.h           ttmap.h \
cdrom.h         fstypes.h       m_param.h       signal.h        tty.h \
cfgdb.h         fullstat.h      m_types.h       sleep.h         ttychars.h \
cfgodm.h        gdlextcb.h      m_wait.h        socket.h        ttydev.h \
chownx.h        gea.h           machine.h       socketvar.h     types.h \
ciouser.h       gfs.h           malloc.h        soluser.h       uio.h \
comio.h         gpai.h          mbuf.h          space.h         un.h \
conf.h          gswio.h         mdio.h          specnode.h      unpcb.h \
configrec.h     hd_psn.h        mman.h          srcobj.h        uprintf.h \
context.h       hft.h           mntctl.h        stat.h          user.h \
core.h          i_machine.h     mode.h          statfs.h        ustat.h \
cred.h          id.h            mpqp.h          strconf.h       utsname.h \
cs.h            init.h          msg.h           stream.h        var.h \
dbexp.h         ino.h           msgbuf.h        strinfo.h       vattr.h \
dbg_codes.h     inode.h         mstsave.h       strlog.h        vfs.h \
dbkersym.h      intr.h          nlist.h         stropts.h       vlimit.h \
ddi.h           io.h            param.h         strstat.h       vminfo.h \
debug.h         io3270.h        pcl.h           sysconfig.h     vmount.h \
dev.h           ioacc.h         pin.h           sysdma.h        vmuser.h \
device.h        iocc.h          poll.h          sysinfo.h       vnode.h \
deviceq.h       ioctl.h         pri.h           syslog.h        vtimes.h \
devinfo.h       iostat.h        priv.h          sysmacros.h     wait.h \
dir.h           ipc.h           proc.h          syspest.h       watchdog.h \
display.h       iplcb.h         protosw.h       systm.h         x25ddi.h \
dlpi.h          jctype0.h       pseg.h          tacct.h         x25user.h \
dma.h           jctype1.h       ptrace.h        tape.h          xcoff.h \
domain.h        kinfo.h         pty.h           tapedd.h        xmalloc.h \
dump.h          lc_core.h       qlcextcb.h      tcb.h           xmem.h

EXPDIR  = /usr/lpp/xlC/include/sys/

.include <${RULES_MK}>
