# @(#)05	1.3  src/bos/usr/lpp/blkmux/Makefile, sysxcat, bos411, 9428A410j 1/20/94 08:47:51
#
#   COMPONENT_NAME: 370PCA_DD
#
#   FUNCTIONS: none
#
#   ORIGINS: 27
#
#
#   (C) COPYRIGHT International Business Machines Corp. 1993
#   All Rights Reserved
#   Licensed Materials - Property of IBM
#   US Government Users Restricted Rights - Use, duplication or
#   disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#

VPATH		= ${TARGET_MACHINE}

SUBDIRS		= test samples

ILIST		= helpmux.cat \
		  README

IDIR 		= /usr/lpp/blkmux/

MSGHDRS		= helpmux_msg.h
CATFILES	= helpmux.cat
HFILES		= ${MSGHDRS}	

.include <${RULES_MK}>
