# @(#)92        1.15  src/bos/usr/Makefile, Makefiles, bos411, 9428A410j 5/31/94 11:04:32
# COMPONENT_NAME:
#
# FUNCTIONS:
#
# ORIGINS: 27
#
# IBM CONFIDENTIAL -- (IBM Confidential Restricted when
# combined with the aggregated modules for this product)
#                  SOURCE MATERIALS
# (C) COPYRIGHT International Business Machines Corp. 1988, 1993
# All Rights Reserved
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#

EXPINC_SUBDIRS		= include ccs bin sbin lib lpp

EXPLIB_SUBDIRS		= bin lib ccs sbin lpp

SUBDIRS			= include bin ccs lbin lib lpp sbin share ucb \
			  games samples sys

.include <${RULES_MK}>
