# @(#)74        1.1  src/bldenv/date/Makefile, ade_build, bos412, GOLDA411a 2/22/93 15:57:33
#
#   COMPONENT_NAME: BOSBUILD
#
#   FUNCTIONS: 
#
#   ORIGINS: 27
#
#   IBM CONFIDENTIAL -- (IBM Confidential Restricted when
#   combined with the aggregated modules for this product)
#                    SOURCE MATERIALS
#
#   (C) COPYRIGHT International Business Machines Corp. 1993
#   All Rights Reserved
#   US Government Users Restricted Rights - Use, duplication or
#   disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#

VPATH		= ${MAKETOP}/bos/usr/bin/date

PROGRAMS	= date
MSGHDRS		= date_msg.h
CATFILES	= date.cat
HFILES		= ${MSGHDRS}

ILIST		= date
IDIR		= /usr/bin/

CFLAGS		= -D_BSD -DAIXV3AR

.include <${RULES_MK}>
