# @(#)76        1.1  src/bos/usr/include/netiso/Makefile, Makefiles, bos411, 9428A410j 8/5/92 16:18:23
# COMPONENT_NAME:
#
# FUNCTIONS:
#
# ORIGINS: 10,27
#
# IBM CONFIDENTIAL -- (IBM Confidential Restricted when
# combined with the aggregated modules for this product)
#                  SOURCE MATERIALS
# (C) COPYRIGHT International Business Machines Corp. 1988, 1989
# All Rights Reserved
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#

IDIR		= /usr/include/netiso/

DATAFILES	= \
	argo_debug.h \
	argoxtwentyfive.h \
	clnl.h \
	clnp.h \
	clnp_stat.h \
	cltp_var.h \
	cons.h \
	cons_ifx25.h \
	cons_pcb.h \
	eonvar.h \
	esis.h \
	iso.h \
	iso_errno.h \
	iso_map.h \
	iso_pcb.h \
	iso_snpac.h \
	iso_var.h \
	tp_clnp.h \
	tp_events.h \
	tp_ip.h \
	tp_meas.h \
	tp_param.h \
	tp_pcb.h \
	tp_seq.h \
	tp_stat.h \
	tp_states.h \
	tp_timer.h \
	tp_tpdu.h \
	tp_trace.h \
	tp_user.h

INCLUDES	= ${DATAFILES} tp_astring.c

ILIST		= ${DATAFILES}

.include <${RULES_MK}>
