# @(#)64	1.1  src/bos/usr/lib/netls/common/Makefile, libnetls, bos411, 9428A410j 3/24/94 12:25:47
#
#   COMPONENT_NAME: libnetls
#
#   FUNCTIONS: none
#
#   ORIGINS: 27
#
#   IBM CONFIDENTIAL -- (IBM Confidential Restricted when
#   combined with the aggregated modules for this product)
#                    SOURCE MATERIALS
#
#   (C) COPYRIGHT International Business Machines Corp. 1994
#   All Rights Reserved
#   US Government Users Restricted Rights - Use, duplication or
#   disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#
# Makefile


EXPDIR		= /usr/include/
INCLUDES	= ifor_common_msg.h
MSGHDRS		= ifor_common_msg.h
CATFILES	= ifor_common.cat
HFILES		= ${MSGHDRS}

.include <${RULES_MK}>
