# @(#)25	1.20  src/bos/usr/lib/nls/loc/Makefile, cfgnls, bos41B, 9504A 12/19/94 14:37:50
#
#   COMPONENT_NAME: CFGNLS
#
#   FUNCTIONS: none
#
#   ORIGINS: 27
#
#   IBM CONFIDENTIAL -- (IBM Confidential Restricted when
#   combined with the aggregated modules for this product)
#                    SOURCE MATERIALS
#
#   (C) COPYRIGHT International Business Machines Corp. 1993,1994
#   All Rights Reserved
#   US Government Users Restricted Rights - Use, duplication or
#   disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#

EXPINC_SUBDIRS	= methods

SUBDIRS	= aix31 km locale iconv iconvTable methods imk imt sim jim \
		  imcompose uconv uconvTable ccsid swkbd CN.im ZH.im

.include <${RULES_MK}>
