# @(#)27        1.3  src/bos/kernext/ent/devices.mca.8ef5.rte.trc.S, sysxent, bos411, 9439A411b 9/26/94 16:13:12
#
#   COMPONENT_NAME: SYSXENT
#
#   FUNCTIONS: none
#
#   ORIGINS: 27
#
#
#   (C) COPYRIGHT International Business Machines Corp. 1993
#   All Rights Reserved
#   Licensed Materials - Property of IBM
#   US Government Users Restricted Rights - Use, duplication or
#   disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#
* /etc/trcfmt
+351 1.0 "@entdd" \
	"EN3COM DD XMIT: " O2 A4.8 "d1=" X4 " d2=" X4 " d3=" X4

+352 1.0 "@entdd" \
	"EN3COM DD RECV: " O2 A4.8 "d1=" X4 " d2=" X4 " d3=" X4

+353 1.0 "@entdd" \
	"EN3COM DD OTHER: " O2 A4.8 "d1=" X4 " d2=" X4 " d3=" X4

+354 1.0 "@entdd" \
	"EN3COM DD ERR: " O2 A4.8 "d1=" X4 " d2=" X4 " d3=" X4

