#
# dependents of giol.o:
giol.o: ${MAKETOP}bos/kernext/inputdd/inc/sys/gio.h
giol.o: ${MAKETOP}../export/power/kernel/include/sys/errno.h
giol.o: ${MAKETOP}../export/power/kernel/include/standards.h
giol.o: ${MAKETOP}../export/power/kernel/include/sys/types.h
giol.o: ${MAKETOP}../export/power/kernel/include/sys/m_types.h
giol.o: ${MAKETOP}../export/power/kernel/include/sys/intr.h
giol.o: ${MAKETOP}../export/power/kernel/include/sys/m_intr.h
giol.o: ${MAKETOP}../export/power/kernel/include/sys/timer.h
giol.o: ${MAKETOP}../export/power/kernel/include/sys/time.h
giol.o: ${MAKETOP}../export/power/kernel/include/sys/processor.h
giol.o: ${MAKETOP}../export/power/kernel/include/sys/cblock.h
giol.o: ${MAKETOP}../export/power/kernel/include/sys/except.h
giol.o: ${MAKETOP}../export/power/kernel/include/sys/m_except.h
giol.o: ${MAKETOP}../export/power/kernel/include/sys/watchdog.h
giol.o: ${MAKETOP}bos/kernext/inputdd/inc/sys/inputdd.h
giol.o: ${MAKETOP}../export/power/kernel/include/sys/syspest.h
giol.o: ${MAKETOP}../export/power/kernel/include/sys/uio.h
giol.o: ${MAKETOP}../export/power/kernel/include/sys/xmem.h
giol.o: ${MAKETOP}../export/power/kernel/include/sys/adspace.h
giol.o: ${MAKETOP}../export/power/kernel/include/sys/seg.h
giol.o: ${MAKETOP}../export/power/kernel/include/sys/inode.h
giol.o: ${MAKETOP}../export/power/kernel/include/jfs/inode.h
giol.o: ${MAKETOP}../export/power/kernel/include/sys/param.h
giol.o: ${MAKETOP}../export/power/kernel/include/sys/m_param.h
giol.o: ${MAKETOP}../export/power/kernel/include/sys/limits.h
giol.o: ${MAKETOP}../export/power/kernel/include/float.h
giol.o: ${MAKETOP}../export/power/kernel/include/jfs/fsparam.h
giol.o: ${MAKETOP}../export/power/kernel/include/sys/sysmacros.h
giol.o: ${MAKETOP}../export/power/kernel/include/jfs/ino.h
giol.o: ${MAKETOP}../export/power/kernel/include/jfs/fsdefs.h
giol.o: ${MAKETOP}../export/power/kernel/include/jfs/filsys.h
giol.o: ${MAKETOP}../export/power/kernel/include/jfs/jfsmount.h
giol.o: ${MAKETOP}../export/power/kernel/include/sys/vnode.h
giol.o: ${MAKETOP}../export/power/kernel/include/sys/stat.h
giol.o: ${MAKETOP}../export/power/kernel/include/sys/mode.h
giol.o: ${MAKETOP}../export/power/kernel/include/sys/lockl.h
giol.o: ${MAKETOP}../export/power/kernel/include/sys/lock_def.h
giol.o: ${MAKETOP}../export/power/kernel/include/sys/cred.h
giol.o: ${MAKETOP}../export/power/kernel/include/sys/priv.h
giol.o: ${MAKETOP}../export/power/kernel/include/sys/tcb.h
giol.o: ${MAKETOP}../export/power/kernel/include/sys/pcl.h
giol.o: ${MAKETOP}../export/power/kernel/include/jfs/quota.h
giol.o: ${MAKETOP}../export/power/kernel/include/sys/vmuser.h
giol.o: ${MAKETOP}../export/power/kernel/include/sys/acl.h
giol.o: ${MAKETOP}../export/power/kernel/include/sys/access.h
giol.o: ${MAKETOP}../export/power/kernel/include/sys/systemcfg.h
giol.o: ${MAKETOP}../export/power/kernel/include/sys/ioacc.h
giol.o: ${MAKETOP}../export/power/kernel/include/sys/ddtrace.h
giol.o: ${MAKETOP}../export/power/kernel/include/sys/trchkid.h
giol.o: ${MAKETOP}../export/power/kernel/include/sys/trcmacros.h
giol.o: ${MAKETOP}../export/power/kernel/include/sys/errids.h
giol.o: ${MAKETOP}../export/power/kernel/include/sys/err_rec.h
giol.o: ${MAKETOP}../export/power/kernel/include/sys/signal.h
giol.o: ${MAKETOP}../export/power/kernel/include/sys/context.h
giol.o: ${MAKETOP}../export/power/kernel/include/sys/mstsave.h
#
# dependents of giou.o:
giou.o: ${MAKETOP}bos/kernext/inputdd/inc/sys/gio.h
giou.o: ${MAKETOP}../export/power/kernel/include/sys/errno.h
giou.o: ${MAKETOP}../export/power/kernel/include/standards.h
giou.o: ${MAKETOP}../export/power/kernel/include/sys/types.h
giou.o: ${MAKETOP}../export/power/kernel/include/sys/m_types.h
giou.o: ${MAKETOP}../export/power/kernel/include/sys/intr.h
giou.o: ${MAKETOP}../export/power/kernel/include/sys/m_intr.h
giou.o: ${MAKETOP}../export/power/kernel/include/sys/timer.h
giou.o: ${MAKETOP}../export/power/kernel/include/sys/time.h
giou.o: ${MAKETOP}../export/power/kernel/include/sys/processor.h
giou.o: ${MAKETOP}../export/power/kernel/include/sys/cblock.h
giou.o: ${MAKETOP}../export/power/kernel/include/sys/except.h
giou.o: ${MAKETOP}../export/power/kernel/include/sys/m_except.h
giou.o: ${MAKETOP}../export/power/kernel/include/sys/watchdog.h
giou.o: ${MAKETOP}bos/kernext/inputdd/inc/sys/inputdd.h
giou.o: ${MAKETOP}../export/power/kernel/include/sys/syspest.h
giou.o: ${MAKETOP}../export/power/kernel/include/sys/uio.h
giou.o: ${MAKETOP}../export/power/kernel/include/sys/xmem.h
giou.o: ${MAKETOP}../export/power/kernel/include/sys/malloc.h
giou.o: ${MAKETOP}../export/power/kernel/include/sys/device.h
giou.o: ${MAKETOP}../export/power/kernel/include/sys/file.h
giou.o: ${MAKETOP}../export/power/kernel/include/sys/param.h
giou.o: ${MAKETOP}../export/power/kernel/include/sys/m_param.h
giou.o: ${MAKETOP}../export/power/kernel/include/sys/limits.h
giou.o: ${MAKETOP}../export/power/kernel/include/float.h
giou.o: ${MAKETOP}../export/power/kernel/include/jfs/fsparam.h
giou.o: ${MAKETOP}../export/power/kernel/include/sys/sysmacros.h
giou.o: ${MAKETOP}../export/power/kernel/include/sys/access.h
giou.o: ${MAKETOP}../export/power/kernel/include/sys/lock_def.h
giou.o: ${MAKETOP}../export/power/kernel/include/sys/cred.h
giou.o: ${MAKETOP}../export/power/kernel/include/sys/priv.h
giou.o: ${MAKETOP}../export/power/kernel/include/sys/mode.h
giou.o: ${MAKETOP}../export/power/kernel/include/sys/tcb.h
giou.o: ${MAKETOP}../export/power/kernel/include/sys/pcl.h
giou.o: ${MAKETOP}../export/power/kernel/include/sys/lockl.h
giou.o: ${MAKETOP}../export/power/kernel/include/fcntl.h
giou.o: ${MAKETOP}../export/power/kernel/include/sys/flock.h
giou.o: ${MAKETOP}../export/power/kernel/include/unistd.h
giou.o: ${MAKETOP}../export/power/kernel/include/sys/lockf.h
giou.o: ${MAKETOP}../export/power/kernel/include/sys/stat.h
giou.o: ${MAKETOP}../export/power/kernel/include/sys/low.h
giou.o: ${MAKETOP}../export/power/kernel/include/sys/sleep.h
giou.o: ${MAKETOP}../export/power/kernel/include/sys/adspace.h
giou.o: ${MAKETOP}../export/power/kernel/include/sys/seg.h
giou.o: ${MAKETOP}../export/power/kernel/include/sys/inode.h
giou.o: ${MAKETOP}../export/power/kernel/include/jfs/inode.h
giou.o: ${MAKETOP}../export/power/kernel/include/jfs/ino.h
giou.o: ${MAKETOP}../export/power/kernel/include/jfs/fsdefs.h
giou.o: ${MAKETOP}../export/power/kernel/include/jfs/filsys.h
giou.o: ${MAKETOP}../export/power/kernel/include/jfs/jfsmount.h
giou.o: ${MAKETOP}../export/power/kernel/include/sys/vnode.h
giou.o: ${MAKETOP}../export/power/kernel/include/jfs/quota.h
giou.o: ${MAKETOP}../export/power/kernel/include/sys/vmuser.h
giou.o: ${MAKETOP}../export/power/kernel/include/sys/acl.h
giou.o: ${MAKETOP}../export/power/kernel/include/sys/systemcfg.h
giou.o: ${MAKETOP}../export/power/kernel/include/sys/ioacc.h
giou.o: ${MAKETOP}../export/power/kernel/include/sys/ddtrace.h
giou.o: ${MAKETOP}../export/power/kernel/include/sys/trchkid.h
giou.o: ${MAKETOP}../export/power/kernel/include/sys/trcmacros.h
giou.o: ${MAKETOP}../export/power/kernel/include/sys/devinfo.h
giou.o: ${MAKETOP}../export/power/kernel/include/sys/ioctl.h
giou.o: ${MAKETOP}../export/power/kernel/include/sys/ttychars.h
giou.o: ${MAKETOP}../export/power/kernel/include/sys/ttydev.h
