$ @(#)24        1.3.1.1 3/14/95 src/bos/usr/lib/methods/common/devices_p.msg, cfgmethods, bos41J, 9511A_all 10:20:45
$
$  COMPONENT_NAME: (CFGMETHODS) device configuration methods
$ 
$  FUNCTIONS: Devices configuration message catalog
$ 
$  ORIGINS: 83
$ 
$  LEVEL 1, 5 Years Bull Confidential Information
$ 
$ 
$ System Object and related devices
$quote "
$set 1
1 "Cabinet"
2 "Operator Panel"
3 "Power Supply"
4 "Power Supply Interface"
5 "Multiprocessor Drawer"
$
$ Family 2 bus
$set 3
1 "MCA Planar"
