$ @(#)30        1.3  src/bos/usr/lib/methods/common/graphdev.msg, magdd, bos41J, 9516A_all 4/18/95 13:42:55
$                                                                 
$  COMPONENT_NAME: (CFGMETHODS) device configuration methods      
$                                                                 
$  FUNCTIONS: Devices configuration message catalog               
$                                                                 
$  ORIGINS: 27                                                    
$                                                                 
$  IBM CONFIDENTIAL -- (IBM Confidential Restricted when          
$  combined with the aggregated modules for this product)         
$                   SOURCE MATERIALS                              
$  (C) COPYRIGHT International Business Machines Corp. 1994       
$  All Rights Reserved                                            
$                                                                 
$  US Government Users Restricted Rights - Use, duplication or    
$  disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
$
$quote "
$        
$ Generic Display Adapter
$ set 1 
$
1 Screen width in millimeters
2 Screen height in millimeters
3 Screen width in pixels
4 Screen height in pixels
5 Physical display ID for adapter
6 Which HFT this display belongs to
7 Bus interrupt level
8 Interrupt priority
9 Pathname of the device dependent configuration method
10 Name of the full function device driver interrupt routine
11 Name of the Common Character Mode device driver
12 Name of the Common Character Mode device driver interrupt routine
13 Name of the CDD kernel load module
14 Name of the CDD kernel load module interrupt routine
15 Display description
$ The first 14 messages of this set should not be translated 
$ as they will be generated from an existing catalog 
90 Server number 
91 Custom font
92 Default color lookup table entry
93 LFT color lookup table entry
94 Immediate frame buffer swap
$
101 GXT500D Graphics Adapter
$
$ Adapter name
102 GXT500 Graphics Adapter
$
$ Adapter name
