$ @(#)82        1.3 8/23/94 src/bos/usr/lib/methods/common/scdisk.msg, cfgmethods, bos411, 9435A411a 16:57:19
$
$ COMPONENT_NAME: (CFGMETHODS) device configuration methods
$
$ FUNCTIONS: SCSI CD-ROM, Disk, Read/Write Optical configuration message 
$            catalog
$
$ ORIGINS: 27, 83
$
$ IBM CONFIDENTIAL -- (IBM Confidential Restricted when
$ combined with the aggregated modules for this product)
$                  SOURCE MATERIALS
$ (C) COPYRIGHT International Business Machines Corp. 1994
$ All Rights Reserved
$
$ US Government Users Restricted Rights - Use, duplication or
$ disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
$
$ LEVEL 1, 5 Years Bull Confidential Information
$
$quote "
$
$  SCSI CD-ROM Drives and SCSI Read/Write Optical Drives
$set 1
1 "CD-ROM Drive"
2 "RESERVE device on open"
3 "PREVENT ejection of media when open"
4 "Physical volume identifier"
10 "Other SCSI CD-ROM Drive"
11 "Multimedia CD-ROM Drive"
12 "SCSI CD-ROM Drive"
13 "SCSI Multimedia CD-ROM Drive"
14 "Differential SCSI CD-ROM Drive"
15 "Differential SCSI Multimedia CD-ROM Drive"
16 "16 Bit SCSI CD-ROM Drive"
17 "16 Bit SCSI Multimedia CD-ROM Drive"
18 "16 Bit Differential SCSI CD-ROM Drive"
19 "16 Bit Differential SCSI Multimedia CD-ROM Drive"
20 "Other SCSI Read/Write Optical Drive"
21 "127 MB SCSI Read/Write Optical Drive"
22 "SCSI Read/Write Optical Drive"
23 "Differential SCSI Read/Write Optical Drive"
24 "SCSI Multimedia Read/Write Optical Drive"
25 "Differential SCSI Multimedia Read/Write Optical Drive"
26 "16 Bit SCSI Read/Write Optical Drive"
27 "16 Bit Differential SCSI Read/Write Optical Drive"
28 "16 Bit SCSI Multimedia Read/Write Optical Drive"
29 "16 Bit Differential SCSI Multimedia Read/Write Optical Drive"
30 "Queue DEPTH"
31 "Queuing TYPE"
32 "Use QERR bit"
33 "Device CLEARS its Queue on error"
34 "READ/WRITE time out value"
35 "START UNIT time out value"
36 "REASSIGN time out value"
37 "FORMAT unit time out value"
38 "READ time out value"
40 "Play AUDIO supported"
41 "MODE 2 FORM 1 Density Code"
42 "MODE 2 FORM 2 Density Code"
43 "CD-DA Density Code"
60 "Size in Megabytes"
$
$  SCSI Disk Drives
$set 2
1 "320 MB SCSI Disk Drive"
2 "Physical volume identifier"
3 "400 MB SCSI Disk Drive"
4 "160 MB SCSI Disk Drive"
5 "355 MB SCSI Disk Drive"
6 "670 MB SCSI Disk Drive"
7 "857 MB SCSI Disk Drive"
8 "Other SCSI Disk Drive"
9 "1.0 GB SCSI Disk Drive"
10 "1.37 GB SCSI Disk Drive"
11 "1.2 GB SCSI Disk Drive (in 2.4 GB Disk Unit)"
12 "200 MB SCSI Disk Drive"
13 "2.0 GB SCSI Disk Drive" 
14 "540 MB SCSI Disk Drive"
15 "1.0 GB Differential SCSI Disk Drive"
16 "2.0 GB Differential SCSI Disk Drive"
17 "2.0 GB 16 Bit Differential SCSI Disk Drive"
18 "2.0 GB 16 Bit SCSI Disk Drive"
19 "1.0 GB 16 Bit Differential SCSI Disk Drive"
20 "730 MB SCSI Disk Drive"
21 "1.1 GB SCSI Disk Drive"
22 "1.1 GB 16 Bit SCSI Disk Drive"
23 "1.1 GB 16 Bit Differential SCSI Disk Drive"
24 "2.2 GB SCSI Disk Drive"
25 "2.2 GB 16 Bit SCSI Disk Drive"
26 "2.2 GB 16 Bit Differential SCSI Disk Drive"
27 "4.5 GB 16 Bit SCSI Disk Drive"
28 "4.5 GB 16 Bit Differential SCSI Disk Drive"
29 "270 MB SCSI Disk Drive"
30 "Queue DEPTH"
31 "Queuing TYPE"
32 "Use QERR bit"
33 "Device CLEARS its Queue on error"
34 "READ/WRITE time out value"
35 "START unit time out value"
36 "REASSIGN time out value"
40 "340 MB SCSI Disk Drive"
41 "360 MB SCSI Disk Drive"
42 "810 MB SCSI Disk Drive"
51 "SCSI Disk Drive"
52 "Differential SCSI Disk Drive"
53 "16 Bit SCSI Disk Drive"
54 "16 Bit Differential SCSI Disk Drive"
60 "Size in Megabytes"
