# @(#)95	1.1  src/bldenv/strfile/Makefile, cmdgames, bos412, GOLDA411a 4/2/93 11:05:52
#
# COMPONENT_NAME: CMDGAMES
#
# FUNCTIONS:
#
# ORIGINS: 27
#
# IBM CONFIDENTIAL -- (IBM Confidential Restricted when
# combined with the aggregated modules for this product)
#                  SOURCE MATERIALS
# (C) COPYRIGHT International Business Machines Corp. 1993
# All Rights Reserved
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#

FORTUNEDIR	= ${MAKETOP}bos/usr/games/lib/fortune
VPATH		= ${FORTUNEDIR}
INCFLAGS	= -I${FORTUNEDIR}

PROGRAMS	= strfile

ILIST		= ${PROGRAMS}
IDIR		= /usr/games/lib/fortune/

.include <${RULES_MK}>
