# @(#)91        1.5  src/bos/kernext/disp/ped/pedmacro/Makefile, pedmacro, bos411, 9428A410j 3/24/94 15:22:03
# COMPONENT_NAME: (peddd) Pedernales Device Driver
#
# FUNCTIONS:
#
# ORIGINS: 27
#
# IBM CONFIDENTIAL -- (IBM Confidential Restricted when
# combined with the aggregated modules for this product)
# (C) COPYRIGHT International Business Machines Corp. 1989, 1994
# All Rights Reserved
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#
#

EXPDIR          = /kernel/include/mid/

DATAFILES     =  hw_dd_io_trace.h hw_defer.h hw_hooks.h         \
	        hw_timer.h hw_2dm1con.h hw_FIF2dm1.h   \
	        hw_FIFrms.h hw_HCRkern.h hw_PCBrms.h hw_addrs.h hw_dsp.h       \
	        hw_errno.h hw_ind_mac.h hw_iodefs.h hw_io_kproc.h hw_locks.h   \
	        hw_macros.h hw_model.h hw_model_rms.h hw_names.h hw_regs_k.h   \
	        hw_regs_u.h hw_rmscon.h hw_se_types.h hw_seops.h hw_trace.h    \
	        hw_typdefs.h mid.h

INCLUDES        = ${DATAFILES}

.include <${RULES_MK}>
