$ @(#)68	1.3  src/bos/usr/ccs/lib/libcurses/compat/setupterm.msg, libcurses, bos411, 9428A410j 8/9/91 12:58:00
$
$  COMPONENT_NAME: (LIBCURSE) Curses Library
$
$  FUNCTIONS:  none
$
$  ORIGINS: 27
$
$  IBM CONFIDENTIAL -- (IBM Confidential Restricted when
$  combined with the aggregated modules for this product)
$                   SOURCE MATERIALS
$  (C) COPYRIGHT International Business Machines Corp. 1985, 1989
$  All Rights Reserved
$
$  US Government Users Restricted Rights - Use, duplication or
$  disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
$

$quote "         define quote character.

$len 
$set MS_setupterm        Define initial set#

M_MSG_2 "setuperm: 1371-001 No such terminal: "
M_MSG_4 "setuperm: 1371-002 corrupted term entry\r\n"
M_MSG_5 "setuperm: 1371-003 term entry too long\r\n"
