#!/etc/drivers/soldd
* @(#)68	1.1  src/bos/kernext/sol/soldd.exp, sysxsol, bos411, 9428A410j 4/3/91 03:23:50
*
* COMPONENT_NAME: (SYSXSOL) Serial Optical Link DD Top Half Export List
*
* FUNCTIONS:
*
* ORIGINS: 27
*
* (C) COPYRIGHT International Business Machines Corp. 1988, 1990
* All Rights Reserved
* Licensed Materials - Property of IBM
*
* US Government Users Restricted Rights - Use, duplication or
* disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
*
