# @(#)36	1.1  src/bos/usr/lib/asw/mpqp/Makefile, Makefiles, bos411, 9428A410j 1/26/93 16:34:29
# COMPONENT_NAME:
#
# FUNCTIONS:
#
# ORIGINS: 27
#
# IBM CONFIDENTIAL -- (IBM Confidential Restricted when
# combined with the aggregated modules for this product)
#                  SOURCE MATERIALS
# (C) COPYRIGHT International Business Machines Corp. 1988, 1989
# All Rights Reserved
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#


ILIST		= mpqpasw

IDIR		= /usr/lib/asw/

.include <${RULES_MK}>

