# @(#)60	1.2  src/bos/kernext/tok/devices.mca.8fc8.rte.trc.S, sysxtok, bos410, 9405A410b 11/11/93 11:23:33
#
#   COMPONENT_NAME: SYSXFDDI
#
#   FUNCTIONS: none
#
#   ORIGINS: 27
#
#
#   (C) COPYRIGHT International Business Machines Corp. 1994
#   All Rights Reserved
#   Licensed Materials - Property of IBM
#   US Government Users Restricted Rights - Use, duplication or
#   disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#
* /etc/trcfmt
+30A 1.0 "@fddidd" \
        "FDDI DD XMT: " O2 A4.8 "d1=" X4 " d2=" X4 " d3=" X4 

+30B 1.0 "@fddidd" \
        "FDDI DD RCV: " O2 A4.8 "d1=" X4 " d2=" X4 " d3=" X4

+30C 1.0 "@fddidd" \
        "FDDI DD GEN: " O2 A4.8 "d1=" X4 " d2=" X4 " d3=" X4
