#!/unix
* @(#)47        1.2  src/bos/diag/tu/bloom/slih/bloom_intr.exp, tu_bloom, bos41J, 9514A_all 4/3/95 16:44:34
*
*   COMPONENT_NAME: TU_BLOOM
*
*   FUNCTIONS: none
*
*   ORIGINS: 27
*
*
*   (C) COPYRIGHT International Business Machines Corp. 1995
*   All Rights Reserved
*   Licensed Materials - Property of IBM
*   US Government Users Restricted Rights - Use, duplication or
*   disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
*
bloom_interrupt
