# @(#)72	1.3  src/bos/etc/security/audit/bincmds.S, cfgsaud, bos411, 9428A410j 11/18/93 09:29:58
#
#  COMPONENT_NAME: CFGSAUD
#
#  FUNCTIONS: none
#
#  ORIGINS: 27
#
#  (C) COPYRIGHT International Business Machines Corp. 1989, 1993
#  All Rights Reserved
#  Licensed Materials - Property of IBM
#
#  US Government Users Restricted Rights - Use, duplication or
#  disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#
/usr/sbin/auditcat -p -o $trail $bin
