# @(#)66	1.2  src/bos/etc/security/audit/cmds.S, cfgsaud, bos411, 9428A410j 3/26/91 14:07:37
#  COMPONENT_NAME: CFGSAUD
#
#  ORIGINS: 27
#
#  (C) COPYRIGHT International Business Machines Corp. 1989, 1991
#  All Rights Reserved
#  Licensed Materials - Property of IBM
#
#  US Government Users Restricted Rights - Use, duplication or
#  disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#
/etc/auditcat -p -o $trail $bin
