# @(#)88        1.5  src/bos/etc/security/audit/Makefile, cfgsaud, bos411, 9428A410j 3/29/94 09:23:21
# COMPONENT_NAME: CFGSAUD
#
# FUNCTIONS: none
#
# ORIGINS: 27 
#
# IBM CONFIDENTIAL -- (IBM Confidential Restricted when
# combined with the aggregated modules for this product)
#                  SOURCE MATERIALS
# (C) COPYRIGHT International Business Machines Corp. 1989, 1994
# All Rights Reserved
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.

SCRIPTS		= bincmds config events objects streamcmds

ILIST		= ${SCRIPTS}
IDIR		= /etc/security/audit/

NOUPDATE_LIST   = /etc/security/audit/bincmds \
		  /etc/security/audit/config \
		  /etc/security/audit/events \
		  /etc/security/audit/objects \
		  /etc/security/audit/streamcmds 

.include <${RULES_MK}>
