# @(#)71	1.5  src/bos/etc/security/audit/streamcmds.S, cfgsaud, bos411, 9428A410j 11/18/93 09:31:01
#
#  COMPONENT_NAME: CFGSAUD
#
#  FUNCTIONS:  none
#
#  ORIGINS: 27
#
#  (C) COPYRIGHT International Business Machines Corp. 1989, 1993
#  All Rights Reserved
#  Licensed Materials - Property of IBM
#  US Government Users Restricted Rights - Use, duplication or
#  disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#
/usr/sbin/auditstream | auditpr > /audit/stream.out &
