# @(#)91        1.2  src/bos/usr/lib/nls/loc/jim/jed/Makefile, libKJI, bos411, 9428A410j 2/2/94 21:34:27
#
# COMPONENT_NAME: libKJI
#
# FUNCTIONS: Japanese Input Method
#
# ORIGINS: 27
#
# IBM CONFIDENTIAL -- (IBM Confidential Restricted when
# combined with the aggregated modules for this product)
#                  SOURCE MATERIALS
# (C) COPYRIGHT International Business Machines Corp. 1989, 1991, 1993
# All Rights Reserved
# Licensed Materials - Property of IBM
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#

LIBRARIES	= libjed.a

INCFLAGS	= -I../jmnt -I${MAKETOP}/bos/usr/include
DEBUG		=

OFILES		= jedInit.o \
			jedClose.o \
			jedProc.o \
			jedSetStr.o \
			jedFix.o \
			jedClear.o \
			jedCtrl.o \
			jedMisc.o \
			jedIntern.o

.include <${RULES_MK}>
