# @(#)83	1.7  src/bos/usr/lib/netls/adk/Makefile, libnetls, bos411, 9428A410j 5/26/94 18:12:30
# COMPONENT_NAME:  libnetls
#
# FUNCTIONS:
#
# ORIGINS: 27
#
# IBM CONFIDENTIAL -- (IBM Confidential Restricted when
# combined with the aggregated modules for this product)
#                  SOURCE MATERIALS
# (C) COPYRIGHT International Business Machines Corp. 1988, 1992
# All Rights Reserved
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#

SUBDIRS			= lib X11 bin cat1
EXPINC_SUBDIRS		= include
EXPLIB_SUBDIRS		= lib

.include <${RULES_MK}>

