# @(#)66        1.1  src/bos/diag/tu/sun/Makefile, tu_sunrise, bos411, 9436B411a 9/2/94 13:40:39
#
#   COMPONENT_NAME: tu_sunrise
#
#   FUNCTIONS: Makefile for Sunrise Test Units release bos41*
#
#   ORIGINS: 27
#
#
#   (C) COPYRIGHT International Business Machines Corp. 1994
#   All Rights Reserved
#   Licensed Materials - Property of IBM
#   US Government Users Restricted Rights - Use, duplication or
#   disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#

LIBRARIES       = libsuntu.a

EXPLIB_TARGETS  = export_libsuntu.a
EXPDIR          = /usr/lib/

LIBS            =

OFILES           = \
	hw_manage.o       \
	getsun.o          \
	sunutil.o         \
	px2070util.o      \
	tposreg.o         \
	tvpd.o            \
	t2070reg.o        \
	tmiamireg.o       \
	t560reg.o         \
	pc5xxini.o        \
	makehuff.o        \
	makeq.o           \
	tframebuf.o       \
	tvidsetup.o       \
	pixeldma.o        \
	tdma.o            \
	Compinit.o        \
	Decompinit.o      \
	tscaler.o         \
	tfmem.o           \
	tcompdecomp.o     \
	560ToFrom2070.o   \
	sun_exectu.o

ILIST           =
IDIR            =

.include <${RULES_MK}>
