# @(#)01        1.1  src/bldenv/includes/XTOP/Makefile, ade_build, bos412, GOLDA411a 6/30/94 17:19:00
#
#   COMPONENT_NAME: ade_build 
#
#   FUNCTIONS:
#
#   ORIGINS: 27
#
#   IBM CONFIDENTIAL -- (IBM Confidential Restricted when
#   combined with the aggregated modules for this product)
#                    SOURCE MATERIALS
#
#   (C) COPYRIGHT International Business Machines Corp. 1993
#   All Rights Reserved
#   US Government Users Restricted Rights - Use, duplication or
#   disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#
#   This makefile created to export the listed header files.  This will 
#   allow a machine to build 4.1 without having the X-Windows Development
#   environment installed.

VPATH	= ${MAKETOP}gos/2d/XTOP/include:${MAKETOP}gos/2d/XTOP/lib/X

EXPDIR = /usr/include/X11/

INCLUDES = \
	Xlib.h \
	Xutil.h \
	Xfuncproto.h \
	XWDFile.h


.include <${RULES_MK}>
