# @(#)36        1.1  src/bos/usr/lib/methods/cfgdmxfddi/Makefile, sysxfddi, bos411, 9428A410j 11/29/93 10:15:33
#
# COMPONENT_NAME:
#
# FUNCTIONS:
#
# ORIGINS: 27
#
# IBM CONFIDENTIAL -- (IBM Confidential Restricted when
# combined with the aggregated modules for this product)
#                  SOURCE MATERIALS
# (C) COPYRIGHT International Business Machines Corp. 1993
# All Rights Reserved
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#

VPATH           = ../common

PROGRAMS        = cfgdmxfddi

OFILES          = cfgdmxfddi.o

INCFLAGS        = -I../common

ILIST           = cfgdmxfddi
IDIR		= /usr/lib/methods/

LIBS		= -ls -lodm -lcfg -lrts

.include <${RULES_MK}>
