# @(#)57	1.1  src/bos/usr/lib/nls/loc/imk/hgcomp/Makefile, libkr, bos411, 9428A410j 1/13/93 15:02:21
#
# COMPONENT_NAME:  LIBKR
#
# FUNCTIONS: Korean Input Method
#
# ORIGINS: 27
#
# IBM CONFIDENTIAL -- (IBM Confidential Restricted when
# combined with the aggregated modules for this product)
#                  SOURCE MATERIALS
# (C) COPYRIGHT International Business Machines Corp. 1988, 1993
# All Rights Reserved
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#

LIBRARIES = libhgcomp.a
OFILES    = hgcomp.o
INCFLAGS  = -I${MAKETOP}/bos/usr/lib/nls/loc/imk/include

.include <${RULES_MK}>
