# @(#)73	1.1  src/bldenv/errlg/errprefix/Makefile, cmderrlg, bos412, GOLDA411a 9/28/93 16:39:05
#
#   COMPONENT_NAME: CMDERRLG
#
#   FUNCTIONS:
#
#   ORIGINS: 27
#
#   IBM CONFIDENTIAL -- (IBM Confidential Restricted when
#   combined with the aggregated modules for this product)
#                    SOURCE MATERIALS
#
#   (C) COPYRIGHT International Business Machines Corp. 1993
#   All Rights Reserved
#   US Government Users Restricted Rights - Use, duplication or
#   disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#

PROGRAMS	= errprefix
ILIST		= ${PROGRAMS}
IDIR		= /usr/bin/

.include <${RULES_MK}>
