# @(#) 44 1.2 src/bos/usr/lpp/bosinst/preserve.list/Makefile, bosinst, bos411, 9428A410j 9/10/93 08:12:23
# COMPONENT_NAME: bosinst
#
# FUNCTIONS: Makefile for preserve.list
#
# ORIGINS: 27
#
# IBM CONFIDENTIAL -- (IBM Confidential Restricted when
# combined with the aggregated modules for this product)
#                  SOURCE MATERIALS
# (C) COPYRIGHT International Business Machines Corp. 1993
# All Rights Reserved
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#

DATAFILES	= preserve.list

ILIST		= preserve.list
IDIR		= /etc/


.include <${RULES_MK}>
