# @(#)29	1.1  src/bos/diag/da/siosl/Makefile, dakbdsl, bos411, 9428A410j 12/8/92 18:14:50
#
#   COMPONENT_NAME: DAKBDSL
#
#   FUNCTIONS: 
#
#   ORIGINS: 27
#
#   IBM CONFIDENTIAL -- (IBM Confidential Restricted when
#   combined with the aggregated modules for this product)
#                    SOURCE MATERIALS
#
#   (C) COPYRIGHT International Business Machines Corp. 1992
#   All Rights Reserved
#   US Government Users Restricted Rights - Use, duplication or
#   disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#


SUBDIRS		= kmta kbddev tabletdev

.include <${RULES_MK}>
