# @(#)54	1.2  src/bos/usr/games/lib/quiz/africa.S, cmdgames, bos411, 9428A410j 8/6/91 12:16:21
#
# COMPONENT_NAME: (CMDGAMES) unix games
#
# FUNCTIONS: quiz data file, africa
#
# ORIGINS: 26, 27
#
# This module contains IBM CONFIDENTIAL code. -- (IBM
# Confidential Restricted when combined with the aggregated
# modules for this product)
#                  SOURCE MATERIALS
# (C) COPYRIGHT International Business Machines Corp. 1985, 1989
# All Rights Reserved
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#
#
Algeria:Alg[iers|er]
Botswana:Gaberones
Burundi:Bujumbura
Cameroun:Yaound['e|e'|e]
Central Africa{n Rep{ublic}}:Bangui
Chad:Ndjamena
Congo:Brazzaville
Dahomey:Porto Novo
Ethiopia:Addis Ababa
Gabon:Libreville
Ghana:Accra
Guinea-Bissau:Bissau
Guinea:Conakry
Ivory Coast:Abidjan
Kenya:Nairobi
Lesotho:Maseru
Liberia:Monrovia
Libya:Al Bayda{'}
Malagasy{ Rep{ublic}}|Madagascar:Tananarive
Malawi:Zomba
Mali:Bamako
Mauritania:Nouakchott
Morocco:Rabat
Mo[z|,c|c,|c]ambique:Louren[,c|c,|c]o Marques
Niger:Niamey
Nigeria:Lagos
Rhodesia:Salisbury
Rwanda:Kigali
Senegal:Dakar
Sierra Leone:Freetown
Somali{ Rep{ublic}}:Mogadis[cio|hu]
Sudan:Khartoum
Swaziland:Mbabane
Tanzania:Dar es Salaam
Togo:Lom['e|e'|e]
Tunisia:Tunis
Uganda:Kampala
United Arab Rep{ublic}|Egypt:Cairo
Upper Volta:Ouagadougou
Zambia:Lusaka
Za["i|i"|i]re:Kinshasha
{Rep{ublic} of }South Africa:Pretoria
{The }Gambia:Bathurst
