# @(#)55	1.2  src/bos/usr/games/lib/quiz/america.S, cmdgames, bos411, 9428A410j 8/6/91 12:16:26
#
# COMPONENT_NAME: (CMDGAMES) unix games
#
# FUNCTIONS: quiz data file, america
#
# ORIGINS: 26, 27
#
# This module contains IBM CONFIDENTIAL code. -- (IBM
# Confidential Restricted when combined with the aggregated
# modules for this product)
#                  SOURCE MATERIALS
# (C) COPYRIGHT International Business Machines Corp. 1985, 1989
# All Rights Reserved
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#
#
Argentina:Buenos Aires
Bahamas:Nassau
Barbados:Bridgetown
Bolivia:La Paz|Sucre
Bra[z|s]il:Brasilia
Canada:Ottawa
Chile:Santiago
Colombia:Bogot['a|a'|a]
Costa Rica:San Jose
Cuba:Ha[v|b]ana
Dominican Republic:Santo Domingo
Ecuador:Quito
El Salvador:San Salvador
Guatemala:Guatemala
Guyana:Georgetown
Haiti:Port au Prince
Honduras:Tegucigalpa
Jamaica:Kingston
Mexico:Mexico
Nicaragua:Managua
Panama:Panama
Paraguay:Asunci['o|o'|o]n
Peru:Lima
Trinidad[ and Tobago|]:Port of Spain
United States|US{A}:Washington
Uruguay:Montevideo
Venezuela:Caracas
