# @(#)58	1.2  src/bos/usr/games/lib/quiz/asia.S, cmdgames, bos411, 9428A410j 8/6/91 12:16:43
#
# COMPONENT_NAME: (CMDGAMES) unix games
#
# FUNCTIONS: quiz data file, asia
#
# ORIGINS: 26, 27
#
# This module contains IBM CONFIDENTIAL code. -- (IBM
# Confidential Restricted when combined with the aggregated
# modules for this product)
#                  SOURCE MATERIALS
# (C) COPYRIGHT International Business Machines Corp. 1985, 1989
# All Rights Reserved
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#
#
Afghanistan:Kabul
Australia:Canberra
Bahrein:Manama
Bangladesh:Dacca
Bhutan:Thimbu
Burma:Rangoon
China:Peking
Cyprus:Nicosia
India:New Delhi
Indonesia:Djakarta
Iran:Tehran
Iraq:Baghdad
Israel:Jerusalem
Japan:Tokyo
Jordan:Amman
Khmer|Cambodia:P{h}nom Penh
Kuwait:Al-kuwait
Laos:Vientiane
Lebanon:Beirut
Malaysia:Kuala Lumpur
Maldive Islands:Male
Mongolia:Ulan Bator
Nepal:Katmandu
North Korea:P{'}yongyang
North Yemen:San{'}a
Oman:Muscat
Pakistan:Islamabad
Papua[-| ]New Guinea:Port Moresby
Philippines:Quezon City
Qatar:Doha
Saudi Arabia:Riyadh|J{ei}ddah
Singapore:Singapore
South Korea:Seoul
South Yemen:Aden
Sri Lanka:Colombo
Syria:Damascus
Taiwan:Taipei
Thailand:Bangkok
Turkey:Ankara
United Arab Emirates:Abu Dhabi
Vietnam:Hanoi
