# @(#)59	1.2  src/bos/usr/games/lib/quiz/babies.S, cmdgames, bos411, 9428A410j 8/6/91 12:16:48
#
# COMPONENT_NAME: (CMDGAMES) unix games
#
# FUNCTIONS: quiz data file, babies
#
# ORIGINS: 26, 27
#
# This module contains IBM CONFIDENTIAL code. -- (IBM
# Confidential Restricted when combined with the aggregated
# modules for this product)
#                  SOURCE MATERIALS
# (C) COPYRIGHT International Business Machines Corp. 1985, 1989
# All Rights Reserved
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#
#
cub:lion|tiger|bear
kitten:cat|fox|skunk|rabbit|bobcat|panther
gosling:goose
colt|foal:horse|donkey|zebra
puppy:dog
pup:seal|fox|beaver
duckling:duck
fawn:deer
piglet|shoat:pig
lamb:sheep
kid:goat|antelope
chick:chicken
tadpole|polliwog:frog|toad
joey:kangaroo
calf:cow|whale|moose|elephant|buffalo|giraffe
caterpillar:butterfly|moth
elver:eel
eaglet:eagle
owlet:owl
fingerling|fry:fish
nestling:bird
