# @(#)62	1.2  src/bos/usr/games/lib/quiz/chinese.S, cmdgames, bos411, 9428A410j 8/6/91 12:16:58
#
# COMPONENT_NAME: (CMDGAMES) unix games
#
# FUNCTIONS: quiz data file, chinese
#
# ORIGINS: 26, 27
#
# This module contains IBM CONFIDENTIAL code. -- (IBM
# Confidential Restricted when combined with the aggregated
# modules for this product)
#                  SOURCE MATERIALS
# (C) COPYRIGHT International Business Machines Corp. 1985, 1989
# All Rights Reserved
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#
#
rabbit:dragon
dragon:snake
snake:horse
horse:sheep
sheep:monkey
monkey:rooster
rooster:dog
dog:boar
boar:rat
rat:ox
ox:tiger
tiger:rabbit
