# @(#)63	1.2  src/bos/usr/games/lib/quiz/collectives.S, cmdgames, bos411, 9428A410j 8/6/91 12:17:03
#
# COMPONENT_NAME: (CMDGAMES) unix games
#
# FUNCTIONS: quiz data file, collectives
#
# ORIGINS: 26, 27
#
# This module contains IBM CONFIDENTIAL code. -- (IBM
# Confidential Restricted when combined with the aggregated
# modules for this product)
#                  SOURCE MATERIALS
# (C) COPYRIGHT International Business Machines Corp. 1985, 1989
# All Rights Reserved
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#
#
actors|soldiers:company
angels:host
ants:colony|hill
apes:shrewdness
asses:pace|bunch
badgers:cete
bass:shoal
bears:sloth
bees:swarm
bees|locusts:swarm
birds:dissimulation
brats:passel
buffaloes:herd
candidates:slate
caterpillars:army
cats:clowder
cattle:drove|herd
chickens:peep|flock
crows:murder
curs:cowardice
dogs:pack
doves:dule
ducks:[pad|ba]dling
earthquakes:swarm
eggs:clutch
elephants:herd
elk:gang
engineers:corps
ferrets:business
finches:charm
firemen:brigade
fish:school
foxes:skulk
gangsters:mob
geese in flight:skein
geese on water:gaggle
goats:trip
grapes|banannas:bunch
hawks:cast
hens:brood
herons:siege
horses:haras|team
hounds:kennel
jellyfish:smack
kangaroos|monkeys:troop
kittens:kindle
lapwings:deceit
larks:exaltation|bevy
leopards:leap
lions:pride
locusts:plague
magpies:tidings
maidens|quail:bevy
martens:richness
men:band
moles:labor
monkeys|kangaroos:troop
mountains:range
mules:barren|baren
nightingales:watch
operating companies:at&t|bell system
owls:parliament
oxen:drove
partridges:covey
partridges|grouse:covey
peacocks:ostentation
people:crowd
pheasants:bouquet
plovers:congregation
ponies:string
porpoises:shoal
prisoners:gang
pups:litter
quail|maidens:bevy
rabbits:nest
ravens:unkindness
rhinoceroses:crash
robbers:band
roebucks:bevy
rooks:building
rubbish:heap
seals:pod
sheep:flock
ships:fleet
snipe:walk|wisp
sparrows:host
squirrels:dray
starlings:murmuration
stars:constellation
storks:mustering
swallows:flight
teal:spring
toads:knot
turkeys:rafter
turtledoves:pitying
whales:gam|pod
whales|fish:school
witches:coven
wolves:pack
wolves:route
woodcocks:fall
woodpeckers:descent
worshippers:congregation
{H|h}uns:horde
{wild }swine:sounder
