# @(#)66	1.2  src/bos/usr/games/lib/quiz/europe.S, cmdgames, bos411, 9428A410j 8/6/91 12:17:23
#
# COMPONENT_NAME: (CMDGAMES) unix games
#
# FUNCTIONS: quiz data file, europe
#
# ORIGINS: 26, 27
#
# This module contains IBM CONFIDENTIAL code. -- (IBM
# Confidential Restricted when combined with the aggregated
# modules for this product)
#                  SOURCE MATERIALS
# (C) COPYRIGHT International Business Machines Corp. 1985, 1989
# All Rights Reserved
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#
#
Albania:Tirana|Tirane"
Andorra:Andorra la V[ell|iej]a
Austria:Vienna|Wien
Belgium:Brussel[s|]|Bruxelles
Bulgaria:Sofi[a|ya]
Czechoslovakia:Prague|Praha
Denmark:Copenhagen|K[o|o/]benhavn
East Germany:Berlin
United Kingdom|England|Great Britain|UK:London
Finland:Helsinki
France:Paris
Greece:Athens
Hungary:Budapest
Iceland:Reykjavik
Ireland|Eire:Dublin
Italy:Rom[e|a]
Liechtenstein:Vaduz
Luxembourg:Luxembourg
Malta:Valletta
Monaco:Monte Carlo
Netherlands|Holland:The Hague|'sGravenhage|den Haag|Amsterdam
Norway:Oslo
Poland:Wars[aw|zawa]
Portugal:Lisbo[n|a]
R[u|o]mania:Bucharest|Bucuresti
San Marino:San Marino
Spain:Madrid
Sweden:Stockholm
Switzerland:Bern{e}
Turkey:Ankara
USSR|Russia:Mos[cow|kva]
[West |]Germany:Bonn
Yugoslavia:Belgrade|Beograd
