# @(#)67	1.2  src/bos/usr/games/lib/quiz/greeklang.S, cmdgames, bos411, 9428A410j 8/6/91 12:17:28
#
# COMPONENT_NAME: (CMDGAMES) unix games
#
# FUNCTIONS: quiz data file, greeklang
#
# ORIGINS: 26, 27
#
# This module contains IBM CONFIDENTIAL code. -- (IBM
# Confidential Restricted when combined with the aggregated
# modules for this product)
#                  SOURCE MATERIALS
# (C) COPYRIGHT International Business Machines Corp. 1985, 1989
# All Rights Reserved
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#
#
$luw$:{I} [loose|destroy]
$eluon$:{I} [loosed|destroyed|was loosing|was destroying]
$elusa$:{I} [loosed|destroyed]
$leluka$:{I} have [loosed|destroyed]
$lusw$:{I} will [loose|destroy]
$luswn$:[loosing|destroying]
$lusas$:{having} [loosed|destroyed]
