# @(#)68	1.2  src/bos/usr/games/lib/quiz/inca.S, cmdgames, bos411, 9428A410j 8/6/91 12:17:33
#
# COMPONENT_NAME: (CMDGAMES) unix games
#
# FUNCTIONS: quiz data file, inca
#
# ORIGINS: 26, 27
#
# This module contains IBM CONFIDENTIAL code. -- (IBM
# Confidential Restricted when combined with the aggregated
# modules for this product)
#                  SOURCE MATERIALS
# (C) COPYRIGHT International Business Machines Corp. 1985, 1989
# All Rights Reserved
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#
#
manco capac:sinchi roca
sinchi roca:lloque yupanqui
lloque yupanqui:mayta capac
mayta capac:capac yupanqui
capac yupanqui:inca roca
inca roca:yahuar huacac
yahuar huacac:viracocha
viracocha:pachacuti
pachacuti:tupa inca yupanqui
tupa inca yupanqui:huayna capac
huayna capac:huascar
huascar:atahuallpa
