# @(#)71	1.2  src/bos/usr/games/lib/quiz/locomotive.S, cmdgames, bos411, 9428A410j 8/6/91 12:17:49
#
# COMPONENT_NAME: (CMDGAMES) unix games
#
# FUNCTIONS: quiz data file, locomotive
#
# ORIGINS: 26, 27
#
# This module contains IBM CONFIDENTIAL code. -- (IBM
# Confidential Restricted when combined with the aggregated
# modules for this product)
#                  SOURCE MATERIALS
# (C) COPYRIGHT International Business Machines Corp. 1985, 1989
# All Rights Reserved
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#
#
4-4-0:American
4-6-0:Mogul
4-4-2:Atlantic
4-6-2:Pacific
2-8-0:Consolidation
2-8-2:Mikado
4-8-2:Mountain
2-8-4:Berkshire
4-6-4:Hudson
4-8-4:Northern
2-10-2:Decapod
