# @(#)29        1.2  src/bos/usr/games/lib/quiz/Makefile, cmdgames, bos411, 9428A410j 1/14/93 15:11:58
#
# COMPONENT_NAME: CMDGAMES
#
# FUNCTIONS:
#
# ORIGINS: 27
#
# IBM CONFIDENTIAL -- (IBM Confidential Restricted when
# combined with the aggregated modules for this product)
#                  SOURCE MATERIALS
# (C) COPYRIGHT International Business Machines Corp. 1988, 1993
# All Rights Reserved
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#

SCRIPTS		= africa america areas arith asia babies bard chinese \
		  collectives editor elements europe greeklang inca \
		  index latin locomotive midearth morse mult murders \
		  poetry posneg pres province seq-easy seq-hard sexes \
		  sov state trek ucc

ILIST		= ${SCRIPTS}
IDIR		= /usr/games/lib/quiz/

.include <${RULES_MK}>
