# @(#)73	1.2  src/bos/usr/games/lib/quiz/midearth.S, cmdgames, bos411, 9428A410j 8/6/91 12:17:58
#
# COMPONENT_NAME: (CMDGAMES) unix games
#
# FUNCTIONS: quiz data file, midearth
#
# ORIGINS: 26, 27
#
# This module contains IBM CONFIDENTIAL code. -- (IBM
# Confidential Restricted when combined with the aggregated
# modules for this product)
#                  SOURCE MATERIALS
# (C) COPYRIGHT International Business Machines Corp. 1985, 1989
# All Rights Reserved
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#
#
Shire:Michel Delving|Hobbiton
Mordor:Minas Morgul
Gondor:Minas Tirith
Umbar:{City of the }Corsairs
Rhovanion:Esgaroth{ upon the Long Lake}
Rohan:Edoras
Lothl['o|o|o']rien:Caras Galadon
Breeland:Bree
Arnor:Ann['u|u'|u]minas
Arthedain:Fornost{ Erain}|Norbury of the Kings
