# @(#)76	1.2  src/bos/usr/games/lib/quiz/murders.S, cmdgames, bos411, 9428A410j 8/6/91 12:18:15
#
# COMPONENT_NAME: (CMDGAMES) unix games
#
# FUNCTIONS: quiz data file, murders
#
# ORIGINS: 26, 27
#
# This module contains IBM CONFIDENTIAL code. -- (IBM
# Confidential Restricted when combined with the aggregated
# modules for this product)
#                  SOURCE MATERIALS
# (C) COPYRIGHT International Business Machines Corp. 1985, 1989
# All Rights Reserved
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#
#
Cock Robin:{the }sparrow
sleep|Duncan:Macbeth
{the }cat:curiosity|care
{John {F{.} }}Kennedy|JFK:{Lee Harvey }Oswald|{the }FBI|{the }CIA
{Lee Harvey }Oswald:{Jack }Ruby|{the }FBI|{the }CIA
{Martin Luther }King:{James {Earl }}Ray|{the }FBI|{the }CIA
[Bobby |Robert {F{.} }]Kennedy|RFK:{Sirhan }Sirhan|{the }FBI|{the }CIA
Christ:{the }Romans|{Pontius }Pilate|{the }CIA
{Sharon }Tate:{Charles }Manson
Charles Lindbergh Jr{.}:{Bruno }Hauptman{n}
{Mr{.} }{{and }Mrs{.} }Borden|{her }parents:Lizzie{ Borden}
{Prof{essor} }{James }Moriarty:{Sherlock }Holmes
Achilles:Paris
Abel:Cain
{the }nurses:{Richard }Speck
{J{.} |Julius }Caesar:Brutus{ et al.}
Pompeii:Vesuvius
{Abraham |Abe }Lincoln:{John {Wilkes }}Booth
{Yukio }Mishima:{Yukio }Mishima
{Alexander }Hamilton:{Aaron }Burr
Cleopatra:{the |an }asp
[Ann Boleyn|Catharine Howard]:Henry{ VIII}
vaudeville:{the }movies|film
{the }movies|film:TV|television
{the }VA patients:{the }nurses
