# @(#)80	1.2  src/bos/usr/games/lib/quiz/province.S, cmdgames, bos411, 9428A410j 8/6/91 12:18:36
#
# COMPONENT_NAME: (CMDGAMES) unix games
# 
# FUNCTIONS: quiz data file, province
#
# ORIGINS: 26, 27
#
# This module contains IBM CONFIDENTIAL code. -- (IBM
# Confidential Restricted when combined with the aggregated
# modules for this product)
#                  SOURCE MATERIALS
# (C) COPYRIGHT International Business Machines Corp. 1985, 1989
# All Rights Reserved
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#
#
Newfoundland{ and Labrador}:[St.|Saint] John's
New Brunswick:Fredericton
Prince Edward Island:Charlottetown
Nova Scotia:Halifax
Quebec:Quebec
Ontario:Toronto
Manitoba:Winnipeg
Saskatchewan:Regina
Alberta:Edmonton
British Columbia:Victoria
Yukon Territory:Whitehorse
Northwest Territories:Yellowknife
Canada:Ottawa
