# @(#)81	1.2  src/bos/usr/games/lib/quiz/seq-easy.S, cmdgames, bos411, 9428A410j 8/6/91 12:18:42
#
# COMPONENT_NAME: (CMDGAMES) unix games
#
# FUNCTIONS: quiz data file, seq-easy
#
# ORIGINS: 26, 27
#
# This module contains IBM CONFIDENTIAL code. -- (IBM
# Confidential Restricted when combined with the aggregated
# modules for this product)
#                  SOURCE MATERIALS
# (C) COPYRIGHT International Business Machines Corp. 1985, 1989
# All Rights Reserved
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#
#
1,2,3,4,5,6:7{(integers)}:integers|[natural|counting] numbers
1,2,3,5,8,13:21{(Fibonacci)}:Fibonacci{ seq{ence}| numbers}
1,2,4,8,16,32:64{(powers of 2)}:powers of 2|2[**|^]n
1,2,6,24,120,720:5040{(factorials)}:factorials|n!
1,3,5,7,9,11:13{(odd nos.)}:odd [integ|numb]ers
1,3,6,10,15,21:28{(triangular)}:triangular{ numbers}|C(n,2)
1,3,9,27,81:243{(powers of 3)}:powers of 3|3[**|^]n
1,4,9,16,25:36{(squares)}:squares|n[**|^]2
1,4,16,64:256{(powers of 4)}:powers of 4|4[**|^]n
1,5,25,125:625{(powers of 5)}:powers of 5|5[**|^]n
1,8,27,64,125:216{(cubes)}:cubes|n[**|^]3
2,3,5,7,11,13:17{(primes)}:prime[ number]s
2,4,6,8,10,12:14{(even nos.)}:even [integ|numb]ers|multiples of 2|2n
3,6,9,12,15:18{(3n)}:multiples of 3|3n
