# @(#)84	1.2  src/bos/usr/games/lib/quiz/sexes.S, cmdgames, bos411, 9428A410j 8/6/91 12:18:54
#
# COMPONENT_NAME: (CMDGAMES) unix games
#
# FUNCTIONS: quiz data file, sexes
#
# ORIGINS: 26, 27
#
# This module contains IBM CONFIDENTIAL code. -- (IBM
# Confidential Restricted when combined with the aggregated
# modules for this product)
#                  SOURCE MATERIALS
# (C) COPYRIGHT International Business Machines Corp. 1985, 1989
# All Rights Reserved
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#
#
Y|y:X|x
abbot:abbess
alumnus:alumna
ambassador:ambassadress
boar:sow
buck:doe
bull:cow
cob:pen
colt:filly
curator:curatrix
dog:bitch|vixen
duke:duchess
drake:duck
effeminate|womanish:mannish
gander:goose
gentleman:lady|gentlewoman
jack:jenny
lad:lass
manly:womanly
marquis:marchioness[|e]|marquise
monk:nun
[O|o]edipus complex:[E|e]lectra[| complex]
prince:princess
ram:ewe
rooster|cock:hen
stallion:mare
