# @(#)87	1.2  src/bos/usr/games/lib/quiz/trek.S, cmdgames, bos411, 9428A410j 8/6/91 12:19:15
#
# COMPONENT_NAME: (CMDGAMES) unix games
#
# FUNCTIONS: quiz data file, trek
#
# ORIGINS: 26, 27
#
# This module contains IBM CONFIDENTIAL code. -- (IBM
# Confidential Restricted when combined with the aggregated
# modules for this product)
#                  SOURCE MATERIALS
# (C) COPYRIGHT International Business Machines Corp. 1985, 1989
# All Rights Reserved
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#
#
captain's name:{James |Jim }{T. }Kirk|{james |jim}{t. }kirk
first officers name:Spock|spock|Mr. Spock|mr. spock
name of ship:{the }{u.s.s. }enterprise|Enterprise
name of the "good guys":{the }Federation|federation|{the }federation
name of the "bad guys":{the }klingons|{the }romulans
nickname of chief engineer:scotty|Scotty
nickname of chief medical officer:bones|Bones
machine use for transportation to surface of nearby planet:transporter|shuttlecraft
main engines of ship:warp engines|warp
number of crew:400|four hundred
hand-held weapon:phaser
type of torpedoes used on the ship:photon torpedoes|photon
name of electronic protective device on ship:shields|shield
name of device that makes a ship invisible:cloaking device|cloak|cloaking
type of voice that the on-board computer has:female|feminine|woman's
where first officer comes from:vulcan|Vulcan
rare, but very powerful enemies:romulans|Romulans
reaction that main engines operate on:matter-antimatter{ reaction}|matter/antimatter{ reaction}
slow engines used in emergencies:impulse engines|impulse
