# @(#)55	1.2  src/bos/usr/lib/ncs/Makefile, libncs, bos410 1/18/94 13:30:45
# COMPONENT_NAME:  libncs
#
# FUNCTIONS:
#
# ORIGINS: 27
#
# IBM CONFIDENTIAL -- (IBM Confidential Restricted when
# combined with the aggregated modules for this product)
#                  SOURCE MATERIALS
# (C) COPYRIGHT International Business Machines Corp. 1988, 1992
# All Rights Reserved
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#

SUBDIRS		= bin cat conf lb_test lib perf

# Exported files.
EXPDIR		= /usr/lib/ncs/
EXPINC_SUBDIRS	= idl
EXPLIB_SUBDIRS	= lib

IDIR		= /usr/lib/ncs/
ILIST		= cpyright VERSION

.include <${RULES_MK}>

