# @(#)84	1.2  src/bos/diag/tu/tok/Makefile, tu_tok, bos411, 9428A410j 1/7/94 13:47:18
#
#   COMPONENT_NAME: TU_TOK
#
#   FUNCTIONS: 
#
#   ORIGINS: 27
#
#   IBM CONFIDENTIAL -- (IBM Confidential Restricted when
#   combined with the aggregated modules for this product)
#                    SOURCE MATERIALS
#
#   (C) COPYRIGHT International Business Machines Corp. 1992, 1994
#   All Rights Reserved
#   US Government Users Restricted Rights - Use, duplication or
#   disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#


#-------------------------------------------------------------------------#
#                                                                         #
#     This Makefile builds the library libtoktu.a for the DA application #
#                                                                         #
#-------------------------------------------------------------------------#

LIBRARIES       =   libtoktu.a

EXPLIB_TARGETS  =   export_libtoktu.a
EXPDIR          =   /usr/lib/

OFILES		= 	detrace.o exectu.o fill_buf.o mktu_rc.o qvpd.o \
			tr_stat.o tr_uncode.o rw_pos.o tu001.o tu002.o \
			tu003.o tu007.o tu008.o

.include <${RULES_MK}>
