# @(#)59	1.2  src/bos/usr/lib/nls/loc/imk/ked/Makefile, libkr, bos411, 9428A410j 2/2/94 20:30:12
#
# COMPONENT_NAME:  LIBKR
#
# FUNCTIONS: Korean Input Method
#
# ORIGINS: 27
#
# IBM CONFIDENTIAL -- (IBM Confidential Restricted when
# combined with the aggregated modules for this product)
#                  SOURCE MATERIALS
# (C) COPYRIGHT International Business Machines Corp. 1988, 1993
# All Rights Reserved
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#

LIBRARIES = libked.a

OFILES    = \
	kedClear.o kedClose.o kedCtrl.o kedFix.o kedInit.o \
	kedIntern.o kedMisc.o kedProc.o

INCFLAGS  = -I${MAKETOP}/bos/usr/lib/nls/loc/imk/include -I${MAKETOP}/bos/usr/include

.include <${RULES_MK}>
