# @(#)08        1.4  src/bos/Makefile, Makefiles, bos411, 9428A410j 4/5/94 18:36:26
# COMPONENT_NAME:
#
# FUNCTIONS:
#
# ORIGINS: 27
#
# IBM CONFIDENTIAL -- (IBM Confidential Restricted when
# combined with the aggregated modules for this product)
#                  SOURCE MATERIALS
# (C) COPYRIGHT International Business Machines Corp. 1988, 1989, 1992, 1994
# All Rights Reserved
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#

EXPINC_SUBDIRS		= misc sbin usr diag

EXPLIB_SUBDIRS		= misc usr sbin diag

SUBDIRS			= usr sbin etc objclass diag ${${TARGET_MACHINE}_SUBDIRS}

.include <${RULES_MK}>
