# @(#)22	1.2  src/bos/usr/lpp/Unicode/Makefile, cfgnls, bos411, 9428A410j 4/19/94 10:31:25
#
#   COMPONENT_NAME: CFGNLS
#
#   FUNCTIONS: none
#
#   ORIGINS: 27
#
#   IBM CONFIDENTIAL -- (IBM Confidential Restricted when
#   combined with the aggregated modules for this product)
#                    SOURCE MATERIALS
#
#   (C) COPYRIGHT International Business Machines Corp. 1994
#   All Rights Reserved
#   US Government Users Restricted Rights - Use, duplication or
#   disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#
EXPLIB_SUBDIRS  = methods
SUBDIRS         = methods wim loc charmap X11 tty \
		  lpd samples

SCRIPTS		= uni_install uni_deinstall
ILIST		= README ${SCRIPTS}

IDIR		= /usr/lpp/Unicode/

.include <${RULES_MK}>
