# @(#)75	1.3  src/bos/usr/include/netinet/Makefile, Makefiles, bos411, 9428A410j 9/29/93 09:47:04
# COMPONENT_NAME:
#
# FUNCTIONS:
#
# ORIGINS: 10,27
#
# IBM CONFIDENTIAL -- (IBM Confidential Restricted when
# combined with the aggregated modules for this product)
#                  SOURCE MATERIALS
# (C) COPYRIGHT International Business Machines Corp. 1988, 1989
# All Rights Reserved
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#

VPATH		=${MAKETOP}/bos/kernext/inet

IDIR		= /usr/include/netinet/

DATAFILES	= \
	icmp_var.h \
	if_802_3.h \
	if_802_5.h \
	if_ether.h \
	if_fddi.h \
	if_op.h \
	if_mcast_aux.h \
	igmp.h \
	igmp_var.h \
	in.h \
	in_netarp.h \
	in_pcb.h \
	in_systm.h \
	in_var.h \
	inet_config.h \
	ip.h \
	ip_icmp.h \
	ip_security.h \
	ip_var.h \
	proto_inet.h \
	tcp.h \
	tcp_debug.h \
	tcp_fsm.h \
	tcp_seq.h \
	tcp_timer.h \
	tcp_var.h \
	tcpip.h \
	udp.h \
	udp_var.h

INCLUDES	= ${DATAFILES}

ILIST		= ${DATAFILES}

.include <${RULES_MK}>
