static char sccsid[] = "@(#)63	1.6  src/bos/usr/ccs/lib/libc/atoff.c, libccnv, bos411, 9428A410j 6/16/90 01:04:33";
/*
 * COMPONENT_NAME: LIBCCNV atoff
 *
 * FUNCTIONS: atoff
 *
 * ORIGINS: 27
 *
 * IBM CONFIDENTIAL -- (IBM Confidential Restricted when
 * combined with the aggregated modules for this product)
 *                  SOURCE MATERIALS
 * (C) COPYRIGHT International Business Machines Corp. 1988, 1989
 * All Rights Reserved
 *
 * US Government Users Restricted Rights - Use, duplication or
 * disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
 */

/*
 * NAME: atoff
 *                                                                    
 * FUNCTION: convert ascii string to float
 *                                                                    
 * NOTES:
 *
 *  Atoff is generated by defining  ATOFF and then including
 *  atof.c. Depending on what is defined, atof.c can generate code
 *  for atof, atoff, strtod, or strtof.
 *
 *  See atof.c for details
 *
 * RETURNS: a float value
 *
 */

#define ATOFF 1
#include "atof.c"
