$  @(#)39	1.2  src/bos/usr/ccs/lib/libc/fshelp.msg, libcadm, bos411, 9428A410j 6/16/90 01:02:16
$
$ COMPONENT_NAME: (LIBCADM) Standard C Library System Admin Functions 
$
$ FUNCTIONS: 
$
$ ORIGINS: 27 
$
$ IBM CONFIDENTIAL -- (IBM Confidential Restricted when
$ combined with the aggregated modules for this product)
$                  SOURCE MATERIALS
$ (C) COPYRIGHT International Business Machines Corp. 1989 
$ All Rights Reserved
$
$ US Government Users Restricted Rights - Use, duplication or
$ disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
$ 

$ messages for fshelp

$set MS_FSHELP_ERR
$quote "

Msg_INVAL	"0506-501 Invalid argument"
Msg_INVALFS	"0506-502 Invalid filesystem"
Msg_INVALFILNO	"0506-503 Invalid file number"
Msg_INVALDBLK	"0506-504 Invalid data block"
Msg_INVALMODE	"0506-505 Invalid mode"
Msg_INVALARG	"0506-506 Invalid argument"
Msg_AXSHELPER	"0506-507 Access denied or could not execute"
Msg_ARGMISSING	"0506-508 Argument is missing"
Msg_NOP		"0506-509 That is a no-op."
Msg_SYNTAX	"0506-510 Syntax error"
Msg_UNKVFS	"0506-511 Unknown vfs type"
Msg_UNKOP	"0506-512 Unknown filesystem helper operation"
Msg_VFSMANGLED	"0506-513 VFS file is mangled"
Msg_VFSAXS	"0506-514 VFS file access denied"
Msg_NOTSUP	"0506-515 Filesystem helper does not support this operation"
Msg_WOULDBLOCK	"0506-516 This would block"
Msg_ACTIVE	"0506-517 Inappropriate action on an active filesystem"
Msg_CANTLOCK	"0506-518 Can not lock the device"
Msg_DEVOPEN	"0506-519 Device open failed"
Msg_DEVFAIL	"0506-520 Device operation failed"
Msg_DEVFAILRD	"0506-521 Device read failed"
Msg_DEVFAILWR	"0506-522 Device write failed"
Msg_CORRUPT	"0506-523 Filesystem is corrupt"
Msg_NOMEM	"0506-524 Out of memory"
Msg_INTERNAL	"0506-525 Internal error"
Msg_IMPERR	"0506-526 Implementation-specific error, code = "
Msg_UNKERR	"0506-527 Unknown error, code = "
