# @(#)41        1.1  src/bos/usr/lib/boot/bootutil/Makefile, bosboot, bos411, 9428A410j 3/10/94 11:51:01
# COMPONENT_NAME: bosboot
#
# FUNCTIONS:
#
# ORIGINS: 27
#
# IBM CONFIDENTIAL -- (IBM Confidential Restricted when
# combined with the aggregated modules for this product)
#                  SOURCE MATERIALS
# (C) COPYRIGHT International Business Machines Corp. 1994
# All Rights Reserved
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#

PROGRAMS	= bootutil
MSGHDRS		=
CATFILES	=

ILIST		= bootutil
IDIR		= /usr/lib/boot/

.include <${RULES_MK}>
