# @(#) 78 1.1 src/bos/usr/lpp/bosinst/tape/Makefile, bosinst, bos411, 9428A410j 7/1/93 08:43:14
# COMPONENT_NAME: bosinst
#
# FUNCTIONS: Makefile for tapefiles1
#
# ORIGINS: 27
#
# IBM CONFIDENTIAL -- (IBM Confidential Restricted when
# combined with the aggregated modules for this product)
#                  SOURCE MATERIALS
# (C) COPYRIGHT International Business Machines Corp. 1993
# All Rights Reserved
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#


SCRIPTS		= tapefiles1

ILIST		= tapefiles1
IDIR		= /usr/lpp/bosinst/tape/

.include <${RULES_MK}>
