# @(#)67        1.1  src/bos/usr/include/POWER/diag/Makefile, cmddiag, bos411, 9428A410j 8/5/92 16:17:16
# COMPONENT_NAME:
#
# FUNCTIONS:
#
# ORIGINS: 10,27
#
# IBM CONFIDENTIAL -- (IBM Confidential Restricted when
# combined with the aggregated modules for this product)
#                  SOURCE MATERIALS
# (C) COPYRIGHT International Business Machines Corp. 1988, 1989
# All Rights Reserved
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#

VPATH		= ${MAKETOP}/bos/objclass/${TARGET_MACHINE}

IDIR		= /usr/include/diag/

DATAFILES	= \
	atu.h	\
	bit_def.h	\
	da.h		\
	diag.h		\
	diag_exit.h	\
	diago.h		\
	diagodm.h	\
	tm_input.h	\
	tmdefs.h	

INCLUDES	= ${DATAFILES}

ILIST		= ${DATAFILES}

.include <${RULES_MK}>
