# @(#)00        1.1  src/bos/usr/games/lib/Makefile, cmdgames, bos411, 9428A410j 1/14/93 15:09:00
#
# COMPONENT_NAME: CMDGAMES
#
# FUNCTIONS:
#
# ORIGINS: 27
#
# IBM CONFIDENTIAL -- (IBM Confidential Restricted when
# combined with the aggregated modules for this product)
#                  SOURCE MATERIALS
# (C) COPYRIGHT International Business Machines Corp. 1988, 1993
# All Rights Reserved
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#

SUBDIRS		= fortune quiz

.include <${RULES_MK}>
