# @(#)86       1.1  src/bos/kernext/dlc/smit/Makefile, dlccfg, bos411, 9428A410j 3/31/94 17:37:55 
# COMPONENT_NAME: (DLCCFG) Data Link Control Configuration
#
# FUNCTIONS:  This makefile ships an awk script for the dlc sm_name_hdr entry 
#             in smit.
#
# ORIGINS: 27
#
# IBM CONFIDENTIAL -- (IBM Confidential Restricted when
# combined with the aggregated modules for this product)
#                  SOURCE MATERIALS
# (C) COPYRIGHT International Business Machines Corp. 1994
# All Rights Reserved
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.

VPATH = ${TARGET_MACHINE}

SCRIPTS = sm_name_hdr.awk

ILIST = ${SCRIPTS}

IDIR = /usr/lpp/bos.dlc/com/

.include <${RULES_MK}>
