# @(#)71        1.1  src/bos/usr/ccs/Makefile, Makefiles, bos411, 9428A410j 8/5/92 16:29:56
# COMPONENT_NAME:
#
# FUNCTIONS:
#
# ORIGINS: 27
#
# IBM CONFIDENTIAL -- (IBM Confidential Restricted when
# combined with the aggregated modules for this product)
#                  SOURCE MATERIALS
# (C) COPYRIGHT International Business Machines Corp. 1988, 1989
# All Rights Reserved
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#

EXPINC_SUBDIRS		= lib

EXPLIB_SUBDIRS		= lib

SUBDIRS			= bin lib

.include <${RULES_MK}>
