# @(#)89	1.1  src/bos/usr/lib/netls/adk/cat1/Makefile, libnetls, bos411, 9428A410j 5/26/94 18:14:49
# COMPONENT_NAME:  libnetls
#
# FUNCTIONS:
#
# ORIGINS: 27
#
# IBM CONFIDENTIAL -- (IBM Confidential Restricted when
# combined with the aggregated modules for this product)
#                  SOURCE MATERIALS
# (C) COPYRIGHT International Business Machines Corp. 1988, 1992
# All Rights Reserved
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#

ILIST		= ls_dpass.1.z

IDIR		= /usr/lib/netls/adk/cat1/

.include <${RULES_MK}>

