# @(#)55        1.1  src/bos/usr/lpp/bosinst/turbocr/Makefile, bosinst, bos41J, 9514A_all 4/5/95 09:13:14
# COMPONENT_NAME: bosinst
#
# FUNCTIONS:  Makefile for turbocr
#
# ORIGINS: 27
#
# IBM CONFIDENTIAL -- (IBM Confidential Restricted when
# combined with the aggregated modules for this product)
#                  SOURCE MATERIALS
# (C) COPYRIGHT International Business Machines Corp. 1995
# All Rights Reserved
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#

PROGRAMS	= turbocr

#ILIST		= turbocr
#IDIR		= /usr/lpp/bosinst/

.include <${RULES_MK}>
