static char sccsid[] = "@(#)42	1.1  src/bos/usr/lib/microcode/cxia/Makefile, sysxs128, bos41J, 9512A_all 3/22/95 08:40:33";
# COMPONENT_NAME: MAKEFILES
#
# FUNCTIONS:
#
# ORIGINS: 80
#
# IBM CONFIDENTIAL -- (IBM Confidential Restricted when
# combined with the aggregated modules for this product)
#                  SOURCE MATERIALS
# (C) COPYRIGHT International Business Machines Corp. 1988, 1989
# All Rights Reserved
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#


ILIST		= sxbios.02.01 sxfep.02.01

IDIR		= /usr/lib/microcode/

.include <${RULES_MK}>

