# @(#)21	1.1  src/bos/usr/lib/methods/defmpqd/Makefile, cfgmethods, bos411, 9428A410j 9/8/93 14:01:31
# COMPONENT_NAME:
#
# FUNCTIONS:
#
# ORIGINS: 27
#
# IBM CONFIDENTIAL -- (IBM Confidential Restricted when
# combined with the aggregated modules for this product)
#                  SOURCE MATERIALS
# (C) COPYRIGHT International Business Machines Corp. 1988, 1989
# All Rights Reserved
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#

VPATH		= ../common

PROGRAMS	= defmpqd

OFILES		= location.o ddstools.o defmpqd.o

INCFLAGS	= -I../common

ILIST		= defmpqd
IDIR		= /usr/lib/methods/


LIBS		= -ls -lodm -lcfg -lrts

.include <${RULES_MK}>
