# @(#)49        1.4  src/bos/kernel/pfs/Makefile, syspfs, bos411, 9428A410j 7/7/94 16:52:34
# COMPONENT_NAME:
#
# FUNCTIONS:
#
# ORIGINS: 27
#
# IBM CONFIDENTIAL -- (IBM Confidential Restricted when
# combined with the aggregated modules for this product)
#                  SOURCE MATERIALS
# (C) COPYRIGHT International Business Machines Corp. 1988, 1994
# All Rights Reserved
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#

.include <${MAKETOP}bos/kernel/Kernel.mk>

PAGED_OFILES_PRIM =	\
	disubs.o \
	isubs.o \
	comsubs.o \
	xix_vget.o

PAGED_OFILES	=	\
	dqsubs.o \
	jfslog.o \
	logsubs.o \
	xix_access.o \
	xix_close.o \
	xix_cntl.o \
	xix_create.o \
	xix_dc.o \
	xix_dir.o \
	xix_fclear.o \
	xix_fid.o \
	xix_fsync.o \
	xix_ftrunc.o \
	xix_gattr.o \
	xix_hold.o \
	xix_link.o \
	xix_lookup.o \
	xix_mkdir.o \
	xix_mknod.o \
	xix_mount.o \
	xix_open.o \
	xix_pcl.o \
	xix_quotactl.o \
	xix_rddir.o \
	xix_rdlnk.o \
	xix_rdwr.o \
	xix_rele.o \
	xix_remove.o \
	xix_rename.o \
	xix_rmdir.o \
	xix_root.o \
	xix_sattr.o \
	xix_strat.o \
	xix_symlnk.o \
	xix_sync.o \
	xix_umount.o \
	xix_lckctl.o \
	xix_statfs.o \
	xix_map.o \
	xix_unmap.o

PAGED_OFILES_BACK =	\
	delsubs.o \
	genalloc.o \
	secsubs.o \
	xix_acl.o \
	xix_init.o \
	xix_rtinit.o \
	xix_subs.o

.include <${RULES_MK}>
