# @(#)94	1.3  src/bos/usr/lib/piostw/Makefile, cmdpiostw, bos411, 9428A410j 3/1/94 09:04:24
#
#   COMPONENT_NAME: CMDPIOSTW
#
#   FUNCTIONS: 
#
#   ORIGINS: 27
#
#   IBM CONFIDENTIAL -- (IBM Confidential Restricted when
#   combined with the aggregated modules for this product)
#                    SOURCE MATERIALS
#
#   (C) COPYRIGHT International Business Machines Corp. 1993,1994
#   All Rights Reserved
#   US Government Users Restricted Rights - Use, duplication or
#   disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#

SUBDIRS = fmtrsTW predef

.include <${RULES_MK}>
