#!/unix
* @(#)96
*
*
* COMPONENT_NAME: (tu_wildw) Wildwood LAN adapter test units
*
* FUNCTIONS: Interrupt Handler Export Symbols
*
* ORIGINS: 27
*
* (C) COPYRIGHT International Business Machines Corp. 1993
* All Rights Reserved
* Licensed Materials - Property of IBM
*
* US Government Users Restricted Rights - Use, duplication or
* disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
*
mps_interrupt
