# @(#)51	1.1  src/bos/usr/lib/methods/startsgio/Makefile, inputdd, bos41J, 9510A_all 2/28/95 15:56:54
#   COMPONENT_NAME: RCM
#
#   FUNCTIONS:
#
#   ORIGINS: 27
#
# IBM CONFIDENTIAL -- (IBM Confidential Restricted when
# combined with the aggregated modules for this product)
#                  SOURCE MATERIALS
# (C) COPYRIGHT International Business Machines Corp. 1988, 1993
# All Rights Reserved
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#

PROGRAMS	= startsgio

INCFLAGS	= -I${MAKETOP}/bos/usr/lib/methods/common

ILIST		= startsgio
IDIR		= /usr/lib/methods/

LIBS		= -ls -lodm -lcfg -lrts

.include <${RULES_MK}>
