# @(#)76	1.1  src/bos/usr/lpp/cnls/dict/Makefile, ils-zh_CN, bos41B, 9504A 12/20/94 10:32:24
#
#   COMPONENT_NAME: ils-zh_CN
#
#   FUNCTIONS: none
#
#   ORIGINS: 27
#
#   IBM CONFIDENTIAL -- (IBM Confidential Restricted when
#   combined with the aggregated modules for this product)
#                    SOURCE MATERIALS
#
#   (C) COPYRIGHT International Business Machines Corp. 1994
#   All Rights Reserved
#   US Government Users Restricted Rights - Use, duplication or
#   disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#
ILIST   = abcsysdict.cwd abcsysdict.ovl ensysdict lesysdict pysysdict \
	  fsphsysdict fssjmsysdict fsssysdict fssysdict
IDIR    = /usr/lpp/cnls/dict/

.include <${RULES_MK}>
