# @(#)06 1.7 src/bos/kernext/exp/Makefile, sysxexp, bos411, 9428A410j 4/27/94 10:56:28
# 
# COMPONENT_NAME:
#
# FUNCTIONS:
#
# ORIGINS: 27, 83
#
# IBM CONFIDENTIAL -- (IBM Confidential Restricted when
# combined with the aggregated modules for this product)
#                  SOURCE MATERIALS
# (C) COPYRIGHT International Business Machines Corp. 1988, 1994
# All Rights Reserved
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#
# LEVEL 1, 5 Years Bull Confidential Information
#


IDIR		= /usr/lib/
ILIST		= pse.exp aio.exp diagex.exp ttydbg.exp

.include <${RULES_MK}>
