# @(#)91       1.4  src/bldenv/locales/Makefile, ade_build, bos412, GOLDA411a 4/25/94 16:35:06
#
#
#   COMPONENT_NAME: ade_build
#
#   FUNCTIONS: none
#
#   ORIGINS: 27
#
#   IBM CONFIDENTIAL -- (IBM Confidential Restricted when
#   combined with the aggregated modules for this product)
#                    SOURCE MATERIALS
#
#   (C) COPYRIGHT International Business Machines Corp. 1993,1994
#   All Rights Reserved
#   US Government Users Restricted Rights - Use, duplication or
#   disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#
#

SUBDIRS = ${LOCALES_BUILD_DIR}

.include <${RULES_MK}>
