# @(#)05        1.1  src/bos/usr/lbin/mkwhatis/Makefile, cmdmake, bos411, 9428A410j 8/5/92 16:56:10
# COMPONENT_NAME:
#
# FUNCTIONS:
#
# ORIGINS: 27
#
# IBM CONFIDENTIAL -- (IBM Confidential Restricted when
# combined with the aggregated modules for this product)
#                  SOURCE MATERIALS
# (C) COPYRIGHT International Business Machines Corp. 1988, 1989
# All Rights Reserved
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#

SCRIPTS		= mkwhatis
MSGHDRS		=
CATFILES	=
HFILES		= ${MSGHDRS}
OTHERS		= ${SCRIPTS}

ILIST		= mkwhatis
IDIR		= /usr/lbin/


.include <${RULES_MK}>
