# @(#)15        1.3  src/bldenv/sbtools/Makefile, bldprocess, bos412, GOLDA411a 1/20/94 10:51:51
#
#   COMPONENT_NAME: BLDPROCESS
#
#   FUNCTIONS: none
#
#   ORIGINS: 27,71
#
#   This module contains IBM CONFIDENTIAL code. -- (IBM
#   Confidential Restricted when combined with the aggregated
#   modules for this product)
#                    SOURCE MATERIALS
#
#   (C) COPYRIGHT International Business Machines Corp. 1994
#   All Rights Reserved
#   US Government Users Restricted Rights - Use, duplication or
#   disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#
# Copyright (c) 1990, 1991, 1992  
# Open Software Foundation, Inc. 
#  
# Permission is hereby granted to use, copy, modify and freely distribute 
# the software in this file and its documentation for any purpose without 
# fee, provided that the above copyright notice appears in all copies and 
# that both the copyright notice and this permission notice appear in 
# supporting documentation.  Further, provided that the name of Open 
# Software Foundation, Inc. ("OSF") not be used in advertising or 
# publicity pertaining to distribution of the software without prior 
# written permission from OSF.  OSF makes no representations about the 
# suitability of this software for any purpose.  It is provided "as is" 
# without express or implied warranty. 
#
# ODE 2.1.1

EXPLIB_SUBDIRS		= libsb libode

EXPINC_SUBDIRS		= include

SUBDIRS			= build currentsb mklinks mksb resb sbinfo \
			  uptodate workon

.include <${RULES_MK}>
