# @(#)38        1.7.2.1  src/bos/usr/lib/microcode/bb/Makefile, ucodbb, bos41J, 9520A_all 2/7/95 16:32:10
# COMPONENT_NAME:
#
# FUNCTIONS:
#
# ORIGINS: 27
#
# IBM CONFIDENTIAL -- (IBM Confidential Restricted when
# combined with the aggregated modules for this product)
#                  SOURCE MATERIALS
# (C) COPYRIGHT International Business Machines Corp. 1988, 1989, 1994
# All Rights Reserved
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#


ILIST           = 8d77.32.54 \
	          8d77.44.54 \
	          8d77.44.58 \
	          8d77.a0.13 \
	          8d77.a0.14 \
		  8d77.a0.16 \
                  8d77.a0.17

IDIR            = /usr/lib/microcode/

.include <${RULES_MK}>

