# @(#)05        1.2  src/bos/sbin/Makefile, Makefiles, bos411, 9428A410j 3/12/93 18:15:23
# COMPONENT_NAME:
#
# FUNCTIONS:
#
# ORIGINS: 27
#
# IBM CONFIDENTIAL -- (IBM Confidential Restricted when
# combined with the aggregated modules for this product)
#                  SOURCE MATERIALS
# (C) COPYRIGHT International Business Machines Corp. 1988, 1989
# All Rights Reserved
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#

EXPINC_SUBDIRS		= helpers
EXPLIB_SUBDIRS		= helpers

SUBDIRS		= helpers rc.boot

.include <${RULES_MK}>
