# @(#)71	1.1  src/bos/usr/lib/ncs/cat/Makefile, bos, bos410 3/1/93 11:26:44
# COMPONENT_NAME:  libncs
#
# FUNCTIONS:
#
# ORIGINS: 27
#
# IBM CONFIDENTIAL -- (IBM Confidential Restricted when
# combined with the aggregated modules for this product)
#                  SOURCE MATERIALS
# (C) COPYRIGHT International Business Machines Corp. 1988, 1992
# All Rights Reserved
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#

SUBDIRS		= files utils-a

.include <${RULES_MK}>

