# @(#)72	1.1  src/bos/etc/tsh_profile/Makefile, cmdsh, bos411, 9428A410j 1/22/93 15:26:22
# COMPONENT_NAME: cfgetc
#
# FUNCTIONS:
#
# ORIGINS: 27
#
# IBM CONFIDENTIAL -- (IBM Confidential Restricted when
# combined with the aggregated modules for this product)
#                  SOURCE MATERIALS
# (C) COPYRIGHT International Business Machines Corp. 1988, 1993
# All Rights Reserved
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#

ILIST		= tsh_profile
IDIR		= /etc/

.include <${RULES_MK}>
