# @(#)49	1.1  src/bos/diag/tu/mpa/Makefile, mpatu, bos411, 9428A410j 10/14/93 08:02:44
#
#   COMPONENT_NAME: TU_MPA
#
#   FUNCTIONS: 
#
#   ORIGINS: 27
#
#   IBM CONFIDENTIAL -- (IBM Confidential Restricted when
#   combined with the aggregated modules for this product)
#                    SOURCE MATERIALS
#
#   (C) COPYRIGHT International Business Machines Corp. 1993
#   All Rights Reserved
#   US Government Users Restricted Rights - Use, duplication or
#   disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#

OBJECTS		= exectu.o mpa_tus.o

CFLAGS		= -D DIAGS
LIBS		= -lc

.include <${RULES_MK}>
