# @(#)78	1.8  src/bos/etc/security/environ.S, cfgsauth, bos411, 9428A410j 3/26/91 14:07:56
#  COMPONENT_NAME: CFGSAUTH
#
#  ORIGINS: 27
#
#  (C) COPYRIGHT International Business Machines Corp. 1989, 1991
#  All Rights Reserved
#  Licensed Materials - Property of IBM
#
#  US Government Users Restricted Rights - Use, duplication or
#  disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#

default:

root:

daemon:

bin:

sys:

adm:

uucp:

guest:

