# @(#)95	1.8  src/bos/etc/security/passwd.S, cfgsauth, bos411, 9428A410j 3/26/91 14:08:13
#  COMPONENT_NAME: CFGSAUTH
#
#  ORIGINS: 27
#
#  (C) COPYRIGHT International Business Machines Corp. 1989, 1991
#  All Rights Reserved
#  Licensed Materials - Property of IBM
#
#  US Government Users Restricted Rights - Use, duplication or
#  disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#

root:
	password = 

daemon:
	password = *

bin:
	password = *

sys:
	password = *

adm:
	password = *

uucp:
	password = *

guest:
	password = *

nobody:
	password = *

lpd:
	password = *

