# @(#)59        1.2  src/bos/usr/lib/boot/getrootfs/Makefile, bosboot, bos411, 9428A410j 9/28/93 16:27:34
# COMPONENT_NAME:
#
# FUNCTIONS:
#
# ORIGINS: 27
#
# IBM CONFIDENTIAL -- (IBM Confidential Restricted when
# combined with the aggregated modules for this product)
#                  SOURCE MATERIALS
# (C) COPYRIGHT International Business Machines Corp. 1988, 1989
# All Rights Reserved
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#

SCRIPTS		= getrootfs

ILIST		= getrootfs
IDIR		= /usr/lib/boot/

.include <${RULES_MK}>
