# @(#)09        1.5  src/bos/usr/lib/pios/trans2/Makefile, cmdpios, bos411, 9428A410j 12/4/93 14:53:54
#
# COMPONENT_NAME:
#
# FUNCTIONS:
#
# ORIGINS: 27
#
# IBM CONFIDENTIAL -- (IBM Confidential Restricted when
# combined with the aggregated modules for this product)
#                  SOURCE MATERIALS
# (C) COPYRIGHT International Business Machines Corp. 1988, 1993
# All Rights Reserved
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#

DATAFILES	= \
	420x.437 dp2000 d630 hplj.dn hplj.ecma hplj.ibmus \
	hplj.roman8 4216.roman8 ibm.437 ibm.850 ibm.851 ibm.852 \
	ibm.853 ibm.855 ibm.857 ibm.860 ibm.862 ibm.863 ibm.864 \
	ibm.865 ibm.869 ibm.1046 3812.p0 3812.p1 3812.p2 3816.p1 \
	3816.p2 p9012 ascii 420x.850

ILIST	= ${DATAFILES}
IDIR	= /usr/lib/lpd/pio/trans2/

.include <${RULES_MK}>

420x.850: ${R420X_850}
	${R420X_850} .

420x.437: ${R420X_437}
	${R420X_437} .

dp2000: ${RDP2000}
	${RDP2000} .

d630: ${RD630}
	${RD630} .

hplj.ecma: ${RHPLJ_ECMA}
	${RHPLJ_ECMA} .

hplj.dn: ${RHPLJ_DN}
	${RHPLJ_DN} .

hplj.ibmus: ${RHPLJ_IBMUS}
	${RHPLJ_IBMUS} .

hplj.roman8: ${RHPLJ_ROMAN8}
	${RHPLJ_ROMAN8} .

4216.roman8: ${R4216_ROMAN8}
	${R4216_ROMAN8} .

ibm.437: ${RIBM_437}
	${RIBM_437} .

ibm.850: ${RIBM_850}
	${RIBM_850} .

ibm.851: ${RIBM_851}
	${RIBM_851} .

ibm.852: ${RIBM_852}
	${RIBM_852} .

ibm.853: ${RIBM_853}
	${RIBM_853} .

ibm.855: ${RIBM_855}
	${RIBM_855} .

ibm.857: ${RIBM_857}
	${RIBM_857} .

ibm.860: ${RIBM_860}
	${RIBM_860} .

ibm.862: ${RIBM_862}
	${RIBM_862} .

ibm.863: ${RIBM_863}
	${RIBM_863} .

ibm.864: ${RIBM_864}
	${RIBM_864} .

ibm.865: ${RIBM_865}
	${RIBM_865} .

ibm.869: ${RIBM_869}
	${RIBM_869} .

ibm.1046: ${RIBM_1046}
	${RIBM_1046} .

3812.p0: ${R3812_P0}
	${R3812_P0} .

3812.p1: ${R3812_P1}
	${R3812_P1} .

3812.p2: ${R3812_P2}
	${R3812_P2} .

3816.p1: ${R3816_P1}
	${R3816_P1} .

3816.p2: ${R3816_P2}
	${R3816_P2} .

ascii: ${RASCII}
	${RASCII} .

p9012: ${RP9012}
	${RP9012} .
