# @(#)43	1.2  src/bos/usr/lpp/Unicode/lpd/pio/predef/Makefile, cfgnls, bos411, 9428A410j 4/11/94 08:18:26
#
#   COMPONENT_NAME: CFGNLS
#
#   FUNCTIONS: none
#
#   ORIGINS: 27
#
#   IBM CONFIDENTIAL -- (IBM Confidential Restricted when
#   combined with the aggregated modules for this product)
#                    SOURCE MATERIALS
#
#   (C) COPYRIGHT International Business Machines Corp. 1993
#   All Rights Reserved
#   US Government Users Restricted Rights - Use, duplication or
#   disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#

ILIST		= ibm4019.uni                  

IDIR		= /usr/lpp/Unicode/lpd/pio/predef/

.include <${RULES_MK}>
