# @(#)12	1.1  src/bos/diag/util/ush/Makefile, dutil, bos411, 9428A410j 12/3/93 09:55:21
#
#   COMPONENT_NAME: DUTIL
#
#   FUNCTIONS: 
#
#   ORIGINS: 27
#
#   IBM CONFIDENTIAL -- (IBM Confidential Restricted when
#   combined with the aggregated modules for this product)
#                    SOURCE MATERIALS
#
#   (C) COPYRIGHT International Business Machines Corp. 1993
#   All Rights Reserved
#   US Government Users Restricted Rights - Use, duplication or
#   disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#


PROGRAMS	= ush

LIBS		= -lc -ls

ILIST		= ${PROGRAMS}
IDIR		= /usr/lpp/diagnostics/bin/
ush_OFILES	= ush.o

.include <${RULES_MK}>
