# @(#)50	1.3  src/bos/diag/tu/ethstw/Makefile, tu_ethi_stw, bos411, 9428A410j 1/7/94 13:57:58
#
#   COMPONENT_NAME: TU_ETHI_STW
#
#   FUNCTIONS: 
#
#   ORIGINS: 27
#
#   IBM CONFIDENTIAL -- (IBM Confidential Restricted when
#   combined with the aggregated modules for this product)
#                    SOURCE MATERIALS
#
#   (C) COPYRIGHT International Business Machines Corp. 1992, 1994
#   All Rights Reserved
#   US Government Users Restricted Rights - Use, duplication or
#   disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#


#-------------------------------------------------------------------------#
#                                                                         #
#     This Makefile builds the library libethstwtu.a for the DA application #
#                                                                         #
#-------------------------------------------------------------------------#

LIBRARIES       =   libethstwtu.a

EXPLIB_TARGETS  =   export_libethstwtu.a
EXPDIR          =   /usr/lib/

OFILES		= 	crc_gen.o exectu.o rw_io.o rw_pos.o sr_io.o sr_pos.o \
			rw_smem.o st_eth.o tu001.o tu002.o tu003.o tu004.o \
		 	tu005.o tu006.o tu007.o tu008.o tu009.o tu00A.o \
			tu00B.o tu00C.o tu00D.o tu00E.o tu00F.o tu010.o tu011.o

.include <${RULES_MK}>
