#
# dependents of gio_slih.o:
gio_slih.o: ${MAKETOP}../export/power/usr/include/sys/adspace.h
gio_slih.o: ${MAKETOP}../export/power/usr/include/sys/types.h
gio_slih.o: ${MAKETOP}../export/power/usr/include/standards.h
gio_slih.o: ${MAKETOP}../export/power/usr/include/sys/m_types.h
gio_slih.o: ${MAKETOP}../export/power/usr/include/sys/seg.h
gio_slih.o: ${MAKETOP}../export/power/usr/include/sys/inode.h
gio_slih.o: ${MAKETOP}../export/power/usr/include/jfs/inode.h
gio_slih.o: ${MAKETOP}../export/power/usr/include/sys/param.h
gio_slih.o: ${MAKETOP}../export/power/usr/include/sys/m_param.h
gio_slih.o: ${MAKETOP}../export/power/usr/include/sys/limits.h
gio_slih.o: ${MAKETOP}../export/power/usr/include/float.h
gio_slih.o: ${MAKETOP}../export/power/usr/include/jfs/fsparam.h
gio_slih.o: ${MAKETOP}../export/power/usr/include/sys/sysmacros.h
gio_slih.o: ${MAKETOP}../export/power/usr/include/jfs/ino.h
gio_slih.o: ${MAKETOP}../export/power/usr/include/sys/time.h
gio_slih.o: ${MAKETOP}../export/power/usr/include/jfs/fsdefs.h
gio_slih.o: ${MAKETOP}../export/power/usr/include/jfs/filsys.h
gio_slih.o: ${MAKETOP}../export/power/usr/include/jfs/jfsmount.h
gio_slih.o: ${MAKETOP}../export/power/usr/include/sys/vnode.h
gio_slih.o: ${MAKETOP}../export/power/usr/include/sys/stat.h
gio_slih.o: ${MAKETOP}../export/power/usr/include/sys/mode.h
gio_slih.o: ${MAKETOP}../export/power/usr/include/sys/lockl.h
gio_slih.o: ${MAKETOP}../export/power/usr/include/sys/lock_def.h
gio_slih.o: ${MAKETOP}../export/power/usr/include/sys/uio.h
gio_slih.o: ${MAKETOP}../export/power/usr/include/sys/xmem.h
gio_slih.o: ${MAKETOP}../export/power/usr/include/sys/cred.h
gio_slih.o: ${MAKETOP}../export/power/usr/include/sys/priv.h
gio_slih.o: ${MAKETOP}../export/power/usr/include/sys/tcb.h
gio_slih.o: ${MAKETOP}../export/power/usr/include/sys/pcl.h
gio_slih.o: ${MAKETOP}../export/power/usr/include/jfs/quota.h
gio_slih.o: ${MAKETOP}../export/power/usr/include/sys/vmuser.h
gio_slih.o: ${MAKETOP}../export/power/usr/include/sys/acl.h
gio_slih.o: ${MAKETOP}../export/power/usr/include/sys/access.h
gio_slih.o: ${MAKETOP}../export/power/usr/include/sys/systemcfg.h
gio_slih.o: ${MAKETOP}../export/power/usr/include/sys/ioacc.h
gio_slih.o: ${MAKETOP}../export/power/usr/include/sys/diagex.h
gio_slih.o: ${MAKETOP}../export/power/usr/include/sys/intr.h
gio_slih.o: ${MAKETOP}../export/power/usr/include/sys/m_intr.h
gio_slih.o: ${MAKETOP}../export/power/usr/include/sys/dma.h
gio_slih.o: ${MAKETOP}../export/power/usr/include/sys/sysdma.h
gio_slih.o: ${MAKETOP}../export/power/usr/include/sys/timer.h
gio_slih.o: ${MAKETOP}../export/power/usr/include/sys/processor.h
gio_slih.o: ${MAKETOP}../export/power/usr/include/sys/watchdog.h
gio_slih.o: ${MAKETOP}bos/diag/tu/gio/interrupt/gio_diag.h
gio_slih.o: ${MAKETOP}bos/diag/tu/gio/interrupt/gio.h
gio_slih.o: ${MAKETOP}../export/power/usr/include/sys/cblock.h
gio_slih.o: ${MAKETOP}../export/power/usr/include/sys/except.h
gio_slih.o: ${MAKETOP}../export/power/usr/include/sys/m_except.h
