# @(#)68	1.3  src/bldenv/bldtools/afscpsrc/Makefile, bldprocess, bos412, GOLDA411a 6/25/94 10:42:51
#
#   COMPONENT_NAME: BLDTOOLS
#
#   FUNCTIONS:
#
#   ORIGINS: 27
#
#   IBM CONFIDENTIAL -- (IBM Confidential Restricted when
#   combined with the aggregated modules for this product)
#                    SOURCE MATERIALS
#
#   (C) COPYRIGHT International Business Machines Corp. 1993
#   All Rights Reserved
#   US Government Users Restricted Rights - Use, duplication or
#   disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#

PROGRAMS	= bldafsdcp

ILIST		= bldafsdcp

IDIR		= /usr/bld/

# force the compile to pick up include files off the build machine.
bldafsdcp.o_INCARGS = -I/usr/include

.include <${RULES_MK}>
