# @(#)30	1.3  src/bos/kernel/include/netns/Makefile, sysxxns, bos411, 9428A410j 7/24/93 14:11:11
#
# COMPONENT_NAME:
#
# FUNCTIONS:
#
# ORIGINS: 27
#
# IBM CONFIDENTIAL -- (IBM Confidential Restricted when
# combined with the aggregated modules for this product)
#                  SOURCE MATERIALS
# (C) COPYRIGHT International Business Machines Corp. 1988, 1989
# All Rights Reserved
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#

VPATH		=${MAKETOP}/bos/kernext/xns

DATAFILES	= \
	idp.h \
	idp_var.h \
	ns.h \
	ns_error.h \
	ns_if.h \
	ns_pcb.h \
	proto_ns.h \
	sp.h \
	spidp.h \
	spp_debug.h \
	spp_timer.h \
	spp_var.h

INCLUDES	= ${DATAFILES}

EXPDIR		=/kernel/include/netns/


.include <${RULES_MK}>
