# @(#)63        1.4  src/bos/usr/lpp/bos/Makefile, Makefiles, bos41J, 174392.bos 3/24/95 11:13:39
# COMPONENT_NAME:
#
# FUNCTIONS:
#
# ORIGINS: 27
#
# IBM CONFIDENTIAL -- (IBM Confidential Restricted when
# combined with the aggregated modules for this product)
#                  SOURCE MATERIALS
# (C) COPYRIGHT International Business Machines Corp. 1988, 1989
# All Rights Reserved
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#

SUBDIRS		= migrate

VPATH		= ${MAKETOP}/packages/bos/rte/usr
SCRIPTS		= mksysck README bos.rte.pre_i
MSGHDRS		= 
CATFILES	= 
HFILES		= ${MSGHDRS}
OTHERS		= ${SCRIPTS}

ILIST		= mksysck mksysck.awk README bos.rte.pre_i
IDIR		= /usr/lpp/bos/


.include <${RULES_MK}>
