# @(#)44	1.5  src/bldenv/pkgtools/subptf/bldgreplist.S, pkgtools, bos412, GOLDA411a 6/8/94 15:06:24
#
#   COMPONENT_NAME: PKGTOOLS
#
#   FUNCTIONS: none
#
#   ORIGINS: 27
#
#   IBM CONFIDENTIAL -- (IBM Confidential Restricted when
#   combined with the aggregated modules for this product)
#                    SOURCE MATERIALS
#
#   (C) COPYRIGHT International Business Machines Corp. 1991,1994
#   All Rights Reserved
#   US Government Users Restricted Rights - Use, duplication or
#   disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#
^#
/BUILD/
/INSTALL/
/export_
/build_all
/install_all
/installcat_
/inst.images/
/XREF/
