# @(#)95	1.4  src/bldenv/pkgtools/subptf/LIBNAMES.S, pkgtools, bos412, GOLDA411a 2/26/92 15:48:08
# COMPONENT_NAME: (BLDTOOLS) BAI Build Tools
#
# FUNCTIONS: LIBNAMES.S
#
# ORIGINS: 27
#
# (C) COPYRIGHT International Business Machines Corp. 1991, 1992
# All Rights Reserved
# Licensed Materials - Property of IBM
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#
!!/lib/c/libc.a.min
