# @(#)24	1.14  src/bldenv/pkgtools/subptf/Makefile, pkgtools, bos412, GOLDA411a 4/4/94 17:35:15
#
#   COMPONENT_NAME: PKGTOOLS
#
#   FUNCTIONS: 
#
#   ORIGINS: 27
#
#   IBM CONFIDENTIAL -- (IBM Confidential Restricted when
#   combined with the aggregated modules for this product)
#                    SOURCE MATERIALS
#
#   (C) COPYRIGHT International Business Machines Corp. 1992,1993
#   All Rights Reserved
#   US Government Users Restricted Rights - Use, duplication or
#   disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#

SCRIPTS		= subptf bldchangelist bldcoreqs bldcurdef blddefectlist \
	          bldenvlist bldgetalllists bldgetlists bldgetptfid \
	          subfilelpp subgroup bldhistory bldhistorylib \
		  bldifreqs bldinfo bldinfolib bldmakelist bldmid bldoptlib \
		  bldnormalize bldprereqs bldprevdef bldptfdepend \
		  subptfformat subptfpkg bldreviselist bldtd \
		  bldtdlib bldunique bldupdatelist bldxreflist \
		  bldgreplist bldabstracts bldorderstatus \
		  blddepunique bldlinkdata bldmissdefects \
		  bldcut bldaddptfids bldsaveptfinfo \
		  bldgetfamily bldfilterdeps capStderr subptfopts LIBNAMES

ILIST           = ${SCRIPTS}

IDIR            = /usr/bin/

.include <${RULES_MK}>


