# @(#)61        1.2  src/bldenv/gos/Xlib/Makefile, xlib, bos412, GOLDA411a 1/24/94 13:43:06
#
# COMPONENT_NAME: xlib
#
# FUNCTIONS: Makefile
#
# ORIGINS: 27
#
# This module contains IBM CONFIDENTIAL code. -- (IBM
# Confidential Restricted when combined with the aggregated
# modules for this product)
#                  SOURCE MATERIALS
# (C) COPYRIGHT International Business Machines Corp. 1987, 1994
# All Rights Reserved
# Licensed Materials - Property of IBM
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#
#

VPATH		= ${MAKETOP}/gos/2d/XTOP/lib/X/util

CFLAGS          = -DAIXV3

PROGRAMS	= makekeys
ILIST		= ${PROGRAMS}
IDIR		= /usr/bin/

.include <${RULES_MK}>

