# @(#) 74 1.2 src/bos/usr/lpp/bosinst/berror/Makefile, bosinst, bos411, 9428A410j 6/30/93 17:31:09
# COMPONENT_NAME: bosinst
#
# FUNCTIONS:  Makefile for berror
#
# ORIGINS: 27
#
# IBM CONFIDENTIAL -- (IBM Confidential Restricted when
# combined with the aggregated modules for this product)
#                  SOURCE MATERIALS
# (C) COPYRIGHT International Business Machines Corp. 1993
# All Rights Reserved
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#

PROGRAMS	= berror

ILIST		= berror
IDIR		= /usr/lpp/bosinst/

.include <${RULES_MK}>
