# @(#)72	1.1  src/bos/usr/lib/ncs/cat/files/Makefile, bos, bos410 3/1/93 11:28:00
# COMPONENT_NAME:  libncs
#
# FUNCTIONS:
#
# ORIGINS: 27
#
# IBM CONFIDENTIAL -- (IBM Confidential Restricted when
# combined with the aggregated modules for this product)
#                  SOURCE MATERIALS
# (C) COPYRIGHT International Business Machines Corp. 1988, 1992
# All Rights Reserved
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#

ILIST		= \
	glb_obj.txt \
	glb_site.txt \
	uuidname.txt

IDIR		= /usr/lib/ncs/cat/files/

.include <${RULES_MK}>

