# @(#)71	1.2  src/bos/kernext/disp/ped/inc/Makefile, peddd, bos411, 9428A410j 3/4/93 14:06:42
#
#   COMPONENT_NAME: PEDDD
#
#   FUNCTIONS: 
#
#   ORIGINS: 27
#
#   IBM CONFIDENTIAL -- (IBM Confidential Restricted when
#   combined with the aggregated modules for this product)
#                    SOURCE MATERIALS
#
#   (C) COPYRIGHT International Business Machines Corp. 1993
#   All Rights Reserved
#   US Government Users Restricted Rights - Use, duplication or
#   disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#


VPATH 	        =${MAKETOP}bos/kernext/inc/POWER

EXPDIR		= /kernel/include/

MID_INCFILES    = ddsmid.h 

CDD_INCFILES    = bidefs.h 

INCLUDES	= ${MID_INCFILES} ${CDD_INCFILES} 

.include <${RULES_MK}>
