# COMPONENT_NAME: (ucodserdasd) Serial Dasd Subsystem Microcode 
# # @(#)87        1.4  src/bos/usr/lib/microcode/serdasd/copyright.S, ucodserdasd, bos411, 9428A410j 12/6/93 05:02:55#
# FUNCTIONS: none
#
# ORIGINS: 27
#
# (C) COPYRIGHT International Business Machines Corp. 1991 
# All Rights Reserved
# Licensed Material - Property of IBM
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
##

##
# NAME: copyright.S
#
# FUNCTION: copyright header information
#
# RETURN VALUE DESCRIPTION:
#        none
##

Serial Dasd Subsystem Microcode
(C) Copyright IBM Corp. 1991,1993
