# @(#)84        1.18  src/bos/usr/lib/microcode/serdasd/Makefile, ucodserdasd, bos411, 9428A410j 1/27/94 16:36:44
# COMPONENT_NAME: (ucodserdasd) Serial Dasd Subsystem Microcode
#
# FUNCTIONS: Makefilec
#
# ORIGINS: 27
#
# IBM CONFIDENTIAL -- (IBM Confidential Restricted when
# combined with the aggregated modules for this product)
#                  SOURCE MATERIALS
# (C) COPYRIGHT International Business Machines Corp. 1993
# All Rights Reserved
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#


ILIST		= 8f78.00.16

IDIR		= /usr/lib/microcode/

.include <${RULES_MK}>

