# @(#)94  1.3  src/bos/kernext/ient/devices.mca.8ef2.com.trc.S, sysxient, bos41B, 412_41B_sync 12/8/94 14:24:40 
#
#   COMPONENT_NAME: SYSXENT
#
#   FUNCTIONS: none
#
#   ORIGINS: 27
#
#
#   (C) COPYRIGHT International Business Machines Corp. 1993
#   All Rights Reserved
#   Licensed Materials - Property of IBM
#   US Government Users Restricted Rights - Use, duplication or
#   disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#
* /etc/trcfmt

+320 1.0 "@ethdd" \
	"IENT DD XMIT:  " O2 A4.8 "d1=" X4 " d2=" X4 " d3=" X4

+321 1.0 "@ethdd" \
	"IENT DD RECV:  " O2 A4.8 "d1=" X4 " d2=" X4 " d3=" X4

+322 1.0 "@ethdd" \
	"IENT DD OTHER: " O2 A4.8 "d1=" X4 " d2=" X4 " d3=" X4

+323 1.0 "@ethdd" \
	"IENT DD ERROR: " O2 A4.8 "d1=" X4 " d2=" X4 " d3=" X4

