# @(#)27	1.3  src/bos/usr/lpp/blkmux/samples/Makefile, sysxcat, bos411, 9428A410j 1/20/94 08:49:15
#
#   COMPONENT_NAME: 370PCA_DD
#
#   FUNCTIONS: none
#
#   ORIGINS: 27
#
#
#   (C) COPYRIGHT International Business Machines Corp. 1993
#   All Rights Reserved
#   Licensed Materials - Property of IBM
#   US Government Users Restricted Rights - Use, duplication or
#   disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#

VPATH		= ${TARGET_MACHINE}

ILIST		= catapp.c catkern.c

IDIR 		= /usr/lpp/blkmux/samples/

.include <${RULES_MK}>
