# @(#)83	1.3  src/bos/kernext/dlc/include/Makefile, sysxdlcg, bos411, 9428A410j 2/25/93 15:50:47
#
# COMPONENT_NAME: (SYSXDLCG) Data Link Controls
#
# FUNCTIONS: Makefile
#
# ORIGINS: 27
#
# IBM CONFIDENTIAL -- (IBM Confidential Restricted when
# combined with the aggregated modules for this product)
#                  SOURCE MATERIALS
# (C) COPYRIGHT International Business Machines Corp. 1993
# All Rights Reserved
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#
#----------------------------------------------------------------------
#  Makefile for Data Link Control exported include file
#-----------------------------------------------------------------------

.include <${MAKETOP}bos/kernext/Kernext.mk>

gdlextcb.h_IDIR = /usr/include/sys/
ILIST = gdlextcb.h

EXPDIR = /kernel/include/sys/

INCLUDES = gdlextcb.h

.include <${RULES_MK}>

