# @(#)28       1.3  src/bos/kernext/mps_tok/mps_tok.trc.S, sysxmps, bos411, 9432A411a 8/4/94 21:54:21 
#
#   COMPONENT_NAME: sysxmps -- Wildwood Token Ring Devive Driver
#
#   FUNCTIONS: none
#
#   ORIGINS: 27
#
#
#   (C) COPYRIGHT International Business Machines Corp. 1994
#   All Rights Reserved
#   Licensed Materials - Property of IBM
#   US Government Users Restricted Rights - Use, duplication or
#   disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#
* /etc/trcfmt 

+32D 1.0 "@mpsdd" \
        "MPS DD XMT: " O2 A4.8 "d1=" X4 " d2=" X4 " d3=" X4 

+32E 1.0 "@mpsdd" \
        "MPS DD RCV: " O2 A4.8 "d1=" X4 " d2=" X4 " d3=" X4

+32F 1.0 "@mpsdd" \
        "MPS DD ERR: " O2 A4.8 "d1=" X4 " d2=" X4 " d3=" X4

+338 1.0 "@mpsdd" \
        "MPS DD OTHER: " O2 A4.8 "d1=" X4 " d2=" X4 " d3=" X4
