# @(#)49	1.2  src/bos/diag/boot/.version.S, diagboot, bos41J, 9510A_all 3/3/95 13:54:28
# COMPONENT_NAME: DIAGBOOT
#
# FUNCTIONS: CDROM Version number
#
# ORIGINS: 27
#
# (C) COPYRIGHT International Business Machines Corp. 1995
# All Rights Reserved
# Licensed Materials - Property of IBM
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#
4 1 3
