# @(#)85	1.3  src/bos/diag/boot/config5.dep.S, diagboot, bos41J, 9517B_all 4/24/95 15:14:50
#
# COMPONENT_NAME: DIAGBOOT
#
# FUNCTIONS: Configuration dependency file
#	     This file has all the methods and drivers needed
#	     to configure psla, msla
#
# ORIGINS: 27
#
# (C) COPYRIGHT International Business Machines Corp. 1994
# All Rights Reserved
# Licensed Materials - Property of IBM
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#
#	psla/msla
./usr/lib/methods/cfgpsla
./usr/lib/methods/cfgmsla
./usr/lib/methods/cfghia
./usr/lib/drivers/psladd
./usr/lib/drivers/hiadd
./usr/lib/microcode/8787S.00.01
./usr/lib/microcode/8787d50.00.01
./usr/lib/microcode/8787dpl2.00.01
./usr/lib/microcode/8787dpl3.00.01
./usr/lib/microcode/8787dwrp.00.01
./usr/lib/microcode/8787dmod.00.01
./usr/lib/microcode/8787dp.00.01
./usr/lib/microcode/8787dd1.00.01
./usr/lib/microcode/8787dd2.00.01
