# @(#)90	1.1  src/bos/diag/boot/disks.stz.S, diagboot, bos411, 9428A410j 2/22/94 10:14:33
#
#
# COMPONENT_NAME: DIAGBOOT
#
# FUNCTIONS: Diagnostic Disk Media devices Configuration File List
#
# ORIGINS: 27
#
# (C) COPYRIGHT International Business Machines Corp. 1994
# All Rights Reserved
# Licensed Materials - Property of IBM
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#
########################################################################
/etc/stanzas/disk.scsi.1000mb.add
/etc/stanzas/disk.scsi.1000mbde.add
/etc/stanzas/disk.scsi.1200mb.add
/etc/stanzas/disk.scsi.1370mb.add
/etc/stanzas/disk.scsi.160mb.add
/etc/stanzas/disk.scsi.2000mb.add
/etc/stanzas/disk.scsi.2000mb16bitde.add
/etc/stanzas/disk.scsi.2000mbde.add
/etc/stanzas/disk.scsi.200mb.add
/etc/stanzas/disk.scsi.320mb.add
/etc/stanzas/disk.scsi.355mb.add
/etc/stanzas/disk.scsi.400mb.add
/etc/stanzas/disk.scsi.540mb.add
/etc/stanzas/disk.scsi.670mb.add
/etc/stanzas/disk.scsi.857mb.add
/etc/stanzas/disk.scsi.osdisk.add
