# @(#)31	1.3  src/bos/diag/boot/linkedfiles.dep.S, diagboot, bos411, 9438B411a 9/20/94 15:45:27
#
#
# COMPONENT_NAME: DIAGBOOT
#
# FUNCTIONS: Used to create symbolic links between files.
#		
#
# ORIGINS: 27
#
# (C) COPYRIGHT International Business Machines Corp. 1994
# All Rights Reserved
# Licensed Materials - Property of IBM
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#
########################################################################
/usr/lpp/diagnostics/da/dacorv /usr/lpp/diagnostics/bin/mcorv
/usr/bin/compress /usr/bin/uncompress
/usr/bin/dosdir /usr/bin/dosread
