# @(#)12	1.5  src/bos/diag/boot/tapediag3C.dep.S, diagboot, bos41J, 9510A_all 3/3/95 13:52:29
#
# COMPONENT_NAME: DIAGBOOT - DIAGNOSTIC DISKETTE
#
# FUNCTIONS: Diagnostic Diskette 3C Content File
#
# ORIGINS: 27
#
# (C) COPYRIGHT International Business Machines Corp.  1994
# All Rights Reserved
# Licensed Materials - Property of IBM
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#
########################################################################
#	gemini
./usr/lib/methods/cfggem
./usr/lib/drivers/gemdd
./usr/lib/microcode/8ffdgu.00.04
./usr/lib/microcode/8ffdgt.00.04
./usr/lib/microcode/8ffdgv.00.04
./usr/lib/microcode/8ffdvp.00.03
./usr/lib/microcode/8ffdc2.00.04
./usr/lib/microcode/8ffdsh.00.04
./usr/lib/microcode/8ffddc25.00.02
./usr/lib/microcode/8ffddbif.00.01
./usr/lib/microcode/8ffddgcp.00.02
./usr/lib/lpp/diagnostics/da/dgraph
./usr/lib/lpp/diagnostics/catalog/default/dgraph.cat
#	Ruby
./usr/lib/methods/cfgrby
./usr/lib/drivers/rbydd
./usr/lpp/diagnostics/da/druby
./usr/lpp/diagnostics/catalog/default/druby.cat
./usr/lib/microcode/8fbccp.00.00
./usr/lib/microcode/8fbcap.00.00
./usr/lib/microcode/8fbccp1.00.00
./usr/lib/microcode/8fbcap1.00.00
./usr/lib/microcode/8fbclogp.00.00
./usr/lib/microcode/8fbclogp1.00.00
./usr/lib/microcode/8fbchigp.00.00
./usr/lib/microcode/8fbchigp1.00.00
