# @(#)20	1.3  src/bos/diag/boot/term.dep.S, diagboot, bos411, 9428A410j 4/22/94 09:44:10
#
# COMPONENT_NAME: DIAGBOOT
#
# FUNCTIONS: Terminal Dependency List File
#
# ORIGINS: 27
#
# (C) COPYRIGHT International Business Machines Corp. 1994
# All Rights Reserved
# Licensed Materials - Property of IBM
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#
########################################################################
./usr/share/lib/terminfo/i/ibmpc
./usr/share/lib/terminfo/i/ibm3101
./usr/share/lib/terminfo/i/ibm3151
./usr/share/lib/terminfo/i/ibm3161
./usr/share/lib/terminfo/i/ibm3162
./usr/share/lib/terminfo/i/ibm3163
./usr/share/lib/terminfo/i/ibm3164
./usr/share/lib/terminfo/v/vs100
./usr/share/lib/terminfo/v/vt100
./usr/share/lib/terminfo/v/vt320
./usr/share/lib/terminfo/v/vt330
./usr/share/lib/terminfo/v/vt340
./usr/share/lib/terminfo/t/tvi950
./usr/share/lib/terminfo/t/tvi925
./usr/share/lib/terminfo/t/tvi920
./usr/share/lib/terminfo/t/tvi912
./usr/share/lib/terminfo/w/wyse30
./usr/share/lib/terminfo/w/wyse50
./usr/share/lib/terminfo/w/wyse60
./usr/share/lib/terminfo/w/wyse100
./usr/share/lib/terminfo/w/wyse350
./usr/share/lib/terminfo/s/sun
./usr/share/lib/terminfo/l/lft
