# @(#)24	1.2  src/bos/usr/lpp/Unicode/X11/app-defaults/Makefile, cfgnls, bos411, 9428A410j 2/7/94 09:51:57
#
#   COMPONENT_NAME: CFGNLS
#
#   FUNCTIONS: none
#
#   ORIGINS: 27
#
#   IBM CONFIDENTIAL -- (IBM Confidential Restricted when
#   combined with the aggregated modules for this product)
#                    SOURCE MATERIALS
#
#   (C) COPYRIGHT International Business Machines Corp. 1994
#   All Rights Reserved
#   US Government Users Restricted Rights - Use, duplication or
#   disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#

ILIST		= Mwm XMdemos Aixterm Aixim Msmit XTerm

IDIR		= /usr/lpp/Unicode/X11/app-defaults/

.include <${RULES_MK}>
