# @(#)51        1.1  src/bos/etc/csh.cshrc/Makefile, cmdcsh, bos411, 9433A411a 8/9/94 10:55:19
# COMPONENT_NAME: (CMDCSH) C Shell
#
# FUNCTIONS:
#
# ORIGINS: 27
#
# IBM CONFIDENTIAL -- (IBM Confidential Restricted when
# combined with the aggregated modules for this product)
#                  SOURCE MATERIALS
# (C) COPYRIGHT International Business Machines Corp. 1994 
# All Rights Reserved
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#

ILIST		= csh.cshrc
IDIR		= /etc/

.include <${RULES_MK}>
