# @(#)01        1.1  src/bos/usr/ccs/lib/libunpack/Makefile, Makefiles, bos411, 9428A410j 8/5/92 16:21:10
# COMPONENT_NAME:
#
# FUNCTIONS:
#
# ORIGINS: 27
#
# IBM CONFIDENTIAL -- (IBM Confidential Restricted when
# combined with the aggregated modules for this product)
#                  SOURCE MATERIALS
# (C) COPYRIGHT International Business Machines Corp. 1988, 1989
# All Rights Reserved
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#



LIBRARIES	= libunpack.a
MSGHDRS         =
CATFILES        =
HFILES          = ${MSGHDRS}

EXPLIB_TARGETS  = export_libunpack.a

ILIST           = libunpack.a
IDIR            = /usr/ccs/lib/

OFILES		= unpack.o

.include <${RULES_MK}>
