#
# dependents of chk_errlog.o:
chk_errlog.o: ${MAKETOP}../export/power/usr/include/stdio.h
chk_errlog.o: ${MAKETOP}../export/power/usr/include/standards.h
chk_errlog.o: ${MAKETOP}../export/power/usr/include/va_list.h
chk_errlog.o: ${MAKETOP}../export/power/usr/include/sys/types.h
chk_errlog.o: ${MAKETOP}../export/power/usr/include/sys/m_types.h
chk_errlog.o: ${MAKETOP}../export/power/usr/include/sys/limits.h
chk_errlog.o: ${MAKETOP}../export/power/usr/include/float.h
chk_errlog.o: ${MAKETOP}../export/power/usr/include/string.h
chk_errlog.o: ${MAKETOP}../export/power/usr/include/sys/errids.h
chk_errlog.o: ${MAKETOP}../export/power/usr/include/sys/err_rec.h
chk_errlog.o: ${MAKETOP}../export/power/usr/include/diag/diag.h
chk_errlog.o: ${MAKETOP}../export/power/usr/include/diag/diag_define.h
chk_errlog.o: ${MAKETOP}../export/power/usr/include/diag/da.h
chk_errlog.o: ${MAKETOP}../export/power/usr/include/sys/cfgdb.h
chk_errlog.o: ${MAKETOP}../export/power/usr/include/diag/tm_input.h
chk_errlog.o: ${MAKETOP}bos/diag/tu/ruby/tu_info.h
chk_errlog.o: ${MAKETOP}bos/diag/tu/ruby/tu_ruby.h
#
# dependents of chk_runtype.o:
chk_runtype.o: ${MAKETOP}../export/power/usr/include/stdio.h
chk_runtype.o: ${MAKETOP}../export/power/usr/include/standards.h
chk_runtype.o: ${MAKETOP}../export/power/usr/include/va_list.h
chk_runtype.o: ${MAKETOP}../export/power/usr/include/sys/types.h
chk_runtype.o: ${MAKETOP}../export/power/usr/include/sys/m_types.h
chk_runtype.o: ${MAKETOP}../export/power/usr/include/sys/limits.h
chk_runtype.o: ${MAKETOP}../export/power/usr/include/float.h
chk_runtype.o: ${MAKETOP}../export/power/usr/include/diag/diago.h
chk_runtype.o: ${MAKETOP}../export/power/usr/include/asl.h
chk_runtype.o: ${MAKETOP}../export/power/usr/include/stdarg.h
chk_runtype.o: ${MAKETOP}../export/power/usr/include/diag/tm_input.h
chk_runtype.o: ${MAKETOP}../export/power/usr/include/diag/tmdefs.h
chk_runtype.o: ${MAKETOP}bos/diag/tu/ruby/tu_info.h
chk_runtype.o: ${MAKETOP}bos/diag/tu/ruby/tu_ruby.h
chk_runtype.o: druby_msg.h
chk_runtype.o: ${MAKETOP}../export/power/usr/include/limits.h
chk_runtype.o: ${MAKETOP}../export/power/usr/include/nl_types.h
chk_runtype.o: ${MAKETOP}../export/power/usr/include/mesg.h
chk_runtype.o: ${MAKETOP}bos/diag/tu/ruby/debug.h
#
# dependents of druby.o:
druby.o: ${MAKETOP}../export/power/usr/include/stdio.h
druby.o: ${MAKETOP}../export/power/usr/include/standards.h
druby.o: ${MAKETOP}../export/power/usr/include/va_list.h
druby.o: ${MAKETOP}../export/power/usr/include/sys/types.h
druby.o: ${MAKETOP}../export/power/usr/include/sys/m_types.h
druby.o: ${MAKETOP}../export/power/usr/include/sys/limits.h
druby.o: ${MAKETOP}../export/power/usr/include/float.h
druby.o: ${MAKETOP}../export/power/usr/include/asl.h
druby.o: ${MAKETOP}../export/power/usr/include/stdarg.h
druby.o: ${MAKETOP}../export/power/usr/include/nl_types.h
druby.o: ${MAKETOP}../export/power/usr/include/mesg.h
druby.o: ${MAKETOP}../export/power/usr/include/diag/tm_input.h
druby.o: ${MAKETOP}../export/power/usr/include/diag/diag_exit.h
druby.o: ${MAKETOP}../export/power/usr/include/diag/da.h
druby.o: ${MAKETOP}../export/power/usr/include/sys/cfgdb.h
druby.o: ${MAKETOP}../export/power/usr/include/diag/diago.h
druby.o: ${MAKETOP}bos/diag/tu/ruby/tu_ruby.h
druby.o: ${MAKETOP}bos/diag/tu/ruby/tu_info.h
druby.o: druby_msg.h
druby.o: ${MAKETOP}../export/power/usr/include/limits.h
druby.o: ${MAKETOP}bos/diag/tu/ruby/srn_report.h
druby.o: ${MAKETOP}bos/diag/da/ruby/druby.h
druby.o: ${MAKETOP}bos/diag/tu/ruby/debug.h
#
# dependents of init_da.o:
init_da.o: ${MAKETOP}../export/power/usr/include/stdio.h
init_da.o: ${MAKETOP}../export/power/usr/include/standards.h
init_da.o: ${MAKETOP}../export/power/usr/include/va_list.h
init_da.o: ${MAKETOP}../export/power/usr/include/sys/types.h
init_da.o: ${MAKETOP}../export/power/usr/include/sys/m_types.h
init_da.o: ${MAKETOP}../export/power/usr/include/sys/limits.h
init_da.o: ${MAKETOP}../export/power/usr/include/float.h
init_da.o: ${MAKETOP}../export/power/usr/include/nl_types.h
init_da.o: ${MAKETOP}../export/power/usr/include/mesg.h
init_da.o: ${MAKETOP}../export/power/usr/include/locale.h
init_da.o: ${MAKETOP}../export/power/usr/include/diag/diago.h
init_da.o: ${MAKETOP}../export/power/usr/include/asl.h
init_da.o: ${MAKETOP}../export/power/usr/include/stdarg.h
init_da.o: ${MAKETOP}../export/power/usr/include/diag/tm_input.h
init_da.o: ${MAKETOP}../export/power/usr/include/diag/diag_exit.h
init_da.o: ${MAKETOP}bos/diag/tu/ruby/tu_info.h
init_da.o: ${MAKETOP}bos/diag/tu/ruby/tu_ruby.h
init_da.o: ${MAKETOP}bos/diag/tu/ruby/debug.h
#
# dependents of panel_init.o:
panel_init.o: ${MAKETOP}../export/power/usr/include/stdio.h
panel_init.o: ${MAKETOP}../export/power/usr/include/standards.h
panel_init.o: ${MAKETOP}../export/power/usr/include/va_list.h
panel_init.o: ${MAKETOP}../export/power/usr/include/sys/types.h
panel_init.o: ${MAKETOP}../export/power/usr/include/sys/m_types.h
panel_init.o: ${MAKETOP}../export/power/usr/include/sys/limits.h
panel_init.o: ${MAKETOP}../export/power/usr/include/float.h
panel_init.o: ${MAKETOP}../export/power/usr/include/nl_types.h
panel_init.o: ${MAKETOP}../export/power/usr/include/mesg.h
panel_init.o: ${MAKETOP}../export/power/usr/include/diag/diago.h
panel_init.o: ${MAKETOP}../export/power/usr/include/asl.h
panel_init.o: ${MAKETOP}../export/power/usr/include/stdarg.h
panel_init.o: ${MAKETOP}../export/power/usr/include/diag/diag.h
panel_init.o: ${MAKETOP}../export/power/usr/include/diag/diag_define.h
panel_init.o: ${MAKETOP}../export/power/usr/include/diag/diag_exit.h
panel_init.o: ${MAKETOP}../export/power/usr/include/diag/tm_input.h
panel_init.o: ${MAKETOP}../export/power/usr/include/diag/tmdefs.h
panel_init.o: ${MAKETOP}../export/power/usr/include/diag/dcda_msg.h
panel_init.o: ${MAKETOP}../export/power/usr/include/limits.h
panel_init.o: ${MAKETOP}bos/diag/tu/ruby/tu_info.h
panel_init.o: ${MAKETOP}bos/diag/tu/ruby/tu_ruby.h
panel_init.o: druby_msg.h
panel_init.o: ${MAKETOP}bos/diag/da/ruby/ruby_msgdat.h
panel_init.o: ${MAKETOP}bos/diag/tu/ruby/debug.h
#
# dependents of test_tube_da.o:
test_tube_da.o: ${MAKETOP}../export/power/usr/include/stdio.h
test_tube_da.o: ${MAKETOP}../export/power/usr/include/standards.h
test_tube_da.o: ${MAKETOP}../export/power/usr/include/va_list.h
test_tube_da.o: ${MAKETOP}../export/power/usr/include/sys/types.h
test_tube_da.o: ${MAKETOP}../export/power/usr/include/sys/m_types.h
test_tube_da.o: ${MAKETOP}../export/power/usr/include/sys/limits.h
test_tube_da.o: ${MAKETOP}../export/power/usr/include/float.h
test_tube_da.o: ${MAKETOP}../export/power/usr/include/fcntl.h
test_tube_da.o: ${MAKETOP}../export/power/usr/include/sys/flock.h
test_tube_da.o: ${MAKETOP}../export/power/usr/include/unistd.h
test_tube_da.o: ${MAKETOP}../export/power/usr/include/sys/access.h
test_tube_da.o: ${MAKETOP}../export/power/usr/include/sys/lockf.h
test_tube_da.o: ${MAKETOP}../export/power/usr/include/sys/stat.h
test_tube_da.o: ${MAKETOP}../export/power/usr/include/sys/mode.h
test_tube_da.o: ${MAKETOP}../export/power/usr/include/diag/tm_input.h
test_tube_da.o: ${MAKETOP}bos/diag/tu/ruby/tu_info.h
test_tube_da.o: ${MAKETOP}bos/diag/tu/ruby/tu_ruby.h
test_tube_da.o: ${MAKETOP}bos/diag/tu/ruby/ros_info.h
test_tube_da.o: ${MAKETOP}bos/diag/tu/ruby/ruby_dd_if.h
test_tube_da.o: ${MAKETOP}bos/diag/tu/ruby/mailbox.h
test_tube_da.o: ${MAKETOP}bos/diag/tu/ruby/ccm_request.h
test_tube_da.o: ${MAKETOP}bos/diag/tu/ruby/srn_report.h
test_tube_da.o: druby_msg.h
test_tube_da.o: ${MAKETOP}../export/power/usr/include/limits.h
test_tube_da.o: ${MAKETOP}../export/power/usr/include/nl_types.h
test_tube_da.o: ${MAKETOP}../export/power/usr/include/mesg.h
test_tube_da.o: ${MAKETOP}bos/diag/tu/ruby/debug.h
test_tube_da.o: ${MAKETOP}bos/diag/tu/ruby/color_bar.h
test_tube_da.o: ${MAKETOP}bos/diag/tu/ruby/color_bar_12.h
