#
# dependents of dsga.o:
dsga.o: ${MAKETOP}../export/power/usr/include/stdio.h
dsga.o: ${MAKETOP}../export/power/usr/include/standards.h
dsga.o: ${MAKETOP}../export/power/usr/include/va_list.h
dsga.o: ${MAKETOP}../export/power/usr/include/sys/types.h
dsga.o: ${MAKETOP}../export/power/usr/include/sys/m_types.h
dsga.o: ${MAKETOP}../export/power/usr/include/sys/limits.h
dsga.o: ${MAKETOP}../export/power/usr/include/float.h
dsga.o: ${MAKETOP}../export/power/usr/include/signal.h
dsga.o: ${MAKETOP}../export/power/usr/include/sys/signal.h
dsga.o: ${MAKETOP}../export/power/usr/include/sys/context.h
dsga.o: ${MAKETOP}../export/power/usr/include/sys/m_param.h
dsga.o: ${MAKETOP}../export/power/usr/include/sys/mstsave.h
dsga.o: ${MAKETOP}../export/power/usr/include/sys/errno.h
dsga.o: ${MAKETOP}../export/power/usr/include/sys/cfgodm.h
dsga.o: ${MAKETOP}../export/power/usr/include/odmi.h
dsga.o: ${MAKETOP}../export/power/usr/include/sys/dir.h
dsga.o: ${MAKETOP}../export/power/usr/include/sys/lkup.h
dsga.o: ${MAKETOP}../export/power/usr/include/limits.h
dsga.o: ${MAKETOP}../export/power/usr/include/locale.h
dsga.o: ${MAKETOP}../export/power/usr/include/diag/diago.h
dsga.o: ${MAKETOP}../export/power/usr/include/asl.h
dsga.o: ${MAKETOP}../export/power/usr/include/stdarg.h
dsga.o: ${MAKETOP}../export/power/usr/include/diag/diag.h
dsga.o: ${MAKETOP}../export/power/usr/include/diag/diag_define.h
dsga.o: ${MAKETOP}../export/power/usr/include/diag/tm_input.h
dsga.o: ${MAKETOP}../export/power/usr/include/diag/tmdefs.h
dsga.o: ${MAKETOP}../export/power/usr/include/diag/da.h
dsga.o: ${MAKETOP}../export/power/usr/include/sys/cfgdb.h
dsga.o: ${MAKETOP}../export/power/usr/include/diag/da_rc.h
dsga.o: ${MAKETOP}../export/power/usr/include/diag/diag_exit.h
dsga.o: ${MAKETOP}../export/power/usr/include/diag/dcda_msg.h
dsga.o: ${MAKETOP}../export/power/usr/include/nl_types.h
dsga.o: ${MAKETOP}../export/power/usr/include/mesg.h
dsga.o: dsga_msg.h
dsga.o: ${MAKETOP}bos/diag/tu/sgasl/sgamisc.h
dsga.o: ${MAKETOP}bos/diag/tu/sgasl/exectu.h
dsga.o: ${MAKETOP}../export/power/usr/include/diag/atu.h
dsga.o: ${MAKETOP}bos/diag/da/sgasal/dasga.h
