# @(#)15        1.2  src/bldenv/makemsgs/Makefile, bldprocess, bos412, GOLDA411a 3/24/93 18:22:31
#
#   COMPONENT_NAME: BOSBUILD
#
#   FUNCTIONS:
#
#   ORIGINS: 27
#
#   IBM CONFIDENTIAL -- (IBM Confidential Restricted when
#   combined with the aggregated modules for this product)
#                    SOURCE MATERIALS
#
#   (C) COPYRIGHT International Business Machines Corp. 1993
#   All Rights Reserved
#   US Government Users Restricted Rights - Use, duplication or
#   disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#
VPATH	= ${MAKETOP}/hcon/usr/lib/nls/msg/whpmri
INCFLAGS=-I${MAKETOP}/hcon/usr/include
PROGRAMS	= makemsgs

ILIST	= ${PROGRAMS}
IDIR	= /usr/bin/

.include <${RULES_MK}>
