$ @(#)23	1.2  src/bos/usr/lib/methods/cfgmpaa/mpa.msg, mpacfg, bos411, 9428A410j 5/26/93 08:29:11
$
$   COMPONENT_NAME: (MPAMSG) MP/A MESSAGE FILES
$
$   FUNCTIONS: 
$		
$
$   ORIGINS: 27
$
$   IBM CONFIDENTIAL -- (IBM Confidential Restricted when
$   combined with the aggregated modules for this product)
$                    SOURCE MATERIALS
$
$   (C) COPYRIGHT International Business Machines Corp. 1993
$   All Rights Reserved
$   US Government Users Restricted Rights - Use, duplication or
$   disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
$

$ This is the msg src file for the mpa.cat message catalog
$quote "    Use a double quote to delimit text
$delset 1   Clean up the set first by deleteing it
$set 1
1      "Single Port Multiprotocol Adapter/A (MP/A)"
2      "Base Address For Bus I/O Access"
3      "Interrupt Level A"
4      "DMA Level"
5      "Interrupt Priority"
6      ""
7      "Multiprotocol Adapter/A (MP/A) SDLC Device Driver"
8      ""
9      "Interrupt Level B"
10     "Receive Data Transfer Offset"
$
$ This section is for smit messages
$delset 2
$set 2
1      "Single Port Multiprotocol Adapter/A (MP/A)"
2      "Adapter"
3      "Services"
4      "User Applications"
5      "List all Single Port Multiprotocol Adapters"
6      "Manage Device Drivers for Single Port Multiprotocol Adapter/A"
7      "Generate an Error Report"
8      "Trace a Single Port Multiprotocol Adapter/A"
9      "Manage SDLC Device Driver"
10     "Add a Device Driver"
11     "Single Port Multiprotocol Adapter/A"
12     "Remove a Device Driver"
13     "Configure a Defined Device Driver"
14     "SDLC Device Driver"
15     "Apply change to DATABASE only"
16     "Change/Show Characteristics of an SDLC Device Driver"
