# @(#)10	1.1  src/bldenv/bldtools/chksubsys/Makefile, bldprocess, bos412, GOLDA411a 12/10/93 15:45:59
#
#   COMPONENT_NAME: BLDPROCESS
#
#   FUNCTIONS:
#
#   ORIGINS: 27
#
#   IBM CONFIDENTIAL -- (IBM Confidential Restricted when
#   combined with the aggregated modules for this product)
#                    SOURCE MATERIALS
#
#   (C) COPYRIGHT International Business Machines Corp. 1993
#   All Rights Reserved
#   US Government Users Restricted Rights - Use, duplication or
#   disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#

PROGRAMS	= bldsbprint

SCRIPTS         = chksubsys

ILIST		= bldsbprint chksubsys

IDIR		= /usr/bld/

.include <${RULES_MK}>
