# @(#)22        1.8  src/bos/kernel/exp/Makefile, sysexp, bos41B, 412_41B_sync 1/4/95 12:58:34
# COMPONENT_NAME:
#
# FUNCTIONS:
#
# ORIGINS: 27 83
#
# IBM CONFIDENTIAL -- (IBM Confidential Restricted when
# combined with the aggregated modules for this product)
#                  SOURCE MATERIALS
# (C) COPYRIGHT International Business Machines Corp. 1988, 1994
# All Rights Reserved
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#

.include <${MAKETOP}bos/kernel/Kernel.mk>

ILIST		= kernex.exp syscalls.exp lowsys.exp tracecalls.exp \
			sockets.exp statcmd.exp threads.exp
IDIR		= /usr/lib/

.include <${RULES_MK}>


