# @(#)65        1.1  src/bos/usr/include/IN/Makefile, Makefiles, bos411, 9428A410j 8/5/92 16:17:02
# COMPONENT_NAME:
#
# FUNCTIONS:
#
# ORIGINS: 10,27
#
# IBM CONFIDENTIAL -- (IBM Confidential Restricted when
# combined with the aggregated modules for this product)
#                  SOURCE MATERIALS
# (C) COPYRIGHT International Business Machines Corp. 1988, 1989
# All Rights Reserved
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#

IDIR		= /usr/include/IN/

DATAFILES	= \
	AFdefs.h	\
	ARdefs.h	\
	CSdefs.h	\
	DRdefs.h	\
	ERdefs.h        \
	FSdefs.h        \
	FSio.h          \
	LSdefs.h        \
	MSdefs.h        \
	PCdefs.h        \
	PFdefs.h        \
	SGdefs.h        \
	backend.h       \
	q.h             \
	standard.h      \
	stfile.h        \
	uparm.h

INCLUDES	= ${DATAFILES}

ILIST		= ${DATAFILES}

.include <${RULES_MK}>
