# @(#)62        1.1  src/bos/usr/lpp/cnls/Makefile, ils-zh_CN, bos41B, 9504A 12/20/94 10:29:56
#
# COMPONENT_NAME:  ILS-ZH_CN
#
# FUNCTIONS:
#
# ORIGINS: 27
#
# IBM CONFIDENTIAL -- (IBM Confidential Restricted when
# combined with the aggregated modules for this product)
#                  SOURCE MATERIALS
# (C) COPYRIGHT International Business Machines Corp. 1994
# All Rights Reserved
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#

SUBDIRS         = bin dict fonts

.include <${RULES_MK}>
