/* @(#)96  1.2  src/bos/kernext/x25/x25user.st, sysxx25, bos411, 9428A410j 6/15/90 18:52:43 */
/* COMPONENT_NAME: (SYSXX25) X.25 Device Handler Interface
 *
 * FUNCTIONS:
 *
 * ORIGINS: 27
 *
 * (C) COPYRIGHT International Business Machines Corp. 1989
 * All Rights Reserved
 * Licensed Materials - Property of IBM
 *
 * US Government Users Restricted Rights - Use, duplication or
 * disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
 */

#ifndef _H_X25USER
#define _H_X25USER

#include <sys/comio.h>


