# @(#)10        1.19  src/bos/usr/lib/nls/loc/swkbd/Makefile, lftdd, bos41J, 9520A_all 5/10/95 14:07:54
#
#   COMPONENT_NAME: LFTDD
#
#   FUNCTIONS: Makefile
#
#   ORIGINS: 27
#
# IBM CONFIDENTIAL -- (IBM Confidential Restricted when
# combined with the aggregated modules for this product)
#                  SOURCE MATERIALS
# (C) COPYRIGHT International Business Machines Corp. 1993,1994
# All Rights Reserved
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#


#-----------------------------------------------------------------------#
# * files are object files that are compiled in this directory from
# source code in the clone tree and then executed to create the swkb.
#-----------------------------------------------------------------------#

PROGRAMS = \
	usa belgium canada denmark england france      \
	germany iceland italy Ja_JP netherlands norway \
	portugal spain sweden swfrench swgerman fr5080 \
	fs5080 it5080 uk5080 en_US ja_JP fr_BE fr_CF   \
	da_DK en_UK fr_FR gr_GR is_IS it_IT nl_NL      \
	tk_TK tr_TR gk_GK no_NO po_PO sp_SP sv_SV      \
	fr_SW gr_SW fr_FR@5080 fr_SW@5080 it_IT@5080   \
	cs_CZ sk_SK sl_SI sh_SP hu_HU pl_PL sr_SP      \
	ru101 ru102 bg101 bg102 hr_HR ro_RO mk_MK      \
	en_UK@5080 ko_KR zh_TW zh_CN ZH_CN arab israel \
	iw_IL iw_IL@alt pt_BR Ja_JP@alt ja_JP@alt      \
        es_LA Es_LA
        

Ja_JP_ilist	= Ja_JP.IBM-932.lftkeymap
Ja_JP@alt_ilist	= Ja_JP.IBM-932@alt.lftkeymap
arab_ilist	= Ar_AA.IBM-1046.lftkeymap \
		  Ar_AA.IBM-1046@alt.lftkeymap \
		  ar_AA.ISO8859-6.lftkeymap \
		  ar_AA.ISO8859-6@alt.lftkeymap
belgium_ilist	= Fr_BE.IBM-850.lftkeymap \
		  Nl_BE.IBM-850.lftkeymap \
		  De_BE.IBM-850.lftkeymap
bg101_ilist	= bg_BG.ISO8859-5@alt.lftkeymap
bg102_ilist	= bg_BG.ISO8859-5.lftkeymap
canada_ilist	= Fr_CA.IBM-850.lftkeymap
cs_CZ_ilist	= cs_CZ.ISO8859-2.lftkeymap
da_DK_ilist	= da_DK.ISO8859-1.lftkeymap
denmark_ilist	= Da_DK.IBM-850.lftkeymap
en_UK_ilist	= en_GB.ISO8859-1@alt.lftkeymap
en_UK@5080_ilist= en_GB.ISO8859-1.lftkeymap
en_US_ilist	= en_US.ISO8859-1.lftkeymap \
		  C.lftkeymap
england_ilist	= En_GB.IBM-850@alt.lftkeymap
es_LA_ilist	= es_LA.ISO8859-1.lftkeymap
Es_LA_ilist	= Es_LA.IBM-850.lftkeymap
fr5080_ilist	= Fr_FR.IBM-850@alt.lftkeymap
fr_BE_ilist	= fr_BE.ISO8859-1.lftkeymap \
		  de_BE.ISO8859-1.lftkeymap \
		  nl_BE.ISO8859-1.lftkeymap
fr_CF_ilist	= fr_CA.ISO8859-1.lftkeymap
fr_FR_ilist	= fr_FR.ISO8859-1.lftkeymap
fr_FR@5080_ilist= fr_FR.ISO8859-1@alt.lftkeymap
fr_SW_ilist	= fr_CH.ISO8859-1.lftkeymap
fr_SW@5080_ilist= fi_FI.ISO8859-1@alt.lftkeymap \
		  sv_SE.ISO8859-1@alt.lftkeymap
france_ilist	= Fr_FR.IBM-850.lftkeymap
fs5080_ilist	= Fi_FI.IBM-850@alt.lftkeymap \
		  Sv_SE.IBM-850@alt.lftkeymap
germany_ilist	= De_DE.IBM-850.lftkeymap
gk_GK_ilist	= el_GR.ISO8859-7.lftkeymap
gr_GR_ilist	= de_DE.ISO8859-1.lftkeymap
gr_SW_ilist	= de_CH.ISO8859-1.lftkeymap
hr_HR_ilist	= hr_HR.ISO8859-2.lftkeymap
hu_HU_ilist	= hu_HU.ISO8859-2.lftkeymap
iceland_ilist	= Is_IS.IBM-850.lftkeymap
is_IS_ilist	= is_IS.ISO8859-1.lftkeymap
israel_ilist	= Iw_IL.IBM-856.lftkeymap
it5080_ilist	= It_IT.IBM-850@alt.lftkeymap
it_IT_ilist	= it_IT.ISO8859-1.lftkeymap
it_IT@5080_ilist= it_IT.ISO8859-1@alt.lftkeymap
italy_ilist	= It_IT.IBM-850.lftkeymap
iw_IL_ilist	= iw_IL.ISO8859-8.lftkeymap
iw_IL@alt_ilist	= iw_IL.ISO8859-8@alt.lftkeymap \
		  Iw_IL.IBM-856@alt.lftkeymap
ja_JP_ilist	= ja_JP.IBM-eucJP.lftkeymap
ja_JP@alt_ilist	= ja_JP.IBM-eucJP@alt.lftkeymap
ko_KR_ilist	= ko_KR.IBM-eucKR.lftkeymap
mk_MK_ilist	= mk_MK.ISO8859-5.lftkeymap
netherlands_ilist=Nl_NL.IBM-850.lftkeymap
nl_NL_ilist	= nl_NL.ISO8859-1.lftkeymap
no_NO_ilist	= no_NO.ISO8859-1.lftkeymap
norway_ilist	= No_NO.IBM-850.lftkeymap
pl_PL_ilist	= pl_PL.ISO8859-2.lftkeymap
po_PO_ilist	= pt_PT.ISO8859-1.lftkeymap
portugal_ilist	= Pt_PT.IBM-850.lftkeymap
pt_BR_ilist	= pt_BR.ISO8859-1.lftkeymap
ro_RO_ilist	= ro_RO.ISO8859-2.lftkeymap
ru101_ilist	= ru_RU.ISO8859-5.lftkeymap
ru102_ilist	= ru_RU.ISO8859-5@alt.lftkeymap
sh_SP_ilist	= sh_SP.ISO8859-2.lftkeymap
sk_SK_ilist	= sk_SK.ISO8859-2.lftkeymap
sl_SI_ilist	= sl_SI.ISO8859-2.lftkeymap
sp_SP_ilist	= es_ES.ISO8859-1.lftkeymap
spain_ilist	= Es_ES.IBM-850.lftkeymap
sr_SP_ilist	= sr_SP.ISO8859-5.lftkeymap
sv_SV_ilist	= sv_SE.ISO8859-1.lftkeymap \
		  fi_FI.ISO8859-1.lftkeymap
sweden_ilist	= Sv_SE.IBM-850.lftkeymap \
		  Fi_FI.IBM-850.lftkeymap
swfrench_ilist	= Fr_CH.IBM-850.lftkeymap
swgerman_ilist	= De_CH.IBM-850.lftkeymap
tk_TK_ilist	= tr_TR.ISO8859-9.lftkeymap
tr_TR_ilist	= tr_TR.ISO8859-9@alt.lftkeymap
uk5080_ilist	= En_GB.IBM-850.lftkeymap
usa_ilist	= En_US.IBM-850.lftkeymap
zh_TW_ilist	= zh_TW.IBM-eucTW.lftkeymap
zh_CN_ilist     = zh_CN.IBM-eucCN.lftkeymap
ZH_CN_ilist     = ZH_CN.UTF-8.lftkeymap

IDIR		= /usr/lib/nls/loc/
ILIST		:= ${PROGRAMS:@PGM@${${PGM}_ilist}@}

#-----------------------------------------------------------------------#
# Dependency line is lftcode.h, lft_swkbd.h in this directory and the .c files
# in the clone tree.  The .c files are NOT copied into this directory.
# The commands translate to:
#    cc -o usa (clone tree)/sysx/lft/swkb/usa.c -I .
#    chmod 777 usa
#    usa
#-----------------------------------------------------------------------#

INCFLAGS	=-I${MAKETOP}bos/kernext/lft/inc -I${MAKETOP}bos/kernel/sys
CARGS		= -Z/

OTHERS		= ${PROGRAMS:@PGM@${PGM}_executed@}

${ILIST}:
	[ -f ${.TARGET} ] || ${TOUCH} ${.TARGET}

${PROGRAMS:@PGM@${PGM}_executed@}: $${.TARGET:S!_executed!!} $${$${.TARGET:S!_executed!_ilist!}}
	${RM} -f ${.TARGET} ${${.TARGET:S!_executed!_ilist!}}
	${CHMOD} 755 ${.TARGET:S!_executed!!}
	./${.TARGET:S!_executed!!}
	${TOUCH} ${.TARGET}

.include <${RULES_MK}>
