# @(#)71        1.1  src/bos/usr/include/arpa/Makefile, Makefiles, bos411, 9428A410j 8/5/92 16:17:44
# COMPONENT_NAME:
#
# FUNCTIONS:
#
# ORIGINS: 10,27
#
# IBM CONFIDENTIAL -- (IBM Confidential Restricted when
# combined with the aggregated modules for this product)
#                  SOURCE MATERIALS
# (C) COPYRIGHT International Business Machines Corp. 1988, 1989
# All Rights Reserved
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#

IDIR		= /usr/include/arpa/

DATAFILES 	= \
	ftp.h      \
	inet.h      \
	nameser.h      \
	telnet.h      \
	tftp.h

INCLUDES	= ${DATAFILES}

ILIST		= ${DATAFILES}

.include <${RULES_MK}>
