# @(#)16        1.1  src/bldenv/dspcat/Makefile, ade_build, bos412, GOLDA411a 8/18/93 15:20:34
# COMPONENT_NAME:
#
# FUNCTIONS:
#
# ORIGINS: 27
#
# IBM CONFIDENTIAL -- (IBM Confidential Restricted when
# combined with the aggregated modules for this product)
#                  SOURCE MATERIALS
# (C) COPYRIGHT International Business Machines Corp. 1988, 1989
# All Rights Reserved
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#

VPATH		= ${MAKETOP}/bos/usr/bin/gencat:${MAKETOP}/bos/usr/bin/dspcat

PROGRAMS	= dspcat
MSGHDRS		= msgfac_msg.h
CATFILES	= msgfac.cat
HFILES		= ${MSGHDRS}

ILIST		= dspcat
IDIR		= /usr/bin/

INCFLAGS	=-I${MAKETOP}/bos/usr/bin/gencat

.include <${RULES_MK}>
