# @(#)46        1.3  src/bldenv/xargs/Makefile, ade_build, bos412, GOLDA411a 4/12/94 11:12:13
# COMPONENT_NAME:
#
# FUNCTIONS:
#
# ORIGINS: 27
#
# IBM CONFIDENTIAL -- (IBM Confidential Restricted when
# combined with the aggregated modules for this product)
#                  SOURCE MATERIALS
# (C) COPYRIGHT International Business Machines Corp. 1988, 1994
# All Rights Reserved
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#

VPATH           = ${MAKETOP}/bos/usr/bin/xargs
PROGRAMS	= xargs
MSGHDRS		= xargs_msg.h
CATFILES	= xargs.cat
HFILES		= ${MSGHDRS}

ILIST		= xargs
IDIR		= /usr/bin/


.include <${RULES_MK}>

CFLAGS		= -D_BLD
