# @(#)99        1.1  src/bos/usr/lib/boot/srvboot/Makefile, bosboot, bos411, 9428A410j 10/6/93 14:21:30
#
# COMPONENT_NAME: (BOSBOOT)
#
# FUNCTIONS: service boot script
#	     This script configures the console and
#	     brings up dump menu and/or diagnostics 
#	     menu.
#
# ORIGINS: 27
#
# IBM CONFIDENTIAL -- (IBM Confidential Restricted when
# combined with the aggregated modules for this product)
#                  SOURCE MATERIALS
# (C) COPYRIGHT International Business Machines Corp. 1988, 1989
# All Rights Reserved
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#

SCRIPTS		= srvboot

CATFILES	= srvboot.cat

ILIST		= ${SCRIPTS}

IDIR		= /usr/lib/boot/

.include <${RULES_MK}>

srvboot:	srvboot.cat
