# @(#)98        1.2  src/bos/usr/lpp/jls/defaults/Makefile, libKJI, bos411, 9428A410j 3/16/94 10:59:14
#
# COMPONENT_NAME: (libKJI) Japanese Input Method
#
# FUNCTIONS: default jimrc file
#
# ORIGINS: 27
#
# IBM CONFIDENTIAL -- (IBM Confidential Restricted when
# combined with the aggregated modules for this product)
#                  SOURCE MATERIALS
# (C) COPYRIGHT International Business Machines Corp. 1989, 1991, 1993
# All Rights Reserved
# Licensed Materials - Property of IBM
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#

DATAFILES	= jimrc

ILIST		= ${DATAFILES}
IDIR		= /usr/lpp/jls/defaults/
NOUPDATE_LIST   = /usr/lpp/jls/defaults/jimrc

.include <${RULES_MK}>
