# @(#)78	1.3  src/bldenv/cmp/Makefile, ade_build, bos412, GOLDA411a 1/10/94 15:51:28
#
# COMPONENT_NAME: bosbuild
#
# FUNCTIONS:
#
# ORIGINS: 27
#
# IBM CONFIDENTIAL -- (IBM Confidential Restricted when
# combined with the aggregated modules for this product)
#                  SOURCE MATERIALS
# (C) COPYRIGHT International Business Machines Corp. 1992
# All Rights Reserved
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#

PROGRAMS	= cmp

CFLAGS		=-UMSG -D_BLD -D_${TARGET_MACHINE}

ILIST		=${PROGRAMS}
IDIR		=/usr/bin/

.include <${RULES_MK}>
