# @(#)03        1.1  src/bos/usr/lib/methods/ucfgent/Makefile, sysxent, bos411, 9428A410j 3/17/94 15:37:38
# COMPONENT_NAME: SYSXENT
#
# FUNCTIONS:
#
# ORIGINS: 27
#
# IBM CONFIDENTIAL -- (IBM Confidential Restricted when
# combined with the aggregated modules for this product)
#                  SOURCE MATERIALS
# (C) COPYRIGHT International Business Machines Corp. 1994
# All Rights Reserved
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#

VPATH           = ../ucfgcommo

PROGRAMS        = ucfgent

OFILES          = ucfgcommo.o ucfglanwe.o

INCFLAGS        = -I../common -I../cfgcie

ILIST           = ucfgent
IDIR		= /usr/lib/methods/

LIBS		= -ls -lodm -lcfg -lrts

.include <${RULES_MK}>
