# @(#)11        1.3  src/bos/etc/rc.powerfail/Makefile, cmdoper, bos411, 9428A410j 3/17/93 16:28:28
#
# COMPONENT_NAME: CMDOPER
#
# FUNCTIONS:
#
# ORIGINS: 27
#
# IBM CONFIDENTIAL -- (IBM Confidential Restricted when
# combined with the aggregated modules for this product)
#                  SOURCE MATERIALS
# (C) COPYRIGHT International Business Machines Corp. 1993.
# All Rights Reserved
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#

SCRIPTS		= rc.powerfail

CATFILES	= rc_powerfail.cat

ILIST		= ${SCRIPTS}
IDIR		= /etc/

.include <${RULES_MK}>
