# @(#)40	1.1  src/bos/usr/lib/nls/bidi/app-defaults/iw_IL/Makefile, bos, bos410 8/27/93 09:45:23
#
#   COMPONENT_NAME: CFGNLS
#
#   FUNCTIONS: 
#
#   ORIGINS: 27
#
#   IBM CONFIDENTIAL -- (IBM Confidential Restricted when
#   combined with the aggregated modules for this product)
#                    SOURCE MATERIALS
#
#   (C) COPYRIGHT International Business Machines Corp. 1993
#   All Rights Reserved
#   US Government Users Restricted Rights - Use, duplication or
#   disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#



ILIST		= BTerm
 
IDIR		= /usr/lib/nls/bidi/iw_IL/app-defaults/


.include <${RULES_MK}>
