# @(#)48	1.2  src/bos/diag/tu/ethsal/Makefile, tu_ethsal, bos411, 9428A410j 1/7/94 13:58:21
#
#   COMPONENT_NAME: TU_ETHSAL
#
#   FUNCTIONS: 
#
#   ORIGINS: 27
#
#   IBM CONFIDENTIAL -- (IBM Confidential Restricted when
#   combined with the aggregated modules for this product)
#                    SOURCE MATERIALS
#
#   (C) COPYRIGHT International Business Machines Corp. 1992, 1994
#   All Rights Reserved
#   US Government Users Restricted Rights - Use, duplication or
#   disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#


#-------------------------------------------------------------------------#
#                                                                         #
#     This Makefile builds the library libethsaltu.a for the DA application #
#                                                                         #
#-------------------------------------------------------------------------#

LIBRARIES       =   libethsaltu.a

EXPLIB_TARGETS  =   export_libethsaltu.a
EXPDIR          =   /usr/lib/

OFILES		= config.o crcgen.o ethmisc.o exectu.o iotu.o selftest.o  \
			postu.o vpdtu.o wraptu.o

.include <${RULES_MK}>
