# @(#)03	1.3  src/bos/usr/lib/piosk/predef/Makefile, cmdpiosk, bos411, 9428A410j 4/7/94 20:29:18
#
#   COMPONENT_NAME: CMDPIOSK
#
#   FUNCTIONS: 
#
#   ORIGINS: 27
#
#   IBM CONFIDENTIAL -- (IBM Confidential Restricted when
#   combined with the aggregated modules for this product)
#                    SOURCE MATERIALS
#
#   (C) COPYRIGHT International Business Machines Corp. 1993, 1994
#   All Rights Reserved
#   US Government Users Restricted Rights - Use, duplication or
#   disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#

SCRIPTS = ibm4019.kji ibm4029.kji \
ibm4208-502.asc ibm4208-502.kji ibm4216-510.kji ibm5327.kji \
ibm5572.asc ibm5572.kji ibm5573.asc ibm5573.kji ibm5575.asc ibm5575.kji \
ibm5577.asc ibm5577.kji ibm5579.asc ibm5579.kji \
ibm5584.asc ibm5584.kji ibm5585.asc ibm5585.kji \
ibm5587.asc ibm5587.kji ibm5587H.asc ibm5587H.kji ibm5589.asc ibm5589.kji \
canlbp.lips2+ canlbp.lips3 canlbp-B406G.lips2+ canlbp-B406G.lips3 \
canlbp-A404PS.kps oki801ps.kps

IDIR = /usr/lib/lpd/pio/predef/
ILIST = ${SCRIPTS}

.include <${RULES_MK}>
