# @(#)23	1.1  src/bos/usr/lib/netls/ark/Makefile, bos, bos410 3/1/93 10:33:12
# COMPONENT_NAME:  libnetls
#
# FUNCTIONS:
#
# ORIGINS: 27
#
# IBM CONFIDENTIAL -- (IBM Confidential Restricted when
# combined with the aggregated modules for this product)
#                  SOURCE MATERIALS
# (C) COPYRIGHT International Business Machines Corp. 1988, 1992
# All Rights Reserved
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#

ILIST		= i18necho i18ninq
IDIR		= /usr/lib/netls/ark/ils/

.include <${RULES_MK}>

