# @(#)45        1.3  src/bldenv/lockname/Makefile, ade_build, bos412, GOLDA411a 6/2/94 14:12:00
#
#   COMPONENT_NAME: ade_build 
#
#   FUNCTIONS:
#
#   ORIGINS: 27 
#
#   IBM CONFIDENTIAL -- (IBM Confidential Restricted when
#   combined with the aggregated modules for this product)
#                    SOURCE MATERIALS
#
#   (C) COPYRIGHT International Business Machines Corp. 1993
#   All Rights Reserved
#   US Government Users Restricted Rights - Use, duplication or
#   disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#

SCRIPTS		= namedb2h

ILIST		= ${SCRIPTS}
IDIR		= /usr/bin/

.include <${RULES_MK}>
