# @(#)00        1.2  src/bos/usr/ccs/lib/liby/Makefile, liby, bos411, 9428A410j 1/20/93 15:48:19
# COMPONENT_NAME:
#
# FUNCTIONS:
#
# ORIGINS: 27
#
# IBM CONFIDENTIAL -- (IBM Confidential Restricted when
# combined with the aggregated modules for this product)
#                  SOURCE MATERIALS
# (C) COPYRIGHT International Business Machines Corp. 1988, 1989
# All Rights Reserved
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#



LIBRARIES	= liby.a
MSGHDRS         =
CATFILES        =
HFILES          = ${MSGHDRS}

EXPLIB_TARGETS  = export_liby.a

ILIST           = liby.a
IDIR            = /usr/ccs/lib/

OFILES		= libmai.o libzer.o c_libzer.o

.include <${RULES_MK}>
