# @(#)13        1.1  src/bos/usr/lib/lpd/plotlbe/Makefile, Makefiles, bos411, 9428A410j 9/14/92 08:16:18
# COMPONENT_NAME:
#
# FUNCTIONS:
#
# ORIGINS: 27
#
# IBM CONFIDENTIAL -- (IBM Confidential Restricted when
# combined with the aggregated modules for this product)
#                  SOURCE MATERIALS
# (C) COPYRIGHT International Business Machines Corp. 1988, 1989
# All Rights Reserved
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#

PROGRAMS	= plotlbe

OFILES		= plot_msg.o plot_org.o plotbkl.o

LIBS		= -lqb

ILIST		= plotlbe
IDIR		= /usr/lib/lpd/

.include <${RULES_MK}>
