# @(#)31	1.3  src/bos/usr/lpp/Unicode/X11/nls/Makefile, cfgnls, bos411, 9428A410j 4/11/94 08:27:12
#
#   COMPONENT_NAME: CFGNLS
#
#   FUNCTIONS: none
#
#   ORIGINS: 27
#
#   IBM CONFIDENTIAL -- (IBM Confidential Restricted when
#   combined with the aggregated modules for this product)
#                    SOURCE MATERIALS
#
#   (C) COPYRIGHT International Business Machines Corp. 1994
#   All Rights Reserved
#   US Government Users Restricted Rights - Use, duplication or
#   disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#

ILIST		= UTF-8

IDIR		= /usr/lpp/Unicode/X11/nls/

.include <${RULES_MK}>
