# @(#)16        1.2  src/bos/usr/lib/learn/morefiles/Makefile, cmdlearn, bos411, 9428A410j 1/15/93 13:13:46
# COMPONENT_NAME:
#
# FUNCTIONS:
#
# ORIGINS: 27
#
# IBM CONFIDENTIAL -- (IBM Confidential Restricted when
# combined with the aggregated modules for this product)
#                  SOURCE MATERIALS
# (C) COPYRIGHT International Business Machines Corp. 1988, 1989
# All Rights Reserved
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#

DATAFILES	= L0 L0.1a L0.1b L0.1c L0.1d L0.1e L0.1f L0.1g \
		  L1.1a L1.1b L1.1c L1.1d L2.1a L2.1b L2.1c \
		  L2.1d L2.1e L2.1f L3.1a L3.1b L3.1c L3.1d \
		  L3.1e L3.1f L3.1g L4.1a L4.1b L4.1c L4.1d \
		  L4.1e L4.1f L4.1g L4.2a L5.1a L5.1b L5.1c \
		  L5.1d L5.1e L6.1a L6.1b L6.1c L6.1d L6.1e \
		  L6.2e L7.1a

ILIST		= ${DATAFILES}
IDIR		= /usr/share/lib/learn/morefiles/


.include <${RULES_MK}>
