# @(#)25        1.2  src/bos/usr/lib/netls/ark/X11/app-defaults/Makefile, bos, bos410 5/21/93 08:46:11
# COMPONENT_NAME:  libnetls
#
# FUNCTIONS:
#
# ORIGINS: 27
#
# IBM CONFIDENTIAL -- (IBM Confidential Restricted when
# combined with the aggregated modules for this product)
#                  SOURCE MATERIALS
# (C) COPYRIGHT International Business Machines Corp. 1988, 1992
# All Rights Reserved
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#

ILIST		= XLs_Admin XLs_Stat
IDIR		= /usr/lib/netls/ark/X11/app-defaults/

.include <${RULES_MK}>

