# @(#)73        1.2  src/bos/usr/include/jfs/Makefile, Makefiles, bos41J, 145887.bos 3/3/95 09:29:17
# COMPONENT_NAME:
#
# FUNCTIONS:
#
# ORIGINS: 10,27
#
# IBM CONFIDENTIAL -- (IBM Confidential Restricted when
# combined with the aggregated modules for this product)
#                  SOURCE MATERIALS
# (C) COPYRIGHT International Business Machines Corp. 1988, 1995
# All Rights Reserved
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#

IDIR		= /usr/include/jfs/

DATAFILES	= \
	dir.h           \
	filsys.h        \
	fsdefs.h        \
	fsvar.h         \
	genalloc.h      \
	ino.h           \
	ilogx.h		\
	fsparam.h       \
	inode.h         \
	jfsmount.h      \
	quota.h

INCLUDES	= ${DATAFILES} commit.h log.h

ILIST		= ${DATAFILES}

.include <${RULES_MK}>
