# @(#)03        1.1  src/bos/usr/lbin/diffh/Makefile, cmdfiles, bos411, 9428A410j 8/5/92 16:55:54
# COMPONENT_NAME:
#
# FUNCTIONS:
#
# ORIGINS: 27
#
# IBM CONFIDENTIAL -- (IBM Confidential Restricted when
# combined with the aggregated modules for this product)
#                  SOURCE MATERIALS
# (C) COPYRIGHT International Business Machines Corp. 1988, 1989
# All Rights Reserved
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#

VPATH		= ${MAKETOP}/bos/usr/bin/diff

PROGRAMS	= diffh
MSGHDRS		= diff_msg.h
CATFILES	= diff.cat
HFILES		= ${MSGHDRS}

ILIST		= diffh
IDIR		= /usr/lbin/


.include <${RULES_MK}>
