# @(#)96        1.1  src/bldenv/xlC/include/arpa/Makefile, ade_build, bos41J, 9509A_all 2/27/95 12:43:30
#
#   COMPONENT_NAME: ade_build
#
#   FUNCTIONS: none
#
#   ORIGINS: 27
#
#
#   (C) COPYRIGHT International Business Machines Corp. 1995
#   All Rights Reserved
#   Licensed Materials - Property of IBM
#   US Government Users Restricted Rights - Use, duplication or
#   disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#

VPATH = ${MAKETOP}/xlC/usr/lpp/xlC/include/arpa

INCLUDES        = \
		ftp.h       inet.h      nameser.h   telnet.h    tftp.h

EXPDIR  = /usr/lpp/xlC/include/arpa/

.include <${RULES_MK}>
