# @(#)66        1.2  src/bldenv/gos/desktop/dthelp/Makefile, desktop, bos412, GOLDA411a 3/3/94 22:20:33
#
#   COMPONENT_NAME: ade_build
#
#   FUNCTIONS: none
#
#   ORIGINS: 27
#
#
#   (C) COPYRIGHT International Business Machines Corp. 1993
#   All Rights Reserved
#   Licensed Materials - Property of IBM
#   US Government Users Restricted Rights - Use, duplication or
#   disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#

EXPLIB_SUBDIRS	= util util2

SUBDIRS		= util util2 build build2 eltdef eltdef2 helpcomp parser

.include <${RULES_MK}>
