# @(#) 34 1.1 src/bos/usr/lpp/bosinst/Animate/Makefile, bosinst, bos411, 9428A410j 6/30/93 16:57:04
# COMPONENT_NAME: bosinst
#
# FUNCTIONS: Makefile for Animate
#
# ORIGINS: 27
#
# IBM CONFIDENTIAL -- (IBM Confidential Restricted when
# combined with the aggregated modules for this product)
#                  SOURCE MATERIALS
# (C) COPYRIGHT International Business Machines Corp. 1993
# All Rights Reserved
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#

PROGRAMS	= Animate

ILIST		= ${PROGRAMS}
IDIR		= /usr/lpp/bosinst/

.include <${RULES_MK}>
