# @(#)31       1.1  src/bldenv/what/Makefile, bldprocess, bos412, GOLDA411a 10/8/93 20:52:18 
#
#   COMPONENT_NAME: BLDPROCESS
#
#   FUNCTIONS:
#
#   ORIGINS: 27
#
#   IBM CONFIDENTIAL -- (IBM Confidential Restricted when
#   combined with the aggregated modules for this product)
#                    SOURCE MATERIALS
#
#   (C) COPYRIGHT International Business Machines Corp. 1993
#   All Rights Reserved
#   US Government Users Restricted Rights - Use, duplication or
#   disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#


VPATH		= ${MAKETOP}/bos/usr/bin/sccs
INCFLAGS	= -I${MAKETOP}/bos/usr/bin/sccs

MSGHDRS         = cm_msg.h co_msg.h
HFILES          = ${MSGHDRS}
PROGRAMS	= what

LIBS		= -lPW

ILIST		= ${PROGRAMS}
IDIR		= /usr/bin/

.include <${RULES_MK}>
