# @(#)80        1.2  src/bos/usr/include/rpc/Makefile, Makefiles, bos411, 9428A410j 10/25/93 20:48:57
# COMPONENT_NAME:
#
# FUNCTIONS:
#
# ORIGINS: 10,27
#
# IBM CONFIDENTIAL -- (IBM Confidential Restricted when
# combined with the aggregated modules for this product)
#                  SOURCE MATERIALS
# (C) COPYRIGHT International Business Machines Corp. 1988, 1989
# All Rights Reserved
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#

IDIR		= /usr/include/rpc/

DATAFILES	= \
	auth.h          \
	auth_des.h      \
	auth_unix.h     \
	clnt.h          \
	key_prot.h      \
	pmap_clnt.h     \
	pmap_prot.h     \
	pmap_rmt.h      \
	raw.h		\
	rpc.h           \
	rpc_msg.h       \
	svc.h           \
	svc_auth.h      \
	types.h         \
	xdr.h

INCLUDES	= ${DATAFILES}

ILIST		= ${DATAFILES}

.include <${RULES_MK}>
