# @(#)04        1.1  src/bldenv/errlg/msg/Makefile, cmderrlg, bos412, GOLDA411a 2/17/93 08:00:27
#
#   COMPONENT_NAME: BOSBUILD
#
#   FUNCTIONS:
#
#   ORIGINS: 27
#
#   IBM CONFIDENTIAL -- (IBM Confidential Restricted when
#   combined with the aggregated modules for this product)
#                    SOURCE MATERIALS
#
#   (C) COPYRIGHT International Business Machines Corp. 1993
#   All Rights Reserved
#   US Government Users Restricted Rights - Use, duplication or
#   disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#

VPATH		= ${MAKETOP}/bos/usr/bin/errlg/msg

MSGHDRS		= cmderrlg_msg.h
CATFILES	= cmderrlg.cat
OTHERS		= ${MSGHDRS}

INCLUDES	= cmderrlg_msg.h
EXPDIR		= /usr/include/

.include <${RULES_MK}>
