# @(#)16	1.2  src/bos/usr/include/graphics/rby/Makefile, rcmrby, bos411, 9428A410j 5/3/94 09:27:24
#
#   COMPONENT_NAME: rcmrby
#
#   FUNCTIONS: none
#
#   ORIGINS: 27
#
#
#   (C) COPYRIGHT International Business Machines Corp. 1994
#   All Rights Reserved
#   Licensed Materials - Property of IBM
#   US Government Users Restricted Rights - Use, duplication or
#   disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#
VPATH           = ${MAKETOP}bos/kernext/disp/rby/rby

EXPDIR		= /usr/include/rby/
IDIR		= /usr/include/rby/

DATAFILES        = lmalloc.h mbopcode.h pcfaops.h rby.h \
        rby_ddf.h rby_event.h rby_mmap.h rby_structs.h \
        rbyrcmce.h rbytext.h sq_defs.h textstru.h timestamp.h \
        utflags.h utmsg.h

INCLUDES	= ${DATAFILES} 

.include <${RULES_MK}>
