# @(#)60	1.1  src/bos/usr/lpp/bosinst/db/choices.S, bosinst, bos411, 9428A410j 11/15/89 08:50:25
#
# COMPONENT_NAME: (BOSINST) Base Operating System Installation
#
# FUNCTIONS: 
#
# ORIGINS: 27
#
# (C) COPYRIGHT International Business Machines Corp. 1989
# All Rights Reserved
# Licensed Materials - Property of IBM
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#
/usr/lpp/bosinst/images/*/*
