# @(#)71        1.2  src/bos/usr/lpp/bosinst/db/Makefile, bosinst, bos411, 9428A410j 12/21/93 10:51:02
# COMPONENT_NAME:   bosinst
#
# FUNCTIONS:
#
# ORIGINS: 27
#
# IBM CONFIDENTIAL -- (IBM Confidential Restricted when
# combined with the aggregated modules for this product)
#                  SOURCE MATERIALS
# (C) COPYRIGHT International Business Machines Corp. 1988, 1989
# All Rights Reserved
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#

SCRIPTS         = choices
DATAFILES       = class.sample default.client sample.client

ILIST           = choices class.sample default.client sample.client
IDIR            = /usr/lpp/bosinst/db/

.include <${RULES_MK}>
