# @(#)34	1.3  src/bos/diag/tu/siosl/Makefile, tu_siosl, bos411, 9428A410j 4/13/94 12:46:42
#
#   COMPONENT_NAME: TU_SIOSL
#
#   FUNCTIONS: 
#
#   ORIGINS: 27
#
#   IBM CONFIDENTIAL -- (IBM Confidential Restricted when
#   combined with the aggregated modules for this product)
#                    SOURCE MATERIALS
#
#   (C) COPYRIGHT International Business Machines Corp. 1993, 1994
#   All Rights Reserved
#   US Government Users Restricted Rights - Use, duplication or
#   disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#

SUBDIRS			=	kbda

EXPLIB_SUBDIRS		= 	mousea kbda kbddev tableta tabletdev

.include <${RULES_MK}>
