# @(#)38	1.4  src/bos/diag/tu/iop/Makefile, tu_iop, bos41J, 9513A_all 3/9/95 09:01:43
#
#   COMPONENT_NAME: TU_IOP
#
#   FUNCTIONS: 
#
#   ORIGINS: 27, 83
#
#
#   (C) COPYRIGHT International Business Machines Corp. 1989,1995
#   All Rights Reserved
#   Licensed Materials - Property of IBM
#   US Government Users Restricted Rights - Use, duplication or
#   disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#
#   LEVEL 1, 5 Years Bull Confidential Information
#

CFLAGS= -DSEMAPHORE_CODE 

LIBRARIES = libioptu.a
EXPLIB_TARGETS  = export_libioptu.a
EXPDIR = /usr/lib/
ILIST =

OFILES = ioptu.o \
	       tod_funcs.o \
	       sem.o \
	       ioptu_01.o \
	       ioptu_02.o \
	       ioptu_04.o \
	       ioptu_05.o \
	       ioptu_06.o \
	       ioptu_08.o \
	       ioptu_09.o \
	       ioptu_10.o \
	       ioptu_11.o \
	       ioptu_12.o \
	       ioptu_13.o \
	       ioptu_16.o \
	       ioptu_17.o \
	       ioptu_20.o \
	       todtest101.o \
	       todtest102.o \
	       todtest103.o \
	       todtest104.o \
	       todtest105.o \
	       todtest106.o \
	       todtest107.o \
	       todtest108.o \
	       todtest109.o \
	       todtest110.o \
	       todtest111.o \
	       todtest112.o \
	       todtest113.o \
	       todtest114.o

.include <${RULES_MK}>
