/* @(#)68	1.1  src/bos/usr/ccs/lib/libodm/odmhkids.h, libodm, bos411, 9428A410j 12/15/89 10:06:29 */
#define ODMHKWD_ADDR_CLXN           0x1
#define ODMHKWD_ADD_VCHAR           0x2
#define ODMHKWD_BREAKCRIT           0x3
#define ODMHKWD_CHANGE_VCHAR        0x4
#define ODMHKWD_CLOSE_CLXN          0x5
#define ODMHKWD_CMPKMCH             0x6
#define ODMHKWD_CREATE_CLXN         0x7
#define ODMHKWD_DESTROY_CLXN        0x8
#define ODMHKWD_GET_OFFSETS         0x9
#define ODMHKWD_GET_STRING_DBOFF    0xA
#define ODMHKWD_GET_VCHAR           0xB
#define ODMHKWD_INIT_CLASS          0xC
#define ODMHKWD_INIT_CLXN           0xD
#define ODMHKWD_INVOKE              0xE
#define ODMHKWD_MOUNT_CLXN          0xF
#define ODMHKWD_NOTE_CLASS          0x10
#define ODMHKWD_ODM_ADD_OBJ         0x11
#define ODMHKWD_ODM_CHANGE_OBJ      0x12
#define ODMHKWD_ODM_CLOSE_CLASS     0x13
#define ODMHKWD_ODM_CREATE_CLASS    0x14
#define ODMHKWD_ODM_FREE_LIST       0x15
#define ODMHKWD_ODM_GET_BY_ID       0x16
#define ODMHKWD_ODM_GET_FIRST       0x17
#define ODMHKWD_ODM_GET_LIST        0x18
#define ODMHKWD_ODM_GET_NEXT        0x19
#define ODMHKWD_ODM_GET_OBJ         0x1A
#define ODMHKWD_ODM_INITIALIZE      0x1B
#define ODMHKWD_ODM_MOUNT_CLASS     0x1C
#define ODMHKWD_ODM_OPEN_CLASS      0x1D
#define ODMHKWD_ODM_RM_BY_ID        0x1E
#define ODMHKWD_ODM_RM_CLASS        0x1F
#define ODMHKWD_ODM_RM_OBJ          0x20
#define ODMHKWD_ODM_SET_PATH        0x21
#define ODMHKWD_ODM_SET_PERMS       0x22
#define ODMHKWD_ODM_TERMINATE       0x23
#define ODMHKWD_OPEN_CLXNP          0x24
#define ODMHKWD_RAW_ADDR_CLASS      0x25
#define ODMHKWD_RAW_ADD_OBJ         0x26
#define ODMHKWD_RAW_ADD_STR         0x27
#define ODMHKWD_RAW_CLOSE_CLASS     0x28
#define ODMHKWD_RAW_CLOSE_CLXN      0x29
#define ODMHKWD_RAW_FIND_BYID       0x2A
#define ODMHKWD_RAW_FIND_OBJ        0x2B
#define ODMHKWD_RAW_RM_OBJ          0x2C
#define ODMHKWD_VERIFY_CLASS_STRUCTURE 0x2D
