# @(#)80        1.1  src/bldenv/dspmsg/Makefile, ade_build, bos412, GOLDA411a 3/3/93 11:28:50
#
#   COMPONENT_NAME: BOSBUILD
#
#   FUNCTIONS: 
#
#   ORIGINS: 27
#
#   IBM CONFIDENTIAL -- (IBM Confidential Restricted when
#   combined with the aggregated modules for this product)
#                    SOURCE MATERIALS
#
#   (C) COPYRIGHT International Business Machines Corp. 1993
#   All Rights Reserved
#   US Government Users Restricted Rights - Use, duplication or
#   disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#

VPATH		= ${MAKETOP}/bos/usr/bin/dspmsg:${MAKETOP}/bos/usr/bin/gencat

PROGRAMS	= dspmsg
MSGHDRS		= msgfac_msg.h
CATFILES	= msgfac.cat
HFILES		= ${MSGHDRS}

ILIST		= dspmsg
IDIR		= /usr/bin/

INCFLAGS	=-I${MAKETOP}/bos/usr/bin/gencat


.include <${RULES_MK}>
