# @(#)98       1.2  src/bldenv/wc/Makefile, bldprocess, bos412, GOLDA411a 8/4/93 17:25:06 
#
#   COMPONENT_NAME: BOSBUILD
#
#   FUNCTIONS:
#
#   ORIGINS: 27
#
#   IBM CONFIDENTIAL -- (IBM Confidential Restricted when
#   combined with the aggregated modules for this product)
#                    SOURCE MATERIALS
#
#   (C) COPYRIGHT International Business Machines Corp. 1993
#   All Rights Reserved
#   US Government Users Restricted Rights - Use, duplication or
#   disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#

VPATH		= ${MAKETOP}/bos/usr/bin/wc

PROGRAMS	= wc 
MSGHDRS		= wc_msg.h
CATFILES	= wc.cat
HFILES		= ${MSGHDRS}

ILIST		= wc 
IDIR		= /usr/bin/

.include <${RULES_MK}>

