# @(#)19	1.3  src/bos/usr/lib/methods/cfgtablet/Makefile, inputdd, bos41J, 9509A_all 2/14/95 13:11:18
# COMPONENT_NAME: INPUTDD
#
# FUNCTIONS: N/A
#
# ORIGINS: 27
#
# IBM CONFIDENTIAL -- (IBM Confidential Restricted when
# combined with the aggregated modules for this product)
#                  SOURCE MATERIALS
# (C) COPYRIGHT International Business Machines Corp. 1993, 1995
# All Rights Reserved
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#

ILIST       = cfgtablet
IDIR        = /usr/lib/methods/

SCRIPTS		= cfgtablet

.include <${RULES_MK}>
