# @(#)42	1.1  src/bos/usr/lib/netls/ark/include/Makefile, bos, bos410 3/1/93 10:55:12
# COMPONENT_NAME:  libnetls
#
# FUNCTIONS:
#
# ORIGINS: 27
#
# IBM CONFIDENTIAL -- (IBM Confidential Restricted when
# combined with the aggregated modules for this product)
#                  SOURCE MATERIALS
# (C) COPYRIGHT International Business Machines Corp. 1988, 1992
# All Rights Reserved
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#

ILIST		= log.h
IDIR		= /usr/lib/netls/ark/include/

.include <${RULES_MK}>

