# @(#)07        1.2  src/bos/usr/ccs/lib/lib450/Makefile, libt450, bos411, 9428A410j 9/1/92 19:19:26
# COMPONENT_NAME:
#
# FUNCTIONS:
#
# ORIGINS: 27
#
# IBM CONFIDENTIAL -- (IBM Confidential Restricted when
# combined with the aggregated modules for this product)
#                  SOURCE MATERIALS
# (C) COPYRIGHT International Business Machines Corp. 1988, 1989
# All Rights Reserved
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#



LIBRARIES	= lib450.a
MSGHDRS         =
CATFILES        =
HFILES          = ${MSGHDRS}

EXPLIB_TARGETS  = export_lib450.a

ILIST           = lib450.a
IDIR            = /usr/lib/

OFILES		= \
	arc.o box.o circle.o close.o dot.o erase.o \
	label.o line.o linmod.o move.o open.o point.o \
	space.o subr.o

.include <${RULES_MK}>
