# @(#)46	1.1  src/bldenv/fgrep/Makefile, ade_build, bos412, GOLDA411a 10/29/93 15:29:32
#
#   COMPONENT_NAME: BOSBUILD
#
#   FUNCTIONS:
#
#   ORIGINS: 27
#
#   IBM CONFIDENTIAL -- (IBM Confidential Restricted when
#   combined with the aggregated modules for this product)
#                    SOURCE MATERIALS
#
#   (C) COPYRIGHT International Business Machines Corp. 1993
#   All Rights Reserved
#   US Government Users Restricted Rights - Use, duplication or
#   disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#

VPATH		= ${MAKETOP}/bos/usr/bin/grep

PROGRAMS	= fgrep
OFILES		= grep.o
MSGHDRS		= grep_msg.h
CATFILES	= grep.cat
HFILES		= ${MSGHDRS}

ILIST		= fgrep
IDIR		= /usr/bin/

.include <${RULES_MK}>
