# @(#)64        1.1  src/bos/usr/lib/methods/ucfgfdd/Makefile, cfgmethods, bos411, 9428A410j 6/27/94 18:57:52
# COMPONENT_NAME: CFGMETHODS
#
# FUNCTIONS:
#
# ORIGINS: 27
#
# IBM CONFIDENTIAL -- (IBM Confidential Restricted when
# combined with the aggregated modules for this product)
#                  SOURCE MATERIALS
# (C) COPYRIGHT International Business Machines Corp. 1988, 1994
# All Rights Reserved
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#

VPATH		= ../ucfgdevice

PROGRAMS	= ucfgfdd

INCFLAGS	= -I../common

OFILES		= ucfgdevice.o ucfg_parent_dvdr.o ucfg_gen.o

ILIST		= ucfgfdd

IDIR		= /usr/lib/methods/

LIBS		= -ls -lodm -lcfg -lrts

.include <${RULES_MK}>
