# @(#)97	1.3  src/bos/usr/lib/piostw/predef/Makefile, cmdpiostw, bos411, 9428A410j 7/21/93 01:34:37
#
#   COMPONENT_NAME: CMDPIOSTW
#
#   FUNCTIONS: 
#
#   ORIGINS: 27
#
#   IBM CONFIDENTIAL -- (IBM Confidential Restricted when
#   combined with the aggregated modules for this product)
#                    SOURCE MATERIALS
#
#   (C) COPYRIGHT International Business Machines Corp. 1993
#   All Rights Reserved
#   US Government Users Restricted Rights - Use, duplication or
#   disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#

DATAFILES = ibm5575.cht  ibm5577.cht  ibm5585.cht

IDIR = /usr/lib/lpd/pio/predef/
ILIST = ${DATAFILES}

.include <${RULES_MK}>
