# @(#)20	1.19  src/bos/diag/util/Makefile, cmddiag, bos41J, 9512A_all 3/14/95 10:19:50
# COMPONENT_NAME: CMDDIAG
#
# FUNCTIONS:
#
# ORIGINS: 27, 83
#
# IBM CONFIDENTIAL -- (IBM Confidential Restricted when
# combined with the aggregated modules for this product)
#                  SOURCE MATERIALS
# (C) COPYRIGHT International Business Machines Corp. 1992, 1995
# All Rights Reserved
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#
# LEVEL 1, 5 Years Bull Confidential Information

# ubump ump added (feature 82273)

# Added u5081 in defect 123574

# added ukey in defect 152247

SUBDIRS		= ucfgdev ucfgvpd udiagup udtl ufd \
		  umblist umkdskt umlc uscsi ulan udsense uhint ush ueth \
		  uformat ump ubump u5081 udiagmon ukey ugmcode ubackup \
		  udiskenh u7135 udisacfg
.include <${RULES_MK}>
