# @(#)16        1.10  src/bldenv/includes/sys/Makefile, ade_build, bos412, GOLDA411a 10/18/93 09:21:37
#
#   COMPONENT_NAME: BOSBUILD
#
#   FUNCTIONS:
#
#   ORIGINS: 27
#
#   IBM CONFIDENTIAL -- (IBM Confidential Restricted when
#   combined with the aggregated modules for this product)
#                    SOURCE MATERIALS
#
#   (C) COPYRIGHT International Business Machines Corp. 1993
#   All Rights Reserved
#   US Government Users Restricted Rights - Use, duplication or
#   disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#

VPATH		= ${MAKETOP}/bos/kernel/sys:${MAKETOP}/bos/kernel/sys/${TARGET_MACHINE}:${MAKETOP}/bos/usr/include/sys

INCLUDES	= asdef.s ramdd.h comlink.m4 vmdisk.h fscntl.h statfs.h \
		  stat.h systemcfg.h bootrecord.h debug.h rasprobe.h \
		  sstbl.h

EXPDIR		= /usr/include/sys/

.include <${RULES_MK}>
