# @(#)90        1.1  src/bos/usr/lib/nls/loc/jim/jdict/Makefile, libKJI, bos411, 9428A410j 1/20/93 10:57:29
#
# COMPONENT_NAME: libKJI
#
# FUNCTIONS: Japanese Input Method
#
# ORIGINS: 27
#
# IBM CONFIDENTIAL -- (IBM Confidential Restricted when
# combined with the aggregated modules for this product)
#                  SOURCE MATERIALS
# (C) COPYRIGHT International Business Machines Corp. 1989, 1991, 1993
# All Rights Reserved
# Licensed Materials - Property of IBM
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#

LIBRARIES	= libjdict.a

DEBUG		=

OFILES		= jdicts.o

.include <${RULES_MK}>
