#
# @(#) 15 1.11.2.4  src/bldenv/bldtools/rename/lpp_pack_dir.S, bldprocess, bos412, GOLDA411a 8/18/93 17:48:41
#
# COMPONENT_NAME: (BLDPROCESS) BAI Build Process
#
# FUNCTIONS: n/a
#
# ORIGINS: 27
#
# (C) COPYRIGHT International Business Machines Corp. 1989,1993
# All Rights Reserved
# Licensed Materials - Property of IBM
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#
# NAME:          lpp_pack_dir
#
# PURPOSE:       specifies packaging directories for orbit releases
#
# OPTIONS:       n/a
#
# ARGUMENTS:     n/a
#
# FUNCTIONS:     n/a
#
##############################################################################
#
# 3.2.0/3.2.2 entries
#
# sna320
sna	/CHANCE/snaserv/3.2/src/nls/instl/build	snaserv320
snamDe_DE	/CHANCE/snaserv/3.2/src/nls/mri/De_DE	snaserv320
snamEn_US	/CHANCE/snaserv/3.2/src/nls/mri/En_US	snaserv320
snamEs_ES	/CHANCE/snaserv/3.2/src/nls/mri/Es_ES	snaserv320
snamFr_FR	/CHANCE/snaserv/3.2/src/nls/mri/Fr_FR	snaserv320
snamIt_IT	/CHANCE/snaserv/3.2/src/nls/mri/It_IT	snaserv320
snamJa_JP	/CHANCE/snaserv/3.2/src/nls/mri/Ja_JP	snaserv320
snamNl_BE	/CHANCE/snaserv/3.2/src/nls/mri/Nl_BE	snaserv320
snamSv_SE	/CHANCE/snaserv/3.2/src/nls/mri/Sv_SE	snaserv320
# aic322
aic	/CHANCE/aic/3.2.2/src/nls/aic	aic322
aicmEn_US	/CHANCE/aic/3.2.2/src/nls/aicmEn_US	aic322
aicmNl_BE	/CHANCE/aic/3.2.2/src/nls/aicmNl_BE	aic322
aicmFr_FR	/CHANCE/aic/3.2.2/src/nls/aicmFr_FR	aic322
aicmEs_ES	/CHANCE/aic/3.2.2/src/nls/aicmEs_ES	aic322
aicmJa_JP	/CHANCE/aic/3.2.2/src/nls/aicmJa_JP	aic322
aicmko_KR	/CHANCE/aic/3.2.2/src/nls/aicmko_KR	aic322
aicmzh_TW	/CHANCE/aic/3.2.2/src/nls/aicmzh_TW	aic322
#
# 3.2.4 entries
#
# aic324
aic12	/CHANCE/aic/3.2.4/src/nls/aic	aic324
aic12mEn_US	/CHANCE/aic/3.2.4/src/nls/aicmEn_US	aic324
aic12mNl_BE	/CHANCE/aic/3.2.4/src/nls/aicmNl_BE	aic324
aic12mFr_FR	/CHANCE/aic/3.2.4/src/nls/aicmFr_FR	aic324
aic12mEs_ES	/CHANCE/aic/3.2.4/src/nls/aicmEs_ES	aic324
aic12mJa_JP	/CHANCE/aic/3.2.4/src/nls/aicmJa_JP	aic324
aic12mko_KR	/CHANCE/aic/3.2.4/src/nls/aicmko_KR	aic324
aic12mzh_TW	/CHANCE/aic/3.2.4/src/nls/aicmzh_TW	aic324
# blkmux324
blkmux	/CHANCE/blkmux/3.2.4/src/nls/370pinst	blkmux324
# cmdtext324
txtfmt	/EVERS/cmdtext/3.2.4/src/nls/txtfmt	cmdtext324
# des324
des	/NOLANRYAN/des/3.2.4/src/nls/DES	des324
# em78324
em78	/CHANCE/em78/3.2.4/src/nls/lpp	em78324
em78mEn_US	/CHANCE/em78/3.2.4/src/nls/En_US	em78324
em78mEs_ES	/CHANCE/em78/3.2.4/src/nls/Es_ES	em78324
em78mFr_BE	/CHANCE/em78/3.2.4/src/nls/Fr_BE	em78324
em78mFr_CA	/CHANCE/em78/3.2.4/src/nls/Fr_CA	em78324
em78mFr_FR	/CHANCE/em78/3.2.4/src/nls/Fr_FR	em78324
em78mIt_IT	/CHANCE/em78/3.2.4/src/nls/It_IT	em78324
em78mJa_JP	/CHANCE/em78/3.2.4/src/nls/Ja_JP	em78324
em78mNl_BE	/CHANCE/em78/3.2.4/src/nls/Nl_BE	em78324
em78mNl_NL	/CHANCE/em78/3.2.4/src/nls/Nl_NL	em78324
em78mSv_SE	/CHANCE/em78/3.2.4/src/nls/Sv_SE	em78324
em78mDe_DE	/CHANCE/em78/3.2.4/src/nls/De_DE	em78324
# hanfs324
hanfs	/CHANCE/hanfs/3.2.4/src/nls/hanfs	hanfs324
# icraft324
icraft	/EVERS/icraft/3.2.4/src/nls/icraft	icraft324
# netware324
netware	/EVERS/netware/3.2.4/src/nls/netware	netware324
# ntwkmgmt324
netmgr	/CHANCE/ntwkmgmt/3.2.4/src/nls/netmgr	ntwkmgmt324
# pcsim324
pcsim	/EVERS/pcsim/3.2.4/src/nls/pcsim.obj	pcsim324
pcsimmDe_DE	/EVERS/pcsim/3.2.4/src/nls/mri/pcsimmDe_DE	pcsim324
pcsimmEn_US	/EVERS/pcsim/3.2.4/src/nls/mri/pcsimmEn_US	pcsim324
pcsimmEs_ES	/EVERS/pcsim/3.2.4/src/nls/mri/pcsimmEs_ES	pcsim324
pcsimmFr_FR	/EVERS/pcsim/3.2.4/src/nls/mri/pcsimmFr_FR	pcsim324
pcsimmIt_IT	/EVERS/pcsim/3.2.4/src/nls/mri/pcsimmIt_IT	pcsim324
pcsimmJa_JP	/EVERS/pcsim/3.2.4/src/nls/mri/pcsimmJa_JP	pcsim324
pcsimmNl_BE	/EVERS/pcsim/3.2.4/src/nls/mri/pcsimmNl_BE	pcsim324
pcsimmNo_NO	/EVERS/pcsim/3.2.4/src/nls/mri/pcsimmNo_NO	pcsim324
# tenplus324
INed	/EVERS/tenplus/3.2.4/src/nls/INed	tenplus324
# xmgr324
x_st_mgr	/EVERS/xmgr/3.2.4/src/nls/installp	xmgr324
x_st_mgrmDe_DE	/EVERS/xmgr/3.2.4/src/nls/mri/De_DE	xmgr324
x_st_mgrmEn_US	/EVERS/xmgr/3.2.4/src/nls/mri/En_US	xmgr324
x_st_mgrmEs_ES	/EVERS/xmgr/3.2.4/src/nls/mri/Es_ES	xmgr324
x_st_mgrmFr_FR	/EVERS/xmgr/3.2.4/src/nls/mri/Fr_FR	xmgr324
x_st_mgrmIt_IT	/EVERS/xmgr/3.2.4/src/nls/mri/It_IT	xmgr324
x_st_mgrmJa_JP	/EVERS/xmgr/3.2.4/src/nls/mri/Ja_JP	xmgr324
x_st_mgrmNl_BE	/EVERS/xmgr/3.2.4/src/nls/mri/Nl_BE	xmgr324
x_st_mgrmNo_NO	/EVERS/xmgr/3.2.4/src/nls/mri/No_NO	xmgr324
x_st_mgrmSv_SE	/EVERS/xmgr/3.2.4/src/nls/mri/Sv_SE	xmgr324
#
# 3.2.5 entries
#
# bitternut325
cns	/CHANCE/cns/3.2.5/src/nls/ts/install	bitternut325
ntx	/CHANCE/ntx/3.2.5/src/nls/adapter/install	bitternut325
# bos325
bos	/NOLANRYAN/bos/3.2.5/src/nls/bosrun	bos325
bosadt	/NOLANRYAN/bos/3.2.5/src/nls/bosadt	bos325
bosext1	/NOLANRYAN/bos/3.2.5/src/nls/bosext1	bos325
bosext2	/NOLANRYAN/bos/3.2.5/src/nls/bosext2	bos325
bsl	/NOLANRYAN/bos/3.2.5/src/nls/bsl	bos325
dcepthreads	/NOLANRYAN/bos/3.2.5/src/nls/dcepthreads	bos325
# bosnet325
bosnet	/CHANCE/bosnet/3.2.5/src/nls/bosnet	bosnet325
# dsmit325
dsmit_server	/CHANCE/dsmit/3.2.5/src/nls/pkgdsmit/dsmit_server	dsmit325
dsmit_aix	/CHANCE/dsmit/3.2.5/src/nls/pkgdsmit/dsmit_aix	dsmit325
dsmit_hp	/CHANCE/dsmit/3.2.5/src/nls/pkgdsmit/dsmit_hp	dsmit325
dsmit_sun	/CHANCE/dsmit/3.2.5/src/nls/pkgdsmit/dsmit_sun	dsmit325
dsmitmEn_US	/CHANCE/dsmit/3.2.5/src/nls/En_US	dsmit325
# fddi325
fddi	/CHANCE/fddi/3.2.5/src/nls/fddiinst	fddi325
# gos325
X11_3d	/EVERS/gos/3.2.5/src/nls/X11_3d	gos325
X11dev	/EVERS/gos/3.2.5/src/nls/X11dev	gos325
X11fnt	/EVERS/gos/3.2.5/src/nls/X11fnt	gos325
X11mDe_DE	/EVERS/gos/3.2.5/src/nls/MRI/X11mDe_DE	gos325
X11mEn_US	/EVERS/gos/3.2.5/src/nls/MRI/X11mEn_US	gos325
X11mEs_ES	/EVERS/gos/3.2.5/src/nls/MRI/X11mEs_ES	gos325
X11mFr_FR	/EVERS/gos/3.2.5/src/nls/MRI/X11mFr_FR	gos325
X11mIt_IT	/EVERS/gos/3.2.5/src/nls/MRI/X11mIt_IT	gos325
X11mJa_JP	/EVERS/gos/3.2.5/src/nls/MRI/X11mJa_JP	gos325
X11mNl_BE	/EVERS/gos/3.2.5/src/nls/MRI/X11mNl_BE	gos325
X11mNo_NO	/EVERS/gos/3.2.5/src/nls/MRI/X11mNo_NO	gos325
X11mSv_SE	/EVERS/gos/3.2.5/src/nls/MRI/X11mSv_SE	gos325
X11mko_KR	/EVERS/gos/3.2.5/src/nls/MRI/X11mKo_KR	gos325
X11mzh_TW	/EVERS/gos/3.2.5/src/nls/MRI/X11mZh_TW	gos325
X11rte	/EVERS/gos/3.2.5/src/nls/X11rte	gos325
# hcon325
hcon	/CHANCE/hcon/3.2.5/src/nls/whpinstl	hcon325
hconmDe_DE	/CHANCE/hcon/3.2.5/src/nls/De_DE	hcon325
hconmEn_US	/CHANCE/hcon/3.2.5/src/nls/En_US	hcon325
hconmEs_ES	/CHANCE/hcon/3.2.5/src/nls/Es_ES	hcon325
hconmFr_FR	/CHANCE/hcon/3.2.5/src/nls/Fr_FR	hcon325
hconmIt_IT	/CHANCE/hcon/3.2.5/src/nls/It_IT	hcon325
hconmJa_JP	/CHANCE/hcon/3.2.5/src/nls/Ja_JP	hcon325
hconmNl_BE	/CHANCE/hcon/3.2.5/src/nls/Nl_BE	hcon325
hconmSv_SE	/CHANCE/hcon/3.2.5/src/nls/Sv_SE	hcon325
# lz1325
xpres	/EVERS/lz1/3.2.5/src/nls/lz1inst	lz1325
# package325
bsmDe_DE	/NOLANRYAN/package/3.2.5/src/nls/bsmmri/bsmDe_DE	package325
bsmEn_US	/NOLANRYAN/package/3.2.5/src/nls/bsmmri/bsmEn_US	package325
bsmEs_ES	/NOLANRYAN/package/3.2.5/src/nls/bsmmri/bsmEs_ES	package325
bsmFr_FR	/NOLANRYAN/package/3.2.5/src/nls/bsmmri/bsmFr_FR	package325
bsmIt_IT	/NOLANRYAN/package/3.2.5/src/nls/bsmmri/bsmIt_IT	package325
bsmJa_JP	/NOLANRYAN/package/3.2.5/src/nls/bsmmri/bsmJa_JP	package325
bsmNl_BE	/NOLANRYAN/package/3.2.5/src/nls/bsmmri/bsmNl_BE	package325
bsmNo_NO	/NOLANRYAN/package/3.2.5/src/nls/bsmmri/bsmNo_NO	package325
bsmSv_SE	/NOLANRYAN/package/3.2.5/src/nls/bsmmri/bsmSv_SE	package325
# perf325
perfagent	/EVERS/perf/3.2.5/src/nls/perfagent/install	perf325
perfmgr	/EVERS/perf/3.2.5/src/nls/perfmgr/install	perf325
# r5gos325
X11rteR5	/CHANCE/r5gos/3.2.5/src/nls/X11rteR5	r5gos325
X11fntR5	/CHANCE/r5gos/3.2.5/src/nls/X11fntR5	r5gos325
X11mEn_USR5	/CHANCE/r5gos/3.2.5/src/nls/MRI/X11mEn_USR5	r5gos325
X11devR5	/CHANCE/r5gos/3.2.5/src/nls/X11devR5	r5gos325
# r5xmgr324
x_st_mgrR5	/CHANCE/r5xmgr/3.2.5/src/nls/installp	r5xmgr325
#
# End of lpp_pack_dir.
#
