# @(#)78        1.1  src/bldenv/libc_r/Makefile, ade_build, bos412, GOLDA411a 4/18/94 16:46:48
#
#   COMPONENT_NAME: ADE_BUILD
#
#   FUNCTIONS: none
#
#   ORIGINS: 27
#
#   IBM CONFIDENTIAL -- (IBM Confidential Restricted when
#   combined with the aggregated modules for this product)
#                    SOURCE MATERIALS
#
#   (C) COPYRIGHT International Business Machines Corp. 1993
#   All Rights Reserved
#   US Government Users Restricted Rights - Use, duplication or
#   disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#

THREAD_SAFE=yes

.include "${MAKETOP}/bldenv/libc/Makefile"
