# @(#)94	1.7  src/bos/diag/Makefile, cmddiag, bos411, 9428A410j 4/5/94 17:52:44
# COMPONENT_NAME: CMDDIAG
#
# FUNCTIONS:
#
# ORIGINS: 27
#
# IBM CONFIDENTIAL -- (IBM Confidential Restricted when
# combined with the aggregated modules for this product)
#                  SOURCE MATERIALS
# (C) COPYRIGHT International Business Machines Corp. 1992, 1994
# All Rights Reserved
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#

EXPLIB_SUBDIRS	= tu

EXPINC_SUBDIRS	= diags
SUBDIRS		= diags dctrl diagrpt dutil lscfg sysx tu da util boot

.include <${RULES_MK}>
