# @(#)39	1.2  src/bos/diag/tu/iopsl/Makefile, tu_iopsl, bos411, 9428A410j 1/7/94 13:08:40
#
#   COMPONENT_NAME: TU_IOPSL
#
#   FUNCTIONS: 
#
#   ORIGINS: 27
#
#   IBM CONFIDENTIAL -- (IBM Confidential Restricted when
#   combined with the aggregated modules for this product)
#                    SOURCE MATERIALS
#
#   (C) COPYRIGHT International Business Machines Corp. 1992, 1994
#   All Rights Reserved
#   US Government Users Restricted Rights - Use, duplication or
#   disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#

#--------------------------------------------------------------------------#
#                                                                          #
#     This Makefile builds the library libiopsltu.a for the DA application #
#                                                                          #
#--------------------------------------------------------------------------#

LIBRARIES       =   libiopsltu.a

EXPLIB_TARGETS  =   export_libiopsltu.a
EXPDIR          =   /usr/lib/

OFILES		= 	iop.o batterytu.o crcgen.o misc.o todtu.o vpdtu.o

.include <${RULES_MK}>
