# @(#)92        1.1  src/bos/usr/lib/nls/loc/jim/jexm/Makefile, libKJI, bos411, 9428A410j 1/20/93 10:58:04
#
# COMPONENT_NAME: libKJI
#
# FUNCTIONS: Japanese Input Method
#
# ORIGINS: 27
#
# IBM CONFIDENTIAL -- (IBM Confidential Restricted when
# combined with the aggregated modules for this product)
#                  SOURCE MATERIALS
# (C) COPYRIGHT International Business Machines Corp. 1989, 1991, 1993
# All Rights Reserved
# Licensed Materials - Property of IBM
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#

LIBRARIES	= libjexm.a

DEBUG		=

OFILES		= kjopen.o \
			kjterm.o \
			kjinit.o \
			kjclos.o \
			kjinpr.o \
			kjclr.o \
			kjcrst.o \
			confirm.o \
			simage.o \
			m1funcs.o \
			m2cmpmv.o \
			rs.o \
			ktoan.o \
			rkcutil.o \
			other.o \
			misc.o

.include <${RULES_MK}>
