# @(#)53	1.2  src/bldenv/pkgtools/common/Makefile, pkgtools, bos412, GOLDA411a 4/15/94 11:35:48
#
#   COMPONENT_NAME: PKGTOOLS
#
#   FUNCTIONS: 
#
#   ORIGINS: 27
#
#   IBM CONFIDENTIAL -- (IBM Confidential Restricted when
#   combined with the aggregated modules for this product)
#                    SOURCE MATERIALS
#
#   (C) COPYRIGHT International Business Machines Corp. 1992,1993
#   All Rights Reserved
#   US Government Users Restricted Rights - Use, duplication or
#   disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#

OBJECTS = util.o vrmf.o processPtfmsg.o

.include <${RULES_MK}>
