#
# dependents of __bbl_efc6_post_i.o:
__bbl_efc6_post_i.o: ${MAKETOP}../export/power/usr/include/stdio.h
__bbl_efc6_post_i.o: ${MAKETOP}../export/power/usr/include/standards.h
__bbl_efc6_post_i.o: ${MAKETOP}../export/power/usr/include/va_list.h
__bbl_efc6_post_i.o: ${MAKETOP}../export/power/usr/include/sys/types.h
__bbl_efc6_post_i.o: ${MAKETOP}../export/power/usr/include/sys/m_types.h
__bbl_efc6_post_i.o: ${MAKETOP}../export/power/usr/include/sys/limits.h
__bbl_efc6_post_i.o: ${MAKETOP}../export/power/usr/include/float.h
__bbl_efc6_post_i.o: ${MAKETOP}../export/power/usr/include/sys/cfgodm.h
__bbl_efc6_post_i.o: ${MAKETOP}../export/power/usr/include/odmi.h
__bbl_efc6_post_i.o: ${MAKETOP}../export/power/usr/include/sys/dir.h
__bbl_efc6_post_i.o: ${MAKETOP}../export/power/usr/include/sys/lkup.h
__bbl_efc6_post_i.o: ${MAKETOP}../export/power/usr/include/limits.h
__bbl_efc6_post_i.o: ${MAKETOP}../export/power/usr/include/cf.h
#
# dependents of bbl_cfg_load.o:
bbl_cfg_load.o: ${MAKETOP}../export/power/usr/include/stdio.h
bbl_cfg_load.o: ${MAKETOP}../export/power/usr/include/standards.h
bbl_cfg_load.o: ${MAKETOP}../export/power/usr/include/va_list.h
bbl_cfg_load.o: ${MAKETOP}../export/power/usr/include/sys/types.h
bbl_cfg_load.o: ${MAKETOP}../export/power/usr/include/sys/m_types.h
bbl_cfg_load.o: ${MAKETOP}../export/power/usr/include/sys/limits.h
bbl_cfg_load.o: ${MAKETOP}../export/power/usr/include/float.h
bbl_cfg_load.o: ${MAKETOP}../export/power/usr/include/sys/errno.h
bbl_cfg_load.o: ${MAKETOP}../export/power/usr/include/sys/sysconfig.h
bbl_cfg_load.o: ${MAKETOP}../export/power/usr/include/sys/lockl.h
bbl_cfg_load.o: ${MAKETOP}../export/power/usr/include/sys/lock_def.h
bbl_cfg_load.o: ${MAKETOP}../export/power/usr/include/errno.h
bbl_cfg_load.o: ${MAKETOP}../export/power/usr/include/cf.h
bbl_cfg_load.o: ${MAKETOP}bos/usr/lib/methods/common/cfgdebug.h
bbl_cfg_load.o: ${MAKETOP}../export/power/usr/include/sys/aixfont.h
bbl_cfg_load.o: ${MAKETOP}../export/power/usr/include/sys/dir.h
bbl_cfg_load.o: ${MAKETOP}../export/power/usr/include/sys/lkup.h
bbl_cfg_load.o: ${MAKETOP}../export/power/usr/include/limits.h
bbl_cfg_load.o: ${MAKETOP}../export/power/usr/include/sys/file.h
bbl_cfg_load.o: ${MAKETOP}../export/power/usr/include/sys/param.h
bbl_cfg_load.o: ${MAKETOP}../export/power/usr/include/sys/m_param.h
bbl_cfg_load.o: ${MAKETOP}../export/power/usr/include/jfs/fsparam.h
bbl_cfg_load.o: ${MAKETOP}../export/power/usr/include/sys/sysmacros.h
bbl_cfg_load.o: ${MAKETOP}../export/power/usr/include/sys/access.h
bbl_cfg_load.o: ${MAKETOP}../export/power/usr/include/sys/cred.h
bbl_cfg_load.o: ${MAKETOP}../export/power/usr/include/sys/priv.h
bbl_cfg_load.o: ${MAKETOP}../export/power/usr/include/sys/mode.h
bbl_cfg_load.o: ${MAKETOP}../export/power/usr/include/sys/tcb.h
bbl_cfg_load.o: ${MAKETOP}../export/power/usr/include/sys/pcl.h
bbl_cfg_load.o: ${MAKETOP}../export/power/usr/include/fcntl.h
bbl_cfg_load.o: ${MAKETOP}../export/power/usr/include/sys/flock.h
bbl_cfg_load.o: ${MAKETOP}../export/power/usr/include/unistd.h
bbl_cfg_load.o: ${MAKETOP}../export/power/usr/include/sys/lockf.h
bbl_cfg_load.o: ${MAKETOP}../export/power/usr/include/sys/stat.h
bbl_cfg_load.o: ${MAKETOP}../export/power/usr/include/sys/intr.h
bbl_cfg_load.o: ${MAKETOP}../export/power/usr/include/sys/m_intr.h
bbl_cfg_load.o: ${MAKETOP}../export/power/usr/include/vt.h
bbl_cfg_load.o: ${MAKETOP}../export/power/usr/include/sys/font.h
bbl_cfg_load.o: ${MAKETOP}../export/power/usr/include/cdd.h
bbl_cfg_load.o: ${MAKETOP}../export/power/usr/include/cdd_intr.h
bbl_cfg_load.o: ${MAKETOP}../export/power/usr/include/ccm.h
bbl_cfg_load.o: ${MAKETOP}bos/usr/lib/methods/graphics/cfg_graphics.h
bbl_cfg_load.o: ${MAKETOP}bos/usr/lib/methods/graphics/cfg_graphics_macros.h
#
# dependents of cfgbbl.o:
cfgbbl.o: ${MAKETOP}../export/power/usr/include/sys/types.h
cfgbbl.o: ${MAKETOP}../export/power/usr/include/standards.h
cfgbbl.o: ${MAKETOP}../export/power/usr/include/sys/m_types.h
cfgbbl.o: ${MAKETOP}../export/power/usr/include/stdio.h
cfgbbl.o: ${MAKETOP}../export/power/usr/include/va_list.h
cfgbbl.o: ${MAKETOP}../export/power/usr/include/sys/limits.h
cfgbbl.o: ${MAKETOP}../export/power/usr/include/float.h
cfgbbl.o: ${MAKETOP}../export/power/usr/include/fcntl.h
cfgbbl.o: ${MAKETOP}../export/power/usr/include/sys/flock.h
cfgbbl.o: ${MAKETOP}../export/power/usr/include/unistd.h
cfgbbl.o: ${MAKETOP}../export/power/usr/include/sys/access.h
cfgbbl.o: ${MAKETOP}../export/power/usr/include/sys/lockf.h
cfgbbl.o: ${MAKETOP}../export/power/usr/include/sys/stat.h
cfgbbl.o: ${MAKETOP}../export/power/usr/include/sys/mode.h
cfgbbl.o: ${MAKETOP}../export/power/usr/include/sys/sysconfig.h
cfgbbl.o: ${MAKETOP}../export/power/usr/include/sys/lockl.h
cfgbbl.o: ${MAKETOP}../export/power/usr/include/sys/lock_def.h
cfgbbl.o: ${MAKETOP}../export/power/usr/include/sys/device.h
cfgbbl.o: ${MAKETOP}../export/power/usr/include/sys/file.h
cfgbbl.o: ${MAKETOP}../export/power/usr/include/sys/param.h
cfgbbl.o: ${MAKETOP}../export/power/usr/include/sys/m_param.h
cfgbbl.o: ${MAKETOP}../export/power/usr/include/jfs/fsparam.h
cfgbbl.o: ${MAKETOP}../export/power/usr/include/sys/sysmacros.h
cfgbbl.o: ${MAKETOP}../export/power/usr/include/sys/cred.h
cfgbbl.o: ${MAKETOP}../export/power/usr/include/sys/priv.h
cfgbbl.o: ${MAKETOP}../export/power/usr/include/sys/tcb.h
cfgbbl.o: ${MAKETOP}../export/power/usr/include/sys/pcl.h
cfgbbl.o: ${MAKETOP}../export/power/usr/include/sys/intr.h
cfgbbl.o: ${MAKETOP}../export/power/usr/include/sys/m_intr.h
cfgbbl.o: ${MAKETOP}../export/power/usr/include/sys/low.h
cfgbbl.o: ${MAKETOP}../export/power/usr/include/sys/syspest.h
cfgbbl.o: ${MAKETOP}../export/power/usr/include/sys/errno.h
cfgbbl.o: ${MAKETOP}../export/power/usr/include/sys/systemcfg.h
cfgbbl.o: ${MAKETOP}../export/power/usr/include/sys/cfgodm.h
cfgbbl.o: ${MAKETOP}../export/power/usr/include/odmi.h
cfgbbl.o: ${MAKETOP}../export/power/usr/include/sys/dir.h
cfgbbl.o: ${MAKETOP}../export/power/usr/include/sys/lkup.h
cfgbbl.o: ${MAKETOP}../export/power/usr/include/limits.h
cfgbbl.o: ${MAKETOP}../export/power/usr/include/cf.h
cfgbbl.o: ${MAKETOP}bos/usr/lib/methods/common/cfgdebug.h
cfgbbl.o: ${MAKETOP}../export/power/usr/include/sys/ioctl.h
cfgbbl.o: ${MAKETOP}../export/power/usr/include/sys/ttychars.h
cfgbbl.o: ${MAKETOP}../export/power/usr/include/sys/ttydev.h
cfgbbl.o: ${MAKETOP}../export/power/usr/include/sys/devinfo.h
cfgbbl.o: ${MAKETOP}../export/power/usr/include/sys/mdio.h
cfgbbl.o: ${MAKETOP}../export/power/usr/include/sys/iplcb.h
cfgbbl.o: ${MAKETOP}../export/power/usr/include/sys/rosinfo.h
cfgbbl.o: ${MAKETOP}../export/power/usr/include/bbldds.h
#
# dependents of ddstools.o:
ddstools.o: ${MAKETOP}../export/power/usr/include/sys/sysmacros.h
ddstools.o: ${MAKETOP}../export/power/usr/include/sys/param.h
ddstools.o: ${MAKETOP}../export/power/usr/include/sys/m_param.h
ddstools.o: ${MAKETOP}../export/power/usr/include/sys/limits.h
ddstools.o: ${MAKETOP}../export/power/usr/include/standards.h
ddstools.o: ${MAKETOP}../export/power/usr/include/float.h
ddstools.o: ${MAKETOP}../export/power/usr/include/jfs/fsparam.h
ddstools.o: ${MAKETOP}../export/power/usr/include/sys/types.h
ddstools.o: ${MAKETOP}../export/power/usr/include/sys/m_types.h
ddstools.o: ${MAKETOP}../export/power/usr/include/sys/cfgodm.h
ddstools.o: ${MAKETOP}../export/power/usr/include/odmi.h
ddstools.o: ${MAKETOP}../export/power/usr/include/sys/dir.h
ddstools.o: ${MAKETOP}../export/power/usr/include/sys/lkup.h
ddstools.o: ${MAKETOP}../export/power/usr/include/limits.h
ddstools.o: ${MAKETOP}../export/power/usr/include/sys/cfgdb.h
ddstools.o: ${MAKETOP}../export/power/usr/include/cf.h
ddstools.o: ${MAKETOP}bos/usr/lib/methods/common/cfgdebug.h
ddstools.o: ${MAKETOP}../export/power/usr/include/stdio.h
ddstools.o: ${MAKETOP}../export/power/usr/include/va_list.h
ddstools.o: ${MAKETOP}../export/power/usr/include/strings.h
ddstools.o: ${MAKETOP}../export/power/usr/include/string.h
#
# dependents of iplcb_tools.o:
iplcb_tools.o: ${MAKETOP}../export/power/usr/include/sys/types.h
iplcb_tools.o: ${MAKETOP}../export/power/usr/include/standards.h
iplcb_tools.o: ${MAKETOP}../export/power/usr/include/sys/m_types.h
iplcb_tools.o: ${MAKETOP}../export/power/usr/include/stdio.h
iplcb_tools.o: ${MAKETOP}../export/power/usr/include/va_list.h
iplcb_tools.o: ${MAKETOP}../export/power/usr/include/sys/limits.h
iplcb_tools.o: ${MAKETOP}../export/power/usr/include/float.h
iplcb_tools.o: ${MAKETOP}bos/usr/lib/methods/common/cfgdebug.h
iplcb_tools.o: ${MAKETOP}../export/power/usr/include/sys/mdio.h
iplcb_tools.o: ${MAKETOP}../export/power/usr/include/sys/iplcb.h
iplcb_tools.o: ${MAKETOP}../export/power/usr/include/sys/rosinfo.h
