# @(#)59	1.4  src/bos/usr/lpp/Unicode/samples/Makefile, cfgnls, bos411, 9428A410j 4/13/94 10:07:05
#
#   COMPONENT_NAME: CFGNLS
#
#   FUNCTIONS: none
#
#   ORIGINS: 27
#
#   IBM CONFIDENTIAL -- (IBM Confidential Restricted when
#   combined with the aggregated modules for this product)
#                    SOURCE MATERIALS
#
#   (C) COPYRIGHT International Business Machines Corp. 1994
#   All Rights Reserved
#   US Government Users Restricted Rights - Use, duplication or
#   disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#

ILIST = utf8.txt
IDIR = /usr/lpp/Unicode/samples/

.include <${RULES_MK}>
