# @(#)79        1.4  src/bos/usr/lib/methods/graphics/Makefile, dispcfg, bos411, 9428A410j 5/31/94 14:45:24
#
# COMPONENT_NAME: (dispcfg)  Graphics Configuration Code 
#
# FUNCTIONS: Makefile
#
# ORIGINS: 27
#
# IBM CONFIDENTIAL -- (IBM Confidential Restricted when
# combined with the aggregated modules for this product)
#                  SOURCE MATERIALS
# (C) COPYRIGHT International Business Machines Corp. 1993
# All Rights Reserved
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#

EXPDIR          = /usr/include/

INCLUDES        = 	cfg_graphics.h \
					cfg_graphics_frs.h \
					cfg_graphics_macros.h \
					cfg_graphics_dd_cfg.h


IDIR			= /usr/include/

ILIST   	    = 	cfg_graphics.h \
					cfg_graphics_frs.h \
					cfg_graphics_macros.h \
					cfg_graphics_dd_cfg.h


.include <${RULES_MK}>
