# @(#)54        1.1  src/bldenv/mkram/Makefile, ade_build, bos412, GOLDA411a 2/17/93 08:55:56
#
#   COMPONENT_NAME: BOSBUILD
#
#   FUNCTIONS:
#
#   ORIGINS: 27
#
#   IBM CONFIDENTIAL -- (IBM Confidential Restricted when
#   combined with the aggregated modules for this product)
#                    SOURCE MATERIALS
#
#   (C) COPYRIGHT International Business Machines Corp. 1993
#   All Rights Reserved
#   US Government Users Restricted Rights - Use, duplication or
#   disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#

VPATH 		=${MAKETOP}/bos/usr/sbin/mkram:${MAKETOP}/bos/kernel/io

PROGRAMS	= mkram

OFILES		= mkram.o rampack.o

ILIST		= mkram
IDIR		= /usr/sbin/

.include <${RULES_MK}>
