# @(#)06        1.2  src/bldenv/errlg/raslib/Makefile, cmderrlg, bos412, GOLDA411a 3/25/93 08:22:21
#
#   COMPONENT_NAME: BOSBUILD
#
#   FUNCTIONS:
#
#   ORIGINS: 27
#
#   IBM CONFIDENTIAL -- (IBM Confidential Restricted when
#   combined with the aggregated modules for this product)
#                    SOURCE MATERIALS
#
#   (C) COPYRIGHT International Business Machines Corp. 1993
#   All Rights Reserved
#   US Government Users Restricted Rights - Use, duplication or
#   disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#
#err_rec.h_EXPDIR	= /usr/include/sys/
#erec.h_EXPDIR        = /usr/include/sys/

VPATH		= ${MAKETOP}/bos/usr/bin/errlg/raslib:${MAKETOP}/bos/kernel/sys




INCLUDES	= err_rec.h erec.h

EXPDIR		= /usr/include/sys/

.include <${RULES_MK}>

