# @(#)99        1.1  src/bldenv/ed/Makefile, ade_build, bos412, GOLDA411a 2/17/93 07:56:08
#
#   COMPONENT_NAME: BOSBUILD
#
#   FUNCTIONS:
#
#   ORIGINS: 27
#
#   IBM CONFIDENTIAL -- (IBM Confidential Restricted when
#   combined with the aggregated modules for this product)
#                    SOURCE MATERIALS
#
#   (C) COPYRIGHT International Business Machines Corp. 1993
#   All Rights Reserved
#   US Government Users Restricted Rights - Use, duplication or
#   disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#

VPATH		= ${MAKETOP}/bos/usr/bin/ed

PROGRAMS	= ed
MSGHDRS		= ed_msg.h
CATFILES	= ed.cat
HFILES		= ${MSGHDRS}

ILIST		= ed
IDIR		= /usr/bin/

LIBS		=  -lodm -lsrc -lcfg -lbsd

.include <${RULES_MK}>
