# @(#)63	1.2  src/bos/usr/ccs/lib/libtermcap/termcap.db/Makefile, libtermcap, bos411, 9428A410j 6/10/94 15:50:50
#
# COMPONENT_NAME: (LIBTERMCAP) termcap library
#
# FUNCTIONS: 
#
# ORIGINS: 27
#
# IBM CONFIDENTIAL -- (IBM Confidential Restricted when
# combined with the aggregated modules for this product)
#                  SOURCE MATERIALS
# (C) COPYRIGHT International Business Machines Corp. 1994
# All Rights Reserved
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#
#----------------------------------------------------------------#
# Make termcap.db
#----------------------------------------------------------------#

IDIR 	= /usr/share/lib/tabset/
ILIST	= 3101 beehive diablo std teleray vt100 xerox1720

.include <${RULES_MK}>
