* @(#)15        1.1  src/bos/diag/tu/siosl/kbda/slih/kbd_slih.exp, tu_siosl, bos411, 9428A410j 11/18/93 18:25:13
#!/unix
*
*   COMPONENT_NAME: TU_SIOSL
*
*   FUNCTIONS: none
*
*   ORIGINS: 27
*
*
*   (C) COPYRIGHT International Business Machines Corp. 1993
*   All Rights Reserved
*   Licensed Materials - Property of IBM
*   US Government Users Restricted Rights - Use, duplication or
*   disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
*
kbd_interrupt_handler
