# @(#)30        1.1  src/bos/kernext/tm/Makefile, Makefiles, bos411, 9428A410j 8/5/92 18:13:08
# COMPONENT_NAME:
#
# FUNCTIONS:
#
# ORIGINS: 27
#
# IBM CONFIDENTIAL -- (IBM Confidential Restricted when
# combined with the aggregated modules for this product)
#                  SOURCE MATERIALS
# (C) COPYRIGHT International Business Machines Corp. 1988, 1989
# All Rights Reserved
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#

.include <${MAKETOP}bos/kernext/Kernext.mk>

KERNEL_EXT	= tmscsidd
IDIR		= /usr/lib/drivers/
ILIST		= tmscsidd

LIBS		= ${KERNEXT_LIBS}

tmscsidd_ENTRYPOINT	= tmscsi_config

.include <${RULES_MK}>
