$ @(#)09	1.9  src/bos/usr/ccs/lib/libPW/pw.msg, libPW, bos411, 9428A410j 6/6/91 18:46:48
$ COMPONENT_NAME: (LIBPW) Programmers Workbench Library
$
$ FUNCTIONS: 
$
$ ORIGINS: 27 
$
$ IBM CONFIDENTIAL -- (IBM Confidential Restricted when
$ combined with the aggregated modules for this product)
$                  SOURCE MATERIALS
$ (C) COPYRIGHT International Business Machines Corp. 1989
$ All Rights Reserved
$
$ US Government Users Restricted Rights - Use, duplication or
$ disclosure restricted by GSA ADP Schedule Contract with IBM Corp.

$set MS_PW
$quote "
STOVFL "1232-001 regex: stack overflow\n"
XNODIR "1232-002 directory `%s' does not exist (ut1)"
XNOLINK "1232-003 cannot link `%s' to `%s' (ut%d)"
XTABFULL "1232-004 file table full (ut3)"
XNOFILE "1232-005 `%s' does not exist (ut4)"
XNODWRT "1232-006 directory `%s' unwritable (ut2)"
XNOSPC "1232-007 no space! (ut10)"
XTOOBIG "1232-008 file too big (ut8)"
XERRNO "1232-009 errno = %d"
XFUNC "1232-010 %s, function = `%s' (ut11)"
XNORD "1232-011 `%s' unreadable (ut5)"
XNOWRT "1232-012 `%s' unwritable (ut6)"
XNORDWRT "1232-013 `%s' unreadable or unwritable (ut7)"
ERROR "ERROR"

$set MS_PW2
$quote "
XILINST "SIGNAL: 1232-014 Illegal instruction(ut12)"
XTRACE "SIGNAL: 1232-015 Trace/BPT trap(ut12)"
XIOTTR "SIGNAL: 1232-016 IOT trap(ut12)"
XDANG "SIGNAL: 1232-017 Danger(ut12)"
XARITHEX "SIGNAL: 1232-018 Arithmetic exception(ut12)"
XKILD "SIGNAL: 1232-019 Killed(ut12)"
XBUSER "SIGNAL: 1232-020 Bus error(ut12)"
XMEMFLT "SIGNAL: 1232-021 Memory fault(ut12)"
XBADSYS "SIGNAL: 1232-022 Bad system call(ut12)"
XBRKPIP "SIGNAL: 1232-023 Broken pipe(ut12)"
XAMCLOK "SIGNAL: 1232-024 Alarm clock(ut12)"
XTERMAS "SIGNAL: 1232-025 Terminated(ut12)"
