# @(#)43        1.4  src/bos/usr/lib/microcode/fddi/Makefile, ucodfddi, bos41J, 9514A_all 3/14/95 14:37:27
# COMPONENT_NAME: ucodfddi  (Microcode, Fiber Distributed Data Interface)
#
# FUNCTIONS:
#
# ORIGINS: 27
#
# IBM CONFIDENTIAL -- (IBM Confidential Restricted when
# combined with the aggregated modules for this product)
#                  SOURCE MATERIALS
# (C) COPYRIGHT International Business Machines Corp. 1988, 1989
# All Rights Reserved
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#


ILIST           = 8ef4m.02.04 fddi.diag

IDIR            = /usr/lib/microcode/

.include <${RULES_MK}>

