# @(#)19	1.7  src/bos/kernext/disp/inc/Makefile, dispccm, bos41J, 9509A_all 2/7/95 10:46:47
#
#   COMPONENT_NAME: SYSXDISPCCM
#
#   FUNCTIONS: 
#
#   ORIGINS: 27
#
#   IBM CONFIDENTIAL -- (IBM Confidential Restricted when
#   combined with the aggregated modules for this product)
#                    SOURCE MATERIALS
#
#   (C) COPYRIGHT International Business Machines Corp. 1993,1995
#   All Rights Reserved
#   US Government Users Restricted Rights - Use, duplication or
#   disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#

EXPDIR		= /kernel/include/graphics/
disptrc.h_EXPDIR	= /kernel/include/sys/

INCLUDES        = frs_60x_dfa.h 60x_regs.h gs_mon.h disptrc.h pci_regs.h \
		  gs_bus.h

.include <${RULES_MK}>

