# @(#)23	1.5  src/bos/usr/lib/nls/loc/methods/Makefile, cfgnls, bos411, 9428A410j 2/16/94 17:04:55
#
#   COMPONENT_NAME: CFGNLS
#
#   FUNCTIONS:		Makefile for methods
#
#   ORIGINS: 27
#
#   IBM CONFIDENTIAL -- (IBM Confidential Restricted when
#   combined with the aggregated modules for this product)
#                    SOURCE MATERIALS
#
#   (C) COPYRIGHT International Business Machines Corp. 1993,1994
#   All Rights Reserved
#   US Government Users Restricted Rights - Use, duplication or
#   disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#

EXPINC_SUBDIRS	= shared.bidi

SUBDIRS		= ${EXPINC_SUBDIRS}

.include <${RULES_MK}>

