# @(#)62        1.2  src/bos/usr/lib/methods/cfgdiag/Makefile, cfgmethods, bos411, 9428A410j 2/14/94 16:12:24
# COMPONENT_NAME:
#
# FUNCTIONS:
#
# ORIGINS: 27
#
# IBM CONFIDENTIAL -- (IBM Confidential Restricted when
# combined with the aggregated modules for this product)
#                  SOURCE MATERIALS
# (C) COPYRIGHT International Business Machines Corp. 1993
# All Rights Reserved
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#

VPATH		= ../common

PROGRAMS	= cfgdiag

OFILES		= cfgtools.o chkslot.o cfgdiag.o

INCFLAGS	= -I../common

ILIST		= cfgdiag
IDIR		= /usr/lib/methods/


LIBS		= -ls -lodm -lcfg -lrts

.include <${RULES_MK}>
