# @(#)93	1.2  src/bos/usr/lib/pioskr/predef/Makefile, cmdpioskr, bos411, 9428A410j 7/9/93 13:36:52
#
#   COMPONENT_NAME: CMDPIOSKR
#
#   FUNCTIONS: 
#
#   ORIGINS: 27
#
#   IBM CONFIDENTIAL -- (IBM Confidential Restricted when
#   combined with the aggregated modules for this product)
#                    SOURCE MATERIALS
#
#   (C) COPYRIGHT International Business Machines Corp. 1993
#   All Rights Reserved
#   US Government Users Restricted Rights - Use, duplication or
#   disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#
SCRIPTS = ibm4019.kor ibm5575.kor ibm5577.kor

IDIR = /usr/lib/lpd/pio/predef/
ILIST = ${SCRIPTS}

.include <${RULES_MK}>
