# @(#)35	1.1  src/bos/usr/lib/nls/bidi/Makefile, bos, bos410 8/27/93 09:45:07
#
# COMPONENT_NAME: CFGNLS
#
# FUNCTIONS:
#
# ORIGINS: 27
#
# IBM CONFIDENTIAL -- (IBM Confidential Restricted when
# combined with the aggregated modules for this product)
#                  SOURCE MATERIALS
# (C) COPYRIGHT International Business Machines Corp. 1988, 1993
# All Rights Reserved
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#


SUBDIRS		= ar_AA iw_IL maps


.include <${RULES_MK}>
