# @(#)76        1.3  src/bldenv/gos/desktop/scripts/Makefile, desktop, bos412, GOLDA411a 6/3/94 09:56:45
#
#   COMPONENT_NAME: ade_build
#
#   FUNCTIONS: none
#
#   ORIGINS: 27
#
#
#   (C) COPYRIGHT International Business Machines Corp. 1994
#   All Rights Reserved
#   Licensed Materials - Property of IBM
#   US Government Users Restricted Rights - Use, duplication or
#   disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#

VPATH 	= ${MAKETOP}/gos/desktop/cde1/dthelp/parser/helptag:${MAKETOP}/gos/desktop/doc/cde1/LearningProducts/tools

SCRIPTS = helptag processModules AwkHPTagComments

helptag_EXECUTABLE=yes
processModules_EXECUTABLE=yes
AwkHPTagComments_EXECUTABLE=yes

ILIST 	= ${SCRIPTS}
IDIR  	= /opt/dt/etc/

.include <${RULES_MK}>
