# @(#)23	1.3  src/bos/diag/diags/dskpt.stz.S, diagsup, bos411, 9428A410j 4/20/94 18:40:38
#
# COMPONENT_NAME: DIAGBOOT
#
# FUNCTIONS: Diagnostic Disk ODM dependency File List
#
# ORIGINS: 27
#
# (C) COPYRIGHT International Business Machines Corp. 1993, 1994
# All Rights Reserved
# Licensed Materials - Property of IBM
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#
########################################################################
/etc/stanzas/diag.scsidisk.add
/etc/stanzas/diag.disksa.add
/etc/stanzas/diag.8f78.add
/etc/stanzas/diag.df9f.add
