# @(#)22	1.5  src/bos/diag/diags/dskpt.dep.S, diagsup, bos411, 9428A410j 4/8/94 13:08:57
#
# COMPONENT_NAME: DIAGBOOT
#
# FUNCTIONS: Diagnostic Disk Pre-test dependency File List
#
# ORIGINS: 27
#
# (C) COPYRIGHT International Business Machines Corp. 1993, 1994
# All Rights Reserved
# Licensed Materials - Property of IBM
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#
########################################################################
/usr/lpp/diagnostics/bin/dctrl
/usr/lpp/diagnostics/da/dhf
/usr/lpp/diagnostics/da/dhfd
/usr/lpp/diagnostics/da/dh2dasd
/usr/lpp/diagnostics/lib/libdiag.a
/usr/lpp/diagnostics/bin/diagdskpt
/usr/lib/objrepos/PDiagDev
/usr/lib/objrepos/PDiagDev.vc
/usr/lib/objrepos/PDiagAtt
/usr/lib/objrepos/PDiagAtt.vc
/etc/objrepos/CDiagDev
/etc/objrepos/TMInput
/etc/objrepos/FRUB
/etc/objrepos/FRUs
/etc/objrepos/DAVars
/etc/objrepos/MenuGoal
