# @(#)46        1.1  src/bos/etc/passwd/Makefile, Makefiles, bos411, 9428A410j 8/5/92 18:15:13
# COMPONENT_NAME:
#
# FUNCTIONS:
#
# ORIGINS: 27
#
# IBM CONFIDENTIAL -- (IBM Confidential Restricted when
# combined with the aggregated modules for this product)
#                  SOURCE MATERIALS
# (C) COPYRIGHT International Business Machines Corp. 1988, 1989
# All Rights Reserved
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#

SCRIPTS		= passwd

ILIST		= passwd
IDIR		= /etc/

.include <${RULES_MK}>
