# @(#)78	1.12.1.4  src/bos/etc/passwd/passwd.S, cfgsadm, bos411, 9428A410j 6/1/94 17:22:14
#  COMPONENT_NAME: CFGSADM
#
#  ORIGINS: 3, 26, 27
#
#  (C) COPYRIGHT International Business Machines Corp. 1989, 1994
#  All Rights Reserved
#  Licensed Materials - Property of IBM
#
#  US Government Users Restricted Rights - Use, duplication or
#  disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#
root:!:0:0::/:/bin/ksh
daemon:!:1:1::/etc:
bin:!:2:2::/bin:
sys:!:3:3::/usr/sys:
adm:!:4:4::/var/adm:
uucp:!:5:5::/usr/lib/uucp:
guest:!:100:100::/home/guest:
nobody:!:4294967294:4294967294::/:
lpd:!:9:4294967294::/:
