# @(#)51	1.1  src/bos/usr/lib/methods/ucfgktm_std/Makefile, inputdd, bos41J, 9509A_all 2/14/95 12:56:15
#
#   COMPONENT_NAME: INPUTDD
#
#   FUNCTIONS: none
#
#   ORIGINS: 27
#
#   IBM CONFIDENTIAL -- (IBM Confidential Restricted when
#   combined with the aggregated modules for this product)
#                    SOURCE MATERIALS
#
#   (C) COPYRIGHT International Business Machines Corp. 1995
#   All Rights Reserved
#   US Government Users Restricted Rights - Use, duplication or
#   disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#

VPATH		= ../ucfgdevice

PROGRAMS	= ucfgktm_std

INCFLAGS	= -I../common

OFILES		= ucfgdevice.o ucfg_parent_dvdr.o ucfg_gen.o

ILIST		= ucfgktm_std

IDIR		= /usr/lib/methods/

LIBS		= -ls -lodm -lcfg -lrts

.include <${RULES_MK}>
