# @(#)63	1.2  src/bos/diag/tu/sol/Makefile, tu_sol, bos411, 9428A410j 1/7/94 13:42:45
#
#   COMPONENT_NAME: TU_SOL
#
#   FUNCTIONS: 
#
#   ORIGINS: 27
#
#   IBM CONFIDENTIAL -- (IBM Confidential Restricted when
#   combined with the aggregated modules for this product)
#                    SOURCE MATERIALS
#
#   (C) COPYRIGHT International Business Machines Corp. 1992, 1994
#   All Rights Reserved
#   US Government Users Restricted Rights - Use, duplication or
#   disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#

#-------------------------------------------------------------------------#
#                                                                         #
#     This Makefile builds the library libsoltu.a for the DA application #
#                                                                         #
#-------------------------------------------------------------------------#

LIBRARIES       =   libsoltu.a

EXPLIB_TARGETS  =   export_libsoltu.a
EXPDIR          =   /usr/lib/

OFILES		= 	exectu.o tu001.o tu002.o tu003.o tu004.o

.include <${RULES_MK}>
