# @(#)69        1.1  src/bos/usr/lib/boot/mergedev/Makefile, Makefiles, bos411, 9428A410j 8/31/92 19:55:35
# COMPONENT_NAME:
#
# FUNCTIONS:
#
# ORIGINS: 27
#
# IBM CONFIDENTIAL -- (IBM Confidential Restricted when
# combined with the aggregated modules for this product)
#                  SOURCE MATERIALS
# (C) COPYRIGHT International Business Machines Corp. 1988, 1989
# All Rights Reserved
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#

PROGRAMS	= mergedev
MSGHDRS		=
CATFILES	=
HFILES		= ${MSGHDRS}

ILIST		= mergedev
IDIR		= /usr/lib/boot/

LIBS		= -lodm -lcfg

.include <${RULES_MK}>
