# @(#)87        1.2  src/bldenv/basename/Makefile, ade_build, bos412, GOLDA411a 3/18/93 14:02:18
#
#   COMPONENT_NAME: BOSBUILD
#
#   FUNCTIONS:
#
#   ORIGINS: 27
#
#   IBM CONFIDENTIAL -- (IBM Confidential Restricted when
#   combined with the aggregated modules for this product)
#                    SOURCE MATERIALS
#
#   (C) COPYRIGHT International Business Machines Corp. 1993
#   All Rights Reserved
#   US Government Users Restricted Rights - Use, duplication or
#   disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#

VPATH		= ${MAKETOP}/bos/usr/bin/basename

PROGRAMS	= basename
MSGHDRS		= basename_msg.h
CATFILES	= basename.cat
HFILES		= ${MSGHDRS}

ILIST		= basename
IDIR		= /usr/bin/


.include <${RULES_MK}>
