#
# @(#)16  1.2  src/bldenv/bldtools/bldevent.addrs.S, ade_build, bos412, GOLDA411a 11/22/93 14:54:13
#
# COMPONENT_NAME: (BLDPROCESS) BAI Build Process
#
# FUNCTIONS: bldevent.addrs
#
# ORIGINS: 27
#
# (C) COPYRIGHT International Business Machines Corp. 1992
# All Rights Reserved
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#
oldwolf@belgarath
mblevins@austin
dmehaffy@yoda
twalters@ausvm6
randyl@austin
dan@bucko
shaggy@kleikamp
pager@whopper
