#
# @(#)29	1.1  src/bldenv/bldtools/bldtrackingdefect.dat.SVC410.S, bldtools, bos412, GOLDA411a  6/28/94  12:06:18 
#
# COMPONENT_NAME: (BLDTOOLS) BAI Build Tools
#
# FUNCTIONS: bldtrackingdefect data file.
#
# ORIGINS: 27
#
# (C) COPYRIGHT International Business Machines Corp. 1993
# All Rights Reserved
# Licensed Materials - Property of IBM
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.


#
# For the format of this file issue: bldman bldtrackingdefect.dat
#

production|admin@ausaix04@2045|ctbld41|ctbuild41|3|410|noprompt|
test|test01@ausaix05@2550|tracker|bldtrackingdefect|3|325|noprompt|
