#
# @(#)30  1.1  src/bldenv/bldtools/hostsfile.dat.SVC410.S, bldtools, bos412, GOLDA411a 6/28/94 12:07:19
#
# COMPONENT_NAME: (BLDPROCESS) BAI Build Process
#
# FUNCTIONS: hostsfile.dat
#
# ORIGINS: 27
#
# (C) COPYRIGHT International Business Machines Corp. 1992
# All Rights Reserved
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#

#
# Accessing this file should only be done through bldhostsfile.
#
# For the format of this file issue: bldman hostsfile.dat
#

bos410||ade||bos|410|/410_deltas|/full_src|/410_deltas/bos410||obj/power|install/power/ship|*|||
gos410||ade||gos|410|/410_deltas|/full_src|/410_deltas/gos410||obj/power|install/power/ship|*|||
tcpip410||ade||tcpip|410|/410_deltas|/full_src|/410_deltas/tcpip410||obj/power|install/power/ship|*|||
nfs410||ade||nfs|410|/410_deltas|/full_src|/410_deltas/nfs410||obj/power|install/power/ship|*|||
tw410||ade||tw|410|/410_deltas|/full_src|/410_deltas/tw410||obj/power|install/power/ship|*|||
cmdtext410||ade||cmdtext|410|/410_deltas|/full_src|/410_deltas/cmdtext410||obj/power|install/power/ship|*|||
des410||ade||des|410|/410_deltas|/full_src|/410_deltas/des410||obj/power|install/power/ship|*|||
xlc410||ade||xlc|410|/410_deltas|/full_src|/410_deltas/xlc410||obj/power|install/power/ship|*|||
x25sw410||ade||x25sw|410|/410_deltas|/full_src|/410_deltas/x25sw410||obj/power|install/power/ship|*|||
xlf410||ade||xlf|410|/410_deltas|/full_src|/410_deltas/xlf410||obj/power|install/power/ship|*|||
hcon410||ade||hcon|410|/410_deltas|/full_src|/410_deltas/hcon410||obj/power|install/power/ship|*|||
tenplus410||ade||tenplus|410|/410_deltas|/full_src|/410_deltas/tenplus410||obj/power|install/power/ship|*|||
pkg410||ade||pkg|410|/410_deltas|/full_src|/410_deltas/pkg410||obj/power|install/power/ship|*|||
fddi410||ade||fddi|410|/410_deltas|/full_src|/410_deltas/fddi410||obj/power|install/power/ship|*|||
info410||ade||info|410|/410_deltas|/full_src|/410_deltas/info410||obj/power|install/power/ship|*|||
aic410||ade||aic|410|/410_deltas|/full_src|/410_deltas/aic410||obj/power|install/power/ship|*|||
icraft410||ade||icraft|410|/410_deltas|/full_src|/410_deltas/icraft410||obj/power|install/power/ship|*|||
infoxl410||ade||infoxl|410|/410_deltas|/full_src|/410_deltas/infoxl410||obj/power|install/power/ship|*|||
dossvr410||ade||dossvr|410|/410_deltas|/full_src|/410_deltas/dossvr410||obj/power|install/power/ship|*|||
dsmit410||ade||dsmit|410|/410_deltas|/full_src|/410_deltas/dsmit410||obj/power|install/power/ship|*|||
design410||ade||design|410|/410_deltas|/full_src|/410_deltas/design410||obj/power|install/power/ship|*|||
perf410||ade||perf|410|/410_deltas|/full_src|/410_deltas/perf410||obj/power|install/power/ship|*|||
bosl410||ade||bosl|410|/410_deltas|/full_src|/410_deltas/bosl410||obj/power|install/power/ship|*|||
gosl410||ade||gosl|410|/410_deltas|/full_src|/410_deltas/gosl410||obj/power|install/power/ship|*|||
tcpipl410||ade||tcpipl|410|/410_deltas|/full_src|/410_deltas/tcpipl410||obj/power|install/power/ship|*|||
nfsl410||ade||nfsl|410|/410_deltas|/full_src|/410_deltas/nfsl410||obj/power|install/power/ship|*|||
msg410||ade||msg|410|/410_deltas|/full_src|/410_deltas/msg410||obj/power|install/power/ship|*|||
commo410||ade||commo|410|/410_deltas|/full_src|/410_deltas/commo410||obj/power|install/power/ship|*|||
bspi410||ade||bspi|410|/410_deltas|/full_src|/410_deltas/bspi410||obj/power|install/power/ship|*|||
bssi410||ade||bssi|410|/410_deltas|/full_src|/410_deltas/bssi410||obj/power|install/power/ship|*|||
xlpcmpi410||ade||xlpcmpi|410|/410_deltas|/full_src|/410_deltas/xlpcmpi410||obj/power|install/power/ship|*|||
xlfcmpi410||ade||xlfcmpi|410|/410_deltas|/full_src|/410_deltas/xlfcmpi410||obj/power|install/power/ship|*|||
xlCcmpi410||ade||xlCcmpi|410|/410_deltas|/full_src|/410_deltas/xlCcmpi410||obj/power|install/power/ship|*|||
xlC410||ade||xlC|410|/410_deltas|/full_src|/410_deltas/xlC410||obj/power|install/power/ship|*|||
netware410||ade||netware|410|/410_deltas|/full_src|/410_deltas/netware410||obj/power|install/power/ship|*|||
x11devi410||ade||x11devi|410|/410_deltas|/full_src|/410_deltas/x11devi410||obj/power|install/power/ship|*|||
adai410||ade||adai|410|/410_deltas|/full_src|/410_deltas/adai410||obj/power|install/power/ship|*|||
x11_3di410||ade||x11_3di|410|/410_deltas|/full_src|/410_deltas/x11_3di410||obj/power|install/power/ship|*|||
pcsim410||ade||pcsim|410|/410_deltas|/full_src|/410_deltas/pcsim410||obj/power|install/power/ship|*|||
perfreq410||ade||perfreq|410|/410_deltas|/full_src|/410_deltas/perfreq410||obj/power|install/power/ship|*|||
fvtest410||ade||fvtest|410|/410_deltas|/full_src|/410_deltas/fvtest410||obj/power|install/power/ship|*|||
XMGR410||ade||XMGR|410|/410_deltas|/full_src|/410_deltas/XMGR410||obj/power|install/power/ship|*|||
smt410||ade||smt|410|/410_deltas|/full_src|/410_deltas/smt410||obj/power|install/power/ship|*|||
htx410||ade||htx|410|/410_deltas|/full_src|/410_deltas/htx410||obj/power|install/power/ship|*|||
dex410||ade||dex|410|/410_deltas|/full_src|/410_deltas/dex410||obj/power|install/power/ship|*|||
bitternut410||ade||bitternut|410|/410_deltas|/full_src|/410_deltas/bitternut410||obj/power|install/power/ship|*|||
blkmux410||ade||blkmux|410|/410_deltas|/full_src|/410_deltas/blkmux410||obj/power|install/power/ship|*|||
escon410||ade||escon|410|/410_deltas|/full_src|/410_deltas/escon410||obj/power|install/power/ship|*|||
xmgr410||ade||xmgr|410|/410_deltas|/full_src|/410_deltas/xmgr410||obj/power|install/power/ship|*|||
fvlib410||ade||fvlib|410|/410_deltas|/full_src|/410_deltas/fvlib410||obj/power|install/power/ship|*|||
fvcmd410||ade||fvcmd|410|/410_deltas|/full_src|/410_deltas/fvcmd410||obj/power|install/power/ship|*|||
fvcommo410||ade||fvcommo|410|/410_deltas|/full_src|/410_deltas/fvcommo410||obj/power|install/power/ship|*|||
fvsysmgt410||ade||fvsysmgt|410|/410_deltas|/full_src|/410_deltas/fvsysmgt410||obj/power|install/power/ship|*|||
fvkernel410||ade||fvkernel|410|/410_deltas|/full_src|/410_deltas/fvkernel410||obj/power|install/power/ship|*|||
fvgraph410||ade||fvgraph|410|/410_deltas|/full_src|/410_deltas/fvgraph410||obj/power|install/power/ship|*|||
fvbasedd410||ade||fvbasedd|410|/410_deltas|/full_src|/410_deltas/fvbasedd410||obj/power|install/power/ship|*|||
ros_emul_410||ade||ros_emul_|410|/410_deltas|/full_src|/410_deltas/ros_emul_410||obj/power|install/power/ship|*|||
afs410||ade||AFS|410|/410_deltas|/full_src|/410_deltas/afs410||obj/power|install/power/ship|*|||
rspc410||ade||rspc|410|/410_deltas|/full_src|/410_deltas/rspc410||obj/power|install/power/ship|*|||
nep410||ade||nep|410|/410_deltas|/full_src|/410_deltas/nep410||obj/power|install/power/ship|*|||
#
# Entry used to determine the base afs directory.
#
get_afs_base||||get_afs_base|410|||||||410|||

