# @(#)38 1.27 src/bldenv/bldtools/Makefile, bldtools, bos412, GOLDA411a 6/28/94 12:13:30
#
#   COMPONENT_NAME: BOSBUILD
#
#   FUNCTIONS:
#
#   ORIGINS: 27
#
#   IBM CONFIDENTIAL -- (IBM Confidential Restricted when
#   combined with the aggregated modules for this product)
#                    SOURCE MATERIALS
#
#   (C) COPYRIGHT International Business Machines Corp. 1993
#   All Rights Reserved
#   US Government Users Restricted Rights - Use, duplication or
#   disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#

SUBDIRS		= chksubsys afscpsrc

SCRIPTS		= prebuild hostsfile.dat blddatesort bldperlconst \
		  bldstatusfunc CancelPtf bldglobalpath bldperlfunc \
		  bldtmppath CheckStatus bldhostsfile bldperllog \
		  bldverifyreqs CheckSymptom bldinitfunc bldquerymerge \
		  postbuild DeleteStatus bldkshconst bldreleasepath \
		  postpackage QueryStatus bldloginit bldreqlist SetStatus \
		  bldlogpath bldsetstatus sym_lookup bldcycleRemove \
		  bldnodenames bldstatus bldhistorypath bldlog \
		  bldlogset production_areas.dat nodenames.dat bldlock \
		  bldupdatepath showlog v4bld Err.strings RELEASE_LIST \
		  bldevent.addrs bldkshfunc bldCMVCfamily bldgroupdefects \
		  bldtrackingdefect sym_get memo_get showstatus \
		  bldman AddAbstractAsSymptom ChangeAbstracts ChangeMemos \
		  ChangeSymptoms initchanges hostsfile.dat.SVC410 \
		  bldtrackingdefect.dat.SVC410

ILIST		= prebuild hostsfile.dat blddatesort bldperlconst \
		  bldstatusfunc CancelPtf bldglobalpath bldperlfunc \
		  bldtmppath CheckStatus bldhostsfile bldperllog \
		  bldverifyreqs CheckSymptom bldinitfunc bldquerymerge \
		  postbuild DeleteStatus bldkshconst bldreleasepath \
		  postpackage QueryStatus bldloginit bldreqlist SetStatus \
		  bldlogpath bldsetstatus sym_lookup bldcycleRemove \
		  bldnodenames bldstatus bldhistorypath bldlog \
		  bldlogset production_areas.dat nodenames.dat bldlock \
		  bldupdatepath showlog v4bld Err.strings RELEASE_LIST \
		  bldevent.addrs bldkshfunc bldCMVCfamily bldCMVCfamily.dat \
		  bldgroupdefects bldtrackingdefect bldtrackingdefect.dat \
		  sym_get memo_get showstatus bldman \
		  AddAbstractAsSymptom ChangeAbstracts ChangeMemos \
		  ChangeSymptoms initchanges hostsfile.dat.SVC410 \
		  bldtrackingdefect.dat.SVC410

IDIR		= /usr/bld/

.include <${RULES_MK}>
