#
# @(#)24  1.18  src/bldenv/bldtools/nodenames.dat.S, bldprocess, bos412, GOLDA411a 4/14/94 14:06:06
#
# COMPONENT_NAME: (BLDPROCESS) BAI Build Process
#
# FUNCTIONS:  nodenames cross-reference
#
# ORIGINS: 27
#
# (C) COPYRIGHT International Business Machines Corp. 1991, 1992
# All Rights Reserved
# Licensed Materials - Property of IBM
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.


#
# For the format of this file issue: bldman nodenames.dat
#

111 1.1.1
310 3.1
311 3.1.1
312 3.1.2
320 3.2
321 3.2.1
322 3.2.2
324 3.2.4
325 3.2.5
32S 3.2.S
330 3.3
410 4.1 mustfix	build 41approved service pmp
10 1.0
12 1.2
13 1.3
110 110
