# @(#)35        1.30  src/bldenv/bldtools/RELEASE_LIST.S, bldtools, bos41J, 9522A_all 5/30/95 12:45:45
#
# COMPONENT_NAME: (BLDTOOLS) BAI Build Tools
#
# FUNCTIONS:  List of official releases
#
# ORIGINS: 27
#
# (C) COPYRIGHT International Business Machines Corp. 1991, 1992
# All Rights Reserved
# Licensed Materials - Property of IBM
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#
afs41J
bos41J
cmdtext41J
des41J
dsmit41J
dtuimx41J
gos41J
hcon41J
icraft41J
info41J
msg41J
nep41J
netware41J
nfs41J
perf41J
pkg41J
rspc41J
rspc_g41J
ssa41J
tcpip41J
tenplus41J
tw41J
wabi41J
xlC41J
xlf41J
xmgr41J
cde41J
web41J
pcprotocols41J
410hippi41J
id41J
