# @(#)12	1.1  src/bos/kernext/disp/sga/inc/Makefile, sgadd, bos411, 9428A410j 10/29/93 10:49:15
#
#   COMPONENT_NAME: SGADD
#
#   FUNCTIONS: none
#
#   ORIGINS: 27
#
#   IBM CONFIDENTIAL -- (IBM Confidential Restricted when
#   combined with the aggregated modules for this product)
#                    SOURCE MATERIALS
#
#   (C) COPYRIGHT International Business Machines Corp. 1993
#   All Rights Reserved
#   US Government Users Restricted Rights - Use, duplication or
#   disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#

EXPDIR          = /kernel/include/
INCLUDES	= sgadds.h 

.include <${RULES_MK}>
