# @(#)00	1.5  src/bos/usr/lib/piosk/msg/Makefile, cmdpiosk, bos411, 9428A410j 5/15/94 06:33:51
#
#   COMPONENT_NAME: CMDPIOSK
#
#   FUNCTIONS: 
#
#   ORIGINS: 27
#
#   IBM CONFIDENTIAL -- (IBM Confidential Restricted when
#   combined with the aggregated modules for this product)
#                    SOURCE MATERIALS
#
#   (C) COPYRIGHT International Business Machines Corp. 1993, 1994
#   All Rights Reserved
#   US Government Users Restricted Rights - Use, duplication or
#   disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#

MSGHDRS = jfmtrs_msg.h
CATFILES = jfmtrs.cat pioattr2.cat
HFILES = ${MSGHDRS}
OTHERS = ${CATFILES} ${HFILES}

INCLUDES = jfmtrs_msg.h
EXPDIR = /usr/include/

IDIR = /usr/lib/lpd/pio/etc/
ILIST = pioattr2.cat

.include <${RULES_MK}>
