#
# dependents of dbblue.o:
dbblue.o: ${MAKETOP}bos/usr/include/stdio.h
dbblue.o: ${MAKETOP}bos/usr/include/standards.h
dbblue.o: ${MAKETOP}bos/usr/include/va_list.h
dbblue.o: ${MAKETOP}../export/power/usr/include/sys/types.h
dbblue.o: ${MAKETOP}../export/power/usr/include/sys/m_types.h
dbblue.o: ${MAKETOP}../export/power/usr/include/sys/limits.h
dbblue.o: ${MAKETOP}bos/usr/include/float.h
dbblue.o: ${MAKETOP}bos/usr/include/errno.h
dbblue.o: ${MAKETOP}../export/power/usr/include/sys/errno.h
dbblue.o: ${MAKETOP}../export/power/usr/include/sys/signal.h
dbblue.o: ${MAKETOP}../export/power/usr/include/sys/context.h
dbblue.o: ${MAKETOP}../export/power/usr/include/sys/m_param.h
dbblue.o: ${MAKETOP}../export/power/usr/include/sys/mstsave.h
dbblue.o: ../../../../bos/usr/include/sys/errids.h
dbblue.o: ${MAKETOP}../export/power/usr/include/sys/err_rec.h
dbblue.o: ${MAKETOP}bos/usr/include/locale.h
dbblue.o: ${MAKETOP}bos/usr/include/fcntl.h
dbblue.o: ${MAKETOP}../export/power/usr/include/sys/flock.h
dbblue.o: ${MAKETOP}bos/usr/include/unistd.h
dbblue.o: ${MAKETOP}../export/power/usr/include/sys/access.h
dbblue.o: ${MAKETOP}../export/power/usr/include/sys/lockf.h
dbblue.o: ${MAKETOP}../export/power/usr/include/sys/stat.h
dbblue.o: ${MAKETOP}../export/power/usr/include/sys/mode.h
dbblue.o: ../../../../bos/usr/include/sys/cfgodm.h
dbblue.o: ${MAKETOP}bos/usr/include/odmi.h
dbblue.o: ${MAKETOP}../export/power/usr/include/sys/dir.h
dbblue.o: ${MAKETOP}../export/power/usr/include/sys/lkup.h
dbblue.o: ${MAKETOP}bos/usr/include/limits.h
dbblue.o: ${MAKETOP}bos/usr/include/diag/tm_input.h
dbblue.o: ${MAKETOP}bos/usr/include/diag/tmdefs.h
dbblue.o: ${MAKETOP}bos/usr/include/diag/da.h
dbblue.o: ${MAKETOP}../export/power/usr/include/sys/cfgdb.h
dbblue.o: ${MAKETOP}bos/usr/include/diag/diag.h
dbblue.o: ${MAKETOP}bos/usr/include/diag/diag_define.h
dbblue.o: ${MAKETOP}bos/usr/include/diag/diag_exit.h
dbblue.o: ${MAKETOP}bos/usr/include/diag/diago.h
dbblue.o: ${MAKETOP}bos/usr/include/asl.h
dbblue.o: ${MAKETOP}bos/usr/include/stdarg.h
dbblue.o: ${MAKETOP}bos/diag/da/bblue/dbblue.h
dbblue.o: ${MAKETOP}bos/diag/tu/bblue/bblue_tu_type.h
dbblue.o: ${MAKETOP}../export/power/usr/include/sys/mdio.h
dbblue.o: ${MAKETOP}bos/kernext/disp/bbl/inc/bblerr.h
dbblue.o: dbblue_msg.h
dbblue.o: ${MAKETOP}bos/usr/include/nl_types.h
dbblue.o: ${MAKETOP}bos/usr/include/mesg.h
