# @(#)95        1.1  src/bldenv/xlC/include/rpc/Makefile, ade_build, bos41J, 9509A_all 2/27/95 12:43:27
#
#   COMPONENT_NAME: ade_build
#
#   FUNCTIONS: none
#
#   ORIGINS: 27
#
#
#   (C) COPYRIGHT International Business Machines Corp. 1995
#   All Rights Reserved
#   Licensed Materials - Property of IBM
#   US Government Users Restricted Rights - Use, duplication or
#   disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#

VPATH = ${MAKETOP}/xlC/usr/lpp/xlC/include/rpc

INCLUDES        = \
	auth.h        clnt.h        pmap_prot.h   rpc_msg.h     types.h \
	auth_des.h    key_prot.h    pmap_rmt.h    svc.h         xdr.h \
	auth_unix.h   pmap_clnt.h   rpc.h         svc_auth.h

EXPDIR  = /usr/lpp/xlC/include/rpc/

.include <${RULES_MK}>
