#
# dependents of Adapters.o:
Adapters.o: ${MAKETOP}../export/power/usr/include/stdio.h
Adapters.o: ${MAKETOP}../export/power/usr/include/standards.h
Adapters.o: ${MAKETOP}../export/power/usr/include/va_list.h
Adapters.o: ${MAKETOP}../export/power/usr/include/sys/types.h
Adapters.o: ${MAKETOP}../export/power/usr/include/sys/m_types.h
Adapters.o: ${MAKETOP}../export/power/usr/include/sys/limits.h
Adapters.o: ${MAKETOP}../export/power/usr/include/float.h
Adapters.o: ${MAKETOP}../export/power/usr/include/odmi.h
Adapters.o: ${MAKETOP}../export/power/usr/include/sys/dir.h
Adapters.o: ${MAKETOP}../export/power/usr/include/sys/lkup.h
Adapters.o: ${MAKETOP}../export/power/usr/include/limits.h
Adapters.o: ${MAKETOP}../export/power/usr/include/cf.h
Adapters.o: ${MAKETOP}../export/power/usr/include/sys/errno.h
Adapters.o: ${MAKETOP}../export/power/usr/include/sys/sysconfig.h
Adapters.o: ${MAKETOP}../export/power/usr/include/sys/lockl.h
Adapters.o: ${MAKETOP}../export/power/usr/include/sys/lock_def.h
Adapters.o: ${MAKETOP}../export/power/usr/include/sys/param.h
Adapters.o: ${MAKETOP}../export/power/usr/include/sys/m_param.h
Adapters.o: ${MAKETOP}../export/power/usr/include/jfs/fsparam.h
Adapters.o: ${MAKETOP}../export/power/usr/include/sys/sysmacros.h
Adapters.o: ${MAKETOP}bos/diag/tu/gio/Adapters.h
Adapters.o: ${MAKETOP}bos/diag/tu/gio/getodminfo.h
Adapters.o: ${MAKETOP}../export/power/usr/include/sys/diagex.h
Adapters.o: ${MAKETOP}../export/power/usr/include/sys/intr.h
Adapters.o: ${MAKETOP}../export/power/usr/include/sys/m_intr.h
Adapters.o: ${MAKETOP}../export/power/usr/include/sys/dma.h
Adapters.o: ${MAKETOP}../export/power/usr/include/sys/sysdma.h
Adapters.o: ${MAKETOP}../export/power/usr/include/sys/xmem.h
Adapters.o: ${MAKETOP}../export/power/usr/include/sys/timer.h
Adapters.o: ${MAKETOP}../export/power/usr/include/sys/time.h
Adapters.o: ${MAKETOP}../export/power/usr/include/sys/processor.h
Adapters.o: ${MAKETOP}../export/power/usr/include/sys/watchdog.h
Adapters.o: ${MAKETOP}bos/diag/tu/gio/gio_diag.h
Adapters.o: ${MAKETOP}bos/diag/tu/gio/gio.h
Adapters.o: ${MAKETOP}../export/power/usr/include/sys/cblock.h
Adapters.o: ${MAKETOP}../export/power/usr/include/sys/except.h
Adapters.o: ${MAKETOP}../export/power/usr/include/sys/m_except.h
Adapters.o: ${MAKETOP}bos/diag/tu/gio/cfgad.h
#
# dependents of crc.o:
#
# dependents of exectu.o:
exectu.o: ${MAKETOP}bos/diag/tu/gio/atu_gio.h
exectu.o: ${MAKETOP}../export/power/usr/include/stdio.h
exectu.o: ${MAKETOP}../export/power/usr/include/standards.h
exectu.o: ${MAKETOP}../export/power/usr/include/va_list.h
exectu.o: ${MAKETOP}../export/power/usr/include/sys/types.h
exectu.o: ${MAKETOP}../export/power/usr/include/sys/m_types.h
exectu.o: ${MAKETOP}../export/power/usr/include/sys/limits.h
exectu.o: ${MAKETOP}../export/power/usr/include/float.h
exectu.o: ${MAKETOP}../export/power/usr/include/string.h
exectu.o: ${MAKETOP}../export/power/usr/include/fcntl.h
exectu.o: ${MAKETOP}../export/power/usr/include/sys/flock.h
exectu.o: ${MAKETOP}../export/power/usr/include/unistd.h
exectu.o: ${MAKETOP}../export/power/usr/include/sys/access.h
exectu.o: ${MAKETOP}../export/power/usr/include/sys/lockf.h
exectu.o: ${MAKETOP}../export/power/usr/include/sys/stat.h
exectu.o: ${MAKETOP}../export/power/usr/include/sys/mode.h
exectu.o: ${MAKETOP}../export/power/usr/include/errno.h
exectu.o: ${MAKETOP}../export/power/usr/include/sys/errno.h
exectu.o: ${MAKETOP}../export/power/usr/include/sys/devinfo.h
exectu.o: ${MAKETOP}../export/power/usr/include/sys/ioctl.h
exectu.o: ${MAKETOP}../export/power/usr/include/sys/ttychars.h
exectu.o: ${MAKETOP}../export/power/usr/include/sys/ttydev.h
exectu.o: ${MAKETOP}../export/power/usr/include/sys/termio.h
exectu.o: ${MAKETOP}../export/power/usr/include/sys/ttmap.h
exectu.o: ${MAKETOP}../export/power/usr/include/termios.h
exectu.o: ${MAKETOP}../export/power/usr/include/sys/signal.h
exectu.o: ${MAKETOP}../export/power/usr/include/sys/context.h
exectu.o: ${MAKETOP}../export/power/usr/include/sys/m_param.h
exectu.o: ${MAKETOP}../export/power/usr/include/sys/mstsave.h
exectu.o: ${MAKETOP}../export/power/usr/include/sys/device.h
exectu.o: ${MAKETOP}../export/power/usr/include/sys/file.h
exectu.o: ${MAKETOP}../export/power/usr/include/sys/param.h
exectu.o: ${MAKETOP}../export/power/usr/include/jfs/fsparam.h
exectu.o: ${MAKETOP}../export/power/usr/include/sys/sysmacros.h
exectu.o: ${MAKETOP}../export/power/usr/include/sys/lock_def.h
exectu.o: ${MAKETOP}../export/power/usr/include/sys/cred.h
exectu.o: ${MAKETOP}../export/power/usr/include/sys/priv.h
exectu.o: ${MAKETOP}../export/power/usr/include/sys/tcb.h
exectu.o: ${MAKETOP}../export/power/usr/include/sys/pcl.h
exectu.o: ${MAKETOP}../export/power/usr/include/sys/lockl.h
exectu.o: ${MAKETOP}../export/power/usr/include/sys/intr.h
exectu.o: ${MAKETOP}../export/power/usr/include/sys/m_intr.h
exectu.o: ${MAKETOP}../export/power/usr/include/sys/low.h
exectu.o: ${MAKETOP}../export/power/usr/include/sys/syspest.h
exectu.o: ${MAKETOP}../export/power/usr/include/sys/sysconfig.h
exectu.o: ${MAKETOP}../export/power/usr/include/sys/select.h
exectu.o: ${MAKETOP}../export/power/usr/include/sys/time.h
exectu.o: ${MAKETOP}bos/diag/tu/gio/equhft.h
exectu.o: ${MAKETOP}../export/power/usr/include/diag/atu.h
exectu.o: ${MAKETOP}../export/power/usr/include/diag/diago.h
exectu.o: ${MAKETOP}../export/power/usr/include/asl.h
exectu.o: ${MAKETOP}../export/power/usr/include/stdarg.h
exectu.o: ${MAKETOP}bos/diag/tu/gio/Adapters.h
exectu.o: ${MAKETOP}bos/diag/tu/gio/getodminfo.h
exectu.o: ${MAKETOP}../export/power/usr/include/sys/diagex.h
exectu.o: ${MAKETOP}../export/power/usr/include/sys/dma.h
exectu.o: ${MAKETOP}../export/power/usr/include/sys/sysdma.h
exectu.o: ${MAKETOP}../export/power/usr/include/sys/xmem.h
exectu.o: ${MAKETOP}../export/power/usr/include/sys/timer.h
exectu.o: ${MAKETOP}../export/power/usr/include/sys/processor.h
exectu.o: ${MAKETOP}../export/power/usr/include/sys/watchdog.h
#
# dependents of getodminfo.o:
getodminfo.o: ${MAKETOP}../export/power/usr/include/sys/cfgdb.h
getodminfo.o: ${MAKETOP}../export/power/usr/include/sys/cfgodm.h
getodminfo.o: ${MAKETOP}../export/power/usr/include/odmi.h
getodminfo.o: ${MAKETOP}../export/power/usr/include/sys/types.h
getodminfo.o: ${MAKETOP}../export/power/usr/include/standards.h
getodminfo.o: ${MAKETOP}../export/power/usr/include/sys/m_types.h
getodminfo.o: ${MAKETOP}../export/power/usr/include/sys/dir.h
getodminfo.o: ${MAKETOP}../export/power/usr/include/sys/lkup.h
getodminfo.o: ${MAKETOP}../export/power/usr/include/limits.h
getodminfo.o: ${MAKETOP}../export/power/usr/include/sys/limits.h
getodminfo.o: ${MAKETOP}../export/power/usr/include/float.h
getodminfo.o: ${MAKETOP}../export/power/usr/include/sys/sysconfig.h
getodminfo.o: ${MAKETOP}../export/power/usr/include/sys/lockl.h
getodminfo.o: ${MAKETOP}../export/power/usr/include/sys/lock_def.h
getodminfo.o: ${MAKETOP}../export/power/usr/include/cf.h
getodminfo.o: ${MAKETOP}bos/diag/tu/gio/gio.h
getodminfo.o: ${MAKETOP}../export/power/usr/include/sys/intr.h
getodminfo.o: ${MAKETOP}../export/power/usr/include/sys/m_intr.h
getodminfo.o: ${MAKETOP}../export/power/usr/include/sys/timer.h
getodminfo.o: ${MAKETOP}../export/power/usr/include/sys/time.h
getodminfo.o: ${MAKETOP}../export/power/usr/include/sys/processor.h
getodminfo.o: ${MAKETOP}../export/power/usr/include/sys/cblock.h
getodminfo.o: ${MAKETOP}../export/power/usr/include/sys/except.h
getodminfo.o: ${MAKETOP}../export/power/usr/include/sys/m_except.h
getodminfo.o: ${MAKETOP}../export/power/usr/include/sys/watchdog.h
getodminfo.o: ${MAKETOP}bos/diag/tu/gio/cfgad.h
getodminfo.o: ${MAKETOP}bos/diag/tu/gio/Adapters.h
getodminfo.o: ${MAKETOP}bos/diag/tu/gio/getodminfo.h
getodminfo.o: ${MAKETOP}../export/power/usr/include/sys/diagex.h
getodminfo.o: ${MAKETOP}../export/power/usr/include/sys/dma.h
getodminfo.o: ${MAKETOP}../export/power/usr/include/sys/sysdma.h
getodminfo.o: ${MAKETOP}../export/power/usr/include/sys/xmem.h
#
# dependents of gio_util.o:
gio_util.o: ${MAKETOP}../export/power/usr/include/sys/device.h
gio_util.o: ${MAKETOP}../export/power/usr/include/sys/types.h
gio_util.o: ${MAKETOP}../export/power/usr/include/standards.h
gio_util.o: ${MAKETOP}../export/power/usr/include/sys/m_types.h
gio_util.o: ${MAKETOP}../export/power/usr/include/sys/file.h
gio_util.o: ${MAKETOP}../export/power/usr/include/sys/param.h
gio_util.o: ${MAKETOP}../export/power/usr/include/sys/m_param.h
gio_util.o: ${MAKETOP}../export/power/usr/include/sys/limits.h
gio_util.o: ${MAKETOP}../export/power/usr/include/float.h
gio_util.o: ${MAKETOP}../export/power/usr/include/jfs/fsparam.h
gio_util.o: ${MAKETOP}../export/power/usr/include/sys/sysmacros.h
gio_util.o: ${MAKETOP}../export/power/usr/include/sys/access.h
gio_util.o: ${MAKETOP}../export/power/usr/include/sys/lock_def.h
gio_util.o: ${MAKETOP}../export/power/usr/include/sys/cred.h
gio_util.o: ${MAKETOP}../export/power/usr/include/sys/priv.h
gio_util.o: ${MAKETOP}../export/power/usr/include/sys/mode.h
gio_util.o: ${MAKETOP}../export/power/usr/include/sys/tcb.h
gio_util.o: ${MAKETOP}../export/power/usr/include/sys/pcl.h
gio_util.o: ${MAKETOP}../export/power/usr/include/sys/lockl.h
gio_util.o: ${MAKETOP}../export/power/usr/include/fcntl.h
gio_util.o: ${MAKETOP}../export/power/usr/include/sys/flock.h
gio_util.o: ${MAKETOP}../export/power/usr/include/unistd.h
gio_util.o: ${MAKETOP}../export/power/usr/include/sys/lockf.h
gio_util.o: ${MAKETOP}../export/power/usr/include/sys/stat.h
gio_util.o: ${MAKETOP}../export/power/usr/include/sys/intr.h
gio_util.o: ${MAKETOP}../export/power/usr/include/sys/m_intr.h
gio_util.o: ${MAKETOP}../export/power/usr/include/sys/low.h
gio_util.o: ${MAKETOP}../export/power/usr/include/sys/syspest.h
gio_util.o: ${MAKETOP}../export/power/usr/include/sys/errno.h
gio_util.o: ${MAKETOP}../export/power/usr/include/sys/sleep.h
gio_util.o: ${MAKETOP}bos/diag/tu/gio/equhft.h
gio_util.o: ${MAKETOP}bos/diag/tu/gio/Adapters.h
gio_util.o: ${MAKETOP}bos/diag/tu/gio/getodminfo.h
gio_util.o: ${MAKETOP}../export/power/usr/include/sys/diagex.h
gio_util.o: ${MAKETOP}../export/power/usr/include/sys/dma.h
gio_util.o: ${MAKETOP}../export/power/usr/include/sys/sysdma.h
gio_util.o: ${MAKETOP}../export/power/usr/include/sys/xmem.h
gio_util.o: ${MAKETOP}../export/power/usr/include/sys/timer.h
gio_util.o: ${MAKETOP}../export/power/usr/include/sys/time.h
gio_util.o: ${MAKETOP}../export/power/usr/include/sys/processor.h
gio_util.o: ${MAKETOP}../export/power/usr/include/sys/watchdog.h
gio_util.o: ${MAKETOP}bos/diag/tu/gio/gio_diag.h
gio_util.o: ${MAKETOP}bos/diag/tu/gio/gio.h
gio_util.o: ${MAKETOP}../export/power/usr/include/sys/cblock.h
gio_util.o: ${MAKETOP}../export/power/usr/include/sys/except.h
gio_util.o: ${MAKETOP}../export/power/usr/include/sys/m_except.h
gio_util.o: ${MAKETOP}bos/diag/tu/gio/cfgad.h
