$ @(#)99	1.1  src/bos/usr/lib/piosCN/msg/cfmtrs.msg, ils-zh_CN, bos41J, 9507B 1/26/95 09:56:39
$
$   COMPONENT_NAME: ils-zh_CN
$
$   FUNCTIONS: none
$
$   ORIGINS: 27
$
$   IBM CONFIDENTIAL -- (IBM Confidential Restricted when
$   combined with the aggregated modules for this product)
$                    SOURCE MATERIALS
$
$   (C) COPYRIGHT International Business Machines Corp. 1995
$   All Rights Reserved
$   US Government Users Restricted Rights - Use, duplication or
$   disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
$
$
$set 1
$
$       Messages issued by a formatter
$
120 Dummy Message.
MSG_BADFORMFLAG \
0782-500 以 -%.1s 选项设定的参数值无效。\n\
\tCheck the parameter value.\n
$
MSG_BADFORMFLAG1 \
0782-501 以 -%.1s 选项设定的参数值无效。\n\
\tThe parameter value must be + or !.\n\
\tCheck the parameter value.\n
$
MSG_BADFORMFLAG2 \
0782-502 以 -%.1s 选项设定的参数值无效。\n\
\tThe parameter value must be 1 or greater.\n\
\tCheck the parameter value.\n
$
MSG_BADFORMFLAG3 \
0782-503 以 -%.1s 选项设定的参数值无效。\n\
\tThe parameter value must be 0 or greater.\n\
\tCheck the parameter value.\n
MSG_BADFORMFLAG8 \
0782-508 以 -%.1s 选项设定的参数值无效。\n\
\tThe parameter value must be less than the page width.\n\
\tCheck the parameter value.\n
$
MSG_BADUSERFONT1 \
0782-708 无法存取所设定的用户定义的字库文件 %s。\n
$
