# @(#)00	1.1  src/bos/usr/lib/piosCN/msg/Makefile, ils-zh_CN, bos41J, 9507B 1/26/95 09:56:41
#
#   COMPONENT_NAME: ils-zh_CN
#
#   FUNCTIONS: none
#
#   ORIGINS: 27
#
#   IBM CONFIDENTIAL -- (IBM Confidential Restricted when
#   combined with the aggregated modules for this product)
#                    SOURCE MATERIALS
#
#   (C) COPYRIGHT International Business Machines Corp. 1995
#   All Rights Reserved
#   US Government Users Restricted Rights - Use, duplication or
#   disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#
MSGHDRS = cfmtrs_msg.h ufmtrs_msg.h
INCLUDES = ${MSGHDRS}
EXPDIR = /usr/include/

CATFILES = cfmtrs.cat pioattr8.cat pioattr9.cat ufmtrs.cat

ILIST = ${CATFILES}
IDIR = /usr/lib/lpd/pio/etc/

.include <${RULES_MK}>
