# @(#)33	1.1  src/bos/diag/util/ueth/Makefile, dsaueth, bos411, 9428A410j 12/6/93 08:13:35
#
#   COMPONENT_NAME: DSAUETH
#
#   FUNCTIONS: none
#
#   ORIGINS: 27
#
#
#   (C) COPYRIGHT International Business Machines Corp. 1989,1993
#   All Rights Reserved
#   Licensed Materials - Property of IBM
#   US Government Users Restricted Rights - Use, duplication or
#   disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#

SUBDIRS		= eth ethstw ethsal

.include <${RULES_MK}>
