# @(#)84        1.3  src/bos/usr/lib/ncs/cat/utils-a/Makefile, bos, bos410 5/21/93 08:54:10

# COMPONENT_NAME:  libncs
#
# FUNCTIONS:
#
# ORIGINS: 27
#
# IBM CONFIDENTIAL -- (IBM Confidential Restricted when
# combined with the aggregated modules for this product)
#                  SOURCE MATERIALS
# (C) COPYRIGHT International Business Machines Corp. 1988, 1992
# All Rights Reserved
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#


ILIST		= \
	drm_admin \
	glbd \
	lb_admin \
	lb_find \
	llbd \
	nrglbd \
	stcode \
	uuid_gen

IDIR		= /usr/lib/ncs/cat/utils-a/

.include <${RULES_MK}>

