# @(#)18        1.6  src/bos/usr/lib/assist/Makefile, cmdassist, bos410 4/5/94 15:08:46
#
# COMPONENT_NAME:  cmdassist
#
# FUNCTIONS:
#
# ORIGINS: 27
#
# IBM CONFIDENTIAL -- (IBM Confidential Restricted when
# combined with the aggregated modules for this product)
#                  SOURCE MATERIALS
# (C) COPYRIGHT International Business Machines Corp. 1994
# All Rights Reserved
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#

ILIST		= sm_instdev.add \
                  sm_isa.add \
                  sm_migrate.add \
                  sm_overwrite.add \
                  sm_preinstall.add \
                  sm_preserve.add


IDIR            = /usr/lib/assist/add_files/

.include <${RULES_MK}>
