# @(#)67	1.2  src/bos/usr/lib/pios/bidi/fonts/4234/Makefile, cmdpios, bos411, 9432A411a 8/5/94 12:42:19

#
# COMPONENT_NAME: (CMDPIOS) Printer Backend
#
# ORIGINS: 27
#
# IBM CONFIDENTIAL -- (IBM Confidential Restricted when
# combined with the aggregated modules for this product)
#                  SOURCE MATERIALS
# (C) COPYRIGHT International Business Machines Corp. 1989
# All Rights Reserved
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#


DATAFILES       = CP1046.ibm4234.dp CP1046.ibm4234.nlq

ILIST           = ${DATAFILES}
IDIR            = /usr/lib/lpd/pio/fonts/ibm4234/

.include <${RULES_MK}>

CP1046.ibm4234.dp:	CP1046.4234.dp
	$(CP) ${.ALLSRC} ${.TARGET}

CP1046.ibm4234.nlq:	CP1046.4234.nlq
	$(CP) ${.ALLSRC} ${.TARGET}
