# @(#)96        1.2  src/bos/kernext/audio/Makefile, sysxacpa, bos411, 9428A410j 3/30/94 13:48:17
# COMPONENT_NAME:
#
# FUNCTIONS:
#
# ORIGINS: 27
#
# IBM CONFIDENTIAL -- (IBM Confidential Restricted when
# combined with the aggregated modules for this product)
#                  SOURCE MATERIALS
# (C) COPYRIGHT International Business Machines Corp. 1988, 1989
# All Rights Reserved
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#

# SUBDIRS		= acpa   * Commented out: ACPA not supported in 4.1

.include <${RULES_MK}>
