#
# dependents of cdd_entry.o:
cdd_entry.o: ${MAKETOP}../export/power/kernel/include/sys/types.h
cdd_entry.o: ${MAKETOP}bos/usr/include/standards.h
cdd_entry.o: ${MAKETOP}../export/power/kernel/include/sys/m_types.h
cdd_entry.o: ${MAKETOP}../export/power/kernel/include/sys/aixfont.h
cdd_entry.o: ${MAKETOP}../export/power/kernel/include/lft.h
cdd_entry.o: ${MAKETOP}../export/power/kernel/include/fkproc.h
cdd_entry.o: ${MAKETOP}../export/power/kernel/include/sys/intr.h
cdd_entry.o: ${MAKETOP}../export/power/kernel/include/sys/m_intr.h
cdd_entry.o: ${MAKETOP}../export/power/kernel/include/fkprocFont.h
cdd_entry.o: ${MAKETOP}../export/power/kernel/include/sys/errno.h
cdd_entry.o: ${MAKETOP}../export/power/kernel/include/sys/xmem.h
cdd_entry.o: ${MAKETOP}../export/power/kernel/include/sys/display.h
cdd_entry.o: ${MAKETOP}../export/power/kernel/include/sys/rcm_win.h
cdd_entry.o: ${MAKETOP}../export/power/kernel/include/sys/aixgsc.h
cdd_entry.o: ${MAKETOP}../export/power/kernel/include/sys/rcm.h
cdd_entry.o: ${MAKETOP}../export/power/kernel/include/sys/systemcfg.h
cdd_entry.o: ${MAKETOP}../export/power/kernel/include/sys/except.h
cdd_entry.o: ${MAKETOP}../export/power/kernel/include/sys/m_except.h
cdd_entry.o: ${MAKETOP}../export/power/kernel/include/sys/proc.h
cdd_entry.o: ${MAKETOP}../export/power/kernel/include/sys/ptrace.h
cdd_entry.o: ${MAKETOP}../export/power/kernel/include/sys/thread.h
cdd_entry.o: ${MAKETOP}../export/power/kernel/include/sys/mstsave.h
cdd_entry.o: ${MAKETOP}../export/power/kernel/include/sys/m_param.h
cdd_entry.o: ${MAKETOP}../export/power/kernel/include/sys/processor.h
cdd_entry.o: ${MAKETOP}../export/power/kernel/include/sys/lock_def.h
cdd_entry.o: ${MAKETOP}../export/power/kernel/include/sys/var.h
cdd_entry.o: ${MAKETOP}../export/power/kernel/include/sys/atomic_op.h
cdd_entry.o: ${MAKETOP}../export/power/kernel/include/sys/timer.h
cdd_entry.o: ${MAKETOP}../export/power/kernel/include/sys/time.h
cdd_entry.o: ${MAKETOP}../export/power/kernel/include/sys/resource.h
cdd_entry.o: ${MAKETOP}../export/power/kernel/include/sys/pri.h
cdd_entry.o: ${MAKETOP}../export/power/kernel/include/sys/lockl.h
cdd_entry.o: ${MAKETOP}../export/power/kernel/include/sys/limits.h
cdd_entry.o: ${MAKETOP}bos/usr/include/float.h
cdd_entry.o: ${MAKETOP}../export/power/kernel/include/sys/rcm_wg.h
cdd_entry.o: ${MAKETOP}../export/power/kernel/include/sys/pwr_mgr.h
cdd_entry.o: ${MAKETOP}../export/power/kernel/include/sys/watchdog.h
cdd_entry.o: ${MAKETOP}../export/power/kernel/include/lft_swkbd.h
cdd_entry.o: ${MAKETOP}../export/power/kernel/include/vt.h
cdd_entry.o: ${MAKETOP}../export/power/kernel/include/sys/font.h
cdd_entry.o: ${MAKETOP}../export/power/kernel/include/lft_dds.h
cdd_entry.o: ${MAKETOP}../export/power/kernel/include/sys/cfgdb.h
cdd_entry.o: ${MAKETOP}../export/power/kernel/include/kks.h
cdd_entry.o: ${MAKETOP}../export/power/kernel/include/lftras.h
cdd_entry.o: ${MAKETOP}../export/power/kernel/include/sys/dir.h
cdd_entry.o: ${MAKETOP}../export/power/kernel/include/sys/lkup.h
cdd_entry.o: ${MAKETOP}bos/usr/include/limits.h
cdd_entry.o: ${MAKETOP}bos/usr/include/jfs/dir.h
cdd_entry.o: ${MAKETOP}../export/power/kernel/include/sys/mdio.h
cdd_entry.o: ${MAKETOP}../export/power/kernel/include/sys/file.h
cdd_entry.o: ${MAKETOP}../export/power/kernel/include/sys/param.h
cdd_entry.o: ${MAKETOP}bos/usr/include/jfs/fsparam.h
cdd_entry.o: ${MAKETOP}../export/power/kernel/include/sys/sysmacros.h
cdd_entry.o: ${MAKETOP}../export/power/kernel/include/sys/access.h
cdd_entry.o: ${MAKETOP}../export/power/kernel/include/sys/cred.h
cdd_entry.o: ${MAKETOP}../export/power/kernel/include/sys/priv.h
cdd_entry.o: ${MAKETOP}../export/power/kernel/include/sys/mode.h
cdd_entry.o: ${MAKETOP}../export/power/kernel/include/sys/tcb.h
cdd_entry.o: ${MAKETOP}../export/power/kernel/include/sys/pcl.h
cdd_entry.o: ${MAKETOP}bos/usr/include/fcntl.h
cdd_entry.o: ${MAKETOP}../export/power/kernel/include/sys/flock.h
cdd_entry.o: ${MAKETOP}bos/usr/include/unistd.h
cdd_entry.o: ${MAKETOP}../export/power/kernel/include/sys/lockf.h
cdd_entry.o: ${MAKETOP}../export/power/kernel/include/sys/stat.h
cdd_entry.o: ${MAKETOP}../export/power/kernel/include/cdd.h
cdd_entry.o: ${MAKETOP}../export/power/kernel/include/cdd_macros.h
cdd_entry.o: ${MAKETOP}bos/kernext/disp/rby/cdd/rby_cdd_hw_defs.h
