#
# dependents of b.o:
b.o: /usr/include/stdio.h
b.o: /usr/include/standards.h
b.o: /usr/include/va_list.h
b.o: /usr/include/sys/types.h
b.o: /usr/include/sys/m_types.h
b.o: /usr/include/sys/limits.h
b.o: /usr/include/float.h
b.o: /usr/include/stdlib.h
b.o: /usr/include/sys/localedef.h
b.o: /usr/include/sys/lc_core.h
b.o: /usr/include/locale.h
b.o: /usr/include/sys/localedef31.h
b.o: /usr/include/string.h
b.o: ${MAKETOP}bos/usr/bin/awk/awk.h
b.o: /usr/include/regex.h
b.o: /usr/include/limits.h
b.o: /usr/include/ctype.h
b.o: /usr/include/math.h
b.o: awk_msg.h
b.o: ${MAKETOP}../export/power/bldenv/usr/include/nl_types.h
b.o: ${MAKETOP}../export/power/bldenv/usr/include/mesg.h
b.o: y.tab.h
#
# dependents of lex.yy.o:
lex.yy.o: /usr/include/stdio.h
lex.yy.o: /usr/include/standards.h
lex.yy.o: /usr/include/va_list.h
lex.yy.o: /usr/include/sys/types.h
lex.yy.o: /usr/include/sys/m_types.h
lex.yy.o: /usr/include/sys/limits.h
lex.yy.o: /usr/include/float.h
lex.yy.o: /usr/include/stddef.h
lex.yy.o: /usr/include/locale.h
lex.yy.o: /usr/include/stdlib.h
lex.yy.o: /usr/include/sys/localedef.h
lex.yy.o: /usr/include/sys/lc_core.h
lex.yy.o: /usr/include/sys/localedef31.h
lex.yy.o: ${MAKETOP}bos/usr/bin/awk/awk.h
lex.yy.o: /usr/include/regex.h
lex.yy.o: /usr/include/limits.h
lex.yy.o: /usr/include/ctype.h
lex.yy.o: /usr/include/math.h
lex.yy.o: awk_msg.h
lex.yy.o: ${MAKETOP}../export/power/bldenv/usr/include/nl_types.h
lex.yy.o: ${MAKETOP}../export/power/bldenv/usr/include/mesg.h
lex.yy.o: y.tab.h
#
# dependents of lib.o:
lib.o: /usr/include/stdio.h
lib.o: /usr/include/standards.h
lib.o: /usr/include/va_list.h
lib.o: /usr/include/sys/types.h
lib.o: /usr/include/sys/m_types.h
lib.o: /usr/include/sys/limits.h
lib.o: /usr/include/float.h
lib.o: /usr/include/stdlib.h
lib.o: /usr/include/sys/localedef.h
lib.o: /usr/include/sys/lc_core.h
lib.o: /usr/include/locale.h
lib.o: /usr/include/sys/localedef31.h
lib.o: /usr/include/string.h
lib.o: /usr/include/errno.h
lib.o: /usr/include/sys/errno.h
lib.o: ${MAKETOP}../export/power/bldenv/usr/include/nl_types.h
lib.o: ${MAKETOP}../export/power/bldenv/usr/include/mesg.h
lib.o: /usr/include/langinfo.h
lib.o: ${MAKETOP}bos/usr/bin/awk/awk.h
lib.o: /usr/include/regex.h
lib.o: /usr/include/limits.h
lib.o: /usr/include/ctype.h
lib.o: /usr/include/math.h
lib.o: awk_msg.h
lib.o: y.tab.h
#
# dependents of main.o:
main.o: /usr/include/stdio.h
main.o: /usr/include/standards.h
main.o: /usr/include/va_list.h
main.o: /usr/include/sys/types.h
main.o: /usr/include/sys/m_types.h
main.o: /usr/include/sys/limits.h
main.o: /usr/include/float.h
main.o: /usr/include/signal.h
main.o: /usr/include/sys/signal.h
main.o: /usr/include/sys/context.h
main.o: /usr/include/sys/m_param.h
main.o: /usr/include/sys/mstsave.h
main.o: /usr/include/locale.h
main.o: /usr/include/stdlib.h
main.o: /usr/include/sys/localedef.h
main.o: /usr/include/sys/lc_core.h
main.o: /usr/include/sys/localedef31.h
main.o: /usr/include/errno.h
main.o: /usr/include/sys/errno.h
main.o: ${MAKETOP}bos/usr/bin/awk/awk.h
main.o: /usr/include/regex.h
main.o: /usr/include/limits.h
main.o: /usr/include/ctype.h
main.o: /usr/include/math.h
main.o: awk_msg.h
main.o: ${MAKETOP}../export/power/bldenv/usr/include/nl_types.h
main.o: ${MAKETOP}../export/power/bldenv/usr/include/mesg.h
main.o: y.tab.h
main.o: /usr/include/unistd.h
main.o: /usr/include/sys/access.h
main.o: /usr/include/sys/lockf.h
main.o: ${MAKETOP}../export/power/bldenv/usr/include/sys/stat.h
main.o: /usr/include/sys/mode.h
#
# dependents of parse.o:
parse.o: /usr/include/stdio.h
parse.o: /usr/include/standards.h
parse.o: /usr/include/va_list.h
parse.o: /usr/include/sys/types.h
parse.o: /usr/include/sys/m_types.h
parse.o: /usr/include/sys/limits.h
parse.o: /usr/include/float.h
parse.o: /usr/include/stdlib.h
parse.o: /usr/include/sys/localedef.h
parse.o: /usr/include/sys/lc_core.h
parse.o: /usr/include/locale.h
parse.o: /usr/include/sys/localedef31.h
parse.o: /usr/include/string.h
parse.o: ${MAKETOP}bos/usr/bin/awk/awk.h
parse.o: /usr/include/regex.h
parse.o: /usr/include/limits.h
parse.o: /usr/include/ctype.h
parse.o: /usr/include/math.h
parse.o: awk_msg.h
parse.o: ${MAKETOP}../export/power/bldenv/usr/include/nl_types.h
parse.o: ${MAKETOP}../export/power/bldenv/usr/include/mesg.h
parse.o: y.tab.h
#
# dependents of proctab.o:
proctab.o: ${MAKETOP}bos/usr/bin/awk/awk.h
proctab.o: /usr/include/regex.h
proctab.o: /usr/include/sys/types.h
proctab.o: /usr/include/standards.h
proctab.o: /usr/include/sys/m_types.h
proctab.o: /usr/include/limits.h
proctab.o: /usr/include/sys/limits.h
proctab.o: /usr/include/float.h
proctab.o: /usr/include/ctype.h
proctab.o: /usr/include/sys/localedef.h
proctab.o: /usr/include/sys/lc_core.h
proctab.o: /usr/include/locale.h
proctab.o: /usr/include/sys/localedef31.h
proctab.o: /usr/include/math.h
proctab.o: /usr/include/stdlib.h
proctab.o: awk_msg.h
proctab.o: ${MAKETOP}../export/power/bldenv/usr/include/nl_types.h
proctab.o: ${MAKETOP}../export/power/bldenv/usr/include/mesg.h
proctab.o: /usr/include/stdio.h
proctab.o: y.tab.h
#
# dependents of run.o:
run.o: /usr/include/stdio.h
run.o: /usr/include/standards.h
run.o: /usr/include/va_list.h
run.o: /usr/include/sys/types.h
run.o: /usr/include/sys/m_types.h
run.o: /usr/include/sys/limits.h
run.o: /usr/include/float.h
run.o: /usr/include/stdlib.h
run.o: /usr/include/sys/localedef.h
run.o: /usr/include/sys/lc_core.h
run.o: /usr/include/locale.h
run.o: /usr/include/sys/localedef31.h
run.o: /usr/include/string.h
run.o: /usr/include/setjmp.h
run.o: /usr/include/math.h
run.o: ${MAKETOP}bos/usr/bin/awk/awk.h
run.o: /usr/include/regex.h
run.o: /usr/include/limits.h
run.o: /usr/include/ctype.h
run.o: awk_msg.h
run.o: ${MAKETOP}../export/power/bldenv/usr/include/nl_types.h
run.o: ${MAKETOP}../export/power/bldenv/usr/include/mesg.h
run.o: y.tab.h
#
# dependents of tran.o:
tran.o: /usr/include/stdio.h
tran.o: /usr/include/standards.h
tran.o: /usr/include/va_list.h
tran.o: /usr/include/sys/types.h
tran.o: /usr/include/sys/m_types.h
tran.o: /usr/include/sys/limits.h
tran.o: /usr/include/float.h
tran.o: /usr/include/stdlib.h
tran.o: /usr/include/sys/localedef.h
tran.o: /usr/include/sys/lc_core.h
tran.o: /usr/include/locale.h
tran.o: /usr/include/sys/localedef31.h
tran.o: /usr/include/string.h
tran.o: ${MAKETOP}bos/usr/bin/awk/awk.h
tran.o: /usr/include/regex.h
tran.o: /usr/include/limits.h
tran.o: /usr/include/ctype.h
tran.o: /usr/include/math.h
tran.o: awk_msg.h
tran.o: ${MAKETOP}../export/power/bldenv/usr/include/nl_types.h
tran.o: ${MAKETOP}../export/power/bldenv/usr/include/mesg.h
tran.o: y.tab.h
#
# dependents of y.tab.o:
y.tab.o: ${MAKETOP}bos/usr/bin/awk/awk.h
y.tab.o: /usr/include/regex.h
y.tab.o: /usr/include/sys/types.h
y.tab.o: /usr/include/standards.h
y.tab.o: /usr/include/sys/m_types.h
y.tab.o: /usr/include/limits.h
y.tab.o: /usr/include/sys/limits.h
y.tab.o: /usr/include/float.h
y.tab.o: /usr/include/ctype.h
y.tab.o: /usr/include/sys/localedef.h
y.tab.o: /usr/include/sys/lc_core.h
y.tab.o: /usr/include/locale.h
y.tab.o: /usr/include/sys/localedef31.h
y.tab.o: /usr/include/math.h
y.tab.o: /usr/include/stdlib.h
y.tab.o: awk_msg.h
y.tab.o: ${MAKETOP}../export/power/bldenv/usr/include/nl_types.h
y.tab.o: ${MAKETOP}../export/power/bldenv/usr/include/mesg.h
y.tab.o: /usr/include/stdio.h
