# @(#)25        1.1  src/bos/kernel/include/aixif/Makefile, sysxaixif, bos411, 9428A410j 8/5/92 16:11:04
# COMPONENT_NAME:
#
# FUNCTIONS:
#
# ORIGINS: 10,27
#
# IBM CONFIDENTIAL -- (IBM Confidential Restricted when
# combined with the aggregated modules for this product)
#                  SOURCE MATERIALS
# (C) COPYRIGHT International Business Machines Corp. 1988, 1989
# All Rights Reserved
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#

VPATH		= ${MAKETOP}bos/usr/include/aixif

IDIR		= /kernel/include/aixif/

DATAFILES	= net_if.h x25xlate.h X25xlate.h

INCLUDES	= ${DATAFILES}


.include <${RULES_MK}>
