# @(#)53	1.1  src/bos/usr/lib/nls/bidi/maps/ar_AA.ibm3151/Makefile, bos, bos410 8/27/93 09:46:10
#
#   COMPONENT_NAME: CFGNLS
#
#   FUNCTIONS: 
#
#   ORIGINS: 27
#
#   IBM CONFIDENTIAL -- (IBM Confidential Restricted when
#   combined with the aggregated modules for this product)
#                    SOURCE MATERIALS
#
#   (C) COPYRIGHT International Business Machines Corp. 1993
#   All Rights Reserved
#   US Government Users Restricted Rights - Use, duplication or
#   disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#



ILIST		= kbrd.MAP symetric.MAP
 
IDIR		= /usr/lib/nls/bidi/maps/ar_AA.ibm3151@alt/


.include <${RULES_MK}>
