# @(#)24        1.1  src/bos/usr/lib/methods/cfgdmxeth/Makefile, sysxent, bos411, 9428A410j 9/20/93 17:26:01
#
# COMPONENT_NAME:
#
# FUNCTIONS:
#
# ORIGINS: 27
#
# IBM CONFIDENTIAL -- (IBM Confidential Restricted when
# combined with the aggregated modules for this product)
#                  SOURCE MATERIALS
# (C) COPYRIGHT International Business Machines Corp. 1993
# All Rights Reserved
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#

VPATH		= ../common

PROGRAMS        = cfgdmxeth

OFILES          = cfgdmxeth.o

INCFLAGS	= -I../common

ILIST           = cfgdmxeth
IDIR		= /usr/lib/methods/

LIBS		= -ls -lodm -lcfg -lrts

.include <${RULES_MK}>
