# @(#)52        1.2  src/bos/kernel/s/aud/Makefile, syssaud, bos411, 9428A410j 10/27/93 16:38:56
# COMPONENT_NAME:
#
# FUNCTIONS:
#
# ORIGINS: 27
#
# IBM CONFIDENTIAL -- (IBM Confidential Restricted when
# combined with the aggregated modules for this product)
#                  SOURCE MATERIALS
# (C) COPYRIGHT International Business Machines Corp. 1988, 1993
# All Rights Reserved
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#

.include <${MAKETOP}bos/kernel/Kernel.mk>

PAGED_OFILES	=	\
	auditlog.o	\
	auditproc.o

PAGED_OFILES_BACK =	\
	audit.o		\
	auditbin.o	\
	auditevent.o	\
	auditobj.o	\
	auditsym.o	\
	globals.o

.include <${RULES_MK}>
