# @(#)76        1.2  src/bos/usr/lpp/bosinst/scripts/scrip500/Makefile, bosinst, bos411, 9428A410j 12/21/93 14:06:59
# COMPONENT_NAME:  bosinst
#
# FUNCTIONS:
#
# ORIGINS: 27
#
# IBM CONFIDENTIAL -- (IBM Confidential Restricted when
# combined with the aggregated modules for this product)
#                  SOURCE MATERIALS
# (C) COPYRIGHT International Business Machines Corp. 1988, 1989
# All Rights Reserved
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#

SCRIPTS         = sendfssz

ILIST           = sendfssz

IDIR            = /usr/lpp/bosinst/scripts/

.include <${RULES_MK}>
