$ @(#)40    1.1  src/bos/usr/ccs/lib/libcurses/libcurses.msg, libcurses, bos411, 9428A410j 9/3/93 15:09:45
$
$   COMPONENT_NAME: LIBCURSES
$
$   FUNCTIONS: libcurses.msg (Message Catalog)
$
$   ORIGINS: 27
$
$   IBM CONFIDENTIAL -- (IBM Confidential Restricted when
$   combined with the aggregated modules for this product)
$                    SOURCE MATERIALS
$
$   (C) COPYRIGHT International Business Machines Corp. 1992
$   All Rights Reserved
$   US Government Users Restricted Rights - Use, duplication or
$   disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
$
$quote "       Define quote character.

$set MS_LIBCURSES

NOTERM    "1371-001 Terminal %s is unknown.\n"
$
CORRUPT   "1371-002 Corrupted terminfo entry.\n"
$
LONGTERM  "1371-003 Terminfo entry is too long.\n"
$
NOACCESS  "1371-004 /usr/share/lib/terminfo is unaccessible.\n"
$
LONGPATH  "1371-005 Terminfo pathname for device exceeds 512 characters.\n"
$
MALLOC    "1371-006 malloc returned NULL.\n"
$
NOTREAD   "1371-007 Unable to read terminfo file for %s terminal.\n"
$
SPECTERM  "1371-008 Please provide a more specific terminal type than %s.\n"
$
