# @(#)08        1.6  src/bos/usr/lib/pios/trans1/Makefile, cmdpios, bos411, 9428A410j 4/1/94 14:43:57
#
# COMPONENT_NAME: (CMDPIOS) Printer Backend
#
# FUNCTIONS:
#
# ORIGINS: 27
#
# IBM CONFIDENTIAL -- (IBM Confidential Restricted when
# combined with the aggregated modules for this product)
#                  SOURCE MATERIALS
# (C) COPYRIGHT International Business Machines Corp. 1988, 1994
# All Rights Reserved
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#

DATAFILES	= 850 IBM-437 IBM-850 IBM-856 IBM-1046 ISO8859-1 \
		  ISO8859-2 ISO8859-3 ISO8859-4 ISO8859-5 ISO8859-6 \
		  ISO8859-7 ISO8859-8 ISO8859-9 UCS-2 UTF-8

ILIST		= ${DATAFILES}
IDIR		= /usr/lib/lpd/pio/trans1/

.include <${RULES_MK}>

850: ${RUN850}
	${RUN850} .

IBM-437: ${RUNIBM_437}
	${RUNIBM_437} .

IBM-850: ${RUNIBM_850}
	${RUNIBM_850} .

IBM-856: ${RUNIBM_856}
	${RUNIBM_856} .

IBM-1046: ${RUNIBM_1046}
	${RUNIBM_1046} .

ISO8859-1: ${RUNISO8859_1}
	${RUNISO8859_1} .

ISO8859-2: ${RUNISO8859_2}
	${RUNISO8859_2} .

ISO8859-3: ${RUNISO8859_3}
	${RUNISO8859_3} .

ISO8859-4: ${RUNISO8859_4}
	${RUNISO8859_4} .

ISO8859-5: ${RUNISO8859_5}
	${RUNISO8859_5} .

ISO8859-6: ${RUNISO8859_6}
	${RUNISO8859_6} .

ISO8859-7: ${RUNISO8859_7}
	${RUNISO8859_7} .

ISO8859-8: ${RUNISO8859_8}
	${RUNISO8859_8} .

ISO8859-9: ${RUNISO8859_9}
	${RUNISO8859_9} .

UCS-2: ${RUNUCS_2}
	${RUNUCS_2} .

UTF-8: ${RUNUTF_8}
	${RUNUTF_8} .
