# @(#)88        1.4  src/bldenv/bdftopcf/Makefile, ade_build, bos412, GOLDA411a 1/20/94 08:16:38
#
#   COMPONENT_NAME: BOSBUILD
#
#   FUNCTIONS:
#
#   ORIGINS: 27
#
#   IBM CONFIDENTIAL -- (IBM Confidential Restricted when
#   combined with the aggregated modules for this product)
#                    SOURCE MATERIALS
#
#   (C) COPYRIGHT International Business Machines Corp. 1993
#   All Rights Reserved
#   US Government Users Restricted Rights - Use, duplication or
#   disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#

bdftopcf_EXECUTABLE	= yes

ILIST			= bdftopcf
IDIR			= /usr/bin/

.include <${RULES_MK}>
