# @(#)62	1.2  src/bos/usr/lib/pios/bidi/fonts/4019/Makefile, cmdpios, bos411, 9432A411a 8/5/94 11:44:27

#
# COMPONENT_NAME: (CMDPIOS) Printer Backend
#
# ORIGINS: 27
#
# IBM CONFIDENTIAL -- (IBM Confidential Restricted when
# combined with the aggregated modules for this product)
#                  SOURCE MATERIALS
# (C) COPYRIGHT International Business Machines Corp. 1989
# All Rights Reserved
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#


DATAFILES       = courier-nasseem bask-nasseem-bold bask-nasseem-italic

ILIST           = ${DATAFILES}
IDIR            = /usr/lib/lpd/pio/fonts/ibm4019/

.include <${RULES_MK}>
