# @(#)66	1.1  src/bos/usr/lib/nls/bidi/maps/iw_IL.ISO8859-8@alt/Makefile, cfgnls, bos411, 9428A410j 8/27/93 09:46:57
# COMPONENT_NAME: CFGNLS
#
# FUNCTIONS:
#
# ORIGINS: 27
#
# IBM CONFIDENTIAL -- (IBM Confidential Restricted when
# combined with the aggregated modules for this product)
#                  SOURCE MATERIALS
# (C) COPYRIGHT International Business Machines Corp. 1988, 1993
# All Rights Reserved
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#



ILIST		= in.MAP kbrd.MAP out.MAP symetric.MAP
 
IDIR		= /usr/lib/nls/bidi/maps/iw_IL.ISO8859-8@alt/


.include <${RULES_MK}>
