#
#
#
#   ORIGINS: 27
#
#
#

#VPATH	= ${MAKETOP}gos/2d/MOTIF/lib/Xm

EXPDIR	= /usr/include/Xm/

DATAFILES	= \
	MessageB.h \
	XmP.h \
	VirtKeys.h \
	VirtKeysP.h \
	MwmUtil.h \
	Xm.h \
	LabelP.h \
	RepType.h \
	ManagerP.h \
	XmStrDefs.h \
	VendorS.h \
	BaseClassP.h \
	Label.h \
	PrimitiveP.h \
	AtomMgr.h \
	CutPaste.h \
	ScrollBarP.h \
	DropSMgr.h \
	DropSMgrP.h \
	DropTrans.h \
	DragC.h \
	DragCP.h \
	ScrollBar.h \
	Display.h \
	DisplayP.h \
	Protocols.h \
	BulletinBP.h \
	ScrolledW.h \
	ScrolledWP.h \
	Form.h \
	PushB.h \
	PushBG.h \
	LabelG.h \
	Frame.h \
	RowColumn.h \
	RowColumnP.h \
	BulletinB.h \
	CascadeBG.h \
	ToggleBG.h \
	SeparatoG.h \
	SelectioB.h \
	DialogS.h \
	TextF.h \
	TextFP.h \
	CascadeB.h \
	ToggleB.h \
	XmAll.h \
	ArrowB.h \
	ArrowBG.h \
	Command.h \
	DragDrop.h \
	DragIcon.h \
	DragOverS.h \
	DrawingA.h \
	DrawnB.h \
	DrawP.h \
	FileSB.h \
	List.h \
	ListP.h \
	MainW.h \
	MenuShell.h \
	MenuUtilP.h \
	ShellEP.h \
	PanedW.h \
	Scale.h \
	Separator.h \
	Screen.h \
	ScreenP.h \
	DesktopP.h \
	VendorSEP.h \
	ExtObjectP.h \
	Text.h
	

INCLUDES	= ${DATAFILES}

.include <${RULES_MK}>

