# @(#)95	1.1  src/bos/usr/lib/netls/adk/X11/app-defaults/Makefile, libnetls, bos411, 9428A410j 5/26/94 18:25:53
# COMPONENT_NAME:  libnetls
#
# FUNCTIONS:
#
# ORIGINS: 27
#
# IBM CONFIDENTIAL -- (IBM Confidential Restricted when
# combined with the aggregated modules for this product)
#                  SOURCE MATERIALS
#   (C) COPYRIGHT International Business Machines Corp. 1994
# All Rights Reserved
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#

ILIST           = XLs_DPass
IDIR            = /usr/lib/netls/adk/X11/app-defaults/

.include <${RULES_MK}>
