# @(#)93	1.4  src/bos/sbin/helpers/Makefile, Makefiles, bos411, 9428A410j 4/25/94 14:56:24
#
# COMPONENT_NAME:
#
# FUNCTIONS:
#
# ORIGINS: 27
#
# IBM CONFIDENTIAL -- (IBM Confidential Restricted when
# combined with the aggregated modules for this product)
#                  SOURCE MATERIALS
# (C) COPYRIGHT International Business Machines Corp. 1988, 1994
# All Rights Reserved
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#

EXPINC_SUBDIRS	= v3fshelpers
EXPLIB_SUBDIRS	= v3fshelpers

SUBDIRS		= v3fshelpers

.include <${RULES_MK}>
